### ISSUE TITLE
Graph Type Registrations

### ISSUE THREAD

**Issue by bugged84** [graphql-dotnet/graphql-dotnet#1011]
Consider the [docs](https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#aspnet-core) which show the `StarWarsQuery`, `StarWarsMutation`, and other Graph types being registered as singletons.

This will cause issues once various dependencies are added to these graph types, as the dependencies will effectively become singletons as well. Is there a reason for registering the graph types as singletons?

**Comment by bogdancice** [comment]
In our app we registered GraphQL and GraphgQL Types as Singletone because we have a large schema (lots of queries and mutations), this approach improved the API performance significantly because the initialization of all the queries and mutations is done only at Startup. If we define the Types as Scoped then at each request **ALL** the queries and mutations are initialized because GraphQL is building the entire graph before analyzing the request body (even if my request contains only one or two query). I think that you should test the performance hit on your app if you use Scoped vs Singletone and see if it's worth it to use Scoped. We didn't had any other issues when we used Scoped instead of Singletone

**Comment by bugged84** [comment]
@bogdancice but if they are all singleton, then how are you getting scoped dependencies? For example, you wouldn't want to share a single Entity Framework DbContext between all mutation requests. Are you injecting factories everywhere instead?

**Comment by joemcbride** [comment]
One thing to also know is that all Graph types take on the same lifetime of the Schema.  So a Graph type is only created once for a given Schema instance and is reused.  So depending on your injected services you could have similar issues even when not Singleton.

**Comment by bogdancice** [comment]
@bugged84 great point. We are getting scoped DataContext object from HttpContextAccessor.
Example:
``` 
public class UserRepository
{
        private DataContext DbContext => m_accessor.HttpContext.RequestServices.GetRequiredService<DataContext>();

        public UserRepository(IHttpContextAccessor accessor)
        {
            m_accessor = accessor;
        }
}
```

This is working fine if the repository is used when an API request is made, but if we want to use this repositories on some background tasks/threads (e.g. we want some database entities to be updated based on some context information) this repositories will be useless because HttpContext is Null. For fixing that we created another Repo class.

```
public class ScopedRepository
{
        private DataContext DbContext => m_serviceProvider.GetRequiredService<DataContext>();

        public ScopedRepository(IServiceProvider serviceProvider)
        {
            m_serviceProvider = serviceProvider;
        }
}
```

And the background task will look something like this:

```
 public class BackgroundTask
{ 
        private readonly IServiceScopeFactory m_scopeFactory;

        public BackgroundTask(IServiceScopeFactory scopeFactory)
        {
            m_scopeFactory = scopeFactory;
        }
        public async void ExecuteBackgroundAction(object input)
        {
                using (var scope = m_scopeFactory.CreateScope())
                {
                    var scopedRepository= scope.ServiceProvider.GetService<IScopedCreativeRepository>();
                     //call the repository methods
                }
        }
}
```

We know this is not the best approach (duplicating the repos is not a scalable idea ) and we will refactor this when we have more time. I think that using a factory for getting DataContext is a better idea, we just have to test it :)

@bugged84 let us know if you find a better solution for this challenge ;)

**Comment by bugged84** [comment]
@bogdancice I use Autofac for my DI and I've solved the issue by using two DbContext registrations.

The first is registered with a lifetime scope per request and is resolved by key for my repositories (read-only).

```
private static void RegisterRepositories(ContainerBuilder builder)
{
   const string repositoryClassNameSuffix = "Repository";

   builder
     .Register(GetMyContext)
     .Named<DbContext>(repositoryClassNameSuffix)
      // All repository instances can share a context per request (e.g. read-only)
     .InstancePerLifetimeScope();

   builder
     .RegisterAssemblyTypes(typeof(MyRepository).Assembly)
     .Where(t => t.Name.EndsWith(repositoryClassNameSuffix))
     .AsImplementedInterfaces()
     .WithParameter(
         (info, context) => info.ParameterType == typeof(DbContext)
       , (info, context) =>
            context.ResolveNamed<DbContext>(repositoryClassNameSuffix)
      )
     .InstancePerLifetimeScope();
}
```

The second is registered with a lifetime scope per dependency and is resolved by key as a `Func<DbContext>` for my mutation services.

```
private static void RegisterServices(ContainerBuilder builder)
{
   const string serviceClassNameSuffix = "Service";

   builder
     .Register(GetMyContext)
     .Named<DbContext>(serviceClassNameSuffix)
      // Each service instance needs a separate context per unit of work
     .InstancePerDependency();

   Func<DbContext> GetDbContextFactory(IComponentContext context)
   {
       return
           () => context.Resolve<IComponentContext>().ResolveNamed<DbContext>(serviceClassNameSuffix);
   }

   builder
     .RegisterAssemblyTypes(typeof(MyService).Assembly)
     .Where(t => t.Name.EndsWith(serviceClassNameSuffix))
     .AsImplementedInterfaces()
     .WithParameter(
         (info, context) => info.ParameterType == typeof(Func<DbContext>)
       , (info, context) => GetDbContextFactory(context)
      )
     .InstancePerLifetimeScope();
}
```

Within my services I just write mutations like this:

```
using (var uow = dbContextFactory())
{
    ...
    await uow.SaveChangesAsync();
}
```

**Comment by bugged84** [comment]
> One thing to also know is that all Graph types take on the same lifetime of the Schema. So a Graph type is only created once for a given Schema instance and is reused. So depending on your injected services you could have similar issues even when not Singleton.

@joemcbride I have my schema registered as a transient service rather than singleton. Is there a reason not to do so?

**Comment by joemcbride** [comment]
@bugged84 if you have a very large schema it can cause performance issues to create it on every request.  You’ll have to do some perf testing and see if that applies to your project.

**Comment by bugged84** [comment]
@joemcbride I have not noticed any performance issues so far. How would you determine whether a schema is "large"? Total number of graph types defined? Total number of queries on the root? Is there a ballpark number you can share to give me an idea of what to test for?

**Comment by sungam3r** [comment]
You can use the memory profiler and see the number and size of allocations for your server load. And then you decide on these values whether they are large for you or not. In any case, the repeated re-creation of meta-information, which is the schema and all types in it is a useless load on the garbage collector.

**Comment by bugged84** [comment]
I suppose if the graph types are registered as singletons for metadata purposes (e.g. schema) then their dependencies could be injected as factories (e.g. `Func<MyService>`) to prevent the dependencies from becoming singletons.

**Comment by sungam3r** [comment]
Yes it is.

**Comment by sungam3r** [comment]
Closed as answered.
