### ISSUE TITLE
Int Scalar Type does not conform to GraphQL spec

### ISSUE THREAD

**Issue by wirmar** [graphql-dotnet/graphql-dotnet#1022]
## Description

[According to the documentation](https://graphql-dotnet.github.io/docs/getting-started/schema-types), The `IntGraphType` which represents an `Int` GraphQL type can be used for `int` (32-bit) and `long` (64-bit) c# types.
[According to the latest GraphQL specs](https://facebook.github.io/graphql/June2018/#sec-Int), the `Int` scalar type represents a 32-bit integer value. "The Int scalar type represents a signed 32‐bit numeric non‐fractional value. [...] If the integer internal value represents a value less than -2^31 or greater than or equal to 2^31, a field error should be raised."

### Steps to reproduce

Create a `IntGraphType` field with a backing `long` value.
Return a value from the field, that is >2^31.
Query the field.

### Expected result

The query should return an error.
The documentation should reflect, that `IntGraphType` only represents `int` values.
There could be an additional `LongGraphType` scalar type instead.

### Actual result

It returns the result, that is >2^31.

### Why is this a problem

Not conforming to the spec can lead to discrepancies when trying to work with different implementations of the GraphQL specs.

Personal reason:
This issue came up, because we use a development server, written in Javascript with apollo, that stitches together different graphql endpoints.
Requesting a `long` Field via that proxy server fails, because apollo conforms to the spec. Requesting from the endpoint written with graphql-dotnet directly returns a result.

**Comment by OpenSpacesAndPlaces** [comment]
The primary reason cited is:
"not all platforms and transports support encoding integer numbers larger than 32‐bit"

From discussion here it seems JS is maxing out at 52/53bits:
https://github.com/facebook/graphql/issues/73

--- 

IMO - this seems overly hand holdie on the part of the spec - but it is what it is I guess.
At least for me, the problem I normally run into is a specific API's documentation being ambiguous.

**Comment by sungam3r** [comment]
Also faced with this problem. Indeed, the [specification section](https://graphql.github.io/graphql-spec/June2018/#sec-Int) clearly speaks of honoring `Int`. The fact is that the current implementation of `Int` actually leads to the inoperability of `long` .NET type. 

Both `int` and `long` types are [mapped](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/GraphTypeTypeRegistry.cs) to `IntGraphType`
```c#
 [typeof(int)] = typeof(IntGraphType),
 [typeof(long)] = typeof(IntGraphType),
```
I am writing a code generator that creates a full-featured C# client according to the provided SDL schema or introspection request. I was faced with the fact that all `long` properties are perceived as `int`. This is especially painful in the case of inputs, since in the generated code a method is obtained that limits the input value from `long` to `int`.

Moreover, now GraphQL library implements a whole bunch of other numeric scalars: `ShortGraphType`, `UShortGraphType`, `ULongGraphType`, `UIntGraphType`. Also one of my [PR](#1091) adds support for `ByteGraphType` and `SByteGraphType`. In this respect, the absence of an explicit type of `LongGraphType` looks pretentious. It seems to me that this is an artificial restriction associated with early considerations about the implementation of support of this type.

Also I have seen [this comment](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/IntGraphType.cs#L25) and I understand that this implementation was due to the desire to do as best as possible but there it is more about JSON numeric behaviour and not what the GraphQL specification requires.

Also I read [this issue](https://github.com/graphql/graphql-spec/issues/73) and see that there was quite a lot of discussion about how it should be done. In fact, it all comes down to sitting on two chairs at the same time. On the one hand, to comply with the specification, on the other hand, to provide a more flexible implementation. This approach has the right to life, but exactly as long as it does not lead to problems of correctness, which we are beginning to observe now.

Thus, I propose to add an explicit `LongGraphType` and map it to `long`. Now for this the most opportune moment, since the library received a new major version. Then it will be more problematic to make such significant changes.

**Comment by sungam3r** [comment]
Also see this graphql/graphql-spec#597:
![image](https://user-images.githubusercontent.com/21261007/65614131-c3e7b280-dfbf-11e9-885b-bfdd17c8245c.png)

**Comment by sungam3r** [comment]
@joemcbride Perhaps we already have enough arguments in favor of finally separating the processing of types `Int` and `Long`? I do not think that the consequences of this change will be dramatic.

**Comment by Ekkeir** [comment]
This would be a highly anticipated change for us.
We have some ids defined as long. Inability to differenciate between the two types when interpreting the schema is causing us quite some grief.

**Comment by joemcbride** [comment]
@sungam3r Yes, we should do this as part of the 3.0 milestone.
