### ISSUE TITLE
How to handle multiple data loader calls?

### ISSUE THREAD

**Issue by magnusottosson** [graphql-dotnet/graphql-dotnet#1042]
Hi,

I have some code like this:

```
Field<ProcductGraphType, Product>()
                .Name("accessories")
                .ResolveAsync(async ctx =>
                {

                    var relationShipLoader = accessor.Context.GetOrAddLoader("RelationShipLoader", GetAccessoriesRelationShip);

                    var relationShips = await relationShipLoader.LoadAsync("product1");
                    var productIds = relationShips.Select(x => x.Id);
               
                    var productsLoader = accessor.Context.GetOrAddLoader("ProductsLoader", GetProducts);

                    var products = await relationShipLoader.LoadAsync(productIds);

                    return products;
                });
```

I have read that you have to create all task before calling await but how do I handle scenarious like above where I need the result from the first loader as input for the second loader?

In the above case the second await will never execute.

**Comment by joemcbride** [comment]
Admittedly I'm no expert on the DataLoader feature, though I'm fairly certain this scenario is not currently supported by it.

**Comment by magnusottosson** [comment]
I guess that the dataloader implementation in GraphQL does not support this because the task are only triggered once in this scope. Previously I have been working with facebooks javascript implementation and it supports using multiple dataloaders and you can even chain dataloaders so one loader uses another loader inside itself.

The use case above seems like a common scenario that should be supportet? Maybe it's just me that dont understand how to solve this?

My solution was to create another dataloader that performs all the calls it seend inside itself. This works but the loader will be very specific to this use case and wont combine requests with others where only the relationship is needed etc...

**Comment by jpabeem** [comment]
I am currently facing the same problem, only difference is that I am encountering it when querying two fields which both use DataLoaders within the same request. 

@magnusottosson care to elaborate on your solution? Thanks!

**Comment by johnrutherford** [comment]
@magnusottosson  Yeah, it's not supported. Async stuff works a lot differently in node.js than in .NET. 

I've spent a lot of time working on this problem. It would be possible to do this with a separate thread that is constantly checking for more work queued for a data loader. The problem is that there would be no way to know when no more requests will be added. So it wouldn't be able to batch optimally.

Maybe we could have two implementations to choose from...? That might be more confusing, though.

@jpabeem, could you elaborate and share some code? What problem are you having? There's no reason the DataLoader shouldn't work with multiple fields.
