### ISSUE TITLE
DateTime CLR type lose time component by default

### ISSUE THREAD

**Issue by pavel-usachev** [graphql-dotnet/graphql-dotnet#1082]
## Description

Excuse me, I've read all other issues about Date vs DateTime vs DateTimeOffset and still can't understand why default behavior is to map `DateTime` to `DateGraphType`, not to `DateTimeGraphType`? That means clr type `DateTime` is losing its time component by default. Is it by design feature or an issue?

### Steps to reproduce

```c#
public class DateTimeSchema : Schema
{
    public DateTimeSchema()
    {
        var query = new ObjectGraphType<Model>();
        query.Field(f => f.DateField).Resolve(_ => new DateTime(1000, 10, 10, 1, 2, 3));
        Query = query;
    }

    private class Model
    {
        public DateTime DateField { get; set; }
    }
}
```

Query: `{ dateField }`

### Expected result

```
{
  "data": {
    "dateField": "1000-10-10T01:02:03"
  }
}
```

### Actual result

```
{
  "data": {
    "dateField": "1000-10-10"
  }
}
```

**Comment by joemcbride** [comment]
I can be convinced to change that.  Makes sense.

**Comment by RehanSaeed** [comment]
Since I raised the PR to make it this way, here is my reasoning. It is not recommended by Microsoft to use the `DateTime` type in .NET, this is official guidance. `DateTimeOffset` is supposed to be used instead which includes an additional timezone offset value.

There are times though where you might want to represent a date without a time component. Since there is no built in type for this purpose in .NET the `DateTime` type makes the most sense. Therefore, given the above advice that you shouldn't be using `DateTime` to represent date and time, it made sense to repurpose `DateTime` to only represent dates without the time component.

**Comment by d3vi1h3aRt** [comment]
@RehanSaeed thanks for your explanation! Now I see the point.

**Comment by abarger-bss** [comment]
@RehanSaeed Although I respect Microsoft's guidance on `DateTime` v. `DateTimeOffset`, I'm not sure this library is the appropriate place to take a stand on the issue. `DateTime` has a time component -legacy blunder or not, it's there, and library code which truncates a client's time component by default is, to me, surprising at best. 

This exact issue bit us; we were frustrated that code otherwise using the expression based syntax for creating fields had to change to the looser builder syntax to force a conversion to DateTimeGraphType.

I propose a client who cares about date-only `DateTime`s should handle that in application code, or at least explicitly drop times in the resolver.

**Comment by sungam3r** [comment]
@RehanSaeed following the recommendations should not be the price of correctness. Recommendations are a relative thing and are not the ultimate truth. In this case, there is a loss of accuracy which leads to silent errors (worst type of error). The library implementation is not the place to make such a decision about truncation time component. Let the client decide which data type to use - `DateTime` or `DateTimeOffset` or something else.

There are a lot of reasons why exactly `DateTime` can be used as a property of an object. For example, this object is from an immutable binary code that we cannot change. Or, this property is intended solely for dates in local time.

>  It is not recommended by Microsoft to use the DateTime type in .NET, this is official guidance.

As I understand it, the [official Microsoft recommendation](https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime) sounds like "do not use `DateTime`, use `DateTimeOffset` instead," and not "you can use `DateTime`, but be prepared for the fact that you can lose time component at any moment":

> Note
These uses for DateTimeOffset values are much more common than those for DateTime values. As a result, DateTimeOffset should be considered the default date and time type for application development.

**Comment by RehanSaeed** [comment]
You can still decide to go against the guidelines in .NET, it's just not the default out of the box behaviour.

**Comment by sungam3r** [comment]
It's not about whether to follow guidelines or go "against" them. The point is in the default behavior, which should not be a surprise.

As @abarger-bss said:
> I'm not sure this library is the appropriate place to take a stand on the issue. DateTime has a time component -legacy blunder or not, it's there, and library code which truncates a client's time component by default is, to me, surprising at best.

**Comment by PeymanDinani** [comment]
Any update on this?  
I agree with @sungam3r and @abarger-bss 
DateTime has time field so regardless of recommendations and guidelines it should convert correctly based on type. If enforcing Microsoft recommendation is a priority then getting rid of DateTime altogether is a better way than modifying data during conversion.

**Comment by BenjaBobs** [comment]
Since the next version will have a lot of breaking changes anyway, this would be a good time to consider if this is something to be acted upon.

**Comment by sungam3r** [comment]
I think that there is no choice now. After merging #993 any date(time) formatted not as just `1000-10-10` will throw `FormatException`.

**Comment by sungam3r** [comment]
@pavel-usachev @RehanSaeed @BenjaBobs As I said now actual result for test example looks like
```json
{
      "errors": [
        {
          "message": "Expected date to have no time component. Value: 10.10.1000 1:02:03",
          "extensions": {
            "code": "FORMAT",
            "codes": [
              "FORMAT"
            ]
          }
        }
      ]
    }
```

**Comment by BenjaBobs** [comment]
So does this mean that `DateTime` will keep pointing to `DateGraphType`?

**Comment by sungam3r** [comment]
Of course not.
