### ISSUE TITLE
Help with mapping of GenericClasses to GrapghType

### ISSUE THREAD

**Issue by bharadwajesha** [graphql-dotnet/graphql-dotnet#1085]
I have the following **models**:

```
 public class UserInfo
 {
        public string UserAlias { get; set; }
        public List<int> Subs { get; set; }
        public List<int> Biz { get; set; }
}
```

```
 public class EntityCollection<T>
 {
        public bool MoreRecords { get; set; }
        public string ContinuationToken { get; set; }
        public IList<T> Results { get; set; }
}
```

I have made the **GraphTypes** for these models as follows:

```
public UserInfoGraphType()
{
            Field(x => x.UserAlias);
            Field<ListGraphType<IntGraphType>>("biz", resolve: context=>context.Source.Biz);
            Field<ListGraphType<IntGraphType>>("subs", resolve: context => context.Source.Subs);
}

```

```
public class EntityCollectionType<T>:  ObjectGraphType<EntityCollection<T>> where T: IObjectGraphType
    {
        public EntityCollectionType()
        {
            Field(x => x.MoreRecords);
            Field(x => x.ContinuationToken);
            Field<ListGraphType<T>>("Results");
        }
    }
```

This is my **query**: 

 ```
public Queries(IRepository<UserInfo> UserInfoRepository)
        {
            Field<EntityCollectionType<UserInfoGraphType>>("userinfo", 
                                                                arguments: new QueryArguments { new QueryArgument<StringGraphType> { Name="userAlias"} },
                                                                resolve: context => {
                                                                    return new EntityCollection<UserInfo>();
                                                                    }
                                                                );
        }


```
Firing the "userinfo" query gives me the following **error**: 

> {GraphQL.ExecutionError: Expected value of type "SMDPDaaS.GraphTypes.EntityCollectionType`1[SMDPDaaS.GraphTypes.UserInfoGraphType]" for "EntityCollectionType`1" but got: SMDPDaaS.ModelEntity.EntityCollection`1[SMDPDaaS.ModelEntity.UserInfo].
>    at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node)
>    at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)}

How do I make the graphql engine map SMDPDaaS.ModelEntity.EntityCollection`1[SMDPDaaS.ModelEntity.UserInfo] to
SMDPDaaS.GraphTypes.EntityCollectionType`1[SMDPDaaS.GraphTypes.UserInfoGraphType]?

**Comment by alexschrod** [comment]
It's very hard to read your question, because you have not [formatted your text correctly](https://guides.github.com/features/mastering-markdown/), but even when I try my best to look past that, I feel like there's something missing here. You have a `where T: IObjectGraphType` in your code, but you haven't declared a `T` anywhere, nor do you appear to use it anywhere, although that could just be due to the formatting issues.

**Comment by bharadwajesha** [comment]
I have tried to improve the formatting. Hope it helps. What I am essentially trying to do it to create a GraphType where one of the fields will be a list of another complex GraphType. The complex GraphType can vary and hence declared as ListGraphType<T> in the  EntityCollectionType<T> class. Does this help?

**Comment by alexschrod** [comment]
The problem is that you're using the same T in `EntityCollectionType<T>` and in `EntityCollection<T>`. For instance, if you have an `EntityCollection<UserInfo>`, you're going to need an `EntityCollectionType<UserInfoGraphType>` to represent it.

I suggest you add another generic parameter to `EntityCollectionType` to help with this:

```
public class EntityCollectionType<TSource, TGraphType>
    : ObjectGraphType<EntityCollection<TSource>> where TGraphType: IObjectGraphType
{
    public EntityCollectionType()
    {
        Field(x => x.MoreRecords);
        Field(x => x.ContinuationToken);
        Field<ListGraphType<TGraphType>>("Results"); // Why not x => x.Results?
    }
}
```

You haven't posted your full code, so I can't test that it works on my end, but that should get you started. Remember that resolvers always return their source types, not their graph types. Which is why you can't use the same `T` for `EntityCollectionType` as you use for `EntityCollection`.

**Comment by bharadwajesha** [comment]
I get it now. This worked. Thank you.
