### ISSUE TITLE
Interface Implementation: must resolve to Object with value received null

### ISSUE THREAD

**Issue by MagenicJB** [graphql-dotnet/graphql-dotnet#1092]
I am not using RegisterTypes as Mentioned in [https://github.com/graphql-dotnet/graphql-dotnet/issues/1046](url) . I cross posted this question on SO as well here. https://stackoverflow.com/questions/55397923/net-graphql-interface-implementation-must-resolve-to-object-with-value-receive

Good Morning,

I am still new to GraphQL but learning lots and enjoying it very much. The mobile devs on my team are anxious to switch over to consume ONE GraphQL endpoint.

So I've been developing little pilot project as I learn each new skill / capability. This one however has me stumped. I am trying to implement an interface in GraphQL and getting an error. Following the Star Wars example and other articles on Google it LOOKS to me like I have done it correctly but I keep getting this error.

Abstract type X must resolve to an Object type at runtime for field Proj.X with value 'GY', received 'null'."

Rather than paste 10 cs files here I thought it would be more helpful to people if they could just clone the repo and inspect my code that way.

So I put it here: https://github.com/MagenicJB/GraphQLInterfaces

I'm sure I am doing something wrong so just point me in the right direction please.

TIA

**Comment by SimonCropp** [comment]
@MagenicJB sorry for the much delayed response. have you found a solution to this in that time?

**Comment by sungam3r** [comment]
@MagenicJB Thanks for the example. I was able to reproduce the error. Unfortunately, it is not always possible to respond on time, even if the fix is so simple as in this case. Read this:  https://graphql-dotnet.github.io/docs/getting-started/interfaces#registertype

Fix:
```c#
 public InvestorPortfolioSchema(IDependencyResolver resolver): base(resolver)
        {
            Query = resolver.Resolve<InvestorPortfolioTypeQuery>();
            // ADD THESE 2 LINES TO FIX
            RegisterType<HighRiskStocksType>();
            RegisterType<LowRiskStocksType>();
        }
```

After that, you will see other errors that are related to the fact that your graph types do not implement the necessary interface `RiskStocksInterface`. They simply do not have the required fields. Fields need to be added manually, they are not inherited. The interface contains only field declarations and all implementations must comply with this declaration and specify field resolvers.

**Comment by sungam3r** [comment]
@MagenicJB I hope you already solved the problem.
