### ISSUE TITLE
Check if the property is read-only

### ISSUE THREAD

**Issue by jdiaz-korewireless** [graphql-dotnet/graphql-dotnet#1130]
Wouldn't it be useful to check if the property is not ready only by using `property.CanWrite()`?

Code: https://github.com/graphql-dotnet/graphql-dotnet/blob/febf2b0637628436d8fe5b84d4f51afdfef7a58a/src/GraphQL/ObjectExtensions.cs#L39

Or maybe we can create an [Ignore] attribute to skip the mapping of certain properties, regardless its level of accessibility.

**Comment by sungam3r** [comment]
The remark as a whole is correct, but checking for `property.CanWrite()` with not setting the value makes it difficult to debug. This method is used mostly to convert a dictionary of input argument values into a single root object. It seems to me that an explicit (special) exception would be more useful in this case.

Also I think that there will be little benefit from the custom `[Ignore]`attribute, since the types of arguments are usually created specifically for use in the GraphQL API, there is no need to ignore for other use cases because there are no such scenarios (at least it's hard for me to imagine them).

**Comment by sungam3r** [comment]
@jdiaz-korewireless #1286 fixes this and is waiting for a review.

**Comment by sungam3r** [comment]
@jdiaz-korewireless You can try the latest preview version.
