### ISSUE TITLE
Can I access UserContext in the type constructor?

### ISSUE THREAD

**Issue by danleydmello** [graphql-dotnet/graphql-dotnet#1135]
Hi,

I am creating a type that's derived from ObjectGraphType and adding fields to it dynamically. This works great, Now we need information from HttpRequestMessage in the constructor of this type.  How can I get access to HttpRequestMessage instance outside the Controller?
I tried setting it to Usercontext on ExecutionOptions in DocumentExecuter but UserContext is not available in ObjectGrapType. Is there a way I can achieve this?

**Comment by joemcbride** [comment]
Indeed, you can't access the `UserContext` from the constructor, but you can access the UserContext in the resolver for the field.

```csharp
public class StarWarsQuery : ObjectGraphType
{
  public StarWarsQuery()
  {
    Field<DroidType>(
      "hero",
      resolve: context =>
      {
        // context.UserContext
        return new Droid { Id = "1", Name = "R2-D2" }
      }
    );
  }
}
```

**Comment by sungam3r** [comment]
You **can** access httpcontext in constructor if you create your schema and types as scoped services. Then you can inject `IHttpContextAccessor`.

**Comment by sungam3r** [comment]
You **can** access httpcontext in constructor if you configure your schema/types as scoped services in di container. Then you can inject `IHttpContextAccessor` - https://docs.microsoft.com/ru-ru/dotnet/api/Microsoft.AspNetCore.Http.IHttpContextAccessor?view=aspnetcore-2.1

**Comment by danleydmello** [comment]
@sungam3r , I forgot to mention that I am using HttpSelfHostserver, that means Httpcontext is no good for me. Does types are initiated before Document.ExecuteSync() is called ? And the Schema and types instance are supposed to be a singleton and shared by all the request?

**Comment by sungam3r** [comment]
> Does types are initiated before Document.ExecuteSync() is called ?

Do you mean `DocumentExecuter.ExecuteAsync` ? In principle, yes, by the time this method is called, a scheme has already been created, for example by means of a [middleware](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/GraphQLMiddleware.cs#L34).

Schema and types instances are supposed to be of any scope you want - singleton, scoped etc. I prefer to use singleton, unless there is a compelling reason to do otherwise. Still, the scheme is meta-information, which is usually static. I'm not familiar with HttpSelfHostserver, but I am sure that there is nothing in it that could limit the ability to create objects of one or another scope. I see that there is a DI - `HttpConfiguration.DependencyResolver`, so theoretically you can put scoped `HttpRequestMessage` or the object by which to get it into DI.

**Comment by danleydmello** [comment]
Thank you very much @sungam3r  for clarification. I think I will go with DI approach.

**Comment by sungam3r** [comment]
@danleydmello Is this issue still actual for you?

**Comment by danleydmello** [comment]
No,its all good now. Thanks
