### ISSUE TITLE
Make UserContext IDictionary<object, object>

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#1143]
I think the `UserContext` should be `IDictionary<object, object>`. 

I saw that `ExecutionOptions.UserContext` was recently changed to `IDictionary<string, object>`, but I think it should be changed to `IDictionary<object, object>` with a non-existent key returning `null` rather than throwing an exception. This would closely model `HttpContext.Items`. 

Additionally, `FieldResolverContext.UserContext` is still an `object` and should be updated to match `ExecutionOptions.UserContext`.

@joemcbride, @SimonCropp, thoughts?

**Comment by SimonCropp** [comment]
given this context could be shared between multiple different libs extending  graphql-dotnet, isnt there a risk non-strings dont allow enough scoping to make keys unique?

**Comment by johnrutherford** [comment]
@SimonCropp, on the contrary, it allows for far more options for keys. You can still use strings and most people probably will. But with this change, the key could also be a custom class/struct which implements the necessary equality stuff, a specific internal object instance, etc.

**Comment by joemcbride** [comment]
If we were to change it, would it make more sense to just switch it to `IDictionary` vs. `IDictionary<object, object>`?  `HttpContext.Items` is just `IDictionary`.

**Comment by johnrutherford** [comment]
I don't think it's recommended to use non-generic collections anymore except for backwards-compatibility.

`HttpContext.Items` in ASP.NET Core is an `IDictionary<object, object>`, it may be `IDictionary` in the old ASP.NET, but that's probably because it originated before generics were introduced.

**Comment by joemcbride** [comment]
Good enough for me.  I hadn't noticed that change yet.

**Comment by zlepper** [comment]
A note on that from how we use it: We assign a custom object from our auth middleware in there, which makes it very easy to grab, so changing `FieldResolverContext.UserContext` to a dictionary would require us to update quite a bit of code.

Though this is for a breaking change, so it might be alright, but please do consider that case also :)

**Comment by SimonCropp** [comment]
@zlepper does making your context class inherit from dictionary make it easier?

**Comment by zlepper** [comment]
That could certainly work around the issue, though it would allow people to write arbitrary values, which I doubt we want.

**Comment by zlepper** [comment]
Nevermind, replied too fast: 
Our model extends ClaimsPrincipal, so we can't extend Dictionary also. We need to extend ClaimsPrincipal to assign our object to HttpContext.User.

**Comment by SimonCropp** [comment]
We expose claimsprincipal in our our use contexts as well. But we do it as a property, not via inheritance

**Comment by zlepper** [comment]
I certainly believe there are other solutions, such as putting our own model in a claim, and then accessing it, and creating the dictionary for graphql from that, however i just wanted to put the information out there, that this might break some applications :)

There is nothing that can't be solved by adding more abstractions :D

**Comment by sungam3r** [comment]
Just want to clarify.

1. Change in itself does not require much effort, but there is doubt whether it is really necessary.
2. > You can still use strings and most people probably will. But with this change, the key could also be a custom class/struct which implements the necessary equality stuff, a specific internal object instance, etc

@johnrutherford Existing code that receives dictionary keys will then not be able to count on the fact that these are strings.

3. > I think it should be changed to IDictionary<object, object> **with a non-existent key returning null rather than throwing an exception**

@johnrutherford We can’t control it in any way. It completely depends on the implementation of the interface. Most people will use `Dictionary<>` as base class for `UserContext`, so the vast majority will likely rely on exception if accessing a non-existent key.

This issue is included in 3.0 milestone. So I just want to make sure that this change is really worth making.

**Comment by sungam3r** [comment]
bump

**Comment by SimonCropp** [comment]
my preference is to keep it as `IDictionary<string, object>`. mostly since i think it makes the contract clearer

i suspect "HttpContext.Items in ASP.NET Core is an IDictionary<object, object>" is for legacy reasons. for comparison in aspnet core they seem to favour  `IDictionary<string, object>` for many other things.

 * https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.viewdatadictionary?view=aspnetcore-3.1
 * https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.viewfeatures.itempdatadictionary?view=aspnetcore-3.1

but i wont loose any sleep over it if it moves to `IDictionary<object, object>`

**Comment by sungam3r** [comment]
> mostly since i think it makes the contract clearer

Agree. I think we need to leave `IDictionary<string, object>`.

**Comment by sungam3r** [comment]
So... closing this one.
