### ISSUE TITLE
Make DataLoader integration simpler

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#1145]
With changes to the UserContext in #1143, I'd like to make DataLoader integration much simpler.

I could add an `EnableDataLoader` boolean to `ExecutionOptions`. This would create the `DataLoaderContext` and set it on the `UserContext`. I would add some extension methods for easily getting the `DataLoaderContext` from a `ResolveFieldContext`. Then `IDataLoaderContextAccessor` could be optional for dependency injection.

**Comment by Shane32** [comment]
@johnrutherford Do you plan to work on this for 3.1, or if not, 4.0?  I'd like to assign the correct milestone, or remove the milestone if you do not know when you will be working on this.

Also, you may wish to reconsider your plans in light of #1730 and #1511 .  Specifically, you can now write an extension function that pulls the `DataLoaderContext` via the `IDataLoaderContextAccessor` via the `IResolveFieldContext.RequestServices` property.  Although it still requires registering the document listener, it would work just fine with `DefaultServiceProvider` because the `AsyncLocal` declaration is now `static` (changed in PR #1511).

It's also possible to have the extension function access the `AsyncLocal` member directly (by changing it to an internal declaration), but this would prevent the new extension function from working with any other `IDataLoaderContextAccessor` implementations.

Note that users can also register the `DataLoaderContext` as a scoped service and ignore the `DataLoaderContextAccessor` and `DataLoaderDocumentListener` classes entirely.  (This is how I use data loaders.)  An extension function could pull `DataLoaderContext` directly from `IResolveFieldContext.RequestServices`.  This requires a "real" service provider, of course; `DefaultServiceProvider` is inadequate as it only supports transient services.

**Comment by Shane32** [comment]
I suggest we close this issue, for reasons described above.

**Comment by sungam3r** [comment]
OK
