### ISSUE TITLE
Changes to IFieldResolver

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/graphql-dotnet#1146]
I've had some thoughts on changes to `IFieldResolver` and `ResolveFieldContext`.

Currently `IFieldResolver.Resolve()` returns an `object`, but in many cases this may be a `Task<T>`, so we need to check that.

I think it would make more sense to have it be async first and return a `Task` or `Task<T>`. The problem with `Task<T>` is that we still have to do tricks to get the value from the task after it has been awaited. So what if we instead added a `Result` property on the `ResolveFieldContext`? The `ResolveAsync` implementation must set the `Result` property before returning.

``` csharp
public interface IFieldResolver
{
    Task ResolveAsync(ResolveFieldContext context);
}
```

So, for example, the `ExpressionFieldResolver` would look like this:

``` csharp
public class ExpressionFieldResolver<TSourceType, TProperty> : IFieldResolver
{
    private readonly Func<TSourceType, TProperty> _property;

    public ExpressionFieldResolver(Expression<Func<TSourceType, TProperty>> property)
    {
        _property = property.Compile();
    }

    public Task ResolveAsync(ResolveFieldContext context)
    {
        context.Result = _property((TSourceType)context.Source);
        // We don't need to do Task.FromResult(), so there are fewer allocations
        return Task.CompletedTask;
    }
}
```

This would make it simpler and more performant to get the result from field resolution.

The FieldBuilder stuff would stay the same so you could still just return the value from your resolve function.  The `AsyncFieldResolver` would look like this:

``` csharp
public class AsyncFieldResolver<TSourceType, TReturnType> : IFieldResolver
{
    private readonly Func<ResolveFieldContext<TSourceType>, Task<TReturnType>> _resolver;

    public AsyncFieldResolver(Func<ResolveFieldContext<TSourceType>, Task<TReturnType>> resolver)
    {
        _resolver = resolver ?? throw new ArgumentNullException(nameof(resolver), "A resolver function must be specified");
    }

    public async Task ResolveAsync(ResolveFieldContext context)
    {
        context.Result = await _resolver(context.As<TSourceType>());
    }
}
```

**Comment by sungam3r** [comment]
> Currently IFieldResolver.Resolve() returns an object, but in many cases this may be a Task<T>, so we need to check that.

Isn't it already happening [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionStrategy.cs#L221)? `IFieldResolver` does his job even returning object.
What goal is achieved?

**Comment by johnrutherford** [comment]
@sungam3r yes, it works now, but to get the result, we have to cast the task to `dynamic` and call `.Result`. This has a perfomance hit. 

It's also a bit unintuitive to return a `Task` or `Task<T>` when the return type for an interface method is `object`. 

The proposed changes would simplify things and make the usage less ambiguous.

**Comment by sungam3r** [comment]
@johnrutherford After working on #1441 it seems to me that your proposal is useful. Indeed, it saves a number of `Task<T>` allocations and makes some internal code a little easier. The only thing I don't like is the need for customers to rewrite all of their resolvers. Moreover, they may not even notice that they need to change the code by assigning the `Result` property. As a result, resolvers will silently "return" `null`. If the field not required (nullable), then graphql api will continue to work, but produce inadequate results. This is obviously a case of backward incompatibility. Another thing is that this is the most dangerous case when this backward incompatibility is well hidden. @joemcbride @Shane32 @johnrutherford what do you think?

**Comment by Shane32** [comment]
Just firing from the hip here, but I really don't like the idea that the Resolve function would expect the consumer to store the result inside context.Result.  Sorry to be so negative, but it seems like a complete anti-pattern if I ever saw one.  If the design were to change, I would strongly consider renaming the Resolve method so it more accurately reflects the operation -- e.g. `SetResultAsync`.  Then at least it would be a little more obvious what was expected of the implementation.

Further, I don't imagine that benchmarks are going to show a significant performance improvement.  Think about it: Does it help truly asynchronous functions?  Barely; they still need a Task created to await on, but you do eliminate a `dynamic` call to `task.Result`.  Does it help synchronous functions?  As it is now, there is a single `if (result is Task task)` check, which returns false, skipping the `dynamic` call to `task.Result`.  So the maximum performance benefit that could be gained for synchronous calls is removing the single `is` check, which amounts to almost nothing (as discovered while working on PR #1500 ).

So bottom line is that:
1. It is an undesirable coding pattern
2. I don't think it's even possible to see a speed benefit here, and if there was one, it would be extremely small
3. It can (and will) cause the above backwards incompatibility issues @sungam3r previously noted

That all being said, if a speed benefit exists that is truly desired here, I'd be okay with making these changes, so long as they remain completely internal to the project (perhaps with an IFieldResolverInternal interface), and the existing IFieldResolver interface, FuncFieldResolver, and AsyncFieldResolver classes remain in place.  The FuncFieldResolver class could take advantage of the "enhanced" performance, while a wrapper class could take results from IFieldResolver.Resolve, and pass them back through the new IFieldResolverInternal interface to the execution strategy.  This idea is complicated by the fact that the ExecutionStrategy is public, so there remains some issues to work out along this train of thought.  Perhaps there is a nice middle ground somewhere.

Lastly, we would need to be sure that out-of-order execution does not cause problems with the new code design.  Specifically, if the execution strategy is checking `task.TaskStatus == RanToCompletion` directly rather than awaiting it (as would likely be done for maximum performance), there must be a memory barrier before reading `context.Result`.  This check offsets gains from eliminating the `is Task` check, although given this should be quicker.

@sungam3r You mentioned that this design might eliminate a number of `Task<T>` allocations.  I must be missing something, as I don't see it.  Where are you thinking?

Last comment: performance could possibly be gained by changing the return signature of `ExecuteNodeAsync` to simply `Task` rather than `Task<ExecutionNode>`.  The compiler could then internally use `Task.CompletedTask` when returning from the function under synchronous circumstances instead of creating a `Task<T>`.  I have not yet run benchmarks to prove or disprove this theory, but there certainly is no need for the return value here, as it will always equal the ExecutionNode that was passed to it from the caller.

**Comment by sungam3r** [comment]
>  Where are you thinking?

As a rough example:

```c#
 public async Task ResolveAsync(ResolveFieldContext context)
    {
        var a = await someservice.GetStringAsync();
        return Task.FromResult(a + "my_data"); 
    }
```

vs

```c#
 public async Task ResolveAsync(ResolveFieldContext context)
    {
         var a = await someservice.GetStringAsync();
         context.Result = a + "my_data";
    }
```

The point is that we untie the function of waiting for the result from the function of storing the result inside of `Task<T>` (no result boxing).

In general, I want to say that I am skeptical about such optimizations, since with an unknown (minimal) gain they raise a lot of questions. If we are already engaged in optimizations, then there are many other places where the effect will be much more visible.

**Comment by Shane32** [comment]
I get the concept, but your first sample isn't valid code.  Within an `async` function, you cannot return a `Task<T>` -- you return the value and the framework boxes it if necessary.  `Task.FromResult` is only used in **synchronous** functions that return a `Task<T>`.  And if it was a synchronous function, they should just return the value instead of a boxed value from the resolver.  Further, in the second example, a unique `Task` class must be created by .Net due to the `await` in the function that executes `context.Result = a + "my_data";` after the awaited value is returned.  So you don't save an object creation.

For an asynchronous function (containing an `await`), maybe there's a benefit at the end of the await chain where it returns the value .... and maybe there isn't.  A `Task<T>` already exists either way for sure.  I'd bet there isn't.

> In general, I want to say that I am skeptical about such optimizations, since with an unknown (minimal) gain they raise a lot of questions. If we are already engaged in optimizations, then there are many other places where the effect will be much more visible.

I agree

**Comment by Shane32** [comment]
I just checked -- it definitely does not save an object creation between the two sample code snippets above (assuming the syntax error was fixed in the first sample) -- even if the GetStringAsync function returns synchronously.

**Comment by Shane32** [comment]
Scratch that... the compiler DOES do some optimizations when GetStringAsync runs synchronously.  So as long as the await chain runs synchronously, it is possible to save an object creation.

**Comment by sungam3r** [comment]
>  your first sample isn't valid code. Within an async function, you cannot return a Task<T> -- you return the value and the framework boxes it if necessary.

I know. It was an unsuccessful attempt to demonstrate what was happening (boxing).

**Comment by sungam3r** [comment]
>  your first sample isn't valid code. Within an async function, you cannot return a Task<T> -- you return the value and the framework boxes it if necessary.

I know. It was an unsuccessful attempt to demonstrate what was happening (boxing).

**Comment by sungam3r** [comment]
Nevertheless, it seems to me that we have shifted our focus to optimization. The primary intention of this issue was to simplify the design itself, in order to do less manipulation with `Task/dynamic`. I think it’s worth doing PR and see what happens. We will see whether the code has become simpler or if significant changes have been required on the caller, which have hidden all the benefits. In addition, with the help of benchmarks it’s now easy to check whether there will be at least some improvement.

**Comment by sungam3r** [comment]
> I just checked -- it definitely does not save an object creation between the two sample code snippets above (assuming the syntax error was fixed in the first sample) -- even if the GetStringAsync function returns synchronously.

@Shane32 Would you like to make PR?

**Comment by Shane32** [comment]
Sounds like fun. If I have time this weekend I’ll do it.

**Comment by Shane32** [comment]
But we probably need a relevant benchmark since I’m guessing introspection doesn’t use async fields. Perhaps a couple variations of the hero query will do ?  Guess I’ll cross that bridge when I come to it

**Comment by sungam3r** [comment]
Of course, you can make special schema for this test with relevant async/sync resolvers to compare results.

**Comment by sungam3r** [comment]
I propose to close this issue and the associated PR as `wontfix`.

**Comment by sungam3r** [comment]
It's time.
