### ISSUE TITLE
Schema first should fail on schema buildup when types not match schema

### ISSUE THREAD

**Issue by lanwin** [graphql-dotnet/graphql-dotnet#1155]
## Summary

Schema first should fail on schema build up (application start) if schema does not match the given types (even if the types are not used).

### Basic example
```csharp
public class Query
{
    public Test Test()=> new Test();
}

public class Test
{
    public string Id => "foo";
}
               
static void Main(string[] args)
{
    var schema = Schema.For(@"
        type Test{
            id: ID!
            name: String!
        }

        type Query {
            test: Test!
        }
        ", _ =>
    {
        _.Types.Include<Query>();
    });

    var json = schema.Execute(_ =>
    {
        _.Query = "{ test { id } }";
    });
}
```
In the given example I would expect  `Schema.For` or `schema.Execute` fail with an exception that tells my that there is a property `name` on type `Test` which has no resolver assigned.

### Motivation

While playing with the newer schema first stuff, I discovered that its pretty easy to get stuff wrong without knowing it.

My expectation is that it fails on start/schema build up or that there is a method like `schema.validate()` which tells me that I missed that my schema is wrong. 

The current approach means that I or my users have to do a query to know that the schema fails.

**Comment by sungam3r** [comment]
@lanwin Thank you for report. I wanted to check what you wrote for a very long time. Indeed, fields may not have a resolver. In this case, [`NameFieldResolver`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Resolvers/NameFieldResolver.cs) is used. The difficulty of detecting an erroneous situation is that the result of the `NameFieldResolver` depends on the object that is used in runtime (source, parent object). See #2005 . I added two special tests. One does indeed result in an error - `issue_1155_throws`, as you wrote. But the other one - `issue_1155_with_custom_root_does_not_throw` - succeeds due to the fact that it uses another object at runtime. That is why it is difficult to tell if the scheme is wrong. The schema itself is not enough, it depends on the state passed inside the schema when the request is executed. At least I came to this conclusion. I myself would like to have stricter checks. Perhaps @joemcbride or @Shane32 will be able to suggest something.

**Comment by sungam3r** [comment]
@lanwin So could/should this issue be closed?

**Comment by lanwin** [comment]
@sungam3r I am not exactly sure if I understood your answer correctly. So the case I reported above will now throw a proper exception? But there is another case witch may will not be able to throw an exception?

**Comment by Shane32** [comment]
I think it is possible to implement this feature in a limited fashion, but it may break down for for complicated schemas, such as if unions were defined.  Of course if `Test()` returned an `object`, then type checking would not be possible.

@sungam3r I'd think all that would be necessary is to walk the object tree during `Schema.For`, matching the defined fields with available methods/properties on the class, walking the schema recursively so long as the field's matching method/property returns a well-defined object (e.g. an interface/class, not `object` or `Task<object>`).

**Comment by sungam3r** [comment]
> So the case I reported above will now throw a proper exception? But there is another case witch may will not be able to throw an exception?

No, I have not added any new checks during the schema build phase. As I said earlier, this information is not enough, because correctness depends on the values used at runtime.

**Comment by sungam3r** [comment]
> with **available** methods/properties on the **class**

What class and what is _available_?

@Shane32 I thought exactly the same when I started to solve this problem. But what about inheriting classes or interfaces? This information is only available at runtime. That is, we *can* add additional checks, but they will either be redundant or insufficient. I am always in favor of additional checks to maintain correctness. But in this case (precisely described above) I cannot do that.

Let's look at a specific example, I wrote tests for it. One test generates an error, the other succeeds. What does this tell us?

**Comment by Shane32** [comment]
I fail to understand where the difficulty is.  Of course if you pass in another type at runtime than what is expected, it will produce a runtime error, just as if you return the wrong type of object back from a field resolver it produces a runtime error.  That doesn't mean that compile-type checks (in this case, schema-build-time-checks) are not valid.  So if we added code to validate the schema at schema build time, of course it would produce an error if you validated it against `Query` with fields that do not exist in the object tree.  You should validate the schema against `QueryEx` if you plan to pass an instance of `QueryEx` to the `RootValue` property and want to use the `name` field on `TestEx`.  This would be all be expected.  Further, as would be expected in any OOP design, using an instance of `QueryEx` for the root value on a schema that was validated against `Query` should work perfectly.

**Comment by sungam3r** [comment]
It is *possible* that there is no difficulty. It is generally possible to agree that each field after creating a schema **must** have `Resolver` property set (not `null`). Now if it is not set, then `NameFieldResolver` is used: `var resolver = node.FieldDefinition.Resolver ?? NameFieldResolver.Instance;`. It won't be a problem to set it up ahead of time, because we've been using a shared `NameFieldResolver.Instance` for a long time (so no additional memory cost). Then the check is reduced to the fact that the each `Resolver` property should not be equal to `null`.

**Comment by sungam3r** [comment]
@lanwin Done. Fix will be published in v4.
