### ISSUE TITLE
Provide json property names in ExecutionResult

### ISSUE THREAD

**Issue by ManuelDeLeon** [graphql-dotnet/graphql-dotnet#116]
Shouldn't ExecutionResult provide the json property names with the correct case?

```cs
    public class ExecutionResult
    {
        [JsonProperty(PropertyName = "data")]
        public object Data { get; set; }

        [JsonProperty(PropertyName = "errors", NullValueHandling = NullValueHandling.Ignore)]
        public ExecutionErrors Errors { get; set; }
    }
```

That way you don't get errors if you decide not to force camelCase on your JSON objects:

```cs
    public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            config.Formatters.Clear();

            //var settings = new JsonSerializerSettings();
            //settings.ContractResolver = new CamelCasePropertyNamesContractResolver();

            //config.Formatters.Add(new JsonMediaTypeFormatter { Indent = true, SerializerSettings = settings });
            config.Formatters.Add(new JsonMediaTypeFormatter { Indent = true });

            // Web API routes
            config.MapHttpAttributeRoutes();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "api/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
            );
        }
    }
```

**Comment by joemcbride** [comment]
Currently, this project ILMerge's its own version of Json.NET, so those `JsonProperty` attributes will only apply if you use the `DocumentWriter`.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Http/DocumentWriter.cs

Those values should always be lowercase to conform to the GraphQL spec.

**Comment by ManuelDeLeon** [comment]
The thing is that without the camel case resolver I get "Data" instead of
"data". If I add the json property name or just rename the property to
lowercase I get the proper casing ("data") without the camel case resolver.

**Comment by joemcbride** [comment]
That would be expected if you're not using the `DocumentWriter`.  You will also have issues with the formatting of errors if you're not using the `DocumentWriter`.

**Comment by ManuelDeLeon** [comment]
I'm confused about the following statements (they seem to contradict themselves):
`those JsonProperty attributes will only apply if you use the DocumentWriter.` (regarding https://github.com/graphql-dotnet/graphql-dotnet/issues/116#issue-163246025)
And:
`That would be expected if you're not using the DocumentWriter` (regarding https://github.com/graphql-dotnet/graphql-dotnet/issues/116#issuecomment-229798447)


Assuming ExecutionResult doesn't need JsonProperty or a change of case, how should I modify the `GraphQL.GraphiQL` project so that it doesn't force camel case on the JSON objects?

**Comment by joemcbride** [comment]
I didn't realize you were using the source code directly and not the Nuget package.  Though my statements still apply. I don't know why its not working in your specific case - I don't know what version you're running or what changes you have made.  You are running an older version of the source.

The latest source relies on the formatter settings configured in the `DocumentWriter` combined with a custom converter on the `ExecutionResult` class.  An older version of the GraphiQL sample didn't use the `DocumentWriter` and didn't have the custom converter.

I would suggest to get the latest source.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionResult.cs
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionResultJsonConverter.cs
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.GraphiQL/Controllers/GraphQLController.cs

**Comment by ManuelDeLeon** [comment]
I'm using the Nuget version on my project but let's take your `GraphQL.GraphiQL` example. 

I just cloned the whole project, restored the packages, and modified the character interface (in StarWars) so that the name is PascalCase (also updated Droid and Human to match).

At this point the schema returns the right case ("Name"), the intellisense also yields the correct result, but when I run the query, name is lowercase.

Query:
```
{
  hero {
    Name
  }
}
```

Result:
```
{
  "data": {
    "hero": {
      "name": "R2-D2"
    }
  }
}
```

What else do I need to do on your sample project(s) so that the JSON comes back with the right case?

**Comment by joemcbride** [comment]
You would have to remove the formatter in the `DocumentWriter` class.  That is not currently possible with the Nuget package.

Note that the GraphQL spec requires certain properties to be lowercase, such as the `errors` and `data`.  There could be others that I haven't ran into due to the use of the formatter.  The `errors` and `data` should be taken care of with `ExecutionResultJsonConverter` though.

**Comment by joemcbride** [comment]
You could possibly work around this issue by doing:

1. Create your own `DocumentWriter` class without the formatter settings
2. Create a new object with the same properties as `ExecutionResult`
3. Create a local copy of the `ExecutionResultJsonConverter`
4. Apply that converter to your new object
5. Use your local `DocumentWriter` to serialize the result

This is currently an issue because JSON.NET is ILMerged with the Nuget.  I will probably stop doing ILMerging sometime in the future to fix this issue and because .NET Core doesn't support it.

**Comment by ManuelDeLeon** [comment]
Why does DocumentWriter forces JSON objects to have camelCase keys in the first place? I mean, `data` and `errors` can be lowercase (along with the rest of GraphQL specific keys) and the user's JSON object keys maintain their case.

**Comment by joemcbride** [comment]
That is how I built it.  I always try to use camelCase on all of my Apis since they are typically being used by JavaScript.

I'm willing to review a PR if you want to make it configurable.

**Comment by ManuelDeLeon** [comment]
Making it configurable doesn't make much sense. Wouldn't you agree with following?

1) The client should receive the object keys in whatever casing the schema has. If the schema says `Name` the object key should be `Name`, not `name`.

2) The client should receive the object keys in whatever casing their alias has. If they query `Name: name` the object key should be `Name`, not `name`.

**Comment by joemcbride** [comment]
No, I purposefully set it up so it would always output camelCase.  My opinion is they should always be camelCase.  I would consider registering a field name as PascalCase a bug in my API.  I understand that you want that to behave differently so I'm willing to accept a PR to make that behavior configurable, keeping the current default behavior.

**Comment by ManuelDeLeon** [comment]
I understand you use camelCase and indeed it would be a bug in your API if a field is PascalCase. My point is that forcing the response to be camelCase doesn't prevent you from having casing bugs in your API. 

Consider the scenario where you make a typo and give a field the name `StateCode` instead `stateCode`. Without forcing the case in your output you have a bug in your API: case not matching the convention. If you force camelCase in your output you'd still have a bug: the schema is different than the output.

And then there's the issue of the consumer of your API not being able to alias the fields to whatever case they want.

Now if you don't think it's a bug for the output to be different than the schema and the aliases, then I'll see about that PR. It's your library after all.

**Comment by joemcbride** [comment]
>My point is that forcing the response to be camelCase doesn't prevent you from having casing bugs in your API.

From my previous response:
>I would consider registering a field name as PascalCase a bug in my API.

As for Aliases, no, everything should be camelCase.  When you have the requirement that everything should be camelCase, none of those issues apply.

I've known about this for a long time.  I even went as far as starting to [enforce it on field name registration](https://github.com/graphql-dotnet/graphql-dotnet/blob/639a625c55cacd2186940976f590a03f27320bae/src/GraphQL/GraphQL.cs#L439) on the vNext spike to ensure uniformity.

If you want that feature, write the code and submit it.  Its as simple as that.  That is what Open Source is about.  Collaboration and helping each other.  However, you are exactly right.  If I don't want that feature in this project I have every right to refuse it.  In this case, I would accept code for that feature.

All the time you've spent trying to convince me otherwise you probably could have written the code.
