### ISSUE TITLE
MissingMethodException ExecutionOptions.set_user

### ISSUE THREAD

**Issue by ronMilne** [graphql-dotnet/graphql-dotnet#1168]
When launching the UI Playground, I receive the aforementioned exception, this is the full exception stack trace.

```cs
System.MissingMethodException: Method not found: 'Void GraphQL.ExecutionOptions.set_UserContext(System.Object)'.
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.GetOptions(String operationName, String query, Inputs variables, Object context, CancellationToken cancellationToken)
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.ExecuteAsync(String operationName, String query, Inputs variables, Object context, CancellationToken cancellationToken)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
I'm unsure on how to actually fix it? This is what I have in configure services
```cs
services.AddScoped<IDependencyResolver>(s => new FuncDependencyResolver(s.GetRequiredService));
services.AddScoped<FlightInformationSchema>();
services.AddGraphQL(opt => opt.ExposeExceptions = true).AddGraphTypes(ServiceLifetime.Scoped)
```

.Net Core 3 Preview 5 hosted within Kestrel.

I have the following nuget references defined

GraphQL (3.0.0-preview-1141)
GraphQL.Server.Transports.AspNetCore (3.4.0)
GraphQL.Server.AspNetCore.Playground (1.0.0-beta2)

Ron.

**Comment by sungam3r** [comment]
Hey. I know this problem well. It is caused by the fact that you are using the new version of GraphQL, but old versions of other packages - GraphQL.Server.Transports.AspNetCore and so on. There are some problems with supporting these projects - https://github.com/graphql-dotnet/server/issues/193
There backward compatibility between GraphQL 2.4.0 and 3.0.0 is lost (`set_UserContext` method changed). As a result, I simply rebuilt all the necessary packages locally and placed them in the corporate repository. You need to synchronously update the upstream packages so that they match the new GraphQL API.

**Comment by joemcbride** [comment]
Updated NuGet packages for the server project have been published that support the 3.0 preview of the GraphQL Project.  Look for version `3.5.0-alpha0014` (will take it a bit for Nuget to index it).

**Comment by pjvds** [comment]
@joemcbride I can confirm that upgrading to `3.5.0-alpha0014` for `GraphQL.Server.Transports.AspNetCore` and the websocket variant fixed this issue.

**Comment by sungam3r** [comment]
Resolved.
