### ISSUE TITLE
DataLoader and SerialExecutionStrategy not bulking

### ISSUE THREAD

**Issue by kYann** [graphql-dotnet/graphql-dotnet#1191]
## Description

When using DataLoader and SerialExecutionStrategy, the DispatchAllAsync is executed after each nodes, loosing the benefit of dataloader on list.

### Steps to reproduce

Set SerialExecutionStrategy for Query.
Return List of item where one of the Field is using the BatchLoader
Put a breakpoint in your fetch function and see only one id in the list.

### Expected result

The fetch function should be called after all the nodes have been executed

### Actual result

Fetch function is called after each node have been executed

### Environment

Windows, GraphQL 2.3.0

**Comment by Shane32** [comment]
This is an important feature, due to the fact that there is no Dependency Injection scope management when running the ParallelExecutionStrategy, preventing the parallel strategy from being used with class libraries which rely upon scoped services.  Hence, the SerialExecutionStrategy is often a requirement, preventing the use of DataLoaders at present.

The DataLoader mechanism should be redesigned to support proper operation within a SerialExecutionStrategy.  I suggest something like this (when run with the SerialExecutionStrategy):

1. All queued nodes that are not data loaders should be run
2. All data loader nodes should be prepped
3. All data loaders should be run
4. All data loader nodes should be resolved
5. Loop above steps

This is not possible with the current DataLoader design, and might unfortunately require that the DataLoader functionality be more tightly integrated to graphql.

**Comment by sebastienros** [comment]
Also blocking for OrchardCore. We need to use Serial Execution (for all the bad things that can happen with the parallel one), and then data loaders can't be used, which is a huge limitation in terms of perf.
