### ISSUE TITLE
How do I deserialize paginated arrays?

### ISSUE THREAD

**Issue by LukasRoper** [graphql-dotnet/graphql-dotnet#1225]
## Summary

A problem I've been running into recently is dealing with pagination of Json I receive from the server. I can work around some instances but would like a better approach. So this sample query here illustrates a problem I can run into:

Modules
    {
        ID
        Title
        Description
        Lessons
        {
            edges
            {
                node
                {
                    ID
                }
            }
        }
    }

So for the lessons array, the server inserts the edges and node elements because of the use of pagination. With pagination turned off, the structure of the request is much more as I expect:

Modules
{
    ID
    Title
    Description
    Lessons
    {
        ID
    }
}

I'm using JSON.Net with the C# library provided by GraphQL. 

I suppose two questions here, firstly is this difference expected in terms of the json I receive? And if that's the case, does anyone have workarounds they use?

Thanks!

**Comment by Shane32** [comment]
This question seems to be more of a client question as it relates to a specific API, rather than a question as to how to implement a specific design in GraphQL.NET.  Moreover as the question has not been answered in 4 years, I'm closing.  @LukasRoper if you have a question regarding the GraphQL.NET API, please ask - thanks!
