### ISSUE TITLE
Recursively nested query 

### ISSUE THREAD

**Issue by danleydmello** [graphql-dotnet/graphql-dotnet#1248]
I have nested schema like this

ClassA {
   int Prop1,
  ClassA Prop2
}

I can query this schema like:
```
query {
 ClassA {
     Prop2 {
        Prop1
      }
  }
}
```

The problem is the resolver does not add "Prop1" in the context.SubFields dictionary. 

If I change my above query to add Prop1 to ClassA field then it works:
```
query {
 ClassA {
    Prop1
     Prop2 {
        Prop1
      }
  }
}
```

Is this a bug or its by design that you need to include fields at all levels of recursively nested queries?

Thanks
Danley

**Comment by joemcbride** [comment]
Yes, that is by design and according to the GraphQL spec at present.  You will only get the fields you request.  You can use things like fragments to structure your queries, but recursion is not supported.

https://graphql.org/learn/queries/#fragments
https://graphql.org/learn/queries/#inline-fragments

https://github.com/graphql/graphql-spec/issues/91#issuecomment-206743676

**Comment by danleydmello** [comment]
Thanks @joemcbride
