### ISSUE TITLE
Remove all about IDependencyResolver

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#1283]
I suggest deleting this:

1. `IDependencyResolver`
2. `DependencyResolverToServiceProviderAdapter`
3. `FuncDependencyResolver`

It seems that there is no more sense in keeping them in code. The current alpha version is already backwards incompatible with version 2.4.0.

**Comment by abarger-bss** [comment]
I am interested in a reason for this change if any is available. The issue only states the code is already backwards incompatible.  Changes like this make me concerned for the upgrade path to 3.0 whenever it arrives. Let's not forget there has been a long gap since a stable release of the package. At some point IDependencyResolver was obsoleted in `Schema`, but because this was never released in a stable version, no one had a chance to comply voluntarily!

**Comment by sungam3r** [comment]
The reason is that this interface is redundant and creates unnecessary semantic load. Yes, it was tagged as `Obsolete` for a while. Now it is deleted. The documentation is updated accordingly.

I must say that even without this change, many new preview versions of graphql-dotnet and server packages contain backward incompatible changes. Sometimes it is necessary to fix existing errors, add features or simplify the design.

I hope for the forthcoming release of version 3.0, but it depends on the contribution of many participants.

**Comment by flieks** [comment]
@sungam3r thanks but where is this change in the docs.
this is still old: https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

**Comment by flieks** [comment]
nevermind i found it in your pr https://github.com/graphql-dotnet/examples/pull/25/files

**Comment by sungam3r** [comment]
See #1321
