### ISSUE TITLE
How to implement federated schemas?

### ISSUE THREAD

**Issue by luzannew** [graphql-dotnet/graphql-dotnet#1308]
First of all, thanks for the initial implementation for federated schemas.

## Summary
I have a question about how to implement federated schemas with the graphql-dotnet package. I saw a small example in the PR https://github.com/graphql-dotnet/graphql-dotnet/pull/1233 but I'm not sure how to implement this in a GraphType codebase.

## Relevant information

I tried it with this approach, but I have no clue how to use it? There is a For() which can be used to reference a type, but what type do I need to pass?

`
public class AccountsFederatedSchema : FederatedSchema
{ }`

### Environment (if relevant)
Package versions:
```
<PackageReference Include="GraphQL" Version="3.0.0-preview-1268" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0027" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.2.0" />
```

Could you provide an example how to use the federated schemas? Thanks!

**Comment by mac2000** [comment]
Seems like at moment it will not work for code first aproach (aka graphtype first) wondering for maintainers perspective of view what will be a good decision here, to make it easier in future to migrate things, lets imagine that we wish to start new project with few entities, we wish to split them upfront into different services and combine altogether in a gateway, e.g.:

![ideal world](https://www.plantuml.com/plantuml/svg/ROz12eD034NtEKMMTU4TTEMoXT8312QCmZYZIQHu-mw2CbftuV7V_wHH8x5b301jz4iWmRh6HqV6Nreh69xlCsYZapIuCuJZtFX7MHIzqDJF0Lsoo5PTCg-azf-1UxTeLKj2dd7AlkVSUbjKJEp2kEeSyaB3qUL_Vm00)

At moment we can not do it and there is few posible workarounds

![workaround1](https://www.plantuml.com/plantuml/svg/RP0n2iCm34LtdK9ZC-GEoTInXT8322pSW6CdaaB9xMjI6kmqctYy_mPrQYIsZ06WZtu99DYsUBcIyPlM1eRRemPzT986LqFOpuq_bKNH2qslEM1CZfk3SKzgHmFETaLFM0rTiiYMSoU5ebovS18ekcf9o3DEUUbvJ__PN_opnrNdaDiTHvVVzm40)

- easy to start from dotnet perspective (no graphql and new tech here)
- will be harder to make both dotnet and node schemas in sync
- will be harder to have a bullet prof ci/cd
- unnecessary layer of rest
- in future node wrapper can be removed and dotnet graphql used instead
- clients wont see change when things will swap

![workaround2](https://www.plantuml.com/plantuml/svg/ROux2e0m40Nxd69BKtW7FO62U810bZMGdxjhuUqDDeAadHaURn9rh5UAnioPhkWOnX46ObUFCu8lcb6j2SlMvNFsN8BlElCdRxKBie1eOKS8jOWIsdwwDlcbwPOpjjK9isz_7m00)

- will not have issues with ci/cd
- will be harder for multiple people to work together instead of own services they will work on little monolith
- data may be retrieved directly from different storages - will be harder to split in future
- when we will be able to split everything up all we gonna need from clients to change url from dotnet graphql to gateway


I'm just trying to figure out what other posible options and pros/cons might be here

**Comment by CyrilleFormont** [comment]
Hi there,
Any news about this ? It's becoming hugely important as schema stitching is depreciated

**Comment by sungam3r** [comment]
Unfortunately, I have not watched at the federated schemas yet, I can not advise anything. @joemcbride  was the one who added support for federated schemas.

**Comment by rohankasture** [comment]
Does anyone know how to write a federated schema using a schema-first approach using GRAPHL ASP DOT NET CORE?

I referred the below link but it's not working for me

https://github.com/graphql-dotnet/graphql-dotnet/pull/1233

**Comment by rohankasture** [comment]
namespace WebApplication1
{
    public class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
    }

    public class Query
    {
        public static User[] users = new[] {
        new User { Id = "1", Name = "Ada Lovelace", Username = "@ada" },
        new User { Id = "2", Name = "Alan Turing", Username = "@complete" }
    };

        public User Me()
        {
            return users[0];
        }
    }
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            var schema = FederatedSchema.For(@"
    extend type Query {
        me: User
    }

    type User @key(fields: ""id"") {
        id: ID!
        username: String!
    }
",
 _ =>
 {
     _.Types.Include<Query>();
     _.Types.For("User").ResolveReferenceAsync(ctx =>
     {
         var id = (string)ctx.Arguments["id"];
         var user = Query.users.FirstOrDefault(x => x.Id == id);
         return Task.FromResult(user);
     });
 });
          
            app.Run(async (context) =>
            {
                
                var result = await new DocumentExecuter().ExecuteAsync(doc =>
                {
                    doc.Schema = schema;
                  //  doc.Query = schema.Query;
                    
                }).ConfigureAwait(false);
                
                string json = await new DocumentWriter(indent: true).WriteToStringAsync(result);
                await context.Response.WriteAsync(json);
        
            });
         
        }
    }
}

1) I am having some issues on how do we write the app.Run block of code. It needs doc.Query but why I have to define the query again? Any alternative?

**Comment by SamuelCox** [comment]
Is there any movement on this front? I'm basically blocked from using graphql-dotnet because of this

**Comment by sungam3r** [comment]
Nope 😞

**Comment by SamuelCox** [comment]
Is there any way to help or an amount of sponsoring that would allow for this to happen? I appreciate it's really difficult given you're open source and don't necessarily have the resources

**Comment by mac2000** [comment]
#1669 it will become available here, probably after releasing the new version of graphql-dotnet, gonna need to figure out what has been changed and return to it, but at the moment guys are working on a new version hardly so federation is out of scope

**Comment by mac2000** [comment]
BTW @sungam3r it seems that this ticket may be closed in favor to code first proposal ticket

**Comment by sungam3r** [comment]
@SamuelCox If you mean financial sponsorship, I don't think it will have some kind of effect. Mostly two people now work constantly over the project. We work when there is a desire and time. Yes, as always in the OSS our time resources are very scarce and backlog is rather big.

**Comment by sungam3r** [comment]
I do not close the tickets that I do not understand. Let it be open until the feature is implemented.

**Comment by sungam3r** [comment]
>  probably after releasing the new version of graphql-dotnet, gonna need to figure out what has been changed and return to it, but at the moment guys are working on a new version hardly so federation is out of scope

Already done https://www.nuget.org/packages/GraphQL/

**Comment by mac2000** [comment]
@sungam3r that is awesome news! glad to see that, so probably there is a chance that we might return back to code first approach

**Comment by Mithras** [comment]
related https://github.com/graphql-dotnet/graphql-dotnet/pull/3144

**Comment by Shane32** [comment]
Federation 2 support is available for schema-first, code-first, and type-first schemas in GraphQL.NET 8.0 (still in beta at the time of writing). See:

- https://github.com/graphql-dotnet/graphql-dotnet/pull/3921

Complete samples are available for schema-first, code-first, and type-first, from within the repo.
