### ISSUE TITLE
Schema Generator

### ISSUE THREAD

**Issue by holm0563** [graphql-dotnet/graphql-dotnet#132]
I wanted to make the community aware of an enhancement I'm working on. I'm hoping this will be a useful addition and when its ready (withing a few days hopefully) can be pulled into the main branch. Any feedback is appreciated. Thanks!

https://github.com/holm0563/graphql-dotnet/blob/master/src/GraphQl.SchemaGenerator/README.md

**Comment by tlil87** [comment]
FYI: I have already developed a closed-source library for this that we're using in production. I'm currently working to port this over to an open-source repository which will live in [graphql-dotnet/conventions](https://github.com/graphql-dotnet/conventions). Expecting to have the public repo up some time over the next 7-10 days.

**Comment by holm0563** [comment]
I like forward to seeing it thanks! We are in a similar situation.

**Comment by joemcbride** [comment]
What @tlil87 and I talked about in https://github.com/graphql-dotnet/graphql-dotnet/issues/14 was having the "conventions" as a separate project/nuget.  That way if you're not using those conventions then they're not a part of your project.  Mostly because I can also see conventions for say MSSQL, or Postgres, etc.  We've made changes to the core project to support the scenarios that @tlil87 was facing.  If you need changes to support the enhancements you're making I'd welcome the changes.

**Comment by holm0563** [comment]
Thanks. This is currently setup as a separate project. I like the idea of a separate nuget package as well.

**Comment by tlil87** [comment]
@holm0563  FYI
>https://github.com/graphql-dotnet/conventions is up @drobertson123 @dlukez - i will provide more documentation for it soon. per now, the tests and example project are the best sources of information.

**Comment by joemcbride** [comment]
Going to go ahead and close this.
