### ISSUE TITLE
IAsyncEnumerable

### ISSUE THREAD

**Issue by MikeKenyon** [graphql-dotnet/graphql-dotnet#1320]
###  Summary

.NET Core 3.0/Standard 2.1 introduces the IAsyncEnumerable<T> type in order to support async pulls of data back from remote servers in efficient ways.  A typical pattern would feel to return an IAsyncEnumerable<T> back when performing an async lookup as this is doable for a single entity, for example.  However, the executor code [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/952b4ef6950e51bbfe009354f0520180c343e8d4/src/GraphQL/Execution/ExecutionStrategy.cs#L97) is such that it checks for derivation from IEnumerable and not from IAsyncEnumerable and there is no common parentage between the two.

### Basic example

The following code does not properly execute when the returned type of `manager.FindAsync()` is an `IAsyncEnuerable`.
```
            Field<ListGraphType<Graph.MediaEntity>>("findMedia",
                arguments: new QueryArguments
                {
                    new QueryArgument<MediaType>{
                        Name = "type",
                        Description = "The type of media to search for."
                    },
                    new QueryArgument<NonNullGraphType<StringGraphType>>
                    {
                        Name = "query",
                        Description = "The text to search for."
                    }
                },
                resolve: c =>
                {
                    Models.MediaType? type = null;
                    if (c.HasArgument("type"))
                    {
                        type = c.GetArgument<Models.MediaType>("type");
                    }
                    var query = c.GetArgument<string>("query");
                    return manager.FindAsync(query, type);
                });

```
`
### Motivation

While this feature is new, it's a fairly impressive performance gain over prior execution patterns and likely to obtain significant attention.  This is particularly true among database calls and web service calls which are likely to be exposed in this fashion.  

Further, it seems to be working properly when the query in question has no arguments.   This discrepancy presents itself as a fragility in an otherwise stable system.

**Comment by MikeKenyon** [comment]
Current workaround I've come up with this.  It's not at all pretty, but does work.   I get around it with an extension method ... 
```
                    return media.FindAsync(query, type).ToEnumerable().Result;

        public static async Task<IEnumerable<T>> 
            ToEnumerable<T>(this IAsyncEnumerable<T> listing)
        {
            var list = new List<T>();

            await foreach(var entry in listing)
            {
                list.Add(entry);
            }
            return list;
        }

```

Not at all performant, but it does get you past the problem.

**Comment by sungam3r** [comment]
This feature will require us to separately target netstandard2.1 or will have to do runtime checks for type name `IAsyncEnumerable` and then perform manually iteration.

**Comment by MikeKenyon** [comment]
I would imagine that it double-targeting would be preferable.  IAsyncEnumerable<> doesn't derive from IEnumerable<> so you'd have to use reflection to make calls to `GetAsyncEnumerator()` and then to make calls to `MoveNextAsync()`.  I'm guessing that the attending performance cost would be undesirable. 

As I said, it works with code as stands today so long as you don't have a query argument.  That grants the faulty impression that it's supported functionality.  

While it's not HUGELY important _today_, Task<IEnumerable<T>> is going to be slowly replaced with IAsyncEnumerable<T> which is going to eventually make this important.

**Comment by SimonCropp** [comment]
+1 from me to move to netstandard2.1. Given this library targets server deployments, it should be easier for people to move to a new framework

**Comment by casperOne** [comment]
I would throw in a +1 here as well, this would be exceptionally efficient.

However, in looking through the source code in order to find a workaround, it seems that in addition to the issues regarding multi-targeting (I'd prefer a netstandard2.1 version as well ) that @sungam3r mentioned, it would have to introduce `Task`-based methods into the call chain (which doesn't seem to be a major problem, as there are `Task`-based methods further up the chain it seems).

**Comment by Shane32** [comment]
@sungam3r I think we should decide if we want to start multi-targeting during 4.x or change to .NET Standard 2.1 for 5.0.  I suggest the latter.  I think there may be a lot of changes that we can make at the same time, such as using `ValueTask<T>` in place of `Task<T>` in various places.

**Comment by sungam3r** [comment]
`ValueTask<T>` works well both for 2.0 and 2.1. I would like to use multi-targeting and keep supporting 2.0 at least for v5.

**Comment by kuzn-ilya** [comment]
@sungam3r , I would consider depending on https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/1.1.1, which brings IAsyncEnumerable support to .NET Standard 2.0, instead of using reflection for this or waiting for targeting GraphQL to .NET Standard 2.1. As it is mentioned in the description of this package it
> Provides the IAsyncEnumerable<T> and IAsyncDisposable interfaces and helper types for .NET Standard 2.0. This package is not required starting with .NET Standard 2.1 and .NET Core 3.0.
I can make PR a bit later.

**Comment by Shane32** [comment]
Regardless of framework support, supporting `IAsyncEnumerable` by GraphQL.NET presents a challenge in that the execution strategy needs significant changes to make any practical use of an `IAsyncEnumerable`.  At best, asynchronous lists could start executing child nodes before the entire list is read.  And without even more work, this presents a problem in that data loader child nodes could execute before the parent list has completed being read.  Finally, due to the GraphQL specification regarding null bubbling in case of errors/exceptions, all nodes must execute before the result can be returned to the caller.  So it is not really possible to stream the results to the caller as they are being read from the source.

In the meantime, converting the enumerable to a list via `ToListAsync` is easy and does not require any changes to GraphQL.NET.  This method can be imported from various libraries (e.g. System.Linq.Async) or can be hand written with a few lines of code:

```cs
public static async Task<List<T>> ToListAsync<T>(this IAsyncEnumerable<T> list, CancellationToken token = default)
{
    var list = new List<T>();
    await foreach (var entry in list.WithCancellation(token)) list.Add(entry);
    return list;
}
```

The above code sample is virtually identical to the `ToListAsync` provided by EF Core, by the way.

https://github.com/dotnet/efcore/blob/main/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L1989..L2000

The simplicity of the method does not seem to justify adding another reference to .NET Standard 2.0 projects if no benefit can be gained during execution of a query.  For .NET Standard 2.1 projects, we can add code to detect `IAsyncEnumerable` objects and convert them to lists using the above extension method.  Perhaps in the future an enhanced execution strategy could be written to make better use of asynchronous enumerables, and then we can discuss adding the Microsoft.Bcl.AsyncInterfaces reference to .NET Standard 2.0 targets.

Side note: Returning `IEnumerable<T>` or `IAsyncEnumerable<T>` objects directly from EF Core (without using `ToList` or `ToListAsync`) can cause problems with scoped field resolvers, since the database context will be disposed before the enumerable is enumerated.  So scoped field resolvers might require a re-design as well.

**Comment by sungam3r** [comment]
Agree with @Shane32 . I would raise a question otherwise. What does it mean if GraphQL.NET _supports_ `IAsyncEnumerable`? It does not necessarily add to the possibility of processing such a value returned from the resolver. In my opinion, you can check the return value and if it is equal to `IAsyncEnumerable`, then generate an error with a clear text that suggests calling the provided extension method such as for example above.

**Comment by kuzn-ilya** [comment]
@Shane32 , thanks for the detailed explanation. The proposed extension method for converting `IAsyncEnumerable` to `IEnumerable` is a working solution but as @MikeKenyon said above, it is not a performant way to utilize `IAsyncEnumerable` -  using this workaround leads to extra memory consumption by creating a list (for small data sets it is not critical though).
I have found another workaround in the [System.Linq.Async](https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToEnumerable.cs), it doesn't consume extra memory, but still not ideal, because it uses `.GetAwaiter().GetResult()` anti-pattern, so I could not recommend using it.
@sungam3r , answering your question, for me, _supporting `IAsyncEnumerable` by GraphQL.NET_ means that I could return `IAsyncEnumerable` from resolver and GraphQL.Net could handle it without any taxes for workarounds.

Based on the above, I cannot agree with @Shane32 's statement:

> supporting IAsyncEnumerable by GraphQL.NET presents a challenge in that the execution strategy needs significant changes to make any practical use of an IAsyncEnumerable. 

Even if these significant changes will not be made, it would be worth supporting resolving `IAsyncEnumerable`'s "out-of-the-box". Maybe I am wrong, but for me, it does not seem to be a problem - I have just raised [PR](https://github.com/graphql-dotnet/graphql-dotnet/pull/2532) that shows one of the possible working solutions  (it is not ready-to-merge, it is just to support my opinion on this, feel free to reject it)

**Comment by sungam3r** [comment]
>  supporting IAsyncEnumerable by GraphQL.NET means that I could return IAsyncEnumerable from resolver and GraphQL.Net could handle it **without any taxes for workarounds**

@kuzn-ilya see #2237 , GraphQL.NET does not provide streaming transmission of calculated results, they are still **buffered** by a number of reasons before sending a GraphQL response.

**Comment by sungam3r** [comment]
Note - we added conditional reference to Microsoft.Bcl.AsyncInterfaces some time ago, see https://github.com/graphql-dotnet/graphql-dotnet/blob/3486c417f0f037b4b0e3e32132bdc6c1ce31cbcc/src/GraphQL/GraphQL.csproj#L17 . Also GraphQL.NET still supports netstandard2.0 along with 2.1 ,  net5 and net6. @Shane32 I tend to close this issue in a way of just adding note in readme/docs about IAsyncEnumerable support and problems (no ootb support actually) and your helper methodmethod from here https://github.com/graphql-dotnet/graphql-dotnet/issues/1320#issuecomment-829383061. What do you think?

**Comment by Shane32** [comment]
I would comment that @MikeKenyon 's original workaround is essentially identical to Entity Framework's implementation of ToListAsync - see here:

https://github.com/dotnet/efcore/blob/bdd9846218b002005321efed1cf5195cae12f1f2/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L2298

So again, unless the execution strategy undergoes a rewrite to support executing child nodes before the parent node has completed iterating, I do not see any purpose to making changes here.

We do now support `IAsyncEnumerable` for subscriptions.  Also, `@stream` and `@defer` would be quite useful in some of my applications, and would require support of `IAsyncEnumerable`.  But again, this would require a major rewrite of the execution strategy, as well as changes to the execution result and serializer.  This would be a great benefit; I could use it myself; but this is not simple to support.  And we need to be sure the `IAsyncEnumerable` support for subscriptions does not conflict with the `IAsyncEnumerable` support for queries / mutations.

I have been thinking that perhaps for v8 we could implement the minimal changes necessary to the framework to support such a change in the future or within another nuget package.  This would allow a third-party package to add `@stream` or `@defer` support.

But to go back to this issue, I'd probably close it.
