### ISSUE TITLE
Decimal Bug

### ISSUE THREAD

**Issue by holm0563** [graphql-dotnet/graphql-dotnet#138]
When using the decimalgraphtype with objects they will resolve to a floatvalue which converts the string to a double. The the decimalgraphtype will then parse a double and give unexpected results.

See AstPrinter.cs line 272
See DecimalGraphType line 44

My current fix in my fork is to just drop float support in favor of decimals but i know thats not ideal.
https://github.com/holm0563/graphql-dotnet/commit/d2282a89e8ed861e17f744c91e2e1284eb2e0aaa
```
 var query = @"
                mutation SetState{
                    set(request:{decimal:24.15, data:2}){
                        decimal
                    }
                }
            ";

            var expected = @"{
              set: {
                decimal: 24.15
              }
            }";

  var actual = @"{
              set: {
                decimal: 24.14449987
              }
            }";
```

**Comment by joemcbride** [comment]
Thanks for the report - this is a bug in the Antlr `GraphQLVisitor`.  It is parsing the number as a `float`, though then it is getting auto-cast to a `double` since that is what `FloatValue` expects.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Language/GraphQLVisitor.cs#L48
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Language/GraphQLVisitor.cs#L112

Changing those to `double.Parse(...)` fixes the bug.
