### ISSUE TITLE
Error after upgrade to .net core 3.0: The JSON value could not be converted to Newtonsoft.Json.Linq.JToken. Path: $.variables | LineNumber: 0 | BytePositionInLine: 58.

### ISSUE THREAD

**Issue by nielheo** [graphql-dotnet/graphql-dotnet#1509]
## Summary
**All was working when I used .net core 2.2.** 
After upgrade to .net core 3.0
- Browse Schema & Doc from Playground - ERROR
- Query - Working
- Mutation - ERROR

```"errors":{"$.variables":["The JSON value could not be converted to Newtonsoft.Json.Linq.JToken. Path: $.variables | LineNumber: 0 | BytePositionInLine: 58."]}```

### Environment (if relevant)
- MacOS
- Visual Studio 2019
- GraphQL 2.4.0
- Microsoft.NETCore.App 3.1.0

**Comment by sungam3r** [comment]
It will be better to use the last preview versions.

**Comment by zizhexu** [comment]
I got same error, may I know how you solve it? you have closed it, thanks

**Comment by joelmandell** [comment]
I have a similar problem, using the latest preview version.

**Comment by NaanKaran** [comment]
I have a similar problem, using the latest preview version.

**Comment by NaanKaran** [comment]
You have an exception in your code, because you use default json serializer/deserializer in ASP.Net Core WebAPI - System.Text.Json. You can find in documentations, that System.Text.Json doesn't support such deserialization.

You need to switch your default json serializer/deserializer to Newtonsoft.Json, do the following steps:

Install the Microsoft.AspNetCore.Mvc.NewtonsoftJson NuGet package.
In ConfigureServices() add a call to AddNewtonsoftJson()
serviceCollection.AddControllers()
.AddNewtonsoftJson();
For more information about System.Text.Json you can find in Microsoft blog

**Comment by sungam3r** [comment]
I suggest to use GraphQL v3 now.

**Comment by NaanKaran** [comment]
I'm using v3.2.0 but still, I got that issue, so that I ended with Install the Microsoft.AspNetCore.Mvc.NewtonsoftJson NuGet package.
now works for me.

**Comment by sungam3r** [comment]
Well, it is not even GraphQL.NET specific error. It happens before graphql request execution.
