### ISSUE TITLE
Moved graph types to class library and now it's broke

### ISSUE THREAD

**Issue by RedEyedDog** [graphql-dotnet/graphql-dotnet#1528]
## Summary
Hey... I recently moved my graphql types to a classlibary and now my app can't resolve them?

I've referenced them etc and the only way to get it to carry-on is to add to serviceprovider.. is that right?

**Comment by sungam3r** [comment]
How do you register them in DI ?

**Comment by sungam3r** [comment]
If you use `AddGraphTypes` extension then make sure that you use correct `typeFromAssembly` parameter.

**Comment by RedEyedDog** [comment]
When it was working before in same project I had only added my schema to the DI and all worked.. it found the graphtypes and I didnt need to register anymore.

**Comment by sungam3r** [comment]
Maybe you use `DefaultServiceProvider` which can resolve only types with default ctor. Show your configuration and package version.

**Comment by RedEyedDog** [comment]
My class libary is netstandard 2.1 using GraphQl 2.4.0. My server is a netcoreapp3.1 using

**Comment by sungam3r** [comment]
1. You register `FuncDependencyResolver` so it delegates resolve to `IServiceProvider`. If the problem exists then on your side. Watch how you register types in your code.
2. I advise you to install the latest preview version of `GraphQL.Server.Transports.AspNetCore` and UI packages. GraphQL 2.4.0 is rather old, a lot of bugs were fixed since then.

**Comment by RedEyedDog** [comment]
Ok thanks.. got it all working. Thank fully i just needed to do this: 

`AddGraphTypes(typeof(MiViewSchema), ServiceLifetime.Scoped)
`
I've also updated to the latest version etc.

Thanks for all your help.
