### ISSUE TITLE
What is the correct way of returning error messages in subscriptions?

### ISSUE THREAD

**Issue by yuchen-w** [graphql-dotnet/graphql-dotnet#1634]
I'm trying to add some sort of error handling on the backend which exposes the reason for queries failing. 

While what is documented [here](https://graphql-dotnet.github.io/docs/getting-started/errors) works great for queries, I have not been able to get it to work with subscriptions. When I throw an exception in the subscription, I get a generic

>  "Could not subscribe to field "xxx" in query "xxx"

 in the error message that is returned in the playground. How do I customise this message to also include my own error message?

**Comment by sungam3r** [comment]
Make sure that you set `options.ExposeExceptions = true;`, then you can find details inside response.

**Comment by yuchen-w** [comment]
@sungam3r yep I've done that already. I have the following enabled
options.ExposeExceptions = true,
options.ThrowOnUnhandledException = true,

**Comment by DavidKiff** [comment]
I have the same issue... ExposeExceptions doesn't actually expose exceptions, it just controls whether the stack trace is exposed, from what I gather.

Inside the SubscriptionExecutionStrategy , there is code that catches any exceptions in the stream, ignores any errors you've set on the context.Errors collection and ignores the exception details too!  Instead, it creates its own exception with it's own message:

`.Catch<ExecutionResult, Exception>(exception =>
                        Observable.Return(
                            new ExecutionResult
                            {
                                Errors = new ExecutionErrors
                                {
**new ExecutionError(exception.Message, exception),**
                                    GenerateError(
                                        context,
                                        $"Could not subscribe to field '{node.Field.Name}' in query '{context.Document.OriginalQuery}'",
                                        node.Field,
                                        node.Path,
                                        exception)
                                }
                            }.With(context)));`

To fix this, I have added the line in bold above.  

To achieve that I created a new DocumentExecuter (inheriting from the original) and overridint the SelectExecutionStrategy that selects mine (which inherits from the original) and adds in that line!

Its fair enough if GQL wants to add the error, but it shouldnt ignore the exception that's thrown.

**Comment by sungam3r** [comment]
@Shane32 Not at my PC now but I'm sure that mentioned code was rewritten and now allows to customize output.

**Comment by Shane32** [comment]
Correct.  Within GraphQL.NET v7, exceptions via `OnError` are handled properly.  See `SubscriptionExecutionStrategy.HandleExceptionAsync`.  They will currently run the configured `UnhandledExceptionDelegate` and if not configured wrap the error in `UnhandledError`, exactly the same as any other field resolver.  Since GraphQL.NET Server v7 uses `IGraphQLSerializer` to serialize results, I believe that `ErrorInfoProvider` configurations are supported also.  There are also two new options in GraphQL.NET Server v7 which pertain:

- `DisconnectAfterErrorEvent` - Disconnects a subscription from the client if the subscription source dispatches an `OnError` event.  The default value is `true`.
- `DisconnectAfterAnyError` - Disconnects a subscription from the client in the event of any GraphQL errors during a subscription. The default value is `false`.

See:
- https://github.com/graphql-dotnet/server#graphqlwebsocketoptions

Please let me know if there are any issues with exceptions when using GraphQL.NET v7.
