### ISSUE TITLE
Question: Ordering Resolution of ResolverFieldContexts in a custom ObjectGraphType

### ISSUE THREAD

**Issue by amoore-incomm** [graphql-dotnet/graphql-dotnet#1706]
## Summary
We are attempting to use multiple Fields within an ObjectGraphType to dictate the contents for another field within the Type.  Some example code would look like this:

SomeModel that we use for our ObjectGraphType
```
public class SomeModel
{
    public int Num1{get;set;}
    public int Num2 {get;set;}
    public int Sum{get;set;}
}
```` 

And our ObjectGraphType
```
public class SomeModelType : ObjectGraphType<SomeModel>
{
    public SomeModelType(IDataLoaderContextAccessor accessor)
    {
        Field<IntType>()
          .Name("Num1")
          .Description("First Number in our sum")
          .ResolveAsync(context => {
              /*  
                   Here, we asynchronously load up the contents
                   of our Num1.  For arguments sake, we use the 
                   IDataLoadContextAccessor to instrument an API call
                   that will finish at some point in the future.
                   As such, this must be ResolveAsync
              */
              Task<int> intResult = dataLoaderResult;
              return intResult;
           });

        Field<IntType>()
          .Name("Num2")
          .Description("Second Number in our sum")
          .ResolveAsync(context => {
              /*  
                  Same code as above essentially.
              */
           });

        Field<IntType>()
          .Name("Sum")
          .Description("Sum of our first and second number")
          .ResolveAsync(context => {
              /*  
                  ?
              */
           });
    }
}
```

We have quasi solved this issue via Tasks and various `awaiting` concepts (such as Loops checking for statuses to be updated in the body of ResolveAsync() for Num1 or Num2), but they seem to have caused other issues.

My Question: Is there a simpler solution that lay within the GraphQL code that allows us to orchestrate the `ResolveAsync()` of our Sum field to only execute after the other Fields have finished, or do we have to utilize things outside of the GraphQL code to achieve this (Continuations, Task analysis, good old fashioned flags, etc)?

**Comment by kevklam** [comment]
Probably writing a custom ExecutionStrategy, i.e. a fork of ParallelExecutionStrategy. You could make your resolver implement some interface like "IDependencyAwareResolver" that just exposes a list of dependencies (could be as simple as string identifiers), and then have your execution strategy check for nodes with resolvers implementing this interface and block execution of the node (stick it in some separate queue) until all its dependencies have been resolved. I'm doing something similar with "exclusion groups" where certain resolvers can't run in parallel with each other.

The way I see it, you're probably going to run into issues if you try to solve it at the resolver level, because the execution strategy has a configurable max parallel execution limit and you could presumably deadlock if you end up with too many resolvers blocked waiting for dependencies and run out of threads to run the resolvers that actually satisfy the dependencies. Solving it at the ExecutionStrategy level will avoid this by just not executing the resolver until all its dependencies have been satisfied, hence eliminating the risk of running out of threads.

**Comment by sungam3r** [comment]
Yes. Custom `ExecutionStrategy` may be the best way to do what yo want @amoore-incomm . You can place some custom meta-information on your fields about dependencies and then use it in custom strategy to orchestrate execution process.
