### ISSUE TITLE
graphql .Net Framework 3.5 support

### ISSUE THREAD

**Issue by kbpartha17** [graphql-dotnet/graphql-dotnet#1721]
Hello

Can I have GraphQl to support .Net Framework 3.5 . As we need to support Windows XP also

Thanks And With Regards
Partha

**Comment by sungam3r** [comment]
Generally speaking, Windows XP has not been supported for a long time. GraphQL.NET targets netstandard2.0 since 2017 - #441 and support only netstandard2.0 since 2019 - #969 . AFAIK GraphQL.NET never supported .Net Framework 3.5. I can see only net45 TFM in initial commit. .Net Framework 3.5 lacks a lot of APIs used in GraphQL.NET. I’m not at all sure that there will be at least one project in graphql-dotnet org  that supports .Net Framework 3.5. @joemcbride  ?

**Comment by avin-kavish** [comment]
@kbpartha17 Can't you put it in the cloud and have the XP client access it through a web browser? Why do you want to run a graphql server on a local machine?
