### ISSUE TITLE
document execution result writing

### ISSUE THREAD

**Issue by emceelovin** [graphql-dotnet/graphql-dotnet#1743]
i've been scouring the source code for the framework, and i can't seem to find a way/interface that i can supply that allows me to essentially hook the result of a field as its resolved. what i would like to achieve is, instead of taking the result Dictionary returned by DocumentExecutor.ExecuteAsync and manually serializing it to the format i want, i would like to begin my own custom writing as the query is being executed and fields are being resolved. possibly even avoiding the Dictionary<string, object> alltogether. if even possible. If i manually serialize the result now, the following happens(at least from what i see), result is returned, which is however many allocations it takes to build the result Dictionary, which is one step over the result set of data, then i step over all of the data again, and serialize it into the buffer/memory stream of my choice. which is a second allocation for the same data. is there a way i can supply some kind of execution interface, so that i can avoid an extra allocation/unnecessary step over the same data? essentially, the goal is to build the result myself. into the format i want it in. thank you!

**Comment by Shane32** [comment]
It's probably possible, but for multiple reasons you'd need to write your own ExecutionStrategy in order to accomplish that.  In order to meet the graphql spec with your custom implementation, you will probably run into 3 main issues:
1. The document will need to be executed in the order it is serialized (e.g. serial execution strategy), or else you'll need to write special code to serialize data once it is available in the correct order for serialization
2. Graphs need to render all their non-null children before writing any children back to the output, since if a non-null child throws an error, a null needs to bubble up from that node to the parent (since it is a non-null node)
3. Any errors need to be queued to be returned after the rest of the data is serialized

Neat idea, though.

**Comment by sungam3r** [comment]
I agree with the answer from @Shane32. In theory, such a possibility exists, but it is fraught with a number of difficulties. Maybe sometime in the future we will work on it, but there are no such plans now.
