### ISSUE TITLE
GraphiQl query error since 0.11.0.493

### ISSUE THREAD

**Issue by cmiagika** [graphql-dotnet/graphql-dotnet#182]
Hey there

I have a problem with my GraphiQl since I upgraded from 0.10.1.349 to 0.11.0.493.
My error message: Cannot query field \"locations\" on type \"__Directive\"
I found this thread: https://github.com/graphql/graphql-js/issues/369
So I checked my GraphQl versions ant they are all on 0.11.0.493.
I can't figure out what causes this error, because there shouldn't be a difference between these two versions in generating the schema. Or am I missing something?

Thank you for your help 😃.

**Comment by joemcbride** [comment]
This is probably related to https://github.com/graphql-dotnet/graphql-dotnet/issues/176

This should be fixed in the latest https://www.nuget.org/packages/GraphQL/0.12.0-alpha-538

If you don't want to move to 0.12, you can use this version: https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/build/0.11.0.524/artifacts

**Comment by cmiagika** [comment]
Thank you for your fast answare.
I will try to update on 0.12 alpha and will inform you if it worked.
Very good work 👍.

**Comment by joemcbride** [comment]
Closing this.  Let me know if it didn't work.
