### ISSUE TITLE
Easier type system

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#1838]
Hi,

this is more a discussion. In my application I have a custom representation for dynamic Json objects, very similar to JToken and it took my a while to understand the graphql type system and still I am not fully understanding it. I came up with the following code to parse my json:

```
public static IJsonValue ParseJson(object value)
        {
            switch (value)
            {
                case ListValue listValue:
                    return ParseJson(listValue.Value);

                case ObjectValue objectValue:
                    return ParseJson(objectValue.Value);

                case Dictionary<string, object> dictionary:
                    {
                        var json = JsonValue.Object();

                        foreach (var (key, inner) in dictionary)
                        {
                            json[key] = ParseJson(inner);
                        }

                        return json;
                    }

                case List<object> list:
                    {
                        var array = JsonValue.Array();

                        foreach (var item in list)
                        {
                            array.Add(ParseJson(item));
                        }

                        return array;
                    }

                default:
                    return JsonValue.Create(value);
            }
        }
```

As you can see there are at least two representations of a Json object in GraphQL:

* `Dictionary<string, object>`
* `ObjectValue`

But the GraphQL type system is very simple afaik. Just like JSON it knows, Object, Array, Number, Boolean, String, Null. It also knows Enum if I am not wrong, but they can be represented as String.

In addition to that GraphQL dotnet introduces a wide range of types that are used within the parsing process, like Guid, all types of numbers and so on. But my understanding is that they are only relevant when deserializing or serializing objects.

My question is, if the type system cannot be simplified. This has several advantages:

1. It is easier to write custom converters.
2. It is probably faster because you have less allocations.
3. It is probably less code.
4. If we reduce the type system to the JSON equivalents we could use JSON.NET again as serializer.  JSON.NET allows to write custom Readers and Writers that could also work directly on the new type system. The serialization part of  JSON.NET is very powerful and faster than many counterparts. For example I am using it for MongoDB because it is faster.

**Comment by BenjaBobs** [comment]
Without the explicit types we'd be unable to analyse the document for type errors before processing. I personally like knowing that when I have a `DateTimeGraphType` as input argument, I can rely on the input actually being of type `DateTime` or else it would never even reach the resolver.

**Comment by SebastianStehle** [comment]
Before processing what exactly? The input? We definitely need scalars like DateTimeGraphType for the schema and I think it is very great feature to define custom scalars, but for validation you can built custom solutions, e.g. you could define the string like

```
class StringGraphType : GraphType<StringValue>
{
   public virtual bool IsValid(Value value)
   { 
     return value is StringValue;
   }
}

class UriGraphType : StringGraphType
{
   public override bool IsValid(Value value)
   {
      return value is StringValue s && Uri.IsWellFormedUriString(s);
   }
}
```

The costs are the double parsing of Guid ofc, but other types have special methods for it, like the Uri above.

**Comment by sungam3r** [comment]
> If we reduce the type system to the JSON equivalents we could use JSON.NET again as serializer. JSON.NET allows to write custom Readers and Writers that could also work directly on the new type system. The serialization part of JSON.NET is very powerful and faster than many counterparts. 

Faster?  I am absolutely sure that System.Text.Json is faster.  In addition, the Json.Net project has been abandoned.  I've been watching this project for a long time.  But even this is not important.  I just don't understand how one can put Json.Net as the basis for GraphQL.Net.

**Comment by sungam3r** [comment]
And yes, ORIGINAL_EXPRESSION_PROPERTY_NAME is a special hint for resolving one special issue. One day it can be rewritten in one or another way.

**Comment by sungam3r** [comment]
I would advise to formulate the proposals more clearly.  There are plenty of opportunities for improvement.

**Comment by SebastianStehle** [comment]
The JSON libraries have typically two parts:

1. Reading JSON
2. Converting JSON to C# classes.

System.Text.Json can read and parse JSON very efficiently, but the serialization part does not have that much room for improvements. You have to deal with object creation and reflection and this is where JSON.NET is not that bad, especially if you consider how much special cases it supports. For example it is faster than the MongoDB client library.

So you could replace the serialization part with JSON.NET, but of course you don't have to. A clear interface that defines what to convert would help with that. Unfortunately System.Text.Json does not provide the same decoupling in their serialization layer.

Right now it is relatively complicated to deal with objects everywhere, at least if you dig into the source code more. I have spent hours to get my deserializer right.

But obviously you know the code much better than me, so I wanted to start an open discussion.

**Comment by Shane32** [comment]
I am personally in favor of having ScalarGraphTypes serialize data to the same data types the spec allows for inputs -- integers, floating point numbers, strings, enumerations, and booleans.  Right now the system relies on the serializing engine to convert some of the data, such as the DateTimeGraphType, but not others, like the DateGraphType.  So, an updated serializer could break the conversion, and if someone wanted to use another serialization engine besides the ones provided, they would need to verify that all the default formats are serialized in the same format as the provided serialization engines.

Also, the current system does not allow for conversion to or from a null value.  Null values are treated specially within the GraphQL.NET framework.  So for instance you cannot write a ScalarGraphType that converts nulls to empty strings and vice versa.  There should be no reason that a null string cannot be serialized to an empty string and vice versa (it does not violate spec).

I'd also consider serializing the entire `ExecutionResult` differently so that it does not need a dedicated handler installed into the serialization engine.  For instance, if it just returned a Dictionary of primitive types (or other dictionaries/lists).  There are good reasons for the `ExecutionResult` to stay as-is of course also.

Finally, for performance reasons, it would be nice if it could stream the output of the response graph while resolving the fields.  It would require a significant rewrite of the ExecutionStrategy to accomplish this, however, but maybe supporting `@defer` and `@stream` would go along with this rewrite.

**Comment by sungam3r** [comment]
@SebastianStehle We have advanced from the moment of your comment. Scalars were rewritten.
@Shane32 I suggest to close this issue or create a new one (like #2237) to narrow the scope.

**Comment by sungam3r** [comment]
And again ... we have advanced one more time from the moment of my https://github.com/graphql-dotnet/graphql-dotnet/issues/1838#issuecomment-797100141.

> System.Text.Json can read and parse JSON very efficiently, but the serialization part does not have that much room for improvements. 

Optimized and tested.

> Also, the current system does not allow for conversion to or from a null value. Null values are treated specially within the GraphQL.NET framework. So for instance you cannot write a ScalarGraphType that converts nulls to empty strings and vice versa. There should be no reason that a null string cannot be serialized to an empty string and vice versa (it does not violate spec).

Refactored one or several times. I don't remember.

> Finally, for performance reasons, it would be nice if it could stream the output of the response graph while resolving the fields. It would require a significant rewrite of the ExecutionStrategy to accomplish this, however, but maybe supporting @defer and @stream would go along with this rewrite.

Such proposals are tracked by issues like #2237.

So I close this one. @SebastianStehle suggestions about redesign are welcome. You also may be interested in migration notes from `develop` branch. That document tracks new features as well as breaking changes between v4 and v5.

**Comment by Shane32** [comment]
As of now:

> I am personally in favor of having ScalarGraphTypes serialize data to the same data types the spec allows for inputs -- integers, floating point numbers, strings, enumerations, and booleans.

Fixed, but also supports deserializing of native values.  (Not sure why.)

> Also, the current system does not allow for conversion to or from a null value.

Fixed, with some exceptions.

> I'd also consider serializing the entire `ExecutionResult` differently so that it does not need a dedicated handler installed into the serialization engine.

Change more to the opposite effect now -- needs a special handler for the ExecutionResult including data and errors.  This enhances performance since there is no need to convert the tree of execution nodes into dictionaries and lists.

> it would be nice if it could stream the output of the response graph while resolving the fields.

Not planned at this time, due to the fact that null bubbling in the spec cannot be properly supported with a streaming output (unless all leaf nodes were declared as nullable).

**Comment by Shane32** [comment]
Also, with parser improvements, there is another 'layer of deserialization' removed to simplify the scalar graph type code.
