### ISSUE TITLE
Executing both queries and mutations.

### ISSUE THREAD

**Issue by holm0563** [graphql-dotnet/graphql-dotnet#184]
Currently (as per spec) queries and mutations can be passed into a single query but only one would be ran per the operationName field in the DocumentExecutor.ExecuteAsync method call. Currently if a null is passed only the first operation will be ran.

I would like the ability to run all operations and return all the results. I was thinking of making an extension called ExecuteOperationsAsync. This would loop through and run all operations in order.

I know we are pretty strict on new features so I wanted to bring this up and get suggestions before implementing. The good part of it being in this project vs in my schema generator wrapping project is it could be more optimized and only run the document builder once.

This seems like a pretty global need, especially when wanting to really minimize requests sent to the server.

Thanks for any suggestions.

**Comment by joemcbride** [comment]
I'm not sure I want to support that behavior in the core engine directly as it seems to contradict the spec.

That being said, you should be able to do what you are asking without too much trouble.

* You can create your own `IDocumentBuilder` that caches the same document if requested twice (this caching behavior could arguably be in the core project).
* You GraphQL endpoint can use `IDocumentBuilder` to get the `Document` and `IDocumentValidator` to validate it. You can then loop over each of its Operations passing the name to the `DocumentExecuter`.
* Since you already pre-validated the document, you can pass an empty list for Validation Rules so the document isn't validated a second time.  If null is passed it WILL be validated.

**Comment by holm0563** [comment]
Thanks i'll plan on building this feature outside of graphql-dotnet
