### ISSUE TITLE
Add query complexity analysis

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/graphql-dotnet#185]
http://sangria-graphql.org/learn/#protection-against-malicious-queries

**Comment by dNetGuru** [comment]
I'm working on this!

**Comment by dNetGuru** [comment]
I worked on different ways to compute the complexity of a query and decide if it is suitable while keeping the performance overhead minimal and I settled on this approach:

End nodes are scored based on the average impact of resolving each field and their depth (i.e. how nested they are) in the following way).

```Complexity of Node = (Average Impact) ^ Depth of the Node```

This way a query such as ```query { A { B { C D } } }``` assuming that on average (or by a hard-coded maximum) each Field would have **two** graph objects returned (of any type, including lists) we will have the following results:

```
Complexity: 22
Sum(Query depth across all subqueries) : 2
Field{name='A'} : 2
Field{name='B'} : 4
Field{name='C'} : 8
Field{name='D'} : 8
```

Which simply shows that if every query returns the maximum (two) objects then we will be dealing with 22 objects maximum returned. Furthermore we know the level of nesting which is 2.

Reducing the level of nesting will allow the query to have more fields. For example this query ```query { A B C D E F G H I J K }``` has the same complexity value of the previous query (returns on average 22 items) but with less nesting (here all fields have an assigned complexity of 2).

**Comment by dNetGuru** [comment]
In the event that there are multiple queries the query depth will reflect the sum of all sub-queries. For example:
```
{
  empireHero: hero(episode: EMPIRE) {
    name
  }
  jediHero: hero(episode: JEDI) {
    name
  }
}
```
Has a query depth of 2 and Complexity of 12.

I did toy with the idea of passing a list of "expensive fields" or fine tuning each and every field's complexity value but it seemed like a faster heuristic would be preferable in most cases.

The complexity value can be audited for a period of time to establish a baseline for normal distribution of query complexities and then locked in to detect anomalous queries. For this reason I think it would be a good idea to report back the complexity value to the user in th execution result so users can fine tune the allowed complexity on the fly if it fits their application.

Another issue is that the complexity analysis routine would be vulnerable to DoS attacks itself. Since I use recursion to traverse the AST, a ```maxRecursionCount``` can be passed to the ComplexityAnalyzer's constructor which prevents it to loop through more than that number of elements in the tree. This has a defualt value of 100, which is more than enough for almost all cases. (GraphiQL introspection takes ~96). An InvalidOperationException is thrown if traversing the AST takes more than ```maxRecursionCount``` to protect against DoSing the ComplexityAnalyzer.

Known limitations: if a non-inline fragment is included it can skew the results of complexity and depth. I will resolve this soon after I do some code cleanup and find some free time.

**Comment by joemcbride** [comment]
Thanks for this!  I'm swamped with a few things currently, will take a closer look at this next week but looking good at first glance.

**Comment by dNetGuru** [comment]
Sure typing. I'll do more testing and add support for fragments this weekend.

**Comment by dNetGuru** [comment]
Added a lot more to the PR!

The only remaining issues are queries like this:
``` GraphQL
{
  hero {
    friends {
      ...A
    }
  }
  human(id: "1") {
    ...A
  }
  droid(id: "4") {
    ...A
  }
}

fragment A on Character {
  id
  name
  friends {
    id
    name
    friends {
      id
      name
      friends {
        id
        name
        appearsIn
      }
    }
  }
}
```
I'd say the complexity of this query should be (2+avgImpact) * (complexity of fragment A). I'm writing the code to handle this but I don't want the complexity analysis routine to impose any noticeable overhead.

And there is also the issue of limits (like Sangria's example).
``` Scala
complexity = Some((ctx, args, childScore) ⇒ 25.0D + args.arg[Int]("limit") * childScore)
```
Do you think if I should look for the arguments in the AST and override the impact of a field if it has a "first" or "last" N argument? I personally think this is not a good way to approach this problem. For example assume if we were to add a "limit" argument to the "friends" field in the StarWars schema now think about the following query:

```GraphQL
query
{
  hero
  {
    friends(limit:1)
    {
      friends(limit:1)
      {
        friends(limit:1)
        {
          id
        }
      }
    }
  }
}
```
Now this causes the datastore to be queried 4 times (if everyone has at least one friend) but it will end up having a very low complexity due to the "limit" argument here. I'd say going with the number of average number of objects that are present in the datastore per field would be a better estimation since even if there is a "limit" argument or any filter i present the datastore has to scan over that number of objects to find the results anyway.

I'm open to suggestions on this matter if you think otherwise.

**Comment by dNetGuru** [comment]
Fragmented queries are now fully supported.

**Comment by joemcbride** [comment]
Added with https://github.com/graphql-dotnet/graphql-dotnet/pull/209
