### ISSUE TITLE
Custom IValidationRule determie if node is an ObjectGraphType or a Field

### ISSUE THREAD

**Issue by dorlandode** [graphql-dotnet/graphql-dotnet#1858]
I have a custom IValidationRule, in which I want to determine if a client has permission to access ObjectGraphTypes and/or  fields.  As best I can tell ObjectGraphTypes and Fields are processed identically in the ValidateAsync method as I have it written.

Is there a way I am missing to differentiate?

```
public async Task<INodeVisitor> ValidateAsync(ValidationContext context)
{
       var userContext = context.UserContext as IProvideClaimsPrincipal;
       
       await Task.CompletedTask;
            
       return new EnterLeaveListener(_ => {
            
            _.Match<ObjectField>(objectFieldAst => {
                  // This block is never hit.  
                  return;
             });

             _.Match<Field>(fieldAst => {
                    // Both ObjectGraphTypes and Fields are coming across as Fields.
                 return;
            }
       });
}
```

I want to be able to detect ExampleObjectType as and Object and Name, Value as a field.  Is this possible?
```
public class ExampleObjectType: ObjectGraphType<Foo>
{
        public ExampleObjectType()
        {
              this.Field(type => type.Name);
              this.Field(type => type.Value);
        }
}

**Comment by joemcbride** [comment]
`ObjectField` is represented only on `Input` Object types.  So indeed, `ObjectField` would never be called for a `ObjectGraphType` since it is not an `InputObjectGraphType`.  Remember that in this context, you are dealing with the Abstract Syntax Tree of the _query_.

http://spec.graphql.org/June2018/#sec-Input-Object-Values

These classes are modeled after the GraphQL Spec Document grammar, which you can view here:

http://spec.graphql.org/June2018/#sec-Appendix-Grammar-Summary.Document

A GraphQL `Document` is modeled as an `Operation`, with a `SelectionSet`, which contains a `Selection`, which contains a `Field`. 

Example Schema:

```gql
type Droid {
  id: String!
  name: String!
}

type Query {
  hero: Droid
}
```

Example Query:

```gql
query {
  hero {
    id
    name
  }
}
```

This `Operation` is just querying multiple `Field`.  `hero`, `id`, and `name` are all `Field`s of this `Operation`, or `SelectionSet`.  If you wanted to check access to the `Droid` type specifically, you would need to check access to the _returned_ GraphType.  This is done in the `authorization` project like so:

```csharp
_.Match<Field>(fieldAst =>
{
    var fieldDef = context.TypeInfo.GetFieldDef();

    if (fieldDef == null) return;

    // check target field - for example, this would check the `hero` field on the `Query` graph type
    CheckAuth(fieldAst, fieldDef, userContext, context, operationType);
    // check returned graph type - for example, this would check the `Hero` graph type
    CheckAuth(fieldAst, fieldDef.ResolvedType.GetNamedType(), userContext, context, operationType);
});
```

https://github.com/graphql-dotnet/authorization/blob/2d6539a51f774135ff59de90561220cfff75b439/src/GraphQL.Authorization/AuthorizationValidationRule.cs#L57

You will also want to check access to the `Operation`.

```csharp
_.Match<Operation>(astType =>
{
    operationType = astType.OperationType;

    var type = context.TypeInfo.GetLastType();
    CheckAuth(astType, type, userContext, context, operationType);
});
```

https://github.com/graphql-dotnet/authorization/blob/2d6539a51f774135ff59de90561220cfff75b439/src/GraphQL.Authorization/AuthorizationValidationRule.cs#L30-L36

**Comment by dorlandode** [comment]
Thanks, I got it working the way I needed it to work.
