### ISSUE TITLE
How can I handle API versioning?

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/graphql-dotnet#1914]
Imagine I have the query
`cars {
    Id
    Label
}`

and now I have to change it to
`automobiles {
    Id
    Label
}`

I would like to assign a version to these endpoints. For now I can solve this by having the two queries exist side by side, but I would like to only have the cars query available in the 1.0 API and only the automobiles one in the 2.0 API.

Is there a built in way to handle API versioning in GraphQL-dotnet that would allow me to do something like this:
`Field<Automobile>()
    .Name("Automobile")
    .Version(">2.0")
    .Resolve();`

**Comment by sungam3r** [comment]
GraphQL is versionless API, you should not remove fields. Instead use `DeprecationReason` to notify clients about API evolution.

**Comment by julienFlexsoft** [comment]
The thing is that we will change our webApp to use the automobile query but we have a mobileApp that still needs the car query, since we can't force our users to update their app. But we don't want to still propose the car query to the devs that will work with the new version (automobile).

I have workarounds, but I was just wondering if there already was a built-in functionality for it.

**Comment by sungam3r** [comment]
You can even hide some parts of the schema with [`ISchemaFilter`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ISchema.cs#L145).

**Comment by Shane32** [comment]
I'd say deprecation is generally the way to go, but you could register two different schema objects in your DI container, each used with different `ISchemaFilter`s.  It is important not to use the same schema and pass different `ISchemaFilter` instances through to the `ExecutionOptions` as you could create concurrency issues.  (This is fixed in 4.0 by moving where the filter is specified, although basically it's the same fix.)  Then use can use different endpoints for the different schemas.

**Comment by Shane32** [comment]
Since `ISchemaFilter` only hides parts of the schema, it can't really allow for incompatible/different schemas.  You actually have to create a different schema for each version if you want to do that.  If you did need to, you could probably take advantage of some type of local thread storage or AsyncLocal to have type constructors conditionally create fields during schema initialization; a little tricky but probably possible without duplicating all of the schema types.  Or a global variable with a lock during creation to eliminate concurrency issues.

Another possibility is to create your schema with versioning as part of the schema:
```
{
  v1 {
    automobiles {
      id
    }
  }
}
```
while also supporting
```
{
  v2 {
    cars {
      id
    }
  }
}
```
But again you have to make a lot more graph types

**Comment by OpenSpacesAndPlaces** [comment]
I agree with Shane32  - this isn't any different than what you'd have to-do with a REST API either (separate DTOs, separate controllers).

From there do you want to shim both into one service or do two completely separate services.
---

Really only you are going to know how much effort this worth - obviously the lowest hanging fruit is as sungam3r said, have both, deprecate it and then remove it some day down the road.

**Comment by sungam3r** [comment]
Closed as answered.
