### ISSUE TITLE
ReadonlyResolveFieldContext  in 3.0.0.2026

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#1934]
In earlier versions I was able to modify the global ResolveFieldContext as follows:
```
 public object Resolve(IResolveFieldContext rfc)
....
rfc.Arguments = new Dictionary<string, object>(rfc.Arguments,StringComparer.InvariantCultureIgnoreCase);
.....
```

The goal being to allow for arguments to be case-insensitive.
The current version, because it is read-only, I'm not able to make this modification anymore.

Is there any way around this problem - ideally this would just be like a configuration setting or something.

Let me know - thanks for your time!

**Comment by sungam3r** [comment]
By the way we still have `ResolveFieldContext` with setters.
I see one way to quickly resolve your issue on your side - just get `_arguments` field from `ReadonlyResolveFieldContext` with Reflection and set the new value. @Shane32 do we want to provide a case-insensitive option for getting arguments? I doubt.

**Comment by Shane32** [comment]
@OpenSpacesAndPlaces Be aware that calls to `GetArgument` will run the provided argument name through the schema's `NameConverter`, which in its default configuration converts names to camel case.  So, calling `GetArgument<string>("Test")` will match on an argument with the name of `test`.

There had been a bug where `HasArgument("Test")` would not match, but this was fixed in #1549 

As it relates to your needs, you can of course use reflection to patch your old code as @sungam3r described.  You can also use middleware to wrap the `IResolveFieldContext` with a custom implementation that returns a case-insensitive version of the dictionary when requested.

If you were writing new code, I would suggest using `GetArgument` and `HasArgument`, or writing your own extension methods as necessary.  Since `ResolveFieldContext` is now an interface, extension methods will apply to any derived class, which is very nice.  `Arguments` is really only designed for access to the raw list of arguments provided to the field.

@sungam3r I would consider making `Arguments` return a case-insensitive dictionary **if** the graphql spec requires argument names to be unique by more than just case.  We still need to pass names through the name converter in case more has changed than case.  Similarly, people should use the `GetArgument` and `HasArgument` methods so that it runs through the name converter regardless of whether only the case has changed.  Looking at the other side of the argument, returning a case-insensitive dictionary would probably be a nice feature for certain uses.  For example, I have code that passes the entire dictionary of arguments through to the `Source` property of a child graph.  `GetArgument` and `HasArgument` are not accessible in that scenario.  A case-insensitive match would be convenient, although not necessary.

**Comment by sungam3r** [comment]
I am inclined to believe that we should not do support for this particular case. We already have name converters. If someone need special processing for args, then he can take the `Arguments` dictionary directly from resolve context and do whatever. In fact `ResolveFieldContextExtensions` is just extensions.

**Comment by OpenSpacesAndPlaces** [comment]
Thanks for all the time and thought on this.
That gives me a few options for adjusting.

**Comment by OpenSpacesAndPlaces** [comment]
I wanted to a tiny bit more background in-case this comes again.
The remembered reason was because - often people declare classes in Pascal, but then they are auto-converted Camel.

Then coming back in it's now camel vs. pascal (unless you convert or the other).

But as you mentioned - it sounds like 1549 covers the base case - the only residual problem is any customization/existence checking.
