### ISSUE TITLE
Let's use Docusaurus for documentation website!

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/graphql-dotnet#1994]
This is a request to upgrade this project to a better website

using: https://v2.docusaurus.io/

Is there any way we can help on this if this is liked by the graphql-dotnet team?

**Comment by Shane32** [comment]
@joemcbride would have to comment on switching the documentation site format. Personally, I’d be excited about a doc site that has versioning for the APIs so that anyone can view the docs for any version (like getbootstrap.com). I think if the docs site could also auto generate a reference area from the xml docs, laid out similar to the MS docs, that would be absolutely perfect. 

As for helping, certainly - we would need a pull request with the necessary changes along with an updated GitHub Actions workflow that builds the docs. I can assist with the workflow changes to the extent I have time. Once the new doc site is building properly we can review the generated site in the GitHub action artifacts generated for the test run, without actually publishing the site.

**Comment by Jonatthu** [comment]
@Shane32 I recently worked with this framework, and I got a really got experience with it, we can even create blogs and more! So this becomes even more professional. I personally want this project to success since was the first graphql library for dotnet! This project has potential to make some monetization with ads on the possible new website and also maybe launching a premium support for graphql-dotnet!

**Comment by Shane32** [comment]
Sounds great! Before you spend a bunch of time on it, could you supply some links of other sites made with Docusaurus that might be similar, and a brief outline of how you envision the revised docs site? That might make it easier for @joemcbride to consider the change and the rest of us to have an idea of what it would become. 

Thanks in advance for your help in this effort!

**Comment by Jonatthu** [comment]
React Native is made in docusaurus and many more!

https://reactnative.dev/

**Comment by Jonatthu** [comment]
Any update from @joemcbride ?
I can help on the build of this website!

**Comment by joemcbride** [comment]
I'm open to it.  I liked building the Gatsby site, but Docusaurus looks like it has all the features that we need.  👍🏼

**Comment by Jonatthu** [comment]
@joemcbride please do you guys have any chat or group where I could join just for this effort?

**Comment by Shane32** [comment]
I’ll set up something @Jonatthu — thanks!!

**Comment by Shane32** [comment]
I sent you an invite to a slack workspace graphql.slack.com @Jonatthu  - sorry about the delay!

**Comment by sungam3r** [comment]
@Jonatthu Any progress on this?

**Comment by Jonatthu** [comment]
@sungam3r I can have migrated the entire docs site on a pull request at the end of this weekend,
but I need some nice "dotnet-graphql" images assets like logos and branding page.
Would you like to  communicate on slack to decide this?

**Comment by sungam3r** [comment]
While I can not even imagine how documentation will look like. I would like to first see some layout, even if without images. I wan to understand what it will be better than the current documentation.

**Comment by Shane32** [comment]
I agree; I wouldn't worry about branding/images too much at this time; just use placeholder images if/where necessary.

**Comment by sungam3r** [comment]
@Jonatthu Closing?

**Comment by sungam3r** [comment]
Closed due to inactivity.
