### ISSUE TITLE
FloatGraphType arguments can be parsed as integers

### ISSUE THREAD

**Issue by adamjones1** [graphql-dotnet/graphql-dotnet#2047]
I'm running into an issue where a Float is coming through into the `Arguments` dictionary as an `int`. My code expects it to be a `double` and fails on the downcast. It looks like `FloatGraphType` should have

        public override object ParseLiteral(IValue value) => value switch
        {
            FloatValue floatVal => floatVal.Value,
            IntValue intVal => intVal.Value,
            LongValue longVal => longVal.Value,
            _ => null
        };

changed to

        public override object ParseLiteral(IValue value) => value switch
        {
            FloatValue floatVal => floatVal.Value,
            IntValue intVal => ParseValue(intVal.Value),
            LongValue longVal => ParseValue(longVal.Value),
            _ => null
        };

in line with the other numeric scalar types. I can send a PR if we agree this is a bug.

**Comment by Shane32** [comment]
Looks like a bug to me.  All of the scalar types except decimal just have a cast to the proper type.  I think that would be sufficient.

It's also possible that a literal integer could be stored in a `DecimalValue` or a `BigIntValue` if it had no decimal places, and still be a valid `float` value.  For example, the literal 9,223,372,036,854,775,808 (no commas of course) would be stored in a `DecimalValue` rather than a `IntValue`, `LongValue`, or `FloatValue`.  See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types

So I'm thinking something like this would be best:

```cs
    public override object ParseLiteral(IValue value) => value switch
    {
        FloatValue floatVal => floatVal.Value,
        IntValue intVal => (float)intVal.Value,
        LongValue longVal => (float)longVal.Value,
        DecimalValue decimalValue => (float)decimal.Value,
        BigIntValue bigIntValue => (float)bigInt.Value,
        _ => null
    };
```

A PR would be appreciated.  Please note that we should add tests for any bugs fixed or changes made.

**Comment by sungam3r** [comment]
Amazingly I got an error even when float value comes as 1.3 (really float):
![изображение](https://user-images.githubusercontent.com/21261007/102023179-b2ddb980-3d9c-11eb-8329-f807c88a602d.png)

value is `System.Double`:
![изображение](https://user-images.githubusercontent.com/21261007/102023202-d6086900-3d9c-11eb-93cc-30503f6b8153.png)

**Comment by sungam3r** [comment]
@Shane32 You are almost right except the return type. It should be `double`: 
![изображение](https://user-images.githubusercontent.com/21261007/102023912-955e1f00-3d9f-11eb-9f6b-911652885c8e.png)

I went through all the scalars and made sure they all return values of the same type. The exception is `FloatGraphType`. It may return `int`/`double`/`long` 😃

**Comment by Shane32** [comment]
Of course, I wasn't thinking.  I was thinking double and wrote float.  Good catch

**Comment by sungam3r** [comment]
@Shane32 See #2048
