### ISSUE TITLE
DataLoader does not allow for null to be returned for federated schema

### ISSUE THREAD

**Issue by itabaiyu** [graphql-dotnet/graphql-dotnet#2062]
## Description

When using DataLoader in tandem with a federated schema, `null` can no longer be returned and instead an error is thrown. Without DataLoader in place this is not an issue and `null` can be returned for scenarios when the requested data does not exist.

### Steps to reproduce

This can be reproduced with the following code:

**Mock service:**
```
public interface IProductService
{
    Task<Product> GetProductById(int id);

    Task<IDictionary<int, Product>> GetProductsByIds(IEnumerable<int> ids);
}

public class ProductService : IProductService
{
    private readonly IDictionary<int, Product> _productStore = new Dictionary<int, Product>
    {
        {1, new Product {Id = 1, Name = "Product 1"}},
        {2, new Product {Id = 2, Name = "Product 2"}},
        {3, new Product {Id = 3, Name = "Product 3"}}
    };

    public async Task<Product> GetProductById(int id)
    {
        _productStore.TryGetValue(id, out var product);

        return await Task.FromResult(product);
    }

    public async Task<IDictionary<int, Product>> GetProductsByIds(IEnumerable<int> ids)
    {
        var results = new Dictionary<int, Product>();

        foreach (var id in ids)
        {
            _productStore.TryGetValue(id, out var product);

            results.Add(id, product);
        }

        return await Task.FromResult(results);
    }
}
```
**Controller:**
```
[Route("[controller]")]
[ApiController]
public class GraphQlController : Controller
{
    private readonly ISchema _schema;
    private readonly IDocumentExecuter _documentExecuter;
    private readonly IDocumentExecutionListener _documentExecutionListener;

    public GraphQlController(
        ISchema schema,
        IDocumentExecuter documentExecuter,
        IDocumentExecutionListener documentExecutionListener)
    {
        _schema = schema;
        _documentExecuter = documentExecuter;
        _documentExecutionListener = documentExecutionListener;
    }

    [HttpPost]
    public async Task<IActionResult> Post([FromBody] GraphQlQuery query)
    {
        var options = new ExecutionOptions
        {
            Schema = _schema,
            OperationName = query.OperationName,
            Query = query.Query,
            Inputs = query.Variables == string.Empty ? null : query.Variables.ToInputs(),
        };

        options.Listeners.Add(_documentExecutionListener);

        var result = await _documentExecuter.ExecuteAsync(options);

        if (result.Errors?.Count > 0)
        {
            return BadRequest(result.Errors.Select(e => e.Message));
        }

        return Ok(result);
    }
}
```
**Startup.ConfigureServices:**
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    services.AddSingleton<IProductService, ProductService>();

    services.AddSingleton<AnyScalarGraphType>();
    services.AddSingleton<ServiceGraphType>();
    services.AddSingleton<IDataLoaderContextAccessor, DataLoaderContextAccessor>();
    services.AddSingleton<IDocumentExecutionListener, DataLoaderDocumentListener>();
    services.AddTransient<IDocumentExecuter, DocumentExecuter>();

    services.AddTransient(serviceProvider =>
    {
        var productService = serviceProvider.GetRequiredService<IProductService>();
        var dataLoaderContextAccessor = serviceProvider.GetRequiredService<IDataLoaderContextAccessor>();

        return FederatedSchema.For(
            @"
                type Product @key(fields: ""id"") {
                    Id: Int
                    Name: String
                }
            ", _ =>
            {
                _.ServiceProvider = serviceProvider;
                _.Types.For("Product").ResolveReferenceAsync(async context =>
                {
                    // this code works as expected, allowing null to be returned
                    //
                    // var product = await productService.GetProductById((int) context.Arguments["id"]);
                    // return product;

                    // mock async
                    await Task.CompletedTask;

                    var loader = dataLoaderContextAccessor.Context.GetOrAddBatchLoader<int, Product>(
                        "GetProductsById",
                        productService.GetProductsByIds
                    );

                    // this throws errors when null is returned
                    return loader.LoadAsync((int)context.Arguments["id"]);
                });
            });
    });

    services
        .AddMvcCore(options => { options.SuppressOutputFormatterBuffering = true; })
        .AddJsonOptions(options =>
        {
            options.JsonSerializerOptions.Converters.Add(
                new ExecutionResultJsonConverter(new ErrorInfoProvider())
            );
        });
}
```
**Using the following query:**
```
query GetTheProduct {
  _entities(
    representations: [
      { __typename: "Product", id: 1 },
      { __typename: "Product", id: 2 },
      { __typename: "Product", id: 3 },
      { __typename: "Product", id: 4 },
    ]
  ) {
    ... on Product {
      id
      name
    }
  }
}

```

### Expected result

The expected output of the above code and query would be the following:

```
{
  "data": {
    "_entities": [
      {
        "__typename": "Product",
        "id": 1,
        "name": "Product 1"
      },
      {
        "__typename": "Product",
        "id": 2,
        "name": "Product 2"
      },
      {
        "__typename": "Product",
        "id": 3,
        "name": "Product 3"
      },
      null
    ]
  }
}
```

### Actual result

Instead of the above output, we get a `"Error trying to resolve field '_entities'."` with the inner exception of `"Cannot return null for non-null type. Field: _entities, Type: [_Entity]!."`

### Environment

* Host OS: Windows 10
* GraphQL: v3.2.0
* GraphQL.Server.Ui.Playground: v4.4.0
* GraphQL.SystemTextJson: v3.2.0

**Comment by Shane32** [comment]
I'm unfamiliar with federation, but I wrote most of the data loader implementation.  I'm thinking that what's going on is that a data loader result (type of `IDataLoaderResult<T>`) is getting added to the return array here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/823c15ff9399723d6d7db343b704f6bc70881605/src/GraphQL/Utilities/Federation/FederatedSchemaBuilder.cs#L94

Then when the execution strategy resolves the field, I'm guessing something detects that the data type doesn't match (I'm not sure where), causing the entire list to return null.  Since the list itself can't be null, you get the error message seen.

If you can write a PR containing a failing test, I can probably fix the problem.  I would guess that adding a check for `IDataLoaderResult<T>` instances at the end of `FederatedSchemaBuilder.AddRootEntityFields` and if it finds any, returning an `IDataLoaderResult` instance that resolves those instances and returns the array, should fix the problem.

**Comment by Shane32** [comment]
Nope, what I said isn't really the problem; I am able to reproduce the problem without federation.

The problem is that when processing a `ListGraphType<>`, the execution strategy does not properly handle `IDataLoaderResult<T>` values within the returned `IEnumerable`.  This is due to the fact that `ExecutionStrategy.ValidateNodeResult` checks the field type listed in `node.FieldDefinition.ResolvedType`, which returns `[_Entity]!` rather than `node.GraphType` which returns `_Entity`.  However, if the field was defined as `[_Entity!]!`, then `node.GraphType` would still return `_Entity` rather than `_Entity!`.  So, `node.GraphType` doesn't work either.

The easiest solution would be to add another property to `ExecutionNode` that includes the nullable reference.  For instance, `ExecutionNode.ResolvedType` which would normally always equal `ExecutionNode.FieldDefinition.ResolvedType`, except when processing array nodes, where it would strip the list off retaining the `NonNullGraphType` if any.  This is proposed in PR #2064 

@sungam3r you might have a better way to fix this problem; please review.

**Comment by sungam3r** [comment]
> This is due to the fact that ExecutionStrategy.ValidateNodeResult checks the field type listed in node.FieldDefinition.ResolvedType, which returns [_Entity]!

Seems to be the correct behavior, isn't it? I looked at the PR and I have doubts about the correctness of the decision. I suspect that the problem must be solved in a different way. I can't say which one yet. I need some free time.

I see that `CompleteDataLoaderNodeAsync` method overrides `node.Result` property (`IsResultSet` is already `true`). Why?

And one more question:
![изображение](https://user-images.githubusercontent.com/21261007/103106900-7b97c400-464a-11eb-8803-5e5e7d63b1c3.png)

Do we need to execute `CompleteNode` if we set `null` into `node.Result` two lines of code before? I mean what will be if we change condition to
```c#
if (node.Result != null && !(node.Result is IDataLoaderResult))
```

As I said before, it takes me a while to get my head around the dataloader design to come to a thoughtful solution.

**Comment by sungam3r** [comment]
By the way, with changed condition all test are green. This does not mean that it is correct, just a note.

**Comment by Shane32** [comment]
> Seems to be the correct behavior, isn't it?

No.  It's correct for the `ArrayExecutionNode`, but not the child `ObjectExecutionNode`s:

For instance, assuming a field returns a non-null list of nullable type `Person`:

- `ArrayExecutionNode` - should represent `[Person]!` - executes the resolver (which returns an `IEnumerable`) and creates child nodes for each returned value from the `IEnumerable`.
  - Child `ObjectExecutionNode`s - should each represent `Person`, not `[Person]!`.  Since there is no `FieldDefinition` that can accurately represent this child node separate from the array, the `FieldDefinition` points to the parent field.  Previously the null checks inspected `FieldDefinition.ResolvedType` to see if it was non-nullable.  The PR changes this check so that it properly checks against the child type.

> I see that `CompleteDataLoaderNodeAsync` method overrides `node.Result` property (`IsResultSet` is already true). Why?

Any resolver that returns a "data loader result" returns an `IDataLoaderResult`.  `IsResultSet` then becomes true but there's two important points here:

1. The result could become `null` after the data loader finishes executing.
2. None of the subfields or data checks, scalar serialization, or possibly error handling has executed yet.

> Do we need to execute CompleteNode if we set null into node.Result two lines of code before?

Yes.  `ValidateNodeResult` needs to execute in case the type was `[Person!]` and a null value is not allowed.

**Comment by itabaiyu** [comment]
@Shane32 thanks so much for promptly looking into this!

I don't have enough experience with how this is implemented under the hood in the library to comment, but what you've explained above seems to make sense. Will keep an eye out here and on that PR that you've linked. 😄

**Comment by itabaiyu** [comment]
@Shane32 I see that this has been closed. Any idea when a version bump including the changes might be released?

**Comment by Shane32** [comment]
@itabaiyu We're in the middle of wrapping up some stuff, so I'd say within a week.  If it's critical to your timeline, let me know.

**Comment by sungam3r** [comment]
I expect that v4 with all changes from master+develop will be published in the middle of January

**Comment by Shane32** [comment]
I have a vacation now and expect to put in a bunch of time on v4.0 so it might be a little longer @sungam3r .  I definitely think we should release 3.3.0 first.

**Comment by Shane32** [comment]
Note that we have had a target release date of Feb for a long time, and the milestone list shows Jan 31 as our target completion time for 4.0

**Comment by Shane32** [comment]
I really really want to allow resolvers for input objects in 4.0. I’ve already outlined what needs to be done. It’s complex but I should have the time over the next couple weeks.

**Comment by sungam3r** [comment]
OK.
