### ISSUE TITLE
Get header from request in Graphql 3.2.0

### ISSUE THREAD

**Issue by alineSene** [graphql-dotnet/graphql-dotnet#2063]
## Summary
Until version 3.0.0 of Graphql we used controller, getting the Authorization header like that:
![image](https://user-images.githubusercontent.com/20526081/103034201-22913880-4543-11eb-932b-11299a137b4a.png)

How can I get the request headers in version 3.2.0?

**Comment by Shane32** [comment]
3.2.0 should be fully compatible with a 3.0.0 implementation, with only one specific exception.  In your example, there should not be any changes, especially since that portion of the controller action has nothing to do with GraphQL.Net.  However, if you have upgraded your version of Asp.Net, you may need to make changes to your controller action.

Check out the releases page at https://github.com/graphql-dotnet/graphql-dotnet/releases to see a list of changes between minor versions.  You may also wish to review this upgrade guide for 2.x to 3.x if you are upgrading from a version of GraphQL.Net older than 3.0: https://graphql-dotnet.github.io/docs/migrations/migration3/

I'm afraid that the included samples demonstrate using Asp.Net Core 3.x middleware rather than a controller action.  However, a controller action will work just fine.  You may wish to review the sample I referred to here: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/GraphQLMiddleware.cs

The biggest benefit of using middleware rather than a controller action is that you can branch the Asp.Net pipeline sooner, increasing performance.

**Comment by sungam3r** [comment]
GraphQL.NET does nothing with `ApiController.Request` object and its internals. GraphQL.NET knows nothing about ASP.NET Core environment.

**Comment by sungam3r** [comment]
Closed due to inactivity.
