### ISSUE TITLE
Make ObjectGraphType support inheritance from a single parent ObjectGraphType

### ISSUE THREAD

**Issue by jeangsc** [graphql-dotnet/graphql-dotnet#2180]
## Summary

Currently, we can implement interfaces on graphQL with ObjectGraphTypes but I cannot find any way to inherit from another GraphType, my idea is to write a constructor with a GraphType parameter and property Fields would be able to loop on child and parent Fields. It would be forbidden to add an existing field on parent, but we could instead implement an "override" function able to replace parent behavior by the child behavior not modifying parent fields.

### Basic example

I have an ObjectGraphType with Name = "Animal" and an ObjectGraphType with name = "Cat"
Animal has many fields: age, colors, height, weight etc...
Cat would have the same fields but it has extra fields like "clawsLength" or "favoriteCatBiscuit"
It would be better if we had a simple way to create the ObjectGraphType with the parent

### Motivation

I can show how to implement my idea by code, the goal would be to not make existing classes heavier to support extended fields

**Comment by sungam3r** [comment]
What about just inherit cat graph type from animal?

**Comment by jeangsc** [comment]
> What about just inherit cat graph type from animal?

In my case, it's about a runtime implementation. Write something like ObjectGraphType<Cat> : ObjectGraphType<Animal> would probably work very well in a static case at compile time. In our case, we have to handle more than 50 parent classes and probably 15-20 childs for each of them loaded from json files, and our clients using our APIs have their own private classes to handle with their json files. 
My idea is to inherit programatically (like what is done with interfaces and implementation of them) but with a single parent ObjectGraphType (or complexGraphType).
I temporary wrote a new child class copying fields from a parent class passed in constructor but in term of hierarchy, the child class is not seen as a child of the parent class but both of them are considered as independants and if I add a new field on parent after inheritance, we need to add it for each child which is heavier in term of memory and time for loading schema.

**Comment by sungam3r** [comment]
I roughly imagined what you are doing, but so far I can not figure out if we need to do something on the library side. It seems to me that now you have everything to solve the problem. It would be better to give a working example.

**Comment by sungam3r** [comment]
> Currently, we can implement interfaces on graphQL with ObjectGraphTypes but I cannot find any way to inherit from another GraphType

Because the GraphQL specification allows inheritance from interfaces, or rather the implementation of interfaces. In GraphQL, there is no concept of inheritance in the classical sense of object-oriented languages. What you are talking about is rather an aggregation of properties of one type in another type. In the case of interfaces, the implementing type has information about which interfaces it implements. This is also needed for introspection. If we are talking about your case, then I doubt that so-called "parent types" should be stored in the "derived" type.

As I said before
> it seems to me that now you have everything to solve the problem.

Also

> My idea is to inherit programatically 

If I understood the problem correctly, then for you it is enough to write one method that copies the fields of their "base types" into the types of the "descendants".
