### ISSUE TITLE
Remove ISchema interface

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2185]
Related to https://github.com/graphql-dotnet/graphql-dotnet/pull/2183#discussion_r559077942

This has long been a sore question (at least for me).

**Comment by Shane32** [comment]
I thought we pretty recently talked to someone that said that they use a custom implementation of `ISchema`...  I wouldn't remove `ISchema`.

**Comment by sungam3r** [comment]
I would put the question like this - what prevents them from using the inheritance from `Schema`? We can focus on this task instead of keeping alive the `ISchema` that prevents us from doing many things easier.

**Comment by sungam3r** [comment]
So ?

**Comment by Shane32** [comment]
I wouldn't remove `ISchema` at this time.  Interfaces make code much more flexible and easier to test.  It also helps enforce flexibility in design.  

For instance, with the current design, there are many classes and methods that are not replaceable.  For example, `BuildExecutionNode` cannot be overridden, so it is difficult for a third-party implementation to provide derived `ExecutionNode` classes containing additional members.  You'd have to write a replacement for nearly every method in the class!  As such, I have long wanted to make a pass through the entire codebase and add 'virtual' to most members, and remove 'static' from others.  It has prevented me from making changes and modifications in the past as described above.  

I would also like to remove all the internal collection properties that we just added, but this is not a priority at this time.  I'm sure we can realize the same speed benefits without limiting those benefits merely to internal components.  Aside from my own experiences, I know we have seen multiple issues come up that are caused by the inability to replace an individual component.

I think flexibility should be a design goal.  The question isn't "what prevents them from using a class" but rather "what prevents us from using an interface".

Last year I was working on a way to allow the execution stage to only require read-only interfaces, enforcing a read-only schema at runtime.  I still think that should be a design goal, but I have not worked on it recently.  This would allow, for example, having an entirely different schema build process that may be more optimized than another when used for a different purpose.  (e.g. schema-first vs code-first vs conventions)

**Comment by Shane32** [comment]
Ideally I would like to see an `ISchema` interface that provides read-only access to the entire schema, and only the properties of the graphs that are necessary for execution.

**Comment by Shane32** [comment]
Actually writing an implementation of this should be much easier now that we have individual collection classes.
