### ISSUE TITLE
Field as extension

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2263]
See https://github.com/graphql-dotnet/graphql-dotnet/pull/2261#discussion_r571717288

**Comment by sungam3r** [comment]
@Shane32 v4 or v5?

**Comment by Shane32** [comment]
I forgot that there is a reason why `Field()` is not an extension method: because then you have to write this:

```cs
this.Field(x => x.Name);
```

rather than this:

```cs
Field(x => x.Name);
```

I ran into this same problem when trying to add overloads via extension methods in my own code.  Not sure what the best answer is, but probably not make any changes for v4.

**Comment by sungam3r** [comment]
Yeah. Closing then.
