### ISSUE TITLE
Update copyright?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2342]
```
 <Copyright>Copyright 2015-2017 Joseph T. McBride et al. All rights reserved.</Copyright>
```

Is it worth changing the year here? Something else? Ping @joemcbride

**Comment by Shane32** [comment]
The copyright years must be the date of initial publication.  Additional years can be noted if there was new copyrightable material by @joemcbride added in those years.  But, for example, it would be incorrect to say 2015-2021 because he has not added any copyrightable work this year.

See https://www.copyright.gov/circs/circ03.pdf

**Comment by sungam3r** [comment]
So nothing to change?

**Comment by Shane32** [comment]
I would expect that it should probably match the MIT license file, which says `Copyright (c) 2015-2020 Joseph T. McBride`

@joemcbride to comment here.  It's his copyright, after all.
