### ISSUE TITLE
Custom Scalars with Variables

### ISSUE THREAD

**Issue by kyleadams-fm** [graphql-dotnet/graphql-dotnet#2371]
## Summary

I am trying to use a "Custom" scalar by subclassing the LongGraphType for ids in order to obfuscate ids on the frontend. Basically encode an id when we send to the client and decode on input. I noticed that this works just fine when the variables are included directly in the query, but when variables are sent separately from the query I get an incorrect order of operations when trying to decode the id.

## Relevant information

Here is a basic version of the GraphType I'm working with
```
namespace Utils.CustomGraphTypes
{
    internal class BaseIdGraphType : LongGraphType
    {
        public override object ParseLiteral(IValue value) => value switch
        {
            LongValue longValue => ParseValue(longValue.Value),
            IntValue intValue => ParseValue((long) intValue.Value),
            _ => throw new InternalException("Id expected to be a number type")
        };

        protected static long ToLong(object value)
        {
            return (long) ValueConverter.ConvertTo(value, typeof(long));
        }
    }
}
```
```
namespace Utils.CustomGraphTypes
{
    internal class ObjectIdGraphType : BaseIdGraphType
    {
        public override object ParseValue(object value)
        {
            return IdEncoder.DecodeId(ToLong(value));
        }

        public override object Serialize(object value)
        {
            return IdEncoder.EncodeId(ToLong(value));
        }
    }
}
```

When calling the endpoint like this 
```
query ObjectGet {
  object(id: 6453) {
        id
  }
}
```
the decoder works well because `ParseLiteral` is called which will decode the id and then when the object is returned, it goes through `Serialize` to encode the id again. 

However, if I call it like this 
```
query ObjectGet($id: ObjectId!) {
  object(id: $id) {
        id
  }
}
```
The DocumentExecutor https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L322 attempts to Convert the variables and will call `Serialize` on the input and encode the already encoded input id here https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/GraphQLExtensions.cs#L510-L512 and then call serialize later

Why does the input have to be serialized in the variable input and not when directly in the query? Is there a way to configure this so that it will only decode on input and encode when sending to the client?

**Comment by Shane32** [comment]
This has been fixed in version 4, which should be released shortly. You can review the revised behavior in the develop branch. The variables are now only parsed by ParseValue and not run through Serialize under any circumstance. Serialize is now only used when return information from a field resolver.  Let me know if you have any questions.

**Comment by Shane32** [comment]
Check out the revised LongGraphType definition. 

https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/src/GraphQL/Types/Scalars/LongGraphType.cs

You would need to override Serialize also because by default it just calls ParseValue.

I would suggest inheriting from LongGraphType and then call the base method for ParseValue and ParseLiteral, which will always return null or a long. Then if not null, cast to long and apply your transformation. 

Do the same for Serialize: call base.ParseValue (not base.Serialize because that will call your overridden ParseValue method) just to be sure the value is coerced to a long or null. Then apply your transformation.

**Comment by Shane32** [comment]
Alternatively, just duplicate LongGraphType entirely, and override Serialize with code similar to what’s in ParseValue. Add your transformations to the code where applicable and your done. Of course if you know that the value returned from field resolvers will always be a long then Serialize can be simpler. But for literals and variables, you’ll need to support more numeric types because a json number does not carry type information so it might decode as a int or long.

**Comment by Shane32** [comment]
You can also still use the ValueConverter. Or Convert.ChangeType

**Comment by kyleadams-fm** [comment]
Thanks @Shane32 that's awesome this was addressed already. Looking through the changes and your suggestions seems like it will work nicely.
Is there a target date for version 4 to be released?

**Comment by Shane32** [comment]
Yeah - a month ago! We stopped actually to fix the problems related to scalars. I hope to release it within another week or two.
