### ISSUE TITLE
Validation rules and variables

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2372]
See https://github.com/graphql/graphql-spec/pull/825#discussion_r583473500
Ping @Shane32

**Comment by Shane32** [comment]
I do not believe that changes are required for document validation here, and I do not believe it affects caching.

Consider these samples copied from the linked PR:
```
Literal Value            | Variables               | Coerced Value
------------------------ | ----------------------- | ---------------------------
`{ a: $var, b: 123 }`    | `{ var: null }`         | Error: Exactly one key must be specified
`{ a: $var, b: 123 }`    | `{}`                    | Error: Exactly one key must be specified
```
We do not need to know what the variable coerced to in order to validate the document.  We do not need to know if the variable was even provided, since unsupplied variables are coerced to the document-defined variable default value.  Also, the type of the variable is defined within the document, so if we need to verify that the type is valid, that information is already available.

As for the other block noted, it needs to validate that an input object is valid based on the validity of its fields, which can be a variable.  But since the variable's type is known (as it is defined in the document), input object validity can be verified without verifying the variables at the same time.  If variables fail validation, so will the input object.  If they pass, so will the input object.  So we can safely separate the parsing of the document from the parsing of the variables.

It is true that we do not know if the document can be executed without parsing both the document and the variables before the request is executed.  This is handled properly in v4.
