### ISSUE TITLE
Asynchronous ObjectGraphType<TSourceType>.IsTypeOf callback

### ISSUE THREAD

**Issue by DkozhevnikovConfigit** [graphql-dotnet/graphql-dotnet#2470]
## Summary

We are improving our application to utilize Async pattern now. 
Can we request you guys to have an additional async version of ObjectGraphType<TSourceType>.IsTypeOf  callback? 

### Basic example
Like:

```
IsTypeOf = async obj =>
      {
          var result = await db.GetResultAsync();
          return (result .Type == Type0 ||
                  result .Type == Type1);
      };
```

### Motivation

I tried to find the way to achieve it (with IsTypeOf or ResolveType callbacks), but with no luck. 
The problem is to understand what is type is, we have to call our database and we would like to make is asynchronously like we do it with fields resolvers for example.

**Comment by SebastianStehle** [comment]
I think this would really kill your performance

**Comment by Shane32** [comment]
I'm assuming that you are using GraphQL interfaces.  First, I would suggest setting the `ResolveType` delegate within the interface's constructor, so that multiple calls to `IsTypeOf` are not necessary to determine which type is proper.  (If `ResolveType` is used then no calls are made to `IsTypeOf`.)  You can also set the `IsTypeOf` delegate to null within the `ObjectGraphType`'s constructor, but may want it checked anyway so certain requests are fully verified (depends on your exact implementation, requests, and schema).

Either way, however, those delegates only run after a value has been returned from one of your field resolvers.  So I would expect that you should be able to identify the proper type from the database during the initial call to retrieve the data.  Presuming this is so, and assuming you cannot store the type directly inside of the class holding the data (or use .NET OOP design to dictate the correct type), then I suggest storing the type in a cache for the request.  The cache could be a `ConcurrentDictionary` stored within `UserContext`, for example.  In this way there is never a second call to the database to determine the type of the data that was already returned in a prior call.

**Comment by sungam3r** [comment]
Agree. In other words `IsTypeOf`/`ResolveType` are not those APIs that ever need `async` if used properly.

**Comment by sungam3r** [comment]
And by the way async method gives you notning because even if we supply it we also **should** await the result ... but our execution context is not async (as well as some other frames in call stack). So we should change all of our APIs up the stack to be async (so called async infection).

**Comment by DkozhevnikovConfigit** [comment]
ok, thanks all! Closing the ticket.
