### ISSUE TITLE
Unable to serialize '<enum value>' to the scalar type '<enum type>'

### ISSUE THREAD

**Issue by adityavaish** [graphql-dotnet/graphql-dotnet#2485]
## Description

With update to 4.x the enum conversion is broken. This is likely due to this PR

https://github.com/graphql-dotnet/graphql-dotnet/pull/1836

In file 
https://github.com/graphql-dotnet/graphql-dotnet/blob/2e49888da2393b2991bb52a5306b110dc948b224/src/GraphQL/Types/Scalars/EnumerationGraphType.cs#L230 

there is a check to match UnderlyingValue (which is of type int in C#, default). When assigning this value in https://github.com/graphql-dotnet/graphql-dotnet/blob/2e49888da2393b2991bb52a5306b110dc948b224/src/GraphQL/Types/Scalars/EnumerationGraphType.cs#L276
 the value will always be of string type. 

We are using schema first and define enum in schema like

```
enum SourceType {
    UnknownSource,
    Universal,
    Local,
    Standard
}
```

In C# the type defined is

```
public enum SourceType {
    UnknownSource = 0,
    Universal = 1,
    Local = 2,
    Standard = 3
}
```

### Steps to reproduce

Use schemafirst to create schema that uses above enumeration. Also create C# enum and then use schema to run a query.

### Expected result

enum value should be able to cast to enum type. This works as expected in 3.x

### Actual result

enum value is unable to cast to enum type. This is a break in 4.x

**Comment by Shane32** [comment]
All scalar types are more strict in v4.  In the case of enums, you must use the defined internal representation with returning data, which corresponds with the format of the data of the scalar when used as an input.  The schema builder defaults to strings that correspond to the name of the enumeration value.  For example, as an input, the graphql value of `Universal` would be returned as `"Universal"`.  Correspondingly, as an output, you must specify `"Universal"`, not `1` or `SourceType.Universal`.

I think this should be configurable through the `SchemaBuilder` configuration like in this example:

```cs
var schema = Schema.For(definitions, c => {
    c.Types.Include<SourceType>();
});
```

However, this doesn't yet work.  I will post a PR to add this capability.  In the meantime, you can use this workaround:

```cs
var schema = Schema.For(definitions);
schema.Initialize();
schema.ReplaceScalar(new EnumerationGraphType<SourceType>());
```

This will replace the graph type with the specified instance, so you will need to be sure that the other metadata (e.g. description) is properly set on the replacement instance.

Both of the above solutions will start parsing literals and values as the enumeration value rather than a string, so this does not exactly replicate the 3.x behavior.  If you do need to exactly emulate the 3.x behavior, where strings are returned when used as input types, and enumeration instances are accepted when used as output types, then you can do the following to replace the enumeration type entirely:

```cs
private class MyEnum : EnumerationGraphType
{
    public MyEnum()
    {
        Name = "SourceType";
        AddValue("UnknownSource", null, "UnknownSource");
        AddValue("Universal", null, "Universal");
        AddValue("Local", null, "Local");
        AddValue("Standard", null, "Standard");
    }

    public override object Serialize(object value) => base.Serialize(value.ToString());
}

var schema = Schema.For(definitions);
schema.Initialize();
schema.ReplaceScalar(new MyEnum());
```

As of now there are no plans to revert the strict type checking of enumeration values in 4.x, but comments are welcome.  Please note that within 4.x, you ARE allowed to use the underlying value of an .NET enumeration value.  Meaning, if the enumeration is mapped to `SourceType` enum values such as `SourceType.Universal`, then you MAY return `1` rather than `SourceType.Universal`.

**Comment by Shane32** [comment]
@sungam3r We could patch the issue by programming `EnumerationGraphType.FindByValue` to convert the value to a string if `UnderlyingValue` is string.  This would still maintain the rule that internal values are only compared to internal representations.  It would really only help the schema builder or situations where people defined their enumeration values by strings but are returning enum types.

```cs
if (Equals(def.UnderlyingValue, value) || (def.UnderlyingValue is string str && value?.ToString() == str))
```

I would rather address the underlying issue (e.g. #2487) and not implement this patch.  Stricter type checking helps catch name mismatches (like "UnknoenSource" posted in the sample above) when the schema is built, preventing runtime errors.

**Comment by adityavaish** [comment]
Workaround worked!

```
var schema = Schema.For(definitions);
schema.Initialize();
schema.ReplaceScalar(new EnumerationGraphType<SourceType>());
```
