### ISSUE TITLE
Using output type in the response of mutations

### ISSUE THREAD

**Issue by athomasec** [graphql-dotnet/graphql-dotnet#2503]
## Summary
I want to send a field of `ObjectGraph` type in the response of a mutation. I am using apollo GraphQL on the client-side. Returning this way helps with the caching.
I tried to add a field for `ItemGraph` inside `ItemInputGraph`.  But, it will throw an exception since `ItemInputGraph` is of `IInputObjectGraphType` type. Is it possible to add this only at the response of a mutation?

`mutation MarkAsCompleted($item:ItemInputGraph!){
    markAsCompleted(item: $item){
        success
        item { # this should be the same output type used for querying item
            id
            name
            type
            isCompleted
            completedOn
            completedBy
        }
    }
}`

**Comment by Shane32** [comment]
Input types and output types are distinct according to the GraphQL specification. An input type cannot be used for returning data and an output type cannot be used for a field argument. GraphQL.NET enforces this rule.

You can however create matching input and output types that map to the same fields of the same type of object. 

There is also no issue having the item field of the mutation result match the same type as a query for the item. You might simply be adding the field to the wrong graph - rather than adding it to the input graph, you want to add it to the return type of the mutation graph.

**Comment by athomasec** [comment]
> There is also no issue having the item field of the mutation result match the same type as a query for the item. You might simply be adding the field to the wrong graph - rather than adding it to the input graph, you want to add it to the return type of the mutation graph.
This makes sense. Changing the return type did it for me.
