### ISSUE TITLE
Support C# 9 positional record with optional properties as T for IResolveFieldContext.GetArgument<T>()

### ISSUE THREAD

**Issue by TylerEich** [graphql-dotnet/graphql-dotnet#2509]
## Summary

At present, the [`ToObject<T>` method](https://github.com/graphql-dotnet/graphql-dotnet/blob/4.3.0/src/GraphQL/ObjectExtensions.cs#L44) struggles with C# 9's positional record types

This will fail because the query's `searchCriteria` doesn't include an `id` property:
```c#
// Doesn't work
public record SearchCriteria(Guid? Id, string Pattern);
```
```graphql
{
  someQuery(searchCriteria: { pattern: "hello" })
}
```

But this works fine if the record type has a body:
```c#
// Works great
public record SearchCriteria
{
  public Guid? Id { get; init; }
  public string Pattern { get; init }
}
```
```graphql
{
  someQuery(searchCriteria: { pattern: "hello" })
}
```

It would be nice to be able to use positional record types as DTOs without worrying about this behavior.

### Basic example

Here's a more complete scenario:

```c#
using System;
using GraphQL.Types;
using Xunit;

namespace GraphQL.Tests.Bugs
{
    public class RecordTest : QueryTestBase<RecordSchema>
    {
        [Fact]
        public void Record_Should_Return_As_Is()
        {
            var query = @"
{
  search(input: {})
  {
    id
  }
}
";
            var expected = @"{
  ""search"": {
    ""id"": null
  }
}";
            AssertQuerySuccess(query, expected, null);
        }
    }

    public class RecordSchema : Schema
    {
        public RecordSchema()
        {
            Query = new RecordQuery();
        }
    }

    // This one fails
    public record RecordModel(Guid? Id);

    // This one succeeds
    // public record RecordModel
    // {
    //     public Guid? Id { get; init; }
    // }

    public class RecordInput : InputObjectGraphType<RecordModel>
    {
        public RecordInput()
        {
            Field(o => o.Id, nullable: true);
        }
    }

    public class RecordType : ObjectGraphType<RecordModel>
    {
        public RecordType()
        {
            Field(o => o.Id, nullable: true);
        }
    }

    public class RecordQuery : ObjectGraphType
    {
        public RecordQuery()
        {
            Field<RecordType>(
                "search",
                arguments: new QueryArguments(new QueryArgument<RecordInput> { Name = "input" }),
                resolve: ctx =>
                {
                    var arg = ctx.GetArgument<RecordModel>("input"); // Fails with error from https://github.com/graphql-dotnet/graphql-dotnet/blob/4.3.0/src/GraphQL/ObjectExtensions.cs#L106
                    return arg;
                });
        }
    }
}
```

### Motivation

Some may be caught off guard (like I was) when a positional record type behaves differently from a record type with a parameterless constructor.

**Comment by sungam3r** [comment]
@TylerEich The problem your described is not actually a problem with records. Records are supported. This signature
```
public record SearchCriteria(Guid? Id, string Pattern);
```
has no `default values` for both record constructor arguments.

That signature
```
public record SearchCriteria
{
  public Guid? Id { get; init; }
  public string Pattern { get; init }
}
```
has default constructor so it just works. If you change your record to
```
public record SearchCriteria(Guid? Id = null, string Pattern = null);
```
it will work too after #2512 that adds support for such default values.

**Comment by Shane32** [comment]
lol - I wrote a very lengthy reply which it seems like I never posted.  Anyway, this was my conclusion also, that constructors that have arguments with default values are not yet supported, but they should be.

Secondly, we could choose to allow constructors that have required arguments that match defined fields on a graph type.  If a field is not specified (and there's no default value set), it would be initialized as the type's default value.  This behavior is questionable based on the fact that spec says that if the value is not specified, the field is not included in the generated dictionary.  I don't think it would be breaking spec, however, since this deals with deserialization after the dictionary has been created.  The original dictionary can always be accessed by overriding the `ParseDictionary` member of the input object.

@sungam3r We do have to consider that some people may want to coerce input graphs into existing data models, and they may not be able to add default values to the constructors.  Unfortunately there would be no easy workaround for them, since the graph would be defined correctly and yet the data unable to be coerced to the model.  This will become more important as time goes on and `record` types are more widely used.

**Comment by sungam3r** [comment]
> We do have to consider that some people may want to coerce input graphs into existing data models, and they may not be able to add default values to the constructors.

What is the problem? Currently we support default ctors as well as parametrized ctors for `context.GetArgument<T>` method.

**Comment by Shane32** [comment]
> What is the problem?

```cs
    public record RecordModel(Guid? Id);

    public class RecordInput : InputObjectGraphType<RecordModel>
    {
        public RecordInput()
        {
            Field(o => o.Id, nullable: true);
        }
    }
```

The above code snippet still does not function unless `Id` is specified, requiring the data model to be changed to workaround the issue.  There is nothing wrong with the graph, and there is no practical reason why this should fail -- merely a technical reason.  Data models are not always under the control of the GraphQL implementation.  Or rather, many times people wish to use the data models that already exist rather than having to write a new one that is almost identical.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/115275791-ec5b7280-a14a-11eb-91f9-a6c58b6f5847.png)

Current workaround is `ValueConverter.Register`.

**Comment by Shane32** [comment]
There are plenty of workarounds. The point is that there should not need to be one.
