### ISSUE TITLE
PageSize not populating context.First

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#2518]
in version 4.2.0. when i set `ConnectionBuilder<TSource>.PageSize(10);`, then in the resolve `context.First` would return 10

in version 4.3.0. when i set `ConnectionBuilder<TSource>.PageSize(10);`, then in the resolve `context.First` now returns null

Any ideas what changed to cause this?

**Comment by Shane32** [comment]
#2458 changed the connection builders' code a bit, but there should not have been any changes in functionality to old code.

Previously `.PageSize(10)` would set a private variable `_pagesize` which was captured by the `FuncFieldResolver` delegate within `.Resolve()` to create `ResolveConnectionContext`.

Now, `PageSize(10)` sets some field metadata, and within `.Resolve()` the delegate instead accesses a property that accesses field metadata to determine the page size.

This can cause two unintended side-effects:
1. If metadata is changed (e.g. cleared) after the resolver is built, it will change the resolver's behavior.
2. Another dictionary lookup within the field's metadata is required each time the resolver executes.

There are similar unintended side-effects of the `.Bidirectional()` method.  We should probably add a PR to create a local copy of these variables within `Resolve` to fix both of the above unintended changes.  However, it would not seem that this should break correct operation of the code, at least under normal circumstances.

Any chance that the field metadata is cleared after the connection resolver is built?

Can you try calling `field.GetMetadata<int?>("__ConnectionBuilder_PageSize")` and verify it returns 10?  I'd probably check this within your resolver to be sure it isn't changed after the fact somehow.

FYI, the reason the metadata was added is so that extension methods to the connection builders can read the page size and whether the connection is configured as bidirectional.

**Comment by sungam3r** [comment]
Fixed in v4.4

**Comment by Shane32** [comment]
As of now, we have not determined that there was a bug in 4.3, or that the changes in 4.4 would fix the issue.  @SimonCropp to confirm findings.

**Comment by SimonCropp** [comment]
`var metadata = context.FieldDefinition.GetMetadata<int?>("__ConnectionBuilder_PageSize")!;`  returned null

here is my usage https://github.com/SimonCropp/GraphQL.EntityFramework/blob/master/src/GraphQL.EntityFramework/GraphApi/EfGraphQLService_QueryableConnection.cs#L92

**Comment by Shane32** [comment]
Maybe SetField needs to move up a line - before the pagesize and bidirectional methods ?

**Comment by Shane32** [comment]
What does SetField do?

**Comment by Shane32** [comment]
SetField uses reflection to change the builder's underlying FieldType reference.  This is not a supported scenario.  With your current code, setting the description and page size are ineffective.  Most likely, none of the arguments (first, after, before, last) are being added either.

If you move the call to SetField immediately after creating the builder, it will fix most of those problems, but you might still need to add the 'first' & 'after' arguments yourself.

**Comment by Shane32** [comment]
I'm closing this issue, but feel free to reopen if you have any further questions.

**Comment by SimonCropp** [comment]
> SetField uses reflection to change the builder's underlying FieldType reference. This is not a supported scenario

can you expose an api where i can pass in a `FieldType `?

**Comment by Shane32** [comment]
Is there an actual need?  You're not trying to create a builder from an existing field.  It seems you are just trying to manually set the connection type, which is easy from the accessible `FieldType` property.

```cs
            itemGraphType ??= GraphTypeFinder.FindGraphType<TReturn>();

            // delete:
            //var fieldType = GetFieldType<TSource>(name, itemGraphType);

            var builder = ConnectionBuilder<TSource>.Create<FakeGraph>(name);

            // add:
            builder.FieldType.Type = typeof(Types.Relay.ConnectionType<,>).MakeGenericType(itemGraphType, typeof(Types.Relay.EdgeType<>).MakeGenericType(itemGraphType));

            if (description != null)
            {
                builder.Description(description);
            }
            builder.PageSize(pageSize).Bidirectional();

            // delete:
            //SetField(builder, fieldType);
```

This eliminates the use of reflection to set a private property and should work equally as well.

All tests pass with the above changes.  However, you'll probably want to make similar changes in `AddNavigationConnectionField` and eliminate both `SetField` and `GetFieldType`.

**Comment by Shane32** [comment]
@SimonCropp Did you have any other questions here?  I see you have not yet implemented my suggested changes -- did you find another way to solve the problem?

**Comment by SimonCropp** [comment]
nope :)
