### ISSUE TITLE
Is it possible to set MaxParallelExecutionCount per "connection"?

### ISSUE THREAD

**Issue by ThisNoName** [graphql-dotnet/graphql-dotnet#2525]
I'm trying to add GraphQL to an existing service w/ business layer talking to 2-3 databases and maybe half a dozen other services.  All is well except there's always problem with database w/ parallel. Tried GraphQL.MicrosoftDI and WithService/ResolveAsync, etc, it seems improve the situation but never completely address it.

Is there way I can set MaxParallelExecutionCount per "connection"?  i.e., calls to each database or api are serialized, but between database/api still taking full advantage of parallel?

Sorry if this has already been asked and addressed.  I search far and wide, it appears all popular frameworks are facing similar issues.  I can allow parallel queries in my db layer, but I would feel more comfortable having some controls over how many connections client can spin up.  Thanks

**Comment by Shane32** [comment]
So just to confirm, you have other async fields that you want to resolve concurrently with database async calls run in series? (If they are not async then they won’t run concurrently anyway. )

**Comment by Shane32** [comment]
Have you considered using ResolveScoped to have the resolved create a scope for the database calls? Then all can run concurrently.

**Comment by Shane32** [comment]
(Same as the MicrosoftDI project and using WithScoped in the resolve builder)

**Comment by Shane32** [comment]
Would you consider writing your own extension methods for your needs or are you only looking for an easy answer?

**Comment by ThisNoName** [comment]
Thanks for the follow up.  I just started playing around, my sample project looks like this.  I assume WithScope/ResolveAsync is equivalent to ResolveScoped in builder?   

Of course, the business layer are not thread safe, even two read-only queries may update timestamp and cause collision if truly in parallel.  I still run into query issues on occasion.  In real world, client would not call those together, but GraphQL seems exposing that impossibilities.  I can configure my db connection to handle parallel queries, but allowing any client spin up undetermined number of connections doesn't seem right.  

I saw the MaxParallelExecutionCount, just wondering if it can be configured per connection/baseUri, would be nice if we can throttle throughput while still maintain certain parallelism.  I'll dig deeper, just thought that might be something you already had in mind.

Again, thanks for all the great work, this is a lot of fun.

```
    public class AppointmentQuery : ObjectGraphType, IGraphObjectMarker
    {
        public AppointmentQuery()
        {
            Name = "AppointmentQuery";

            Field<ListGraphType<AppointmentType>>().Name("appointment")
                .Resolve().WithScope().WithService<IMediator>()
                .ResolveAsync(async (context, mediator) => await mediator.Send(
                    new AppointmentRequest { userid= context.UserId() }));

            Field<ListGraphType<HotelReservationType>>().Name("reservation")
                .Resolve().WithScope().WithService<IPortalQuery>()
                .ResolveAsync(async (context, query) =>
                {
                    return await query.Reservation(context.UserId());
                });
        }

```

**Comment by Shane32** [comment]
Well, there are a lot of ways to attack this issue; hence the questions.  I wrote a helper library (see https://www.nuget.org/packages/Shane32.GraphQL.DI ) where you can define graphs similar to ASP.Net MVC controllers.  Query arguments are inferred based on argument types, and so on.  One of the features is being able to specify, for each field, if it is capable of running in parallel or not, and if so, if it requires a dedicated service scope.  So with the library you could define all of your database fields as unable to run in parallel, and so the execution strategy will complete any pending async tasks before executing those field resolvers.

In the base library, it is possible perhaps to leverage the fact that data loaders always run after all other nodes have been completed.  (Although all data loader nodes run in parallel with each other at that time.)

None of the above scenarios would actually execute a single database call (but not two) while executing other tasks that can run in parallel.  However, you could write your own resolver extension (similar to ResolveScoped) that accesses an instance of a SemaphoreSlim (contained within an AsyncLocal instance) so that it works similar to an async-compatible `lock`, but only locking on database calls and not other async calls.  Or you could do something based on the same functionality that was contained in a singleton interface (or static variable) that you could reference in the graphs, so you just call `await using var dbLock = dbLocker.WaitAsync();` within your resolver. Those techniques would do everything you want, at the cost of some time to write some specialized code to make it happen.

But, no, there's nothing built-in to do exactly what you want.  If `MaxParallelExecutionCount` is set to 1, you might as well use a `SerialExecutionStrategy`, as there is no way to select which field resolvers are subject to the count.

**Comment by Shane32** [comment]
Sample code (untested):

```cs
public static class DbLocker
{
    private static readonly AsyncLocal<SemaphoreSlim> _lock = new();
    private static readonly DbReleaseLock _release = new();

    /// <summary>
    /// Call to lock on some code. Be sure to call Dispose on the returned object
    /// to release the lock (typically via 'using').
    /// </summary>
    public static async ValueTask<IDisposable> LockAsync(CancellationToken cancellationToken = default)
    {
        await _lock.Value.WaitAsync(cancellationToken);
        return _release;
    }

    /// <summary>
    /// Call to initialize the underlying semaphore for the current async flow.
    /// Be sure to dispose of the returned object when the flow completes (typically via 'using').
    /// </summary>
    public static IDisposable InitializeThread()
        => _lock.Value = new SemaphoreSlim(1);

    private class DbReleaseLock : IDisposable
    {
        public void Dispose() => _lock.Value.Release();
    }
}

public class MyDocExecuter : DocumentExecuter
{
    public override async Task<ExecutionResult> ExecuteAsync(ExecutionOptions options)
    {
        // initialize the semaphore here, using 'using' to ensure it is released
        //   regardless of whether an exception has been thrown
        using var locker = DbLocker.InitializeThread();
        return await base.ExecuteAsync(options);
    }
}

public class MyGraphType : ObjectGraphType
{
    public MyGraphType()
    {
        FieldAsync<StringGraphType>("test", resolve: async context =>
        {
            // this resolver needs to access the database, so "lock" here.
            // note that this "lock" is local to this async flow; graphql queries
            //   will have their own semaphore as AsyncLocal provides this ability
            // we are using 'using' here to ensure the lock is released no matter
            //   if an exception occurs, and we are using a cancellation token so that
            //   in case of any other issue, breaking the client connection will cancel
            //   the lock request and throw an exception.
            using var locker = await DbLocker.LockAsync(context.CancellationToken);
            // call database within the locked context
            return "test";
        });
    }
}
```

**Comment by Shane32** [comment]
You could even provide an extension method on `IResolveFieldContext`:

```cs
public static IDisposable LockDbAsync(this IResolveFieldContext context)
    => DbLocker.LockAsync(context.CancellationToken);

// use like this:
using var locker = await context.LockDbAsync();
```

**Comment by ThisNoName** [comment]
Wow, thank you so much!  I'll dive right in!!!

**Comment by Shane32** [comment]
@ThisNoName are you all set with this issue?
