### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'parent'

### ISSUE THREAD

**Issue by fenomeno83** [graphql-dotnet/graphql-dotnet#2560]
Hi.
I've used until now graphql 3.0.0-preview-1107 and works fine!

Now i want migrate to 4.5 but I have some problems.

The main changes are:

- in previous version i need to register in configureservices.cs

                services.AddSingleton<IDependencyResolver>(_ => new
                FuncDependencyResolver(_.GetRequiredService));
 and for schema registration

        public GraphQLMainSchema(IDependencyResolver resolver) : base(resolver)
        {
            Query = resolver.Resolve<RootQuery>();
            Mutation = resolver.Resolve<RootMutation>();
        }

- in the new version I need to install GraphQL.SystemTextJson and GraphQL.NewtonsoftJson; I don't need to register IDepencyResover as before, and schema registration is

       public GraphQLMainSchema(IServiceProvider provider) : base(provider)
        {
            Query = provider.GetService<RootQuery>();
            Mutation = provider.GetService<RootMutation>();
        }

But, when I start, i have this error
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'parent' with type 'GraphQL.Execution.ObjectExecutionNode'. Path 'data.subFields[0].subFields[0].subFields[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at 
.................................................

Here I use GraphQL.SystemTextJson is in 

       services.AddSingleton<IDocumentWriter, DocumentWriter>();

and here I use GraphQL.NewtonsoftJson is in

     var result = await _documentExecuter.ExecuteAsync(new ExecutionOptions
            {
                Schema = _schema,
                Query = query.Query,
                Inputs = query.Variables.ToInputs() //ToInputs need to import GraphQL.NewtonsoftJson
            });

If I set ReferenceLoopHandling.Ignore to netwonsoft json, I don't have error, but I have infinite loop and schema is not build

Here 2 projects.
**graphql 3.0.0-preview-1107:**
https://github.com/fenomeno83/GRAPHQL-OLD-TEST

**The same, but with upgrate to graphql 4.5**
https://github.com/fenomeno83/GRAPHQL-NEW-TEST
(here, when you start, you have error. If you go in startup.cs, you can decomment row 68 for ReferenceLoopHandling.Ignore, but if you start you have infinite loop, as said before)

How can I solve?

**Comment by Shane32** [comment]
The problem is that at the below line of code you are not using the `IDocumentWriter` implementation provided by either `GraphQL.NewtonsoftJson` or `GraphQL.SystemTextJson` which properly serializes responses.

https://github.com/fenomeno83/GRAPHQL-NEW-TEST/blob/d3c962f7ca5db34b1fc5d90266dede260eaad88e/GraphQL.Globalization.Api/Controllers/GraphQLController.cs#L89

Instead it is being passed the entire result object to Asp.NET to be serialized.  I suggest you read the following document:

https://graphql-dotnet.github.io/docs/guides/serialization

In particular, the section titled 'Serialization of a GraphQL response'.  Then apply the fix to your controller.  Unfortunately I do not have a handy example of the recommended approach to write an Asp.NET controller action which returns a GraphQL.NET response, but it should not be too difficult.  Specifically, there are at least two approaches available to you:
1. Least efficient: Serialize to a string and return the string via `Content()` - see https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.controller.content?view=aspnet-mvc-5.2
2. Most efficient: Use the DocumentWriter to write the result directly to the HttpContext Response.  You may need to write a custom implementation of ActionResult to do so; I'm not sure. 

Ref #2157

If you can get the 'efficient' approach working, please post your findings and perhaps we can then update the docs - thanks!!

**Comment by SebastianStehle** [comment]
You can also register the graphql middleware as a singleton and then just call it in your controller:

https://github.com/Squidex/squidex/blob/master/backend/src/Squidex/Areas/Api/Controllers/Contents/ContentsController.cs#L64

You just have to be careful when writing response headers in action filters, because you cannot write them after writing to the response has started.

But you can write filters like this: https://github.com/Squidex/squidex/blob/6b867865fff5d551ba130ae7a3fd5ba774b2d474/backend/src/Squidex.Web/Pipeline/CachingKeysMiddleware.cs#L42

**Comment by fenomeno83** [comment]
thanks all!!!

I've used this:
https://github.com/graphql-dotnet/graphql-dotnet/issues/2157#issuecomment-758301040

ahd works fine!!!

**Comment by SebastianStehle** [comment]
If you use the middleware you get more features:

* GET+POST
* Batch support.
* Multiple media types.

**Comment by artemiusgreat** [comment]
Calling `ExecuteAsync` on a schema directly makes code cleaner and limits output to related schema only. The code below using executor will return a lot of unrelated data and metrics.  

```
var executor = new DocumentExecutor();
var response = await executor.ExecuteAsync(_serializer, o =>
{
  o.Query = queryParams.Query;
  o.Schema = new UsersSchema();
});
```

In .NET 3.1, you could simplify call to this one.

```
var response = await _schema.ExecuteAsync(o => 
{
  o.Query = queryParams.Query;
});
```

In .NET 6, method `ExecuteAsync` requires parameter `IDocumentWriter` to be set explicitly, so it changes to this one where `documentWriter` should be initialized as a singleton in `Startup.cs`.

```
var response = await _schema.ExecuteAsync(documentWriter, o => 
{
  o.Query = queryParams.Query;
});
```

**Startup.cs**

```
// Startup.cs

services
  .AddSingleton<UsersSchema>()
  .AddSingleton<UsersQuery>()
  .AddSingleton<UsersMutation>()
  .AddSingleton<IDocumentWriter, DocumentWriter>(); // comes from nuget GraphQl.SystemTextJson or GraphQl.NewtonsoftJson

services
  .AddControllers(o => o.RespectBrowserAcceptHeader = true)
  .AddJsonOptions(o =>
  {
    o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
    o.JsonSerializerOptions.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
    o.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
  });

JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
  ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
  ContractResolver = new CamelCasePropertyNamesContractResolver()
};

services
  .AddGraphQL()
  .AddGraphTypes(ServiceLifetime.Scoped);
```

**Controller**

```
[ApiController]
[ApiExplorerSettings(IgnoreApi = true)]
public class UsersController : ControllerBase
{
  private UsersSchema _schema = null;
  private IDocumentWriter _document = null;

  public UsersController(UsersSchema schema, IDocumentWriter document)
  {
    _schema = schema;
    _document = document;
  }

  [HttpPost]
  [Route("services/users")]
  public async Task<dynamic> Query([FromBody] QueryModel queryParams)
  {
    var errors = new List<string>();

    try
    {
      var response = await _schema.ExecuteAsync(_document, o =>
      {
        o.Query = queryParams.Query;
        o.Inputs = queryParams.Variables.ToInputs();
        o.OperationName = queryParams.OperationName;
        o.UserContext = new Dictionary<string, dynamic>();
        o.ValidationRules = DocumentValidator.CoreRules;
        o.EnableMetrics = false;
      });

      return response;

    }
    catch (Exception e)
    {
      errors.Add(e.Message);
    }

    return new ResponseModel<dynamic>
    {
      Errors = errors
    };
  }
}
```

**Comment by Shane32** [comment]
@artemiusgreat I would strongly suggest registering the `ExecutionResultJsonConverter` and `ObjectDictionaryConverter` and removing the registration for `JsonStringEnumConverter`.  Also I would remove the line that ignores reference loops.

Without the `ExecutionResultJsonConverter` being registered, you will find that exceptions will expose server side details to the caller, which can be a security risk.  It is also necessary for almost all of the documentation within https://graphql-dotnet.github.io/docs/guides/serialization#error-serialization to work correctly.

**Comment by Shane32** [comment]
As @fenomeno83 has solved his problem, I'm closing this issue.  Please re-open it if needed.
