### ISSUE TITLE
NFR, Question

### ISSUE THREAD

**Issue by cyberhck** [graphql-dotnet/graphql-dotnet#2564]
Hello team,
I'd like to thank you for this amazing project. I'm actually starting to use this. However, I'm a little stuck on a few things.

First of all, I want to enable federation which looking at some PRs, some documentation I'm almost confident I can do it.

I have two questions,
How can I do the following definition:
```graphqls
extend type User {
  cards: [Card!]!
}
```

While I do know how to do the following:
```graphqls
type User @extends {
  cards: [Card!]!
}
```

I couldn't figure out how to do the non hacky extends with graphql-dotnet library. I'm using code first approach.

Second question is if you have any plans on federation support. Currently we have to implement quite a few things to be able to federate, and that needs to be done in every project.

To support federation we could:
- Create a GraphQL.Federation package and release federation related things there.
- Better is we just include Federation in core package and the only time it'd activate is if user actually uses those directive anyway. This shouldn't break existing graphql projects because it's only adding new directives and new fields to query

While I have seen this is done in schema first approach, I've also seen a PR somewhere which proposed a FederatedSchema, but IMO, Schema should already have federation.

While I'm very new to this project and don't really think I can contribute much, if you are eager to, we can try creating some issues and start sending PRs one at a time. We could have ~6 PRs for ~11 things that needs to be implemented.

**Comment by Shane32** [comment]
In general, I would agree that:
- Federation should be supported in both schema-first and code-first scenarios
- If it makes practical sense, the federation components should be moved to a GraphQL.Federation package (for v5)

Also:
- Documentation should be added
- Working examples should be added
- Tests should be added if not already there
- Xml comments should be added to all public members

The thing is that at present, @sungam3r and I are the principal developers for the library, and I believe that neither of us use federation.  @joemcbride would be the one to ask about federation questions.

If you'd like to tackle this, I'd be happy to work with you reviewing the design and PRs, etc.  But to do so we'd really need to start with documentation and examples so that I can fully understand how federation is designed to be used.

Here's some questions I have to start with:
- Does GraphQL.NET currently support acting as a gateway, as subgraph implementations, or both?
- Does each subgraph implementation need to know about the full graph? (I think not.)  If not, is any special support needed by GraphQL.NET to act as a subgraph implementation?
- Does the gateway implementation need to know about the full graph? (I think so.)  Does it make sense for code-first in this scenario?  If the code-first graphs were re-used, it wouldn't compile without all the code's dependencies.  If they were not re-used, it would be a whole lot of code that could much easier be written as a text file (schema-first).  So at first glance it seems questionable if code-first is useful at all here.
- Would it make sense for the gateway pull and merge the schemas from the subgraph implementations automatically?

**Comment by joemcbride** [comment]
This framework currently supports `extend` and federation in schema-first syntax, but not code-first. Now that directives are supported in code-first, it may be easier to support federation in code-first, though it would still be a bit awkward. Not impossible, but code-first is inherently less dynamically built than schema-first, which I think makes it a bit harder to do all of the configuration required for federation.  All of the pieces for federation are available in the project, it would just be a matter of deciding on what the usable API would look like for code-first.

@Shane32 I don't think that this framework should try to be the gateway for federation.  The Apollo project already provides a gateway which can be deployed independently of the nodes and is backed by the Apollo community. I think this project should only focus on being a node within federation.

**Comment by cyberhck** [comment]
> Does GraphQL.NET currently support acting as a gateway, as subgraph implementations, or both?

GraphQL.NET only needs to implement subgraph implementation, federation is a separate project (apollo-gateway)

> Does each subgraph implementation need to know about the full graph? (I think not.) If not, is any special support needed by GraphQL.NET to act as a subgraph implementation?

each subgraph doesn't need to know about full graph, they simply extend the types,

> Does the gateway implementation need to know about the full graph? (I think so.) Does it make sense for code-first in this scenario? If the code-first graphs were re-used, it wouldn't compile without all the code's dependencies. If they were not re-used, it would be a whole lot of code that could much easier be written as a text file (schema-first). So at first glance it seems questionable if code-first is useful at all here.

This is none of our concerns because GraphQL.NET doesn't need to implement gateway, it only needs to support federation spec, we won't be implementing federated gateway, we'll only make sure our subgraph enable federation.

> Would it make sense for the gateway pull and merge the schemas from the subgraph implementations automatically?

We don't care, GraphQL.NET is about creating federation enabled subgraph, the actual gateway is completely different project, currently only NodeJS implementation exists if I recall correctly.

I'm already doing federation using this project by the way, we just need to do the following:
- Add some scalars: `_Any` `_FieldSet` they're basically string backed, _FieldSet could do validations but I'm currently using string for this and haven't even created these scalars.
- add a union `_Entity` which returns all the types which use `@key` directive (we can go through each registered type and get the items that use `@key` directive
- add a `type _Service {  sdl: String }`, sdl will return your schema, we can use `FederatedSchemaPrinter` which already exists, basically printing the sdl for the graph.
- `extend type Query {  _entities(representations: [_Any!]!): [_Entity]!; : _Service: Service!`
- add some directives: `@external`, `@requires`, `@provides`, `@key`, and optionally `@extends`

The full spec can be found [here](https://www.apollographql.com/docs/federation/federation-spec/)

To look at how I'm doing federation, here's two projects:
- https://github.com/fossapps/Micro.Auth (provides User type)
- https://github.com/fossapps/Micro.AppRegistration (extends that User type)

The first one federation implementation inside the project itself, I'll be removing those and using a temporary nuget package I created: https://github.com/fossapps/Micro.GraphQL.Federation (this basically adds all the boilerplate code for now), but I feel it's not production ready, there's no tests, and I'm not very confident on what it does because so many parts I've copied from Graphql.NET because I needed internals, it's based on some other PR someone posted as well.

Which is why I want federation to be done correctly and with you guys instead of me maintaining a bad project.

If anyone is reading this, please try not to use the federation package I created if you can help it, only if you have no choice, use it but make sure you migrate as soon as GraphQL.NET supports federation :slightly_smiling_face:

**Comment by cyberhck** [comment]
I'll be happy to work on this in a step by step basis, but I'll need a lot of info, because I'm relatively new to .NET world and very new to this project (haven't seen much, only the federation namespace)

**Comment by Mithras** [comment]
related https://github.com/graphql-dotnet/graphql-dotnet/pull/3144

**Comment by Shane32** [comment]
Federation 2 support is available for schema-first, code-first, and type-first schemas in GraphQL.NET 8.0 (still in beta at the time of writing).  See:
- #3921
