### ISSUE TITLE
Unit Testing of Queries/Mutations

### ISSUE THREAD

**Issue by EvanCoh** [graphql-dotnet/graphql-dotnet#2583]
Hello! Thank you for graphql-dotnet.

I have seen on other issues here like [#800](https://github.com/graphql-dotnet/graphql-dotnet/issues/800#issuecomment-416977285) that we are able to run integration tests against Queries and Mutations.

Are we also able to run **Unit Tests** against Queries and Mutations similar to what MS documentation explains [here](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.1) ?

If so, can you point me to a few samples?

**Comment by Shane32** [comment]
Have you looked at the test classes within the GraphQL.Tests project?  Basically, there's some infrastructure that configures a test schema and executes a request along with any necessary variables.  You can do the same, or more likely just use a configuration that sets up the entire schema.  You might set it up so that only a bare minimum of services are registered (just those needed to set up the schema), and then within the test you mock dependent services and register them before execution the request.  Or, as I did recently, you can set it up so that the underlying database is mocked, and all of the business logic is registered normally.

Of course it is possible to directly call the field resolver configured for a field, passing in a mocked IResolveFieldContext, but it might be a whole lot more trouble than it's worth.  (I would say that's closer to the MS documentation.)  Basically, what I've found is that the key to testing is to be able to create tests easily; then it encourages writing a lot of tests.

It really depends on your situation, unfortunately.

**Comment by sungam3r** [comment]
Closed as answered. Feel free to reopen in case of further questions.
