### ISSUE TITLE
Clear recommendation on Dependency Injection with Graphql.net

### ISSUE THREAD

**Issue by EmmanuelPonnudurai** [graphql-dotnet/graphql-dotnet#2584]
## Summary

What is the recommendation from the Graphql.net team on how to deal with dependency injection correctly? 

We know we want the schema to be Singleton. But many a times, we have dependencies which are to be injected within the Query or Mutation classes through the Asp .net core default DI framework via constructor injection, which are scoped due to the nature of how they are. Like a DBContext or any other business-related functionality and we can't force that to ever be a singleton.

This poses a problem as it is incorrect to consume a lower scoped dependency within a higher scoped dependency. 

Here is the docs where we have information around this topic,

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#schema-service-lifetime

We suggest the service Locator pattern which is an anti-pattern and the same is mentioned in the docs as well. So, I am a bit unclear on what is the recommendation precisely? 

Are we saying that this is an anti-pattern, yet is a necessary evil, to overcome the Singleton Schema issue? 

I noticed the mention of `SteroidsDI` which actually seems better in that it clearly states the dependencies that a Query or Mutation depends on, albeit with the `Defer<T>` option, but it still is clear to the consumer or unit test methods probably. However, is this also an encapsulation over service locator pattern _again_?

If we could clearly state what is the recommendation, it would be helpful. We have valuable information on all items but are we saying that we don't want to make a specific recommendation on this topic. Something like, we put all information there for user to decide what is right for them and be aware of the pitfalls? 

For instance, we say this https://github.com/graphql-dotnet/graphql-dotnet/issues/2322#issuecomment-786257956 but if I don't do this, my only other option is that I must use service locator pattern ?

**Comment by Shane32** [comment]
> We suggest the service Locator pattern which is an anti-pattern and the same is mentioned in the docs as well. So, I am a bit unclear on what is the recommendation precisely?
> 
> Are we saying that this is an anti-pattern, yet is a necessary evil, to overcome the Singleton Schema issue?

You've pretty much hit the nail on the head.  Having a scoped schema really kills performance, so a singleton schema is pretty much necessary.

> I noticed the mention of `SteroidsDI` which actually seems better in that it clearly states the dependencies that a Query or Mutation depends on, albeit with the `Defer<T>` option, but it still is clear to the consumer or unit test methods probably. However, is this also an encapsulation over service locator pattern _again_?

That is my opinion as well -- it is basically the same as using `RequestServices`, so why?

I wrote much of the text in the documentation link you referenced, and it pretty much sums up the current suggestion and comments.  If it's unclear as to the recommendation, it's because different people have different viewpoints on this topic.  My personal recommendation is to write as little code as possible inside field resolvers, having them simply retrieve the field arguments, pull the appropriate service via RequestServices, and call the service method with the appropriate arguments.  So the graphs are thin layers over the business logic, and don't contain much code.  For example:

```cs
FieldAsync<NonNullGraphType<ListGraphType<NonNullGraphType<ItemGraphType>>>>(
    "items",
    arguments: new QueryArguments(...),
    resolve: async context => {
        var page = context.GetArgument<int?>("page");
        var orderService = context.RequestServices.GetRequiredService<OrderService>();
        return await orderService.GetItems(page ?? 1);
    });
```

This is how I write my code, for the most part, and what is presented first in the documentation as the primary recommendation; but it really all depends on how you want to design your code.

If you feel strongly about the service locator anti-pattern, perhaps you think the SteroidsDI or Defer system is better and suits your coding style better.  There's nothing wrong with that; hence why there are multiple options presented in the documentation.

It is important to realize the multithreaded aspects to using scoped services with GraphQL.NET.  I assume you've read the documentation page and so I won't reiterate that here.

There is another option also, which solves multiple of these problems.  You can use https://github.com/Shane32/GraphQL.DI to write graphs just like ASP.NET controllers.  You just write classes with methods, which get mapped to graphs with fields.  To add arguments to a field, just add arguments to the method.  You can inject any scoped services you want into the class constructor as the class will be created via DI just like ASP.NET controllers are done, on an as-needed basis.  All of the wire-up is done during schema initialization so there is no performance degradation. You can use attributes to tag methods as needing a service scope or not, or being concurrent or not.  You can inject services directly into methods by adding a `[FromServices]` attribute to an argument, just like ASP.NET.  I wrote the library, but unfortunately I have not documented it at all and there are plenty of features I would like to add -- but it does work very nicely.  Sometime I think it would make a nice addition to integrate into GraphQL.NET, as it is much easier to write pretty-much any kind of graph, and its extensive DI support, but for now it is a standalone library.  Download: https://www.nuget.org/packages/Shane32.GraphQL.DI

**Comment by joelmandell** [comment]
Maybe I do not fully understand your requirements or what you want to achieve.
But I use this:
```
Field<ListGraphType<KeyCardType>>().Name("keycardRegistry")
   .Resolve()
   .WithScope()
   .WithService<TenantData>()
   .Resolve((ctx, tenantData) =>
   {
       return new KeyCards(tenantData).GetAll();
   });
```

I read the linked article about "Service Locator", being an anti-pattern. But I do not see that pattern applied in this case?

**Comment by Shane32** [comment]
Like I said it’s a matter of opinion. I wrote the builders you’re using in that sample as another option, but after most of my production code was already written.  I think it’s pretty clean, for what it is. 

As to whether it’s still an anti-pattern or not, 🤷‍♂️

**Comment by EmmanuelPonnudurai** [comment]
@Shane32 Thank you for the detailed explanation. Appreciate it. 

So, I think we can conclude that for GraphQL.NET, to make schema as singleton, we _must_ use the service locator pattern. The different approaches mentioned here are all using that behind the scenes.

Also, thank you for the pointer to this piece https://github.com/Shane32/GraphQL.DI.  Ill take a closer look.

**Comment by Shane32** [comment]
> Also, thank you for the pointer to this piece https://github.com/Shane32/GraphQL.DI. Ill take a closer look.

I added a working sample application.  Ugh the project needs a lot of work; the setup is too complex and it really needs documentation.

**Comment by EmmanuelPonnudurai** [comment]
Closing this. I am in the process of suggesting doc updates. Hopefully that should clear any confusion with this.

**Comment by sungam3r** [comment]
> However, is this also an **encapsulation** over service locator pattern **again**?

Please read SteroidsDI readme, especially that [part](https://github.com/sungam3r/SteroidsDI#faq):
![изображение](https://user-images.githubusercontent.com/21261007/145121771-dce46b8e-a87c-4245-9e79-4e9a8cacabe6.png)

The attentive reader will pay attention to the word _encapsulation_. If we speak simple words - `ServiceLocator` is when you yourself **pull** the dependencies manually from the inside of your object. Abstractions from SteroidsDI package allows you to **push** dependencies (actually _proxies_ for these dependencies) into your objects. Of course under the hood these dependencies should be **pulled** from DI-container but there is no anything wrong in all that. Look at the methods in `Microsoft.Extensions.DependencyInjection`. Almost each of them has an overload with `IServiceProvider` in lambda to bring the power of `GetService` into user-code.

> So, I think we can conclude that for GraphQL.NET, to make schema as singleton, we **must** use the service locator pattern. 

😮 

> it is basically the same as using `RequestServices`, so why?

One reason is that in some cases there is no `RequestServices` or any other `XXXServices` at all. Most of my time I work with libraries, I develop them instead of concrete services (products). Libraries not particularly for ASP.NET but for a broader set of things. So in my case I should always think about more general approaches and environments.
