### ISSUE TITLE
In Schema First - unhandled exception (FormatException) for malformed ID inputs

### ISSUE THREAD

**Issue by pgaule1984** [graphql-dotnet/graphql-dotnet#2587]
## Description

When using the "schema first" approach, if you specify a graphQL "ID" type on the schema, but use a specific type on your query class (i.e. Guid), then you can get an unhandled exception (FormatException) if the query argument is malformed.

### Steps to reproduce

**GraphQL schema:**

```
type Owner{
    id: ID!
    name: String
    address: String
}

type Query{
    owners: [Owner!]
    owner(id: ID!): Owner
}
```

**C# class**

```
public class Owner
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
}
```

**Query class**

```
[GraphQLMetadata("Query")]
public class SingleGraphQuery
{
    private readonly IOwnerService _ownerService;

    public SingleGraphQuery(IOwnerService ownerService)
    {
        _ownerService = ownerService;
    }
    
    [GraphQLMetadata("owner")]
    public async Task<Models.Owner> GetOwnerById(Guid id)
    {
        return await _ownerService.GetById(id);
    }
}
```

Query to run in the playground (note the malformed Guid)

```
query{
  owner(id:"THIS_IS_NOT_A_GUID"){
    id,
    name,
    address
  }
}

```

### Expected result

Ideally, I would get an error that tells me the GUID is malformed:

```
{
  "errors": [
    {
      "message": "Argument 'id' has invalid value. Expected type 'Guid', found \"THIS_IS_NOT_A_GUID\".",
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "extensions": {
        "code": "ARGUMENTS_OF_CORRECT_TYPE",
        "codes": [
          "ARGUMENTS_OF_CORRECT_TYPE"
        ],
        "number": "5.6.1"
      }
    }
  ],
  "extensions": {}
}

```
This is the message I get if I explicitly alter the schema to use a Guid instead of an ID:

```
type Owner{
    id: Guid!
    name: String
    address: String
}

type Query{
    owners: [Owner!]
    owner(id: Guid!): Owner
}

```
It seems like GraphQL.NET should be able to discern what type is expected based on the type specified in the Query class rather than throwing an unhandled exception.  As a workaround, I created a custom IdGraphType that extends the built-in GuidGraphType, since our ID types always correspond to GUIDs.  The downside of this approach is that it applies to all queries that specify an "ID" type, so if you have a mix of numeric/string/guid types, then it could cause problems.

```
public class CustomIdGraphType : GuidGraphType
{
    public CustomIdGraphType()
    {
        Name = "ID";
    }
}
```

`schema.RegisterType(new CustomIdGraphType());`

### Actual result

**GraphQL response:**
```
{
  "errors": [
    {
      "message": "Error trying to resolve field 'owner'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "owner"
      ],
      "extensions": {
        "code": "FORMAT",
        "codes": [
          "FORMAT"
        ]
      }
    }
  ],
  "data": {
    "owner": null
  },
  "extensions": {}
}
```

**Unhandled Exception**
```
System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
   at System.Guid.Parse(String input)
   at GraphQL.ValueConverter.<>c.<.cctor>b__1_15(String value) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 52
   at GraphQL.ValueConverter.<>c__DisplayClass7_0`2.<Register>b__0(Object v) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 224
   at GraphQL.ValueConverter.TryConvertTo(Object value, Type targetType, Object& result, Type sourceType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 183
   at GraphQL.ObjectExtensions.GetPropertyValue(Object propertyValue, Type fieldType, IGraphType mappedType) in /_/src/GraphQL/ObjectExtensions.cs:line 175
   at GraphQL.ResolveFieldContextExtensions.TryGetArgument(IResolveFieldContext context, Type argumentType, String name, Object& result) in /_/src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs:line 55
   at GraphQL.ResolveFieldContextExtensions.GetArgument(IResolveFieldContext context, Type argumentType, String name, Object defaultValue) in /_/src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs:line 26
   at GraphQL.Reflection.ReflectionHelper.BuildArguments(ParameterInfo[] parameters, IResolveFieldContext context) in /_/src/GraphQL/Reflection/ReflectionHelper.cs:line 112
   at GraphQL.Reflection.AccessorFieldResolver.Resolve(IResolveFieldContext context) in /_/src/GraphQL/Reflection/AccessorFieldResolver.cs:line 19
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 393
```

### Environment
Package Version - 4.5.0

**Comment by Shane32** [comment]
Interesting.  I don't use schema-first, but if it was code-first, all parsing is done by graph type class/instance.  In this case, the IdGraphType does not parse values at all, but just stores them verbatim.  This is why replacing the ID graph type works well - now the input values are properly parsed prior to document execution.  With code first, conversion would take place during `var id = context.GetArgument<Guid>("id");` within the field resolver.  The registered conversion for string to Guid would execute here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/6b9af75f9e891677dcf7f4c35ee7ae2f2cc2a935/src/GraphQL/Conversion/ValueConverter.cs#L183

And the conversion is here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/6b9af75f9e891677dcf7f4c35ee7ae2f2cc2a935/src/GraphQL/Conversion/ValueConverter.cs#L52

Since there is no other error handling, a processing error gets thrown.  See https://graphql-dotnet.github.io/docs/getting-started/errors

The question is, should a processing error be thrown, or an input error be thrown?  L183 could certainly be changed to catch exceptions and throw an ExecutionError, but normally input errors do not get thrown from resolvers.  So if (as would be typical) execution errors are logged via UnhandledExecutionErrorDelegate, it would be important to note that other code might have executed before GetArgument threw the input error.  Also, other fields may have already executed.  Yet, it probably is preferred for an input error to be thrown here.  This same logic would apply to schema-first, where during resolver execution, an input error will be thrown instead of a processing error.

For schema-first, you mentioned the schema could potentially examine the field relationship and adjust the graph type instance properly so that it is coerced to a Guid during parsing.  This really won't work, since a variable can be used in multiple places, potentially for both a Guid and integer, and is defined by the document and parsed only once.  Parsing must be kept separate from document execution.  However, your workaround is an excellent one, and should probably be noted in the documentation as the recommended approach for situations like yours.

**Comment by pgaule1984** [comment]
Thanks for the quick response.  For some context, the only reason we use schema first is because we use apollo federation (although I omitted that detail from this issue because it doesn't require a federated schema to reproduce).  I would much prefer to use code first, but until that is implemented as a code-first feature, we have to use "schema first" and weird things like this will creep up.

I noticed you mentioned the UnhandledExceptionDelegate, which is something we use. Would it be possible to throw a more meaningful exception that indicates the exception happened when parsing the input parameter, rather than a generic "FormatException" that could have happened from anywhere?

I am OK with the workaround, but just wondering if a more meaningful exception could be thrown for other cases.

**Comment by Shane32** [comment]
I think surely for schema-first, input coercion could throw a better exception.  I have not looked at the code for that yet, as I'm only vaguely familiar with how schema-first is coded.

**Comment by Shane32** [comment]
PR would be welcome also

**Comment by Mithras** [comment]
related https://github.com/graphql-dotnet/graphql-dotnet/pull/3144

**Comment by Shane32** [comment]
Note that code-first has a similar problem.  My personal solution is to utilize a custom `IdGraphType` implementation which coerces the value to the correct .NET type.  This only works if the same .NET type is used for all `IdGraphType` uses across the schema.  But then during the input coercion/validation it would fail, before the execution of the request begins.

**Comment by Shane32** [comment]
Can be fixed with new feature:
- #3857
