### ISSUE TITLE
how does the defaultValue of GetArgument work?

### ISSUE THREAD

**Issue by jchn-codes** [graphql-dotnet/graphql-dotnet#2610]
Hey guys,

I'm a bit confused about the defaultValue of the GetArgument function.

`var myArgument = resolveFieldContext.GetArgument("myArgument", string.Empty);`

I would expect that `myArgument` has an empty string (`""`) as value when no argument is passed. instead the result is `null`. 
What do I miss here?

`var myArgument = resolveFieldContext.GetArgument("myArgument") ?? "";` works as expected.

**Comment by Shane32** [comment]
I'd need to see the exact query.  If the field argument was passed null, then null will be returned.  If the field argument is set to a variable, and the variable was set to null, then null will be returned.  If the field argument was set to a variable, and variable default's value is null, and the variable was not specified, then null will be returned.  If the field argument was completely unspecified, then the field argument's default value will be examined and returned if it is not null.  Only if the field argument was completely unspecified and there is no default value set for the field argument will the default value be taken from GetArgument.  If you simply want null values to be replaced with empty strings, then you want to use the syntax you already mentioned (`?? ""`) rather than specifying a default value to GetArgument.

Note that there is no way to set a field argument's default value to a specific value of null -- in that case null by definition is unspecified within GraphQL.NET.

**Comment by jchn-codes** [comment]
Thanks for clarification!
