### ISSUE TITLE
Reusing common logic between fields in the type class

### ISSUE THREAD

**Issue by giy** [graphql-dotnet/graphql-dotnet#2614]
## Summary
Apologies if this has been asked before, but I wanted to ask about how I can re-use certain logic between fields in a graphql-dotnet type class ?

## Relevant information
For e.g.

```
public MyClassType()
{
Name = "MyClassType";
Field<SomeEncloserType>(
            name: "somefield",
resolve: context =>
 {
      var requestName = context.Path.First().ToString();
      var vibrancySettings = (VibrancySettings)context.Variables.ValueFor(requestName);
      var otherSettings = vibrancySettings.SomeOtherSettings;
      var valueSharedBetweenSomeAndAnotherField = otherSettings.SomeCalcProperty;
      .....
     // some logic for somefield using valueSharedBetweenSomeAndAnotherField
 });
```
And this same logic needs to be used all over the place,

```
Field<SomeEncloserType>(
            name: "anotherfield",
resolve: context =>
{
    var requestName = context.Path.First().ToString();
    var vibrancySettings = (VibrancySettings)context.Variables.ValueFor(requestName);
    var otherSettings = vibrancySettings.SomeOtherSettings;
    var valueSharedBetweenSomeAndAnotherField = otherSettings.SomeCalcProperty;
    .....
    // some logic for anotherfield using valueSharedBetweenSomeAndAnotherField
}
```

What would be the right way to calculate valueSharedBetweenSomeAndAnotherField like a method/class variable just once outside the field resolvers, for somefield and anotherfield so that it's calculated just once ?

Should I have another throwaway field for this value, in which case, we can also be always sure that on the tree, this value will always be calculated first before it reaches the field resolvers for somefield and anotherfield ?

Thank you!

**Comment by Shane32** [comment]
I would write an extension method for IResolveFieldContext. Sharing the data between fields may not work if it is dependent on the path because that’s different per field. But the UserContext property can store shared data, which can be precomputed prior to execution or on an as needed basis (e.g. in your extension method). Keep in mind that UserContext is not a thread safe dictionary so be sure to lock it during use if you use parallel execution. (It’s thread safe only if only reading from it within your field resolvers.)

**Comment by giy** [comment]
Thanks Shane! Would another option be to set this as a variable in the parent type class before it reaches my nested method ?

So if MyClassType is called by MyParentClassType for resolving a field say x whose nested fields are somefield and anotherfield, should I calc valueSharedBetweenSomeAndAnotherField as a variable and set it in MyParentClassType ?

Or am I using variables in a way they're not supposed to be used in trying to save re-calcs ? Sorry, I am not very familiar with graphql constructs/ preferred paradigms.

I think re-defining the calcs for valueSharedBetweenSomeAndAnotherField it in 2-3 fields again is not a big issue, if that is the preferred way and the only option available to me. But, I'd love to refactor this in my implementation, in case there's something I've missed in the documentation that provides for a cleaner/ efficient way to avoid re-calcs within fields.

Thank you!

**Comment by Shane32** [comment]
That might work. I have something similar where I have a search field, and I return the arguments from the resolver so the source object for the child fields contain the arguments of the parent field. Basically, whatever works, go for it.

**Comment by giy** [comment]
Hello, thank you for all the suggestions from last time.

I had another quick question while extending our class.
For e.g. I have,
Field<MyCustomTypeA>(
            name: "fieldA",
            resolve: context =>
            {
                ... some complex calc to set fieldA
                context.Variables.Add(new Variable
                {
                    Name = "varA",
                    Value = fieldA
                });
                return fieldA;
            });
Field<MyCustomTypeB>(
            name: "fieldB",
            .. depends on varA to calc fieldB
            });
Field<MyCustomTypeC>(
           name: "fieldC",
            .. depends on value of fieldB
            });

In this case, can I assume that it will be true that the nodes within the tree will be executed in order ? 
So, for e.g. the value of varA will always will be available to fieldB not requiring me to re-add the logic for the calcs for varA within fieldB ?
Or in the case of fieldC I can re-use the value of fieldB without adding all this logic within fieldC ?

Right now, I am seeing that I can get away without redefining these calcs because fieldB is always only calculated after fieldA is calcd and varA is set and fieldC is always only calcd after fieldB, but I'd confirm that this really will always be the case ?
And if so, is there any documentation that I can read to educate myself more about the execution paradigm ?

Thank you!

**Comment by Shane32** [comment]
The GraphQL specification allows parallel or serial execution of graph requests, as discussed here:

https://spec.graphql.org/June2018/#sec-Normal-and-Serial-Execution

In short, the default execution for queries is parallel execution, which may "execute a grouped field set in whatever order it chooses".  However, you may select serial execution, which "must consider each entry from the grouped field set in the order provided in the grouped field set".

I cannot find any documentation on https://graphql-dotnet.github.io/ which describes how to change the execution strategy.  However, it is quite simple; just create a class that inherits `DocumentExecuter` and override `SelectExecutionStrategy`:

```cs
    public class MyDocumentExecuter : DocumentExecuter
    {
        public MyDocumentExecuter(...) : base(...)
        {
        }

        protected override IExecutionStrategy SelectExecutionStrategy(ExecutionContext context)
        {
            return context.Operation.OperationType switch
            {
                OperationType.Query => SerialExecutionStrategy.Instance,
                OperationType.Mutation => SerialExecutionStrategy.Instance,
                OperationType.Subscription => throw new NotSupportedException($"DocumentExecuter does not support executing subscriptions. You can use SubscriptionDocumentExecuter from GraphQL.SystemReactive package to handle subscriptions."),
                _ => throw new InvalidOperationException($"Unexpected OperationType {context.Operation.OperationType}")
            };
        }
    }
```

Of course you will need to register this class with your DI engine as `IDocumentExecuter` or otherwise use the new class.

Keep in mind that there is no restriction that the client will request these fields in order.  So while this may work:

```gql
{
  fieldA
  fieldB
  fieldC
}
```

This may not:

```gql
{
  fieldC
  fieldB
  fieldA
}
```

Further, remember that a client can request field multiple times, possibly with different parameters, as in this sample, which may cause issues if fieldB relies on the output of fieldA:

```gql
{
  fieldA (id: 1)
  fieldAalt: fieldA (id: 2)
  fieldB
}
```

I also noticed that you are storing the temporary value within `context.Variables`.  That property is only for variables passed from the client; use `context.UserContext` instead.  Otherwise this code could fail because `varA` was overwritten by `fieldA` before `someField` executed:

```gql
query ($varA: ID!) {
  fieldA
  fieldB
  fieldC
  someField (id: $varA)
}
```

**Comment by Shane32** [comment]
Personally, I would add a caching layer and pull the results of the reusable logic from the cache in fieldA, fieldB, and/or fieldC, ensuring that the cache key contains any variables necessary to reconstruct the data.  The cache could be limited to the request, rather than a long-lived cache, and could be implemented via serial execution and the `context.UserContext` property, or for parallel execution, by adding a `ConcurrentDictionary` instance to the user context before execution, then manipulating the concurrent dictionary at runtime.  Of course there are fancier ways, such as encapsulating the logic within a service, and storing the concurrent dictionary within an `AsyncLocal<>` created by a document listener.  Or more simply, a scoped service that has the concurrent dictionary created in its constructor.

**Comment by giy** [comment]
Thanks a lot for the suggestions above Shane!

Are there any examples in the repo where I can create functions and set/return variables etc. within a type class so that I only need to do this once ? The method can be called before I need to resolve all of the fields that need this calc ?
Sorry, I am not sure if I am adding more problems by doing this.

**Comment by Shane32** [comment]
We have no examples of the logic I’ve described as it’s rather dependent on your exact scenario. And it’s a bit difficult to give a more specific example without a more specific scenario.

**Comment by Shane32** [comment]
Any further questions here?

**Comment by giy** [comment]
No, happy to close this one out as well. Thank you!
