### ISSUE TITLE
How to validate existence of certain inputs and if they don't exist inject them?

### ISSUE THREAD

**Issue by gregorvilkner** [graphql-dotnet/graphql-dotnet#2649]
I want to use input filters to manage and limit access to certain areas of a graph for certain users. How can I validate if a certain input for filtering exist on certain items in a query? If it doesn't exist I would like to inject an input. The goal is to adjust and return the query, not to resolve it.

Would I use the parser for this?

Thanks.

**Comment by Shane32** [comment]
> I want to use input filters to manage and limit access to certain areas of a graph for certain users. 

I would check out the authorization project: https://github.com/graphql-dotnet/authorization
And also the authorization library within the server project: https://github.com/graphql-dotnet/server

I'm a bit confused about the rest of your question.

**Comment by gregorvilkner** [comment]
Thank you very much for the fast response. Let's say I have 3 queries:

{
  cars( filter: {make: {equalTo: "Ford"}} ) { id vin }
}

{
  cars { id vin }
}

{vehicles{
  cars( filter: {color: {equalTo: "red"}, price: {greaterThan: "14000"}} ) { id vin }
}}

I want to change all 3 queries so that only blue cars are queried for. How can I a) find the cars node, b) see if there's a color filter appied already, c) change an existing color filter value or add a color filter value. So what I want in the end are these 3 queries:

{
  cars( filter: {**_color: {equalTo: "blue"},_** make: {equalTo: "Ford"}} ) { id vin }
}

{
  cars **_( filter: {color: {equalTo: "blue"})_** { id vin }
}

{vehicles{
  cars( filter: {color: {equalTo: "**_blue_**"}, price: {greaterThan: "14000"}} ) { id vin }
}}

**Comment by Shane32** [comment]
You can convert the graphql query string to a 'document' by calling `new GraphQLDocumentBuilder().Build(query)`.  Then you can loop through the objects and modify them as desired.  Note that these objects relate to the original query string, and not to the schema.  So you will need to correlate them yourself as necessary.

When calling the `DocumentExecuter`, pass the modified document in via the `ExecutionOptions.Document` property.

I don't think creating a validation rule will work since modifying the document during validation would probably create problems with the node walker.  But it might work just fine... you'd probably have to test it.

**Comment by Shane32** [comment]
You should also be aware that the document may refer to variables.  The variables are stored separately from the document, and so for example if the query was:

```gql
query ($filter: FilterType) {
  vehicles {
    cars (filter: $filter) { id vin }
  }
}
```

then you would need to separately examine the "filter" variable to see if it contains a color and modify it if needed.

**Comment by Shane32** [comment]
You could also consider overriding the `ParseDictionary` method of the filter input type so that it examines the dictionary and looks for a 'red' value and changes it to 'blue'.  This should be much easier to implement, with the same end result, and without having to dive into validation rules or walking the document and variables looking for specific nodes.  But of course it only applies to input objects.

**Comment by gregorvilkner** [comment]
This is all great advice. Thank you so much. I was able to use the the GraphQLDocumentBuilder to recursively parse through my query. Gets me to the correct fields and let's me inspect what action to take. I also managed to build an argument to add into the document.

I think a big question left on my side is if the library can create a graphql query string? My use case is to manipulate queries and throw them back to an endpoint. Document.ToString() is the AST model. Is there a way to read out a query string?

I'll paste some code snippets later for future reference...

Thanks.

**Comment by Shane32** [comment]
> I think a big question left on my side is if the library can create a graphql query string? My use case is to manipulate queries and throw them back to an endpoint. Document.ToString() is the AST model. Is there a way to read out a query string?

I don't think it was ever implemented.  See https://github.com/graphql-dotnet/parser/issues/11

There is a SchemaPrinter and an AstPrinter in the main library, but neither prints the document generated by `GraphQLDocumentBuilder`.

**Comment by sungam3r** [comment]
Even one more option - add desired "injected" inputs as default values for field arguments.

Closed as answered.

**Comment by Shane32** [comment]
> I think a big question left on my side is if the library can create a graphql query string? My use case is to manipulate queries and throw them back to an endpoint. Document.ToString() is the AST model. Is there a way to read out a query string?

GraphQL-Parser v8, required by GraphQL v5/v7, now has this capability.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/parser#3-astvisitor
