### ISSUE TITLE
Support SQL "JOIN"-based optimizations

### ISSUE THREAD

**Issue by moserware** [graphql-dotnet/graphql-dotnet#265]
This is a more focused continuation of the discussion that started in https://github.com/graphql-dotnet/graphql-dotnet/issues/21

In particular, this issue calls for the `graphql-dotnet` project to implement something similar to [Stem's Join Monster](https://github.com/stems/join-monster) in .NET. That is, we could take various fields (and child fields) that resolve from a database and retrieve them by using a single SQL query with `JOIN`s (and semantic equivalents like `OUTER APPLY`s).

A few key decisions ahead:

1. This probably doesn't belong in core but rather a new repo/NuGet package. What should it be called? "Join Monster.NET"? Something more creative? If we decided to go with "Join Monster.NET", we'd likely need to have a conversation with @acarl005 or others on that project if they'd be OK with us using that name.

2. Should we stick to the Join Monster API or also look towards other similar ideas like [GraphJoiner](https://github.com/mwilliamson/node-graphjoiner)?

3. Should we add additional APIs like the ability to issue a single call with `JOIN`s or multiple calls with `WHERE IN (...)` queries for each level of the subgraph?

**Comment by benmccallum** [comment]
Doesn't look like there's been much progress here 😝 It's certainly a tough problem. 

Over at [graphql-net](https://github.com/ckimes89/graphql-net) the implementation dynamically builds an IQueryable. I'm currently exploring that library, but it's severely lacking in support of the spec (no variables, introspection doesn't work, etc. etc.) and a community that it's unusable for me. I do like the fundamental approach though and I think the wider .NET community really needs the best of both these libraries. 

For instance, using IQueryables it can use projection to only request fields asked for, and can handle things like paging and sorting to for you simply by extending the original IQueryable you provide in your resolver. You can then have any IQueryable provider under there (SQL or CosmosDB) and it just works (for the most part)!

I may be missing something fundamental, but would it be possible for a graphql executor to just continue to build up an IQueryable across/down through fields right until the last moment or execution is required (e.g. service boundary). Then we let the underlying IQueryable provider handle the complexity of resolving it to an optimal query (e.g. EF Core + SQL, or EF Core + CosmosDB which is coming soon).

**Comment by vertonghenb** [comment]
@benmccallum, any luck with exploring the Graphql-net library (F# isn't really my thing at the moment).

The EF Core team has done some remarkable work in their latest version (2.1, still in preview). We should really consider supporting IQueryable which will solve a lot of issues with included properties etc.

I'd gladly participate in this solution, any idea's how to tackle the issue?

**Comment by benmccallum** [comment]
@vertonghenb, For my current project I've decided to go a little more raw and use something called Dapper.GraphQL where you're essentially building up the query yourself so it's optimised by you. Haven't gotten to building on it just yet but my plan is DbUp + Dapper.GraphQL which uses this library (graphql-dotnet) and exposed via graphql-dotnet/server middleware.

I'd love to see the IQueryable support come over into here in some form, but I just don't have the skills in that area of expression building and manipulation, so it's a little out of reach for me. If someone else wanted to help, like @ckimes89, we'd really get the value out of both libraries.

The EF Core team are also working on a CosmosDb EF provider so that'd be amazing to have a CosmosDb collection backing graphql-dotnet endpoint, even though there's no concept of cross-collection JOINs at this stage.

**Comment by vertonghenb** [comment]
@benmccallum The Dapper.GraphQL package looks pretty interesting but I don't like to go back to Dapper especially because of the work being done in EF Core.  However Dapper is still amazing though!

I'll post a Medium article soon how I tried to manage the Join issue. The main idea is to check the include props. (to be continued)

**Comment by joemcbride** [comment]
Not sure if it is well known, but the `ResolveFieldContext` does have a [`SubFields`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ResolveFieldContext.cs#L52) property which is the fields that should be requested.  It looks like that `Dapper.GraphQL` may have a bug in that even though a field is in the `SelectionSet`, it may not necessarily be returned (due to directives mainly).

**Comment by benmccallum** [comment]
@vertonghenb, would be keen to see what you came up with for sure, share a link when you can.

@joemcbride, are you saying that Dapper.GraphQL is building the SELECT clause with SubFields/SelectionSet correctly, but doesn't take into account directives that may mean some fields/columns wouldn't need to be returned for those records? I guess many implementations would overlook this. Maybe a complete example would help, and you/I can log an issue over there.

**Comment by patoncrispy** [comment]
Hey everyone, has there been any progress on this?

**Comment by techniq** [comment]
https://github.com/SimonCropp/GraphQL.EntityFramework has been serving me very well (first GraphQL project, migrating from OData)

**Comment by TheMoogster** [comment]
I guess there is no more progress on this?

**Comment by joemcbride** [comment]
@TheMoogster 3rd party libraries are handling this, it will most likely not be something built-in to the core framework at this point.

**Comment by TheMoogster** [comment]
> @TheMoogster 3rd party libraries are handling this, it will most likely not be something built-in to the core framework at this point.

You know any 3rd party lib that does this for .NET?

**Comment by joemcbride** [comment]
See these resources listed in the docs:

https://graphql-dotnet.github.io/docs/getting-started/databases

**Comment by martinhjulstrom** [comment]
I’ve been tinkering with a project that translates the GraphQL query into an IQueryable select. Paired with Entity Framework it solved both the n+1 problem and the problem of over fetching data in my project. I’ve uploaded the project to [nuget ](https://www.nuget.org/packages/GraphQLToQueryable/)and to [github ](https://github.com/martinhjulstrom/GraphQLToQueryable) if any one is interested.

**Comment by ckimes89** [comment]
@martinhjulstrom that looks remarkably similar to my (notably unmaintained) project ckimes89/graphql-dotnet! Perhaps you can steal some ideas from that and take it farther than I did.

**Comment by martinhjulstrom** [comment]
@ckimes89 great work! I'll look it up if I decide to take it further

**Comment by SimonCropp** [comment]
@joemcbride @sungam3r IMO this should not be in the core of graphql net. AFAIK nothing in the core is stopping people from implementing their own, i cant imagine it would be much different from https://github.com/SimonCropp/GraphQL.EntityFramework.  

So I propose we close this?

**Comment by sungam3r** [comment]
Yes, apparently, it no longer makes sense to keep this issue open. Over 3 years, more than enough 3rd party libs have appeared.
