### ISSUE TITLE
Is it possible to extend fields or inject additional objects to a ConnectionType

### ISSUE THREAD

**Issue by cheaze** [graphql-dotnet/graphql-dotnet#2663]
Hi, I am using GraphQL 2.4.0 with GraphQL.Relay 0.5.0. 

I have been using it successfully for all my needs with serving data to a Gatsby build engine. It's been great.

I have been making use of the ConnectionType in the Relay package.
I need to build a new feature for searching for properties (houses/flats etc), which will return Connection<PropertyType> and take in arguments as parameters, this is all fine and works.
However, in addition to the paged results being returned, my search also needs to be able to return the "facets" of the search.
E.g. Let's say the search returns 40 properties. The facets may say of the 40 results we have "25 houses, 10 flats & 5 bungalows" or "10 properties have 2 bedrooms, 25 have 3 bedrooms, & 5 have 4 bedrooms."
I have this List<Facets> created and returned by the search method and it's ready to go. It's not really part of the property data, it's additional data about the search.
Is there a way to somehow add extra Fields to the Connection? I'd be happy to add this into the PageInfo or as new object on the Connection?
Is this possible, I have tried various things (extending the PageInfoType in my project) but I am struggling to get this going? Is there something clever I am missing?

Maybe I am approaching this the wrong way? Any suggestions?

Thanks!

I am working on a Windows 10 Development machine

**Comment by Shane32** [comment]
This isn't exactly an answer to your question, but this is what I do for my own GraphQL endpoints: I make the results and the facets children of a common parent.  For example:

```gql
{
  properties (minSqft: 500) {
    facets {
      number
      description
    }
    results (first: 100) {
      pageInfo {
        startCursor
        endCursor
      }
      items {
        address
        sqft
      }
    }
  }
}
```

This way, if you only request `facets`, the server does not need to process or return the results, and if you only request `results` the server does not need to process or return the facets.  Notice that the `after` parameter is only on the results.  This is because the facets usually apply to the entire set of data, not just the page you are returning.  However, any search parameters (such as `minSqft` in the above example) are placed on `properties` so that they are applied when returning the facets.

You can of course customize the connection type to return the facets, but you may be wasting CPU/database time if your front-end requests the connection separate from the facets.  I'm not very familiar with GraphQL 2.4.0, as I really have not used anything before 3.0 (the current version is 4.6.0), but likely the codebase is similar.  In the current version, the `ConnectionType` included with GraphQL.NET can easily be extended to a new class and customized for your needs.  You can then use the `Connection<TNodeType, TEdgeType, TConnectionType>()` method in the parent type to specify the exact connection type to use.

As for the Relay project, we have recently published an updated Nuget package that is compatible with the current version of GraphQL.NET.  You may not need it since the basics required for relay are included with GraphQL.NET.  The remaining functionality that exists in the project has to deal with filtering results within .NET.  Since this requires downloading the entire dataset from the database before returning the requested edges, I do not use that code in my own projects, but rather have custom code that applies proper `.Skip()` and `.Take()` LINQ operations to the `IQueryable` prior to retrieval from the database.

**Comment by cheaze** [comment]
Hi @Shane32, thank you for your advice. I will take a look at trying your approach.
Updating to the latest version has been on my backlog too. I will attempt the upgrade process asap.
Thanks again!

**Comment by Shane32** [comment]
Just FYI, be sure to read the upgrade notes when you decide to upgrade.

- 2.x to 3.x: https://graphql-dotnet.github.io/docs/migrations/migration3/
- 3.x to 4.x: https://graphql-dotnet.github.io/docs/migrations/migration4/

The new version comes with many features and bug fixes.  Some of my favorite new features are:

- New data loader design which fixes many bugs
- New exception handling design
- XML comments throughout
- Support for System.Text.Json
- Support for scoped services within a singleton schema
- Improved performance

**Comment by cheaze** [comment]
Thanks @Shane32 for the links to the upgrade notes. I will be sure to follow them carefully.

Thanks also for your original advice. I have followed the same approach as your example and it works really well.

**Comment by Shane32** [comment]
Let me know if you have further questions.
