### ISSUE TITLE
[Question] Is it possible to build an anonymous type from a GraphQL query?

### ISSUE THREAD

**Issue by marshalhayes** [graphql-dotnet/graphql-dotnet#2665]
## Summary

I'm using Entity Framework Core with an NpSQL connector, and have wrapper services for retrieving information from the databases (consider `IPlayerService.GetPlayerById(int id)`). This function returns the row corresponding to that id from the `player` database.

This method is used in the `playerById` GraphQL query:

```graphql
query {
  playerById(id: $id) {
    name
    expirationDate
  }
}
```

I've noticed that, regardless of which fields are requested, the database query always selects every column from the database. I realize this is how Entity Framework works, unless you manually select the properties you need before the SQL query is executed (see [projecting only properties you need](https://docs.microsoft.com/en-us/ef/core/performance/efficient-querying#project-only-properties-you-need)).

**Is there a way to know which fields are being requested from a GraphQL query and somehow map them to an object, generic, or anonymous type?**

I have no issue using reflection or similar if needed. The performance hit would likely be smaller than the extra network overhead, or least I'm hoping so.

## Relevant information 

The `Player` object mentioned above has about 20 columns and looks like this: 

```csharp
public class Player 
{ 
  public int Id { get; set; }
  public string Name { get; set; }
  public string State { get; set; }
  public string Country { get; set; }
  public DateTime? ExpirationDate { get; set; }
  // ... ~15 more properties
}
```

And, the GraphQL query in question is created here:

```csharp
public sealed class PlayerQuery : ObjectGraphType<object>
{
    public PlayerQuery(IServiceProvider serviceProvider)
    {
        Name = "Query";

        QueryArguments getPlayerById = new(new List<QueryArgument>
        {
            new QueryArgument<NonNullGraphType<IntGraphType>> {Name = "id", Description = "ID"}
        });

        FieldAsync<PlayerType>(
            "playerById",
            "Returns a single player by ID",
            getPlayerById,
            async context =>
            {
                using IServiceScope scope = serviceProvider.CreateScope();
                IPlayerService playerService = scope.ServiceProvider.GetRequiredService<IPlayerService>();

                return await playerService
                    .GetPlayerByIdAsync(
                        context.GetArgument<int>("id"),
                        context.CancellationToken
                    );
            }
        );
    }
}
```

I think the ideal solution would give me an object which has a subset of properties in `Player`, which I could then pass to 
the service method like `T IPlayerService.GetPlayerById<T>(int id)` or maybe even `object IPlayerService.GetPlayerById(int id, object subPlayer)` if absolutely necessary.

The `T IPlayerService.GetPlayerById<T>(int id)` would then retrieve the player like this:

```csharp
public T? GetPlayerById<T>(int id)
{
    return databaseContext.Players.Where(p => p.Id == id).Take(1).Select(t => MethodThatUsesReflectionToMapProperties(t, typeof(T)));
}
```

**Comment by Shane32** [comment]
It is certainly possible to do so; I have done it.  It took about a month of effort.  I used this MIT-licensed project as a basis, but there is hardly any code left from the original project now.  https://github.com/SimonCropp/GraphQL.EntityFramework

Basically, my code examines the requested fields, matches them up to the schema, and pulls expressions from stored metadata.  Then it builds them into an expression that can be passed to either Entity Framework or linq2db.  It generates select expressions as dictionaries, since it's not possible to generate anonymous types at runtime (at least, not without a lot more effort, involving dynamically creating assemblies at runtime).  Then the field resolver pulls the proper field from the dictionary.  Unfortunately I cannot share the code, but I can answer questions.

Other people have mentioned using an automapper or something.  I suggest reading the comments on this issue:
- https://github.com/SimonCropp/GraphQL.EntityFramework/issues/145

Note that the current version of linq2db breaks compatibility; I am using v3.3.0.  See:
- https://github.com/linq2db/linq2db/issues/3160
- https://github.com/linq2db/linq2db/issues/3161

The latest versions of Entity Framework Core 2.x, 3.x and 5.x should be compatible, as far as I know.

**Comment by marshalhayes** [comment]
Interesting. I'll take a look at those!

**Comment by sungam3r** [comment]
Feel free to reopen if any questions left.
