### ISSUE TITLE
IResolveFieldContext.Source nullable?

### ISSUE THREAD

**Issue by ericvan76** [graphql-dotnet/graphql-dotnet#2705]
## Summary

I recently updated the package from 4.5.0 to 4.6.1. Found lots of build errors due to the nullable change [#2599](https://github.com/graphql-dotnet/graphql-dotnet/pull/2599). Especially on this `IResolveFieldContext.Source` [code](https://github.com/graphql-dotnet/graphql-dotnet/blame/master/src/GraphQL/ResolveFieldContext/IResolveFieldContext.cs#L104), why is this nullable? I can also see some usages in the same commit having `context.Source!`, which assuming it's not null. Is there any scenario/reason that the source in the resolve context would be null?

**Comment by Shane32** [comment]
`ExecutionOptions.Root` defaults to `null`, and is probably left as null for most implementations.  Because of this, all fields that resolve on the root `Query` or `Mutation` types will have a null `Source` property.

It cannot be null for any child node, however.  Perhaps `IResolveFieldContext<out TSource>` should not have `new TSource? Source` marked as nullable.

**Comment by Shane32** [comment]
In general, I did try to set nullability indicators based on how a user would see/use them.  But some situations are not clear.  For example, `ResolvedType` is generally left as `null` while the schema is being built, but is always resolved during execution.  So here `IProvideResolvedType.ResolvedType` is marked as nullable, since typically it is only used by users while the schema is being built, but you'll see a lot of `!` uses in the code, where it is known that it is only referenced during execution.

I'm happy to review suggestions for changes to nullability markings on members.

**Comment by Shane32** [comment]
Another member that should receive some attention is `GetArgument<T>`.  Right now it returns a `T?` value, and it also accepts a `T? defaultValue = null`.  But for non-null arguments, this will never be null.  Perhaps the return type should be `T`.  If a user wishes they can define `T` as nullable with `?` such as `string?`.  Comments?

**Comment by Shane32** [comment]
Also, `RequestServices` is marked as nullable.  It is not required for GraphQL, but in practice, either it will always be set and often-used, or it will never be set and never used.  So for convenience it would make sense to mark it as non-null, even though this is quite inaccurate.  As of now, it is marked as nullable.

There was a whole lot of complications with the internal execution code, but I don't figure users will typically see that.

**Comment by ericvan76** [comment]
@Shane32 , Thanks for the `IResolveFieldContext<out TSource>.Source` fix, that's great.

Regarding the `GetArgument<T>`, I would split it into two overloads:
```
T GetArgument<T>(string name);
T GetArgument<T>(string name, T default);
``` 

They will all depends on `T`, and user should make this type correct base on the graoh definition. 

The difference between these two is: if the T is non-nullable, the first one will return a c# default, and second will return user-specified default.

e.g. 
```
GetArgument<bool?>("foo"); // <= should return null when foo is not specified
GetArgument<bool?>("foo", true); // <= should return true when foo is not specified
GetArgument<bool>("foo"); // <= return false (c# default) when foo is not specified, This only happens when the foo is nullable in definition, but it's called in this way but not recommended. 
```

Hope this helps, I will take a look at the `RequiredServices` later.

**Comment by ericvan76** [comment]
@Shane32, I took a look at the `RequestServices`. Yes, I use this to resolve dependencies, and it should be always set if using the default DI. In other circumstances where it's not set for any reason, then it shouldn't be used at all. 

I think it should be marked as non-nullable, or the user will run into a runtime error if it's not set but used by accident.

**Comment by Shane32** [comment]
@sungam3r do you have any comments here?

**Comment by sungam3r** [comment]
I was busy for a while. I will continue to watch the email tomorrow.

**Comment by sungam3r** [comment]
`RequestServices` may be `null` so it should be `IServiceProvider?`.

**Comment by Shane32** [comment]
We could set ExecutionOptions.RequestServices to be non-null …. you really shouldn’t have to use `!` every time you use RequestServices.

**Comment by sungam3r** [comment]
Then it will mislead the user and contradict the original idea of NRT.
