### ISSUE TITLE
How to disable Graph Playground Schema Introspection?

### ISSUE THREAD

**Issue by lzhgus** [graphql-dotnet/graphql-dotnet#2749]
## Summary

The playground website should not show for an unauthenticated user, or can we add authentication to the introspection queries? so that we can control the visibility of the schema? 

### Environment (if relevant)
GraphQL.Server.Ui.Playground
and ApolloServerPluginLandingPageGraphQLPlayground

**Comment by sungam3r** [comment]
Are your question about #2692. Anyway, auth is out of scope for GraphQL.NET itself. This may and should be handled at some http hosting layer - ASP.NET Core or anytbhing else.

**Comment by lzhgus** [comment]
Thank you @sungam3r !  In this case, is there any way we can disable the introspection query?

**Comment by sungam3r** [comment]
> The playground website should not show for an unauthenticated user, or can we add authentication to the introspection queries?

Add autenticated requirement (policy) to the `Query` root type. See [auth project readme](https://github.com/graphql-dotnet/authorization) for example. You may use this project or another one specific for ASP.NET Core - the concept the same in both - marking type/field with some policy.

**Comment by lzhgus** [comment]
Thanks @sungam3r, I am using the same authenticated in the code for all the types, so when making other requests, it's working fine. But for the default schema introspection, there is no auth required at all, I may need to handle it from apollo server itself.

**Comment by sungam3r** [comment]
Techically server implemented by GraphQL.NET (or any other) **may** require auth on any part of graphql document.

**Comment by sungam3r** [comment]
@Shane32 IIRC you have implemented that feature among all your changes in server project.

**Comment by Shane32** [comment]
Authorization configuration for GraphQL.NET v7 allows for two configurations that would prevent introspection requests, and a third which allows them:

1. Transport authorization requirements

This is configured on the ASP.NET Core GraphQL middleware and would authorize any request over the configured transport (GET/POST/WebSockets) before it hits the GraphQL.NET execution engine.  Assuming that your server was a shopping mall, this would be like a locked fence around the property; no access at all.

2. Schema authorization requirements

This is configured on the `Schema` instance and processed by the validation rule.  However, requests for invalid fields would be reported as validation errors, so some information may still be revealed to the caller.  In the example above, this would be like locking the entrance to the mall; still no access, but visitors can see signage and other information that may be visible.

3. Graph-type authorization requirements

This is configured on the graph type (such as the `Query` or `Mutation` graph type) and processed by the validation rule.  Since the introspection fields are configured to disregard authentication requirements, they can still be accessed if they are the only field requested by the caller.  This akin to locking explicit stores within a mall; the directory is still viewable by anyone.

Please read here for more details on configuration:
- https://github.com/graphql-dotnet/server#authorization-configuration
