### ISSUE TITLE
Complexity should be calculated only for executed operation

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2866]

**Comment by sungam3r** [comment]
Should be easy after #3177

**Comment by Shane32** [comment]
I would not implement this change as it will require complexity to be calculated for cached documents. And it seems reasonable to calculate complexity for an entire document regardless of the selected operation because the complexity is a static value configured for the schema. 

It is possible to have a different complexity configuration per client but that would require calling ConfigureExecutionOptions to manually set up the complexity rule. We could add a second constructor with a Boolean argument to only check the requested operation, but I would leave it off by default.

**Comment by sungam3r** [comment]
> And it seems reasonable to calculate complexity for an entire document **regardless of the selected operation** because the complexity is a static value configured for the schema.

I don't get it.

```graphql
{
  query hard { user { name accounts { value currency } address { city postcode street } friends { name { friends { name { friends { name } } } } } social_media { id url } } }

  query soft { user { name } }
```

Entire document is analyzed and complexity is calculated for both 'hard' and 'soft' queries. It is obvious that for the 'soft' query it will be strange to have a complexity much more than in reality.

> I would not implement this change as it will require complexity to be calculated for cached documents. 

Cached documents can have **cached** complexity in one way or another.

**Comment by Shane32** [comment]
I’ll try to explain what I’m thinking: Why would someone send the aforementioned query to a server that cannot execute “hard”? That’s like saying you can send a request that contains an invalid field to a schema so long as you don’t execute the field. While possible, all built in validation rules operate on the whole document. Authorization rules don’t but that’s because an authorization rule might vary based on the active user. In this case if the schema is set to only let limited complexity documents be executed, then the document should be disallowed if it contains a query that is too complex regardless of whether it is being executed. 

Now if the complexity properties change dynamically then it should only check the operation being executed. But if it is static, it should check the entire document. 

In version 7, our GraphQL builder method registers the options class as a singleton as well as the validation rule that uses the class. So the value must be static with that configuration. So it should check the whole document. 

If someone wants a dynamic configuration, it’s an advanced scenario, which I don’t mind supporting, but not as default. They would probably add code via ConfigureExecutionOptions to set up the options and add validation rule. An additional property to the validation rule constructor or configuration parameters class would be sufficient.

**Comment by Shane32** [comment]
In a nutshell, if a document contains an operation that is impossible in any condition to execute, then the document should be rejected, regardless of whether the reason is a missing field or it’s too complex.

**Comment by sungam3r** [comment]
>  While possible, all built in validation rules operate on the whole document.

Right because they all **validate** document, it's syntax/logical correctness. Complexity analyzer does not validate document. It uses validation infrastructure to calculate some metric about executed request, that's all.

> Authorization rules don’t but that’s because an authorization rule might vary based on the active user. 

Just as you see the reason for the auth rule, there is a reason for complexity rule - it's designed to control complexity of **executed** fields, not all fields that document contains. By the way, `@skip` and `@include` directives should be handled as well in this regard.

**Comment by sungam3r** [comment]
> This seems quite arbitrary - why would you allow a document that contained the "hard" query if the server is configured such that it is too complex to execute? What point is there to allowing such a query if it can never be valid?

Because I allow an **execution** of concrete operation, not a whole document. "Document" is not a thing that is meant to be executed. "Operation" is such thing. Document is a container for 1 or more operations. Spec authors designed it so that we have "operationName" to set. It makes no sense to calculate the complexity of what will not be executed. It’s the same as demanding at the checkout in the payment store for the entire list of purchases of the client that he made at home and wrote on a notebook, although he was able to find only part of his positions and put them in the basket.

**Comment by Shane32** [comment]
I see it differently than you. To me the complexity validation rule validates the document is valid. If any part isn’t valid, it’s simply not valid. I don’t care what operation is being executed. 

To me the authorization validation rule is the exception, not the standard.

**Comment by sungam3r** [comment]
> To me the authorization validation rule is the exception, not the standard.

😄 Agree. The same idea for complexity :). It's not a standard rule at all that  _validates the document is valid_ as you said.

**Comment by Shane32** [comment]
Complexity analyzer has been rewritten for v8 in #3989 .  It now only analyzes complexity for the operation being executed.  Since the calculated impact may vary based on the variables passed to the query, the complexity analysis cannot be cached in any case.
