### ISSUE TITLE
NRE in GraphQL 4.5.0 where AddResolvedInterfaces checks for fields before AddFields is called

### ISSUE THREAD

**Issue by jamiehowarth0** [graphql-dotnet/graphql-dotnet#2870]
## Description

Given the following test class & interface:

```
private interface IInterfaceWithoutDescription
{
    string Property { get; set; }
    string Method();
}

private class ClassImplementingInterfaces : IInterfaceWithoutDescription
{
    public string Property { get; set; }

    public string Method() => null;
}
```

Lines 298 to 316 of GraphTypeAdapter.cs will attempt to call AddResolvedInterfaces, which checks that fields on the object match fields on the interface, *before* AddFields is called for the object, resulting in an exception.

### Steps to reproduce

See test class above for reproducible example. This is using GraphQL.NET 4.5.0, I have searched the issue bank and couldn't find much related.

### Expected result

Type gets added to the schema.

### Actual result

Exception thrown as the object field corresponding to the interface hasn't yet been added to the schema, resulting in an exception "this object does not implement interface".

### Environment

Windows 11, VS 2022, .NET 4.7.2

**Comment by Shane32** [comment]
Can you produce a larger code sample?  Are you using the conventions project?

**Comment by jamiehowarth0** [comment]
@Shane32 apologies, here's the code that constructs the GraphQLAdapter. This is in a single Xunit test so there should be no risk of any scoping issues.

'''
var builder = new GraphTypeAdapter(new TypeRegistry(), new DefaultServiceProvider(), new CompositeGraphVisitor());

var graphTypeDefinition = builder.Adapt(typeof(ClassImplementingInterfaces).GetTypeInfo());
```

There is an xunit assertion that follows this, but I get the error on calling builder.Adapt.

**Comment by Shane32** [comment]
Which exact nuget packages are you using for GraphQL ?

**Comment by jamiehowarth0** [comment]
```
<PackageReference Include="GraphQL.NewtonsoftJson" Version="4.5.0" />
<PackageReference Include="GraphQL.Relay" Version="0.6.2" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.4.1" />
```

I'm currently debugging GraphQL 4.5.0 from source locally (to find this error) so have swapped out the Nuget package temporarily.

**Comment by Shane32** [comment]
Well, I'm rather confused.  GraphQL.NET does not have a `GraphTypeAdapter` class, nor a `TypeRegistry` or a `CompositeGraphVisitor`.  Moreover, the only functionality within GraphQL.NET to automatically build a graph type is within `AutoRegisteringObjectGraphType` and `AutoRegisteringInputObjectGraphType` (or their helper methods).  In neither case do they handle interfaces.

There is the [conventions project](https://github.com/graphql-dotnet/conventions) which does this type of stuff, and it does have a `GraphTypeAdapter` class, but I do not see any constructors defined.  It also has a static `TypeRegistry` but no `CompositeGraphVisitor`.

I do see that you have mismatched nuget package versions.  The `GraphQL.Server.*` nuget packages should be version 5.x if you plan to use `GraphQL` (and `GraphQL.NewtonsoftJson`) version 4.5.  If you want to retain 4.x of the server project, then use 3.x of `GraphQL` and `GraphQL.NewtonsoftJson`.

The GraphQL projects also support source debugging.  So you should be able to debug into the GraphQL source without installing locally.  To do so, just disable "Just My Code" and enable "Enable Source Link support".  Since it would be a release build, the breakpoints and so on are not as accurate, but it's often sufficient.

![image](https://user-images.githubusercontent.com/6377684/150593499-00a153f5-eece-4a3b-b7b1-ddc299515099.png)

**Comment by Shane32** [comment]
If you can provide a GitHub link to the `GraphTypeAdapter.cs` file you mentioned, I can investigate some more.

FYI, in this repo, the `master` branch contains the current 4.x version.  `develop` contains the unreleased 5.0 version.  To browse repository as was released for version 4.5.0, use this link:

https://github.com/graphql-dotnet/graphql-dotnet/tree/4.5.0

**Comment by jamiehowarth0** [comment]
> Well, I'm rather confused. GraphQL.NET does not have a `GraphTypeAdapter` class, nor a `TypeRegistry` or a `CompositeGraphVisitor`. Moreover, the only functionality within GraphQL.NET to automatically build a graph type is within `AutoRegisteringObjectGraphType` and `AutoRegisteringInputObjectGraphType` (or their helper methods). In neither case do they handle interfaces.
> 
> There is the [conventions project](https://github.com/graphql-dotnet/conventions) which does this type of stuff, and it does have a `GraphTypeAdapter` class, but I do not see any constructors defined. It also has a static `TypeRegistry` but no `CompositeGraphVisitor`.
> 
> I do see that you have mismatched nuget package versions. The `GraphQL.Server.*` nuget packages should be version 5.x if you plan to use `GraphQL` (and `GraphQL.NewtonsoftJson`) version 4.x. If you want to retain 4.x of the server project, then use 3.x of `GraphQL` and `GraphQL.NewtonsoftJson`.
> 
> The GraphQL projects also support source debugging. So you should be able to debug into the GraphQL source without installing locally. To do so, just disable "Just My Code" and enable "Enable Source Link support". Since it would be a release build, the breakpoints and so on are not as accurate, but it's often sufficient.
> 
> ![image](https://user-images.githubusercontent.com/6377684/150593499-00a153f5-eece-4a3b-b7b1-ddc299515099.png)

I'm an idiot and I'll get back to you on this.

This project is https://github.com/umbraco-community/umbraco-graphql - basically bringing GraphQL support to Umbraco, which uses dynamic types generated at runtime to define a schema. I picked this up to upgrade it and there's a ton of functionality that's been duplicated from GraphQL v.prev that's now incorporated into newer versions, so I need to do some Nuget upgrades and reapproach this.

Sorry to waste your time!

**Comment by Shane32** [comment]
No problem; feel free to post if you have any questions.
