### ISSUE TITLE
Arguments need implementation using lync?

### ISSUE THREAD

**Issue by psavanur** [graphql-dotnet/graphql-dotnet#293]
Arguments like human(id: "1000") need implementation using lync to fetch human by id? I was under the impression GraphQL gets the correct result without need for backend implementation similar to fields selection which uses NewtonSoft inside.

Please clarify.

**Comment by jquense** [comment]
nit sure what this means... 

Graphql is a way to query data but you still need a backend to provide that data. your arguments can be whatever you want/need

**Comment by psavanur** [comment]
Yes I want to know if filtered data need to be supplied by us or GraphQL gets it by applying its own query mechanism.

**Comment by joemcbride** [comment]
Filtered data (as in the list of objects that GraphQL will extract fields from) needs to be supplied by you the developer.  For instance, if you have a list of people and you want to only return those who are older than 65 of age, then you the developer needs to do that filtering.

**Comment by jquense** [comment]
yeah GQL doesn't provide any sort of pagination, sorting, or filtering built-in. Instead lets you add arguments you can use to do those things, very similarly (and annoyingly) like REST. Things like Relay.js help a bit, because they add some conventions on top of your graphql schema so that the client (most of relay) can do smart paging.
