### ISSUE TITLE
Lifetime of validation rule in AddValidationRule

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#2947]
@Shane32  I see that rule is added as singleton and user cannot configure this. Why?

**Comment by Shane32** [comment]
The design of the GraphQL builder is not to provide every single method of configuration of services, but to provide options for those configurations that are recommended, with encouragement of the recommended pattern.  Although not recommended, registering a schema as scoped is also supported, due to the wide use.  However, the following services always register as singletons:
- `DocumentExecuter`
- `ComplexityAnalyzer`
- `ErrorInfoProvider`
- `DocumentCache`
- `GraphQLSerializer`
- `ValidationRule`

GraphQL types are registered as transients.

These allow configuration of lifetime:
- `DocumentListener`
- `IFieldMiddleware`
- `Schema`

However, `IFieldMiddleware` can cause major problems if it does not match the schema lifetime.  We probably should only have allowed middleware to be registered as transients by default (so the lifetime matches that of the schema).

Any other use would be considered an 'advanced use case' and require manual registration.  (I have no problem saying that for advanced scenarios, users must configure DI themselves.)

As for particulars, I was imagining that validation rules are primarily for validating an abstract schema.  However, if validation rules need to contact a database to verify authentication information, or something of the sort, I could see that a scoped validation rule would make sense.  Also, since validation rules are configured at execution time, there is no ill effect of having a lifetime that does not match the schema lifetime.  So I would support changing the validation rule extension methods to allow configuration of the registration lifetime, if you agree that it is appropriate.  I would not do so for the other extension methods at this time.

**Comment by sungam3r** [comment]
I can use a workaround like `Defer<T>` though.

**Comment by Shane32** [comment]
I think it makes sense to allow scoped validation rules if you think so also.

**Comment by sungam3r** [comment]
This is not urgently, now we will switch to the use of `Defer<>` from SteroidsDI.

**Comment by Shane32** [comment]
@sungam3r Should we add scoped validation rule support for v8?  I'd leave it as-is, encouraging singleton use.  Users can always register it as a scoped service if they need to in order to override the default lifetime -- for instance:

```cs
services.AddGraphQL(b => b
    /* more */
    .AddValidationRule<MyValidationRule>()
);
services.AddScoped<MyValidationRule>();
```

**Comment by sungam3r** [comment]
Looking through `GraphQLBuilderExtensions.AddValidationRule` overloads I see that we can easily add support for scoped validation rules - just add `ServiceLifetime` parameter with default singleton value and pass it into `RegisterAsBoth`. So I would do it for v8 or even for v7 but I do not want to bother with additional overloads and jumping around `useForCachedDocuments` default parameter.

**Comment by Shane32** [comment]
Transient validation rules would also make sense - every request execution would automatically create a new instance of the validation rule, simplifying local storage of validation rule data during execution.
