### ISSUE TITLE
FeatureRequest: ComplexityAnalysis - individual FieldImpact on GraphType fields

### ISSUE THREAD

**Issue by kantora** [graphql-dotnet/graphql-dotnet#298]
Is is possible to set up individual FieldImpact on GraphType fields, so analysis will be more adequate? (as different field requests bring completely different load impact).

And am I right as it seems to me that now request complexity can be counted as `number of request graph nodes` * `field impact`, so defining both parameters is redundant (as you can just set FieldImpact as 1.0 and define maximum nodes number)?

**Comment by joemcbride** [comment]
I'm honestly not sure, I haven't looked at that feature too in depth yet.  @dNetGuru ?

**Comment by kantora** [comment]
As far as I see from the code, `ComplexityAnalyzer` recursively goes through the graph tree and have access to these fields. So adding FieldImpact to every field should not generate any additional load impact.
It can be `double?`, so for undefined case avgImpact can be used to maintain backward compatibility.

**Comment by kantora** [comment]
But this will give very flexible analysis. As requesting pre-initialized scalar field costs almost nothing. Requesting something that leads to select from db with a large amount of data is complex. This select but with the use of some string filters is very complex. You just can't take an average for such complexity. They are too different.

**Comment by dNetGuru** [comment]
@kantora The ```ComplexityAnalyzer```'s routine was written with two requirements in mind! To be fast (aimed for sub-millisecond runtime) and for the heuristic algorithm to make the least number of assumptions about the backend. The problem is that we need to have an approximation of how complex a given query is WITHOUT doing anything that can lock/take resources which would leave to a DoS vulnerability. The extreme case being writing some routine that takes as much time as it takes to actually execute the query! That would give us pretty accurate results, but would defeat the purpose!

I did experiment with various heuristics (some included a weight map passed into the function etc.) and ran a diverse sample of queries against them to find the best heuristic (that I could come up with) and the fastest one.

Now I do not claim that this is the absolute best approach, it's the one that satisfied the requirement that I had set forth. For this reason there exists a ```IComplexityAnalyzer``` interface if you need to implement your own custom made function that makes all the right assumptions about your sepecific backend and environment.

Making assumptions as to what operation takes more time or if the approximation that everything takes constant time on average would be too much of an assumption about the backend. Keep in mind we just need a good heuristic, not an accurate value. Unless if an operation takes 1000% more time than another I'd say that would be an okay estimation.

About adding a FieldImpact to every Field I would say that I would agree that it would give way for more flexible analysis without having to write your own function. It would be up to @joemcbride to decide if he'd want to do that. I would make the necessary changes to the ```ComplexityAnalyzer``` if Joe's okay with it.

**Comment by dNetGuru** [comment]
> ...complexity can be counted as number of request graph nodes * field impact, so defining both parameters is redundant

No! I guess did write some docs on this (albeit in hurry). But the complexity is defined as the Sum of (Node's Depth * Node's Impact) over all depths (or all layers of the AST).

So no, that is not redundant, since if you have one you have no idea how nested a query is!

The [docs are here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs#L133)! I'll write better docs hopefully when I have the time.

**Comment by kantora** [comment]
@dNetGuru sorry, really missed some points.
As for now looked more deeply into the code and (I hope) got more understanding.
IMHO this code from general implementation 
```
        private static double? GetImpactFromArgs(INode node)
        {
            double? newImpact = null;
            var args = node.Children.First(n => n is Arguments) as Arguments;
            if (args == null) return null;

            if (args.ValueFor("id") != null) newImpact = 1;
            else
            {
                var firstValue = args.ValueFor("first") as IntValue;
                if (firstValue != null) newImpact = firstValue.Value;
                else
                {
                    var lastValue = args.ValueFor("last") as IntValue;
                    if (lastValue != null) newImpact = lastValue.Value;
                }
            }
            return newImpact;
        }
```
looks lika a kludge to work around specific relay connections. But is made in general implementation for every field. Maybe it will be better to move this method to be a part of the Field. So field can implement it depending of it's meaning.

So Field can have virtual method GetFieldImpact() (I still don't have enough understanding of its arguments, but it should have access to the arguments AST) that will return an actual value. By default, it can return avgImpact. But it can be overridden, for example, to make relay connections estimate the number of returned edges by passed arguments.

**Comment by kantora** [comment]
Also, GetFieldImpact can be defined as a delegate to get rid of Field inheritance.

**Comment by dNetGuru** [comment]
Quoting from the docs (the link I shared):
The query depth setting is a good estimation of complexity for most use cases and it loosely translates to the number of unique queries sent to the datastore (however it does not look at how many times each query might get executed). Keep in mind that the calculation of complexity needs to be FAST otherwise it can impose a significant overhead.

One step further would be specifying MaxComplexity and FieldImpact to look at the estimated number of entities (or cells in a database) that are expected to be returned by each query. Obviously this depends on the size of your database (i.e. number of records per entity) so you will need to find the average number of records per database entity and input that into FieldImpact. For example if I have 3 tables with 100, 120 and 98 rows and I know I will be querying the first table twice as much then a good estimation for avgImpact would be 105.


You see, the ```GetImpactFromArgs``` is not a workaround or anything! Since the impact is defined as the number of entities expected to be returned on average (I explained reggae in the docs elsewhere) to was crucial to handle the case were the averages didn't apple and that's when hard limits are imposed by the query on that number of expected returned items.

Again, I'm not opposed to including the value on fields. But delegates? Well, what kind of a method signature would you suggest? Besides, a method signature you're happy with would probably leave the rest of the users unhappy. I'm open to suggestions.

**Comment by kantora** [comment]
Yeah, it is hard to discuss this abstractly. I hope that I can get enough time to work on it this weekend and propose the PR, so everything will become more obvious.

**Comment by kantora** [comment]
As it always happens - task is more complex that seems from the first sight,
Unfortunately, I must admit that this will be the breaking change as current implementation tries to estimate complexity only by query tree without using the schema (it even runs before the query validation).
As it seems to me - the process of complexity analysis very looks like the resolve process with only difference - that there is no actual resolve but calculating complexity on every hop.
I am still working on the PR and will try to show the results soon.

**Comment by joemcbride** [comment]
Just want to make a comment.  The purpose of the complexity analysis is to get an _estimate_ of complexity of the _query_.  Its not designed to use the schema at all.  It should run fast and "bail out" fast if the complexity reaches a certain threshold.  We're not going for a super accurate representation just an estimate.

**Comment by kantora** [comment]
I tried to apply it to the real schema in my project and get a huge complexity estimation for rather simple queries. And as I see - this estimation has a very little touch with reality. Some nodes are arrays - some are not, current estimation doesn't take this into an account. Also, it will be great, if fields that lead to the heavy db request will bring much more field impact then simple cached field value request. I hope, that I can introduce new complexity analyzer based on validators, so these will be just alternative way, not breaking change. Nevertheless, I believe that it is impossible to make any estimations without taking schema in account at all.

And yes - I understand that this should be fast and generate very little load.

**Comment by dNetGuru** [comment]
"Some nodes are arrays - some are not, current estimation doesn't take this into an account."

That is completely untrue! If a node had children then the node and it's children are considered in the complexity!
About the high impact nodes, sure that information can be passed through to the complexity analyzer without introducing breaking changes but can you show with example where it would introduce a meaningful load hence a vulnerability? I can fix this part with a couple of lines of code but I'd like to see if it's actually necessary!

Could you also produce a schema/query example where this would be out of touch with reality? Mind you the complexity number is not really absolute!! It's a heuristic. You'd look at your average complexity out of any given schema and then allow for that plus some leeway.

Can you produce an example where the current method fails? i.e. it doesn't do what it's supposed to which is weeding out abnormally big/heavy load inducing queries while passing through the normal traffic?

**Comment by dNetGuru** [comment]
I thought more about your comment and I guess this feature isn't really that user friendly. It is optimized several times so it's hard to see the original reasoning behind it.

I'm still very interested in seeing an example where this heuristic fails.

I'll think about what I can do about this user friendliness issue. Perhaps a more through documentation would help.

**Comment by joemcbride** [comment]
I could see wanting to be able to say "this particular field is very expensive, please weight this one more".

**Comment by dNetGuru** [comment]
I'll add that and tweak some other things to make this feature more extensible.

**Comment by dNetGuru** [comment]
@kantora take a look at #312.

I will implement the functionality to pass in a dictionary of very expensive fields to the default implementation of ComplexityAnalyzer soon (perhaps by this weekend when I find the time).

/cc @joemcbride

**Comment by kantora** [comment]
`That is completely untrue! If a node had children then the node and it's children are considered in the complexity!`

I haven't meant that node's children aren't taken into account.
In general (I'll simplify for a minute and will forget about fragments for a minute) - every request node can be some object, array or scalar. For arrays - the children complexity should be multiplied by the possible number of children. For non-arrays, we shouldn't do this and just take in account field self-complexity and a sum of the complexity of its children. Just with the use of AST tree, you can't distinguish objects from the array of objects and scalars from the array of scalars (but yes, you can distinguish scalars from objects).

As far as I understood, you are trying to guess the type of node in custom analyzer by its name and/or arguments. And I still miss the point why you don't want to use the ready schema data? And its seems to me, that in #312 you are trying to create a duplicate schema definition for ComplexityAnalyzer just to avoid the usage of the real schema definition.

**Comment by dNetGuru** [comment]
The first part makes very little sense! The children are always taken into account. We check for them in every iteration. Give me an example.

Second part: read the PR's description which says "In that example I implemented a dummy (the logic behind it is flawed for simplicity so don't use that in production)"
You can't just not read these and assume things!
You can now pass the schema or anything you'd please by extending the functionality there. I've passed a dictionary (which isn't a copy of schema, it's just a list of expensive nodes and their cost, again just meant as an example). 

Simply use that PR's pattern and you can write any validation function for the Complexity analysts while passing anything you'd want to that function! I just made out easier to extend without any breaking changes attached with a crude example attached.

**Comment by kantora** [comment]
One more question. Why is complexity analysis run before query validation in document execution conveyor? Are there any risks in validation of malicious queries or validation is considered to be the "heavy" operation?

**Comment by joemcbride** [comment]
@dNetGuru He's talking about the return type of a field.  It is reasonable to want a field that returns a list of objects to have a higher complexity for a field that just returns a scalar.

> Why is complexity analysis run before query validation in document execution conveyor? Are there any risks in validation of malicious queries or validation is considered to be the "heavy" operation?

Yes, you could send a query that bogged down the validation procedure.  You can also add your own validator which could be a database call.

The original intent of feature #185 was to match what Sangria had done, found here: http://sangria-graphql.org/learn/#query-complexity-analysis

It appears they allow you to add an optional complexity number to a Field in your Schema.  Doing something similar in our project makes sense.  Whether that is on the Field directly on the Schema, or you do some other registration with the complexity analyzer, I'm open to either.  I think that should be a built-in feature and not something that a user would have to add on their own.

**Comment by dNetGuru** [comment]
Oh, well I said in my first comment in this thread that I'd be open to that since it doesn't really break anything since it can be implicitly assumed to be set to one.

Now there is one design decision that needs to be made here and that is about passing through the list of weights.

One option would be to generate a map from the schema from field names to weights (needs changing the schema) or only passing the list of more expensive items and their weights down to the validator and implicitly assuming the rest (means faster checks but much less user friendly).

I'll measure the performance penalty of this to see which route to go and make the necessary changes hopefully by this weekend.

**Comment by kantora** [comment]
@dNetGuru according to sangria example - simple weight is not enough. Every field can have complexity delegate that accepts context?, field arguments and pre-calculated child score and returns the final complexity score for this field. This is exactly what I was trying to explain/suggest all this thread.

**Comment by dNetGuru** [comment]
I'm still against delegates and the rest. It might have made sense there but I am not sold on it making a noticeable in detecting malicious queries.

Adding a constant work multiplier for different fields yes, I'm goigoing to add that as soon as I find some free time.

Going through the context seems very wasteful! I'd look into calculating the complexity as the document is being executed and bailing if it goes over in that cad. Perhaps the current system could be the fast first pass and then a more thorough pass can be done during execution with the context in hand.

How close are you to finishing your implementation @kantora I want to take a look at it and see how your implementation holds.

**Comment by joemcbride** [comment]
@dNetGuru I don't think he's talking about the field context during the real execution of a query.  Just a new "context" class that has the information mentioned.  Kind of like how there is a `ValidationContext` when working with validation rules.

**Comment by kantora** [comment]
> I'm still against delegates and the rest. It might have made sense there but I am not sold on it making a noticeable in detecting malicious queries.

@dNetGuru Can you explain why? What are the risks? And as far as I know almost all of GraphQL implementations on other platforms use this approach.
And If you are going to add only constant weight, how do you propose to handle example from Sangria?
`complexity = Some((ctx, args, childScore) ⇒ 25.0D + args.arg[Int]("limit") * childScore)` - when complexity is dependent from field arguments?

> How close are you to finishing your implementation @kantora I want to take a look at it and see how your implementation holds.

I've made some dirty code for PoC, but I really don't like it for now and want to completely rewrite it. 
My friend is working on the extension to implement Sangria approach with use the of custom validators as an external solution (complexity delegate could be stored in the field's metadata).

I can spend this weekend on creating built-in sangria approach as an additional solution, without breaking changes (in the case of approval, the current solution could be just marked as obsolete but will still be compliant) - of course, if there is an interest in it.

**Comment by kantora** [comment]
I've made a PR. Please - look at it.

**Comment by RehanSaeed** [comment]
Not sure if this issue/PR is affected but it would be worthwhile keeping in mind that GraphQL API's like the one from GitHub are also commonly secured using time based throttling. More information: https://github.com/graphql-dotnet/graphql-dotnet/issues/764.

**Comment by sungam3r** [comment]
@kantora @joemcbride @dnetguru The initial issue of individual field impact was solved by using metainformation from the schema. There are other solutions. I agree that there is no ideal.
