### ISSUE TITLE
Subscription field builders should have 'where T : class'

### ISSUE THREAD

**Issue by sungam3r2022** [graphql-dotnet/graphql-dotnet#2995]
where T : class

_Originally posted by @sungam3r2022 in https://github.com/graphql-dotnet/graphql-dotnet/pull/2993#r819924094_

**Comment by Shane32** [comment]
Since `IObservable<T>` must be an object type (currently) or it cannot be cast to `IObservable<object>` used by the underlying execution strategy.

**Comment by Shane32** [comment]
Not practical to implement currently.  Should be implemented within #3583

Ref:
- #3583

**Comment by gao-artur** [comment]
@Shane32 can you explain where this constraint should be added? Maybe I can help with analyzer.

**Comment by Shane32** [comment]
Yes, thanks!

So I think what's going on is this:

```cs
Field<IntGraphType, int>("subscribe")
    .ResolveStream(..,) // or ResolveStreamAsync
```

In this situation, the code on FieldBuilder.cs:348 creates a `SourceStreamResolver` instance but it will throw on SourceStreamResolver.cs:19 if TReturnType (int in this case) is a value type, since `IObservable<out T>` cannot be cast to `IObservable<object?>` for value types.

This will throw on the line of code that attempted it, not during initialization.

However, the auto-registering types already handle this situation with an adapter.  See SourceStreamMethodResolver.cs:170.  It might be easier to just use the adapter (that already exists) for the field builder method thereby fixing the issue than writing an analyzer.  Could be a couple-line fix...I'll try and see.
