### ISSUE TITLE
Working with timezones by taking in ID's

### ISSUE THREAD

**Issue by prchristie** [graphql-dotnet/graphql-dotnet#3013]
## Summary
I believe I am simply having a lapse in my knowledge of how to use graphql/this library. I am fairly new and I can't imagine there isnt a solution for this, but I am really struggling. I wish to expose an API that takes in a datetime with a timezone attached to it. Some googling has led me to believe that getting a list of these availible timezones is not possible, so I wish to expose the timezone input as a string.

My current input looks like this (please tell me to reformat if its not in a standard way)

```
input: DaysBetweenInputType {
    start: TimeZonedDateTimeType {
        timeZoneId: StringGraphType
        dateTime: DateTimeGraphType
    }
}
```

The actual problem is how I get that timeZoneId, call `TimeZoneInfo.FindSystemTimeById(timeZoneId)` to validate and convert to a proper timezone object. My current method is to have a model `TimeZonedDateTime`

```
public struct TimeZonedDateTime
{
    public TimeZonedDateTime(DateTime dateTime, string timeZoneId)
    {
        DateTime = dateTime;
        TimeZoneId = timeZoneId;
    }

    public DateTime DateTime { get; }
    public TimeZoneInfo TimeZone
    {
        get
        {
            return TimeZoneInfo.FindSystemTimeZoneById(TimeZoneId);
        }
    }

    public String TimeZoneId { get; }
}
```

and a type to expose it

```
public class TimeZonedDateTimeType : InputObjectGraphType<TimeZonedDateTime>
{
    public TimeZonedDateTimeType()
    {
        Field(tz => tz.TimeZoneId);
        Field(tz => tz.DateTime);
    }
}
```

but having a TimeZoneId inside that object feels odd to me. 

I think I fundamentally, at some level misunderstand types and models but I am not sure where the misunderstanding is.

A much quicker question that I feel I should know but have somehow missed while reading the docs: Someone has called my API, I have now received a TimebetweenDateTimeType object with a nested TimeZonedDateTimeType object. How do I actually convert these into my model types so that I can call my query handlers

### Environment (if relevant)

Latest version of dotnet graphql.

**Comment by Shane32** [comment]
Typically one would use a DateTimeOffset which gets formatted in a RFC format with the time offset included.  However, I think the current version of GraphQL.NET converts the time stamp to UTC and then drops the offset.  (It might be fixed in the upcoming v5; can't remember.)  Similarly, responses would also be a DateTimeOffset value (or UTC time stored in a DateTime), and the client would convert the UTC timestamp to their own time zone.  Nevertheless, this still doesn't tell you exactly what time zone the client is in.

If you need to store a time zone alongside a timestamp, creating a class like you demonstrated above is a viable option.  But you must be aware that the list of time zone identifiers used by `FindSystemTimeZoneById` is different on Linux versus Windows, and if you are communicating to Javascript clients, I'm not sure which time zone identifiers they use.  If I had such a need, I would likely store a list of time zones in a database on the server, and then allow clients to select from the predetermined list in their user preferences page, or something like that.

**Comment by sungam3r** [comment]
Closed as answered and due to inactivity.
