### ISSUE TITLE
Working with collections of IDataLoaderResult

### ISSUE THREAD

**Issue by maximiliancsuk** [graphql-dotnet/graphql-dotnet#3019]
In my project, I'm using dataloader quite extensively at this point. In most of the usecases I come across so far, I've been able to compose the dataloader calls quite well using `.Then()`. But now I have a case that I don't know how to handle properly.
Essentially, I currently have the following code inside of a GraphQL resolver (hope its readable, it's written from scratch to have a simple example):
```
var r = new List<IDataLoaderResult<ResultingItem?>>();
foreach (var item in listOfItemsIGetFromSomewhere)
{
    IDataLoaderResult<IEnumerable<ResultingItem>> tmp = SomeFunctionThatUsesADataLoaderAndReturnsAnIDataLoaderResult(item);
    var resultingItem = tmp.Then(j=> j.FirstOrDefault()); // calls to FirstOrDefault() sometimes return null
    r.Add(resultingItem);
}
return r;
```
The code above "works" in the sense that it uses the DataLoader properly and hits the underlying database only once. The issue however: the resultingItem list that gets returned contains items that are `null` and those show up in the GraphQL result too. I'd like to filter these out... but I can't wrap my head around where I can do that? I kinda need to inject code AFTER the dataloader has done its thing and I have the raw `IEnumerable<ResultingItem?>>` that I would then filter for `null` items.

I think I _could_ do it by calling `GetResultAsync()` on the `IDataLoaderResult` items manually... but afaict that would defeat the whole purpose of the dataloader, right?

I've tried to shuffle around the code in other ways too, but I just can't seem to get there :(

Any tips?

**Comment by maximiliancsuk** [comment]
Yes, that's exactly my usecase!

In general, it feels like I need a mechanism to transform an `IEnumerable<IDataloaderResult<Item?>>` into an `IDataLoaderResult<IEnumerable<Item?>>` that I could then work with using `.Then()`

**Comment by Shane32** [comment]
Well, I wrote most of the underlying code for the dataloaders as they exist now, so I'll do my best to answer, but I may or may not be able to help!

**Comment by Shane32** [comment]
I think you want to:
1. Start with `IEnumerable<IDataLoaderResult<PARENT?>>` called LIST1.  The act of creating the multiple `IDataLoaderResult`s queues up jobs to be executed against the database
2. Wrap it into a SimpleDataLoader (pardon me if I forget the naming just now) of type `IDataLoaderResult<IEnumerable<CHILD>>`, with a delegate that performs the following inside the delegate:
  1. Take the list LIST1 and enumerate it, calling GetResultAsync on each one.  Since this delegate only gets executed after all other nodes in the query have been executed, this will group with any other similar calls.
  2. Call FirstOrDefault to filter down to the single item; add to a list LIST2
  3. Return LIST2 filtered without nulls.

So like this maybe:

```cs
IEnumerable<IDataLoaderResult<Parent>> parents;  // set parents here
return new SimpleDataLoader<IEnumerable<Child>>(token =>
    {
        return parents.Select(x => x.GetResultAsync(token).FirstOrDefault()).Where(x => x != null);
    });
```

**Comment by Shane32** [comment]
Doesn't quite work because of await.....

**Comment by Shane32** [comment]
```cs
IEnumerable<IDataLoaderResult<Parent>> parents;  // set parents here
return new SimpleDataLoader<IEnumerable<Child>>(token =>
    {
        var tasks = parents.Select(x => x.GetResultAsync(token));
        await Task.WhenAll(tasks);
        var list = new List<Child>(tasks.Count());
        foreach (var task in tasks)
        {
            var childList = await task;
            var child = childList.FirstOrDefault();
            if (child != null)
                list.Add(child);
        }
        return list;
    });
```

**Comment by Shane32** [comment]
Even though you're calling `GetResultAsync` manually, you're doing so at the proper time, as follows:
1. The list of `IDataLoaderResult`s for the parents get created
2. Execution is delayed until all GraphQL nodes execute that is possible, repeating step 1 above
3. `GetResultAsync` for each parent is called, which only ONCE executes a batch query against the database
4. Results are processed
5. Steps 3 and 4 are repeated, except that no more calls to the database occur, since it already happened on the first execution of step 3

**Comment by Shane32** [comment]
Now if you need to use `.Then` to create the original list of parents, all this code goes inside the `.Then`, not outside of it, I believe.  If you have additional questions I can perhaps help further.

**Comment by Shane32** [comment]
If we take a look at the source code for `.Then` here:
```cs
        public static IDataLoaderResult<TResult> Then<T, TResult>(this IDataLoaderResult<T> parent, Func<T, CancellationToken, Task<TResult>> chainedDelegate)
        {
            return new SimpleDataLoader<TResult>(async (cancellationToken) =>
            {
                var result = await parent.GetResultAsync(cancellationToken).ConfigureAwait(false);
                return await chainedDelegate(result, cancellationToken).ConfigureAwait(false);
            });
        }
```
Then it is obvious that what we need here is a `.ThenEnumerable` like this:
```cs
        public static IDataLoaderResult<TResult> ThenEnumerable<T, TResult>(this IEnumerable<IDataLoaderResult<T>> parent, Func<IEnumerable<T>, CancellationToken, Task<TResult>> chainedDelegate)
        {
            return new SimpleDataLoader<TResult>(async (cancellationToken) =>
            {
                var list = new List<T>();
                foreach (var row in parent)
                {
                    list.Add(await row.GetResultAsync(cancellationToken).ConfigureAwait(false));
                }
                return await chainedDelegate(list, cancellationToken).ConfigureAwait(false);
            });
        }
```
And then you could probably use code like this:
```cs
IEnumerable<IDataLoaderResult<Parent>> parents;  // set parents here
return parents.ThenEnumerable(async list => list.Select(x => x.FirstOrDefault()).Where(x => x != null));
```

**Comment by Shane32** [comment]
Yup I think we are both thinking the same thing.

**Comment by sungam3r** [comment]
@maximiliancsuk Regarding your question about sponsoring. This really applies to that project. @joemcbride (owner of this repo) set up integration with opencollective very long time ago. Now two people (@Shane32 and I) are engaged in support for the project on an ongoing basis. This is not the main source of our earnings. We do what we can and when we can. Of course, we are inspired by the sponsorship of the same simple developers as we but I would not say that this in any way affects our priorities and the direction of work. I mean, regardless of the level of sponsoring, we still continue to do what we do.

**Comment by Shane32** [comment]
@maximiliancsuk  to echo @sungam3r :   Sponsoring the project is much appreciated and encourages continued development and support of the project - thanks for asking! 😄  

(I wrote an answer this morning also but forgot to hit send -- oops! lol)

Just FYI, I've written a PR #3021 so that you can use `Then` in the future.  For now it seems you have a working solution, so I won't rush a new release, but it will be in the next release.

**Comment by Shane32** [comment]
I must say, it is pleasant to hear that someone is making good use of the new data loaders.  Prior to the 3.0 release, it would have likely been impossible to provide a satisfactory answer to this type of issue, as the whole concept of `.Then` didn't typically work correctly with the 2.4 release, and instead often caused a deadlock.
