### ISSUE TITLE
v5 Migration problem

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3046]
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Abstract type Character must resolve to an Object type at runtime for field Query.hero with value 'System.Threading.Tasks.Task`1[GraphQL.StarWars.Types.Droid]', received 'null'.
  Source=GraphQL
  StackTrace:
   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in C:\_GITHUB_\graphql-dotnet\src\GraphQL\Execution\ExecutionStrategy.cs:line 620

```

My test contains
> Field<CharacterInterface>("hero", resolve: context => data.GetDroidByIdAsync("3"));

That should be changed in v5 to
> FieldAsync<CharacterInterface>("hero", resolve: async context => await data.GetDroidByIdAsync("3"));

"Bug" can be reproduced easily by changing `StarWarsQuery.cs` line 12.

It was not obvious to me. Code compiles well but throws in runtime. Will we do something to deal with it? Add some kind of check / friendly error message?

**Comment by Shane32** [comment]
Right; "FieldAsync" MUST be used for async resolvers in v5.

It is well documented here, with almost the exact samples you provided above:

https://graphql-dotnet.github.io/docs/migrations/migration5/#32-valuetask-execution-pipeline-support-changes

I would not change anything.  Adding runtime checks to see if an object is a `Task` would only slow execution speed.

**Comment by Shane32** [comment]
In my mind this is like calling an async method without await.  Sure it compiles fine, but it doesn't execute the way you intended.  That's not the fault of the programming language.  You must use await ... if you want it to be awaited anyway.

**Comment by sungam3r** [comment]
> It is well documented here...

I remember, yes.

> Adding runtime checks to see if an object is a Task would only slow execution speed.

😄 Slow by 0.00001% ? I do not believe that this is such a problem. But what I am almost 100% sure - we will be thrown by a number of bug reports about such "weird" errors. We will have to answer each time the same thing and most likely pin this issue on the main page 🤔 .

**Comment by bp74** [comment]
I run into the same issue, and this makes a migration from 4.x to 5.x very dangerous. The code compiles just fine, and if you miss one field you will only notice at runtime.

**Comment by sungam3r** [comment]
@Shane32 The first feedback after a month. I do not presume to say whether it is good or bad 😄 .

**Comment by Shane32** [comment]
I wouldn’t be opposed to a global switch to detect incorrect behavior that can be disabled. Perhaps enabled for v5 and removed for v6.

**Comment by Shane32** [comment]
If the delegate returns a task in a detectable manner, such as when using FieldDelegate, there is code in place to properly handle Tasks, ValueTasks, data loaders and so on. The problem is that Field accepts a delegate that returns object. So there is no way to recognize that a task will be returned at runtime. We also cannot add an effective overload due to Task not being covariant. Meaning if we added an overload for `Task<object>`, it would not be used unless you specifically were returning exactly `Task<object>`. So there’s no good way to detect usage until runtime.

**Comment by Shane32** [comment]
Perhaps it is possible to detect scenarios where the delegate is passed in and coerced.  I will check on that.

**Comment by Shane32** [comment]
So it is possible to detect this scenario by examining the passed in delegate's return type:

```cs
Field<CharacterInterface>("hero", resolve: GetDroidByIdAsync);

Task<Droid> GetDroidByIdAsync(IResolveFieldContext<object> context)
    => _data.GetDroidByIdAsync("3");
```

But not this one, since C# will build the delegate with a return type of `object`:

```cs
Field<CharacterInterface>("hero", resolve: context => data.GetDroidByIdAsync("3"));
```

We could also add an overload and use generics to make this scenario detectable:

```cs
Field(typeof(CharacterInterface), "hero", resolve: context => data.GetDroidByIdAsync("3"));
```

But in the latter case, I don't think that overload is typically used, and adding yet another overload would be questionable.

**Comment by bp74** [comment]
The first scenario is exactly the one we are using all the time. So for us this would help a lot :)

**Comment by sungam3r** [comment]
I would say that #3237 should help to solve mentioned problem.

**Comment by sungam3r** [comment]
@Shane32 Close?

**Comment by Shane32** [comment]
Yes

**Comment by sungam3r** [comment]
@bp74 Take a look at the upcoming during few hours v7.
