### ISSUE TITLE
allow case-insensitive parsing of enumeration values

### ISSUE THREAD

**Issue by gha-zund** [graphql-dotnet/graphql-dotnet#3105]
## Summary

When using enumeration values in mutation arguments, I want to have an option to configure, if the value is parsed case-sensitive or case-insensitive.
(I prefer case-insensitive).

This behavior seems to have changed with v5. 
After upgrading to 5.1.1 (from 4.7.1), my integration tests failed because of that.

### Basic example

Given this enum for example:
`public enum LengthSystem
{
    Metric = 0,
    Imperial = 1,
}`

I want to change that enum value via a mutation, by passing the new value as a variable in the request.
I want to make it work, even if the value is written "imperial" or "Imperial".

At the moment (v5.1.1), the mutation only works if the value is exactly "IMPERIAL".

### Motivation

To prevent typos or hard-to-find bugs. Just want to make things more robust for the caller of my GraphQL API.

**Comment by Shane32** [comment]
You are correct; the design was changed to match the GraphQL specification, which says that names are case sensitive.  See links below:

https://graphql-dotnet.github.io/docs/migrations/migration5#26-code-classlanguage-textenumerationgraphtypecode-parses-exact-names

https://spec.graphql.org/June2018/#sec-Names

I'm not sure that we will want to change the default behavior, since the current behavior matches the official specification.  However, you may create a derived class from `EnumerationGraphType<T>` to allow case-insensitive matching.

I didn't test it, but probably something like this:

```cs
public class CaseInsensitiveEnumerationGraphType<T> : EnumerationGraphType<T>
{
    /// <inheritdoc/>
    public override object? ParseLiteral(GraphQLValue value) => value switch
    {
        GraphQLEnumValue enumValue => Values.FindByName(ChangeEnumCase(enumValue.Name))?.Value ?? ThrowLiteralConversionError(value),
        GraphQLNullValue _ => null,
        _ => ThrowLiteralConversionError(value)
    };

    /// <inheritdoc/>
    public override bool CanParseLiteral(GraphQLValue value) => value switch
    {
        GraphQLEnumValue enumValue => Values.FindByName(ChangeEnumCase(enumValue.Name)) != null,
        GraphQLNullValue _ => true,
        _ => false
    };

    /// <inheritdoc/>
    public override object? ParseValue(object? value) => value switch
    {
        TEnum _ => Values.FindByValue(value)?.Value ?? ThrowValueConversionError(value), // no boxing
        string s => Values.FindByName(ChangeEnumCase(s))?.Value ?? ThrowValueConversionError(value),
        null => null,
        _ => ThrowValueConversionError(value)
    };

    /// <inheritdoc/>
    public override bool CanParseValue(object? value) => value switch
    {
        TEnum _ => Enum.IsDefined(typeof(TEnum), value), // no boxing
        string s => Values.FindByName(ChangeEnumCase(s)) != null,
        null => true,
        _ => false
    };
}
```

The above sample isn't actually case insensitive, rather it is converting to constant-case, so "TesTing" would get converted to "TES_TING" and not match against "TESTING".  But you can modify the code as you see fit (e.g. use `ToUpper()` instead).

You might also need to make modifications to other parts of the codebase so that the above enumeration type is used instead of the default one.  Ideally, this would work, but I'm struggling with some code now that might indicate it is not sufficient:

```cs
services.AddTransient(typeof(EnumerationGraphType<>), typeof(CaseInsensitiveEnumerationGraphType<>));
```

**Comment by Shane32** [comment]
Note that these changes merely make enumerations case insensitive; field and type names are still case-sensitive.

**Comment by gha-zund** [comment]
Thanks for the detailed answer, and also for the the code snippet!

True, I didn't thought about "TestTing" vs "TES_TING"....
And I didn't know about what's written in the official GraphQL spec about casing.

I would give a +1 for fixing #3100, I think this would make the library even more versatile and customizable.

**Comment by PSanetra** [comment]
@Shane32 I don't think implementing a custom `EnumerationGraphType` is possible with the schema first approach, right?

As far as I see the `SchemaBuilder` instantiates those EnumerationGraphTypes directly, without resolution via DI.

**Comment by Shane32** [comment]
Sorry I'm not sure offhand. I don't use schema-first myself so my knowledge there is limited.

**Comment by PSanetra** [comment]
@Shane32 Do you think it was possible to reintroduce the pre v5 behavior via some feature flag?

We can not just introduce such a breaking change into our api.

Even our internal tests fail, because `GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer` uses [ConstantCaseEnumConverter by default](https://github.com/graphql-dotnet/graphql-client/blob/fbf37dfff2830e36a45296079bac27ec60fad550/src/GraphQL.Client.Serializer.Newtonsoft/NewtonsoftJsonSerializer.cs#L15). :frowning_face:

So all our non-constant-case enums will be not usable from clients, which use the default `GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer`.

**Comment by Shane32** [comment]
Do you need another case or case insensitive ?  Did you try marking EnumCase attribute on the clr type of the problematic enums?

**Comment by Shane32** [comment]
Just FYI, I don't maintain or use the GraphQL.Client library myself.

**Comment by Shane32** [comment]
I think we would be happy to accept a PR to in some fashion allow schema-first to utilize non-constant-case enums, if there is no available method now. Maybe we need to allow the Name attribute on enum fields similar to JsonPropertyName. Maybe we need to allow the schema builder to specify a GraphQL type for enums. Maybe adding an option to the schema builder to change the default case of enums. Or some combination.

**Comment by Shane32** [comment]
Offhand I would try not to add a global switch to GlobalSwitches.

**Comment by Shane32** [comment]
EnumCaseAttribute was added in #2899 for version 5.0 I believe

**Comment by Shane32** [comment]
Case insensitive enums is problematic to support because constant case has underscores where camel case and pascal case does not. So we cannot just perform a case insensitive match on the provided string.

**Comment by Shane32** [comment]
Another option is to have the schema builder pull enum types from DI. Except, does it ever pull anything from DI? Well assuming it does, then you could register an open generic for `EnumerationGraphType<>` with your own implementation to write it as you see fit.

If we determine a solution we can probably get it in v7.8.0 assuming it's a non breaking change.

**Comment by PSanetra** [comment]
@Shane32 can you take a look at https://github.com/graphql-dotnet/graphql-dotnet/pull/3913? This way it is possible to use custom GraphTypes when using the schema-first approach and also adds a class in this library to support the use case in this issue.
