### ISSUE TITLE
AddMetrics redesign

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3112]
Every time I see these 2 methods, then I doubt whether it was worth giving the opportunity to independently set up. I understand that `AddMetrics` adds some additional info into `ExecutionResult.Perf` object and `ApolloTracingDocumentExecuter` just copy this info (modifying slightly) into `ExecutionResult.Extensions` object in "tracing" bucket. @Shane32  what do you think?

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/examples/pull/93#discussion_r863102000_

**Comment by Shane32** [comment]
In short, I'm not satisfied either.

Ideally, I think `AddMetrics()` should be enough, and perhaps one overload that is conditional upon the service provider so it can be enabled or disabled depending on a runtime condition.  This is simple enough when the runtime condition is a compilation switch, such as checking if the environment is a development or checking environment variables, but if the condition is based on the `HttpContext.User` or some runtime condition, then this requires that middleware is initialized prior to the schema being initialized -- and the middleware requires significant processing overhead to all requests even if the metrics are not returned in the response.

Within the call to AddMetrics, I would like to see it add a document listener which will append the metrics to the result.  However, we may need to add another method to the document listener.  Or accept the fact that metrics may not include the execution time taken by other document listeners, and similar situations where the document listener method will not run.

Finally, I'm not happy that the metrics information is so tightly integrated to the ResolveFieldContext class.  I would rather see that within AddMetrics, the added middleware contains a reference to an AsyncLocal which is used to pull the current metrics data instance.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/examples/pull/93#discussion_r863118634_

**Comment by Shane32** [comment]
One more note - one can use metrics internally without exposing it to a client via extensions.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/examples/pull/93#discussion_r863150866_

**Comment by Shane32** [comment]
True.  But at that point someone would be writing their own document listener or document executer to actually use the data, and if that's the case, they can write their own builder extension method to perform the necessary registrations.  Potentially we could have an overload to AddMetrics called `AddMetrics<TListener>` which would add the specified listener rather than the default one.

The builder methods are supposed to be easy-to-use helper methods to help configure the GraphQL.NET pipeline without needing to know all of the intricate details and need not cover every single configuration scenario.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/examples/pull/93#discussion_r863153610_

**Comment by sungam3r** [comment]
Rewritten to `AddApolloTracing` extension method. Ping @Shane32 to confirm and close.
