### ISSUE TITLE
Where are bidirectional references used?

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#3150]
Hi,

in my headless CMS I use graphql-dotnet. The user can create schemas with the UI or API and based on this schema definition the graphql endpoints are created. There are basically hundreds of dynamic endpoints. Of course they are cached.

To improve allocations and the general memory usage I reuse as many instances of graphql types as possible, e.g. 
https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Domain.Apps.Entities/Contents/GraphQL/Types/AllTypes.cs

and also query types and resolvers:
https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Domain.Apps.Entities/Contents/GraphQL/Types/Contents/ContentActions.cs

It made a very big difference both in performance and allocations.

BUT I think I have discovered a memory leak. When a type that is referenced by another type also adds a reference back, then this shared type would hold references and never give them free.

I think this is the case with interfaces: https://github.com/Squidex/squidex/blob/master/backend/src/Squidex.Domain.Apps.Entities/Contents/GraphQL/Types/SharedTypes.cs#L23, so I guess I have to find a solution for that.

Do you know other situations where such bidirectional references are used?

**Comment by Shane32** [comment]
In general, I can tell you that sharing GraphQL.NET graph type instances between different schema instances can lead to BIG problems, with the exception of scalar graph types.  In fact, all the built-in scalar types are already cached -- see SchemaTypes.BuiltInScalarMappings -- although not their non-null variants.

Yes, interfaces generally have bidirectional references -- see `ObjectGraphType.AddResolvedInterface` and also `InterfaceGraphType.AddPossibleType`.  I believe somewhere during initialization, these lists are modified to be sure they are the same.

But you will going to have bigger problems than that -- specifically due to initialization of a schema while another request is executing.  If the interface list within the InterfaceGraphType or ObjectGraphType is reinitializing at the exact moment that another thread is reading the list contents, you will get seeming-random concurrency exceptions.  (I can't remember where, but we have had one or more issues with that in the past.)

So you could work around that - let's say you use caching and treat each graphtype instance as a immutable object.  Let's further say that you rewrote SchemaTypes from scratch so that initialization was not performed on any graph types (because perhaps it was done once when a cache miss occurs).  Now you'll realize that if you have an `Animal` interface with `Cat` and `Dog` types, and if `Dog` changes, then it will require a new `Animal` instance, which will require a new `Cat` instance.  And now that you have new `Cat` and `Dog` instances, you probably need a new `Owner` instance because the `cats` field references the `Cat` type.  Basically, due to the nature of GraphQL, almost all graph types in your schema will eventually reference back to each other, causing a new schema to be required if any part of it changes.

Perhaps if you eliminate interfaces (not sure about unions), you might be able to work past some of these issues, but you need to be very wary of them.

If I was attempting what you are attempting, I'd probably tackle it one of two ways:

1. Detect any change to a schema, and if a change is found, reinitialize a new schema without sharing any classes (except scalars), and cache it.

The benefit here is that it is likely easy to implement, and works well with a limited amount of schema changes.  The drawback is cache misses are expensive, and if there are a lot of different schemas, you may have a lot of cache misses.

2. Implement a single, entirely dynamic schema.
- Create a immutable model class that stores the information necessary to build the GraphQL.NET schema.  Implement caching as desired within this class
- Create custom implementations of each GraphQL.NET class (e.g. custom `ObjectGraphType`) that implement the interfaces directly, not a derived instance.
- Have each implemented property, such as `ResolvedType`, dynamically pull from the model for the request, probably via accessing an AsyncLocal instance (just like `IHttpContextAccessor` does).
- Create a custom SchemaTypes implementation which does not initialize any types (since it is all dynamic).

The benefit here is that you can tailor the model to extensively use caching and/or dynamic lookups, such there is very little memory requirements per active schema.  It will also process small queries very quickly.  The drawback is that it is complicated to implement, and large requests will perform a little slower as they are essentially interpreted queries.

It still will be required for the model to remain static during the processing of a single request.  There would be multiple ways to handle this.  If lookups were _entirely_ dynamic, it could be pulled from a database transaction with snapshot isolation.  If the model is downloaded, you could make the model immutable, or implement a synchronization primitive to lock out active requests while the model is being updated.

I had a goal once of attempting to make all of the GraphQL.NET interfaces represent immutable graph types.  If that had been accomplished, it would be much easier to implement the above.  However, this proved to be more difficult than anticipated, due to the initialization code doing stuff like changing capitalization on fields and setting resolved implementations within the graph types.  However, if the initialization code were removed (by rewriting `SchemaTypes`), I think it could probably be implemented as-is with `throw NotImplementedException()` for each property setter.

**Comment by SebastianStehle** [comment]
Thanks a lot for your super fast and super detailed answer.

Fortunately I have never seen concurrency issues and so far the only possible leak seems to be my shared interface type. Besides that I do only share scalars, resolvers and query arguments and a few object types that never reference to other object types. I had a look to the gcdumps and I do not see other types that are growing

When a tenant has made a changed one of the squidex schemas I recreate the whole graphql schema for this tenant, because the types are so connected to each other.

**Comment by Shane32** [comment]
No problem sharing scalars and resolvers.  I generally wouldn't share query arguments unless they were only pointing to scalars, but it's possible that it's fine if the entire descendant tree of referenced types are always static instances.  They will still get reinitialized upon a schema reload, but it's probably okay.  Similarly with object types, if they only reference scalars and no interfaces, you can probably share them.  (not 100% positive, but probably)  And maybe if they only reference other static instance.

**Comment by sungam3r** [comment]
I will add a note that in the general case it is an unsolvable task. We can some extent contribute to the possibility of re-use of objects in different schemas, but we cannot guarantee that everything will work together. As @Shane32 noted, this will inevitably lead to concurrency issues and to the fact that we will be forced to write multithread-aware code in more places. This will greatly complicate the design. Also see discussion in #2830 .

**Comment by Shane32** [comment]
Closing as answered
