### ISSUE TITLE
.AddGraphQL() documentation isn't clear, and example from harness suggests a missing class, GraphQLSettings, which should be provided.

### ISSUE THREAD

**Issue by Xeviva** [graphql-dotnet/graphql-dotnet#3160]
I've been trying to update GraphQL from 4.6.1 to 5.3.0. So many breaking changes. However, it is the changes to set up GQL in startup.cs that concerns me. I have personally found the documentation to be very unclear, so have been picking apart the code base to try and figure out how to do this in V5.3.0.
Having found: 
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Harness/Startup.cs 
There is sample code to set up Graph QL, however this heavily relies on GraphQLSettings which isn't included in the nuget packages

### Steps to reproduce
I am currently using

```
<PackageReference Include="GraphQL" Version="5.3.0" />
<PackageReference Include="GraphQL.Server.All" Version="6.1.0" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="6.1.0" />
<PackageReference Include="GraphQL.SystemTextJson" Version="5.3.0" />
```

and code from above link, with the only change being swapping in my schema.

```cs
services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddErrorInfoProvider((opts, serviceProvider) =>
                {
                    var settings = serviceProvider.GetRequiredService<IOptions<GraphQLSettings>>();
                    opts.ExposeExceptionStackTrace = settings.Value.ExposeExceptions;
                })
                .AddSchema<StarWarsSchema>()
                .AddGraphTypes(typeof(StarWarsQuery).Assembly)
                .AddMiddleware<CountFieldMiddleware>(false) // do not auto-install middleware
                .AddMiddleware<InstrumentFieldsMiddleware>(false) // do not auto-install middleware
                .ConfigureSchema((schema, serviceProvider) =>
                {
                    // install middleware only when the custom EnableMetrics option is set
                    var settings = serviceProvider.GetRequiredService<IOptions<GraphQLSettings>>();
                    if (settings.Value.EnableMetrics)
                    {
                        var middlewares = serviceProvider.GetRequiredService<IEnumerable<IFieldMiddleware>>();
                        foreach (var middleware in middlewares)
                            schema.FieldMiddleware.Use(middleware);
                    }
                }));

            // add something like repository
            services.AddSingleton<StarWarsData>();
```
            
GraphQLSettings is not found in the packages, so this won't actually run for me.

### Expected result

Following the example code provided in the docs and /or project should work out of the box

### Actual result

Error: CS0246	The type or namespace name 'GraphQLSettings' could not be found (are you missing a using directive or an assembly reference?)

I think that GraphQLSettings should be included in the graphQL package if it is required inorder to configure GQL, or at the very least, the documentation has to make super clear how you need to configure this properly.

**Comment by Shane32** [comment]
`GraphQLSettings` is provided as an example of a settings class pulled from appsettings.json or environment variables to configure GraphQL.  It is not necessary; you can use your own class or eliminate it entirely.  I do not use it in any of my projects. 
 For example, if you do not use Apollo Metrics, and don't want/need exception stack traces exposed, you can just write this:

```cs
services.AddGraphQL(builder => builder
    .AddSystemTextJson()
    .AddSchema<StarWarsSchema>()
    .AddGraphTypes(typeof(StarWarsQuery).Assembly));
```

There is no need for the `AddMiddleware<>` code, the `AddErrorInfoProvider` code, or `ConfigureSchema`.

If you want metrics, you can just call `.AddApolloTracing()`.  If you want the stack trace revealed in development, you can write something like `.AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = Environment.IsDevelopment())`.

You will also need to follow the instructions for the server project if you intend to use it.  For instance:

```cs
services.AddGraphQL(builder => builder
    .AddSystemTextJson()
    .AddSchema<StarWarsSchema>()
    .AddGraphTypes(typeof(StarWarsQuery).Assembly)
    .AddHttpMiddleware<ChatSchema>()); // <---- add this

// in app setup
app.UseGraphQL<StarWarsSchema>();
```

Documentation is even poorer in the server project than it is for GraphQL.NET, but there is a sample.  See https://github.com/graphql-dotnet/server/blob/master/samples/Samples.Server/Startup.cs  One of the biggest difficulties is that the GraphQL.NET documentation attempts to explain how to set up GraphQL.NET apart from any server implementation, and the server project(s) attempt to explain configuration of the server project abstract from real implementations.

As for the server project, I have rewritten it from scratch including all-new documentation -- see https://github.com/Shane32/GraphQL.AspNetCore3 .  All the code in that project is slated to be integrated into GraphQL.NET Server 7.0.0 - but will likely not be ready for another month yet.  The new documentation there that you find has several examples with a working GraphQL.NET "chat service" schema used for all of them, but again the documentation focuses on the server side of things and not how to configure the schema.  You will find that I have attempted to make the Startup.cs / Program.cs file as minimal as possible in each sample so that it is easy to tell what is required for a working project.

**Comment by Xeviva** [comment]
yeah...documentation still has always left a lot to de desired in these projects.

**Comment by alexsamson1988** [comment]
In which package is the UseGraphQl extension for the app ? I've spent an insane amount of time to figure out how to make this work I think that once I get it working I will suggest a change to the doccumentation.

**Comment by Shane32** [comment]
Oh sorry, it's in GraphQL.MicrosoftDI

**Comment by Shane32** [comment]
The documentation for all the builder methods is here:

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#dependency-injection-registration-helpers

Please do suggest any improvements to the documentation.

**Comment by Shane32** [comment]
Buried in the documentation there we do state the Nuget package that needs to be referenced, but please feel free to suggest changes to the documentation.  I'm sure it could be better.

![image](https://user-images.githubusercontent.com/6377684/173146379-0633cbfb-6ae6-492e-b2b9-5c0f5becaf92.png)

**Comment by alexsamson1988** [comment]
The addgraphql is fine for me. What I would like to know is the UseGraphQl extension ? How do I setup this part of the APP ? In the example there is a middleware that seems to handle the graphql request but I guess that there is a way to do it without goind with a custom middleware ?

**Comment by Shane32** [comment]
I wrote all new documentation for v7 of the server project, with many new sample projects.  Please see https://github.com/Shane32/GraphQL.AspNetCore3 .  Once we finish copying the functionality over and release v7, I anticipate copying much or all of that documentation over.

**Comment by Shane32** [comment]
If you want to use the new functionality now, you can use the GraphQL.AspNetCore3 nuget package v3.0.0.  The UseGraphQL method is in there.  Or if you are using GraphQL Server v6, then the method is in GraphQL.Server.Transports.AspNetCore

**Comment by Shane32** [comment]
GraphQL.AspNetCore3 will likely be abandoned if/when all its functionality is copied into the server project.

**Comment by Shane32** [comment]
@Xeviva @alexsamson1988 Any other questions here?

**Comment by Xeviva** [comment]
Unfortunately, I'm going to port our apps over to using Hot Chocolate instead of graphQL.net. we're loosing too much time trying to piece together how to get this working from the docs and having to delve into the code to figure it out all the time, so I don't have any more questions for you.

The docs you linked are better, but the real issue you need to fix with this repo is that almost every release you are making some amount of breaking changes, and the documentation has so far never been entirely clear what the upgrade path is. If you're going to keep breaking things, you need to be clearer, e.g. you did this before <insert code example>, you need to do this now <insert code example>, with all the packages involved made clear, since you seem to move functionality between packages too.
