### ISSUE TITLE
Deeply Nested Fragments Fail Based Upon Order of Fragments In Query

### ISSUE THREAD

**Issue by CaptainEsoteric** [graphql-dotnet/graphql-dotnet#3191]
## Description

Using GraphQL DotNet 5.0+ (tried with 5.1 and 5.3), a query like the below fails (simplified example from a more complex project):

```query fragmentTesting
{
  car(id: 1)
  {
    ...lastUpdated
    ...optionsOnCar
  }
}

fragment optionsOnCar on Car
{
  options
  {
    edges
    {
      node
      {
        ...optionDetail
      }
    }
  }
}

fragment optionPrice on Option
{
  price
}

fragment lastUpdated on Car
{
  updatedAt
}

fragment optionDetail on Option
{
  name
  ...optionPrice
  optionContents(first: 9999999)
  {
    edges
    {
      node
      {
        optionContent
        {
          name
        }
      }
    }
  }
}
```

With an error that begins with, 

> "System.Collections.Generic.KeyNotFoundException: The given key 'optionDetail' was not present in the dictionary.\r\n   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at GraphQL.Validation.Complexity.ComplexityVisitor.VisitFragmentSpreadAsync(GraphQLFragmentSpread fragmentSpread, AnalysisContext context) in /_/src/GraphQL/Validation/Complexity/ComplexityVisitor.cs:line 79"

The full error goes on a while, but it appears related to  #3030 Nested Fragments.

However, when we re-arrange the fragments to move the lastUpdated fragment to the beginning or the end of the set of fragments, the query succeeds as expected. If we try a query that looks like this:

```query fragmentTesting
{
  car(id: 1)
  {
    ...lastUpdated
    ...optionsOnCar
  }
}

fragment optionsOnCar on Car
{
  options
  {
    edges
    {
      node
      {
        ...optionDetail
      }
    }
  }
}

fragment optionPrice on Option
{
  price
}

fragment optionDetail on Option
{
  name
  ...optionPrice
  optionContents(first: 9999999)
  {
    edges
    {
      node
      {
        optionContent
        {
          name
        }
      }
    }
  }
}

fragment lastUpdated on Car
{
  updatedAt
}
```

Where the nested fragments are in an unordered, but unbroken group, the query succeeds every time.

### Steps to reproduce
Unfortunately, I do not yet have reliable steps to reproduce from a simple example yet.

### Expected result

I would expect fragment order in the query to be irrelevant. A query would always parse and execute -- throwing errors only from the library consumer's code -- or always return an error from the GraphQL Dotnet subsystems because the query was not well-formed.

### Actual result

Fragment order seems to matter, which is unexpected. It is also a departure from previous GraphQL Dotnet versions from 2 to 4, as this error only appeared in queries as we upgrade from 4 to 5.

### Environment

OS: Windows 10
GraphQL DotNet Version: 5.1 and 5.3
Dotnet Core version: 6.0.3

**Comment by sungam3r** [comment]
Reproduced. I'll try to fix it.

**Comment by Shane32** [comment]
Most likely the cause is because right now we have a custom comparer to compare to see if one fragment should be sorted prior to the other.  I would guess that the comparer might know A compared to B, if A or B is a fragment of the other -- but not A vs B when A requires C and C requires B.  So A and B will be considered equal, and may not be sorted properly.  Then when C is sorted in, it doesn't resort A and B with the additional knowledge that A is prior to C which is prior to B.

FYI @sungam3r , my revised authorization rule is designed to work in a single pass, and does not require sorting of the document's fragments to work properly (at the cost of some complexity in the design).  So it should be immune to this bug. 
 It works this way: types containing fragment spreads are queued until the fragment has been analyzed, at which time authentication is processed.  If a fragment is present prior to the fragment spread, the fragment results are queued so that authentication can occur when the fragment spread is encountered.  This can occur with nested fragments as well, where a fragment spread pointing to an unprocessed fragment is queued until the fragment is encountered, and then the other fragment has its results queued for use in other fragment spreads.  We could apply the same logic to the complexity validation rule if/when we want to rewrite it into a single-pass operation.
