### ISSUE TITLE
Write release notes at https://opencollective.com/graphql-net for v7

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3238]

**Comment by Shane32** [comment]
I'll do this as well; probably tonight, otherwise tomorrow morning.  I unexpectedly spent an inordinate amount of time bumping the server project to 7.0.0 this evening.  Also spent a lot of time writing the release notes for both projects.  The release notes on opencollective should cover both projects.

**Comment by sungam3r** [comment]
Thanks.
