### ISSUE TITLE
Azure memory consumption with graphql

### ISSUE THREAD

**Issue by NicolaiJee** [graphql-dotnet/graphql-dotnet#3296]
Hi
Since i upgraded my graphql application from 4 to 7, we have had a big problem with the memory consumption.
I have made a test that only uses graphql calls, to eliminate any other possible reasons.
I am using .net 6 and all components are upgraded to the latest version from NuGet.
My registration of graphql looks like this:
```
services.AddTransient<ISchema, DefaultSchema>(services => new DefaultSchema(new SelfActivatingServiceProvider(services)));
services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddSchema<DefaultSchema>()
                .AddErrorInfoProvider((opts, serviceProvider) =>
                {
                })
                .AddGraphTypes(typeof(DefaultQuery).Assembly));

            app
     .UseGraphQL<DefaultSchema>();
            app.UseGraphQLPlayground();

```

My schema looks like this:
```
 public class DefaultSchema : Schema
    {
        public DefaultSchema(IServiceProvider resolver)
        : base(resolver)
        {

            RegisterType(new MyBooleanGraphType());
            RegisterType(new MyDecimalGraphType());
            RegisterType(new MyDateGraphType());
            RegisterType(new MyDateTimeGraphType());
            RegisterType(new MyFloatGraphType());
            RegisterType(new MyIntGraphType());
            Query = resolver.GetRequiredService(typeof(DefaultQuery))as DefaultQuery;
            Mutation = resolver.GetRequiredService(typeof(DefaultMutation)) as DefaultMutation;

           // RegisterValueConverter(new FormFileConverter());
        }
    }
```
I have made a simple stress test that just calls one function and the memory just goes up and goes and never goes down.
It will continue up until the azure web app restarts.
Is there something I can try or is it a bug in Graphql, because we didn't have this problem with version 2-4.
It started in version 5.

**Comment by NicolaiJee** [comment]
My function registration looks like this:
```
defaultQuery.FieldAsync<ListGraphType<AssignmentSearchItemType>>(
       this.GetType().Name.Replace("Query", "_") + "search",
       arguments: new QueryArguments(new List<QueryArgument>
            {
                    new QueryArgument<NonNullGraphType<AssignmentSearchDTOType>>
                    {
                        Name = "searchCriteria"
                    }
                    
            }),

            resolve: async context =>
       {
           var assignmentSearch = context.GetArgument<AssignmentSearchDTO>("searchCriteria");
           
           /**/
           IEnumerable<AssignmentSearchItem> data;
           data = await
           serviceProvider.GetRequiredService<IAssignmentService>().Search(assignmentSearch); ;

           return data.ToList();
       }
    ) ;
```

**Comment by Shane32** [comment]
Can you show the code where you execute queries?  Is this hosted by ASP.NET Core?

**Comment by Shane32** [comment]
Actually, you're using GraphQL.NET Server 7 -- `GraphQL.Server.Transports.AspNetCore` -- correct?  I see the call to `app.UseGraphQL();`.

**Comment by NicolaiJee** [comment]
My code that executes the queries looks like this
```
var graphQLClient = new GraphQLHttpClient("https://xxxx/graphql", new NewtonsoftJsonSerializer());
graphQLClient.HttpClient.DefaultRequestHeaders.Add("authorization", "Bearer sometoken");
var request = new GraphQLRequest
{
    Query = @"
    query{ 
  assignment_search(searchCriteria:{campaignTypeId:5,weekNumber:""33-2022"",limit:50})
    {
        assignmentId    numberOfRows    weekNumber    date    startTimeClock    endTimeClock    hasFiles    customerCardId    km    salaryType    customerId    customerName    customerNote    customerEmployeeName    customerPriceWithKm    campaignId    campaignName    chainId    chainName    storeId    storeName    streetInfoFormatted    city    zipCode    employeeId    employeeName    employeeNote    employeeTotalHours    actualEmployeeTotalHours    salesConsultantId    salesConsultantName    createdByRole    evaluation    viewedByCustomer    accountManagers    areaManagers    assignmentStatusId    assignmentStatusName    allowReportingUntil    assignmentCompleted    actualEmployeeTotalHours    emptyHours    deleted    internalNote    internalNoteFormatted

    }


}"
};
for (int i = 0; i < 5000; i++)
{
    var graphQLResponse = await graphQLClient.SendQueryAsync<dynamic>(request);
    Console.WriteLine(graphQLResponse.Data);
}

```
These are the  components:
![image](https://user-images.githubusercontent.com/2285823/185404605-9f6ad442-f47f-43ed-8af2-7b1da0dce62f.png)

Need more info ?

**Comment by Shane32** [comment]
I guess the biggest thing I'm wondering is why the schema is registered as a transient.  Disposable services registered as transients are known to cause a memory leak if created from the root service provider.  Typically a singleton is strongly recommended but a scoped service provider is also supported.

https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposable-transient-services-captured-by-container

Also I see you were trying to use the SelfActivatingServiceProvider, but then you register the schema within the AddGraphQL call below, as well as AddGraphTypes.

You'd normally either do this:

```cs
// register all graph types, and do not use self activating schema
services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddSchema<DefaultSchema>()    // insert service lifetime in argument here
                .AddErrorInfoProvider((opts, serviceProvider) =>
                {
                })
                .AddGraphTypes(typeof(DefaultQuery).Assembly));
```

or

// use self activating schema; no need to register graph types
```cs
services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddSelfActivatingSchema<DefaultSchema>()    // insert service lifetime in argument here
                .AddErrorInfoProvider((opts, serviceProvider) =>
                {
                }));
```

However, you may use AddSelfActivatingSchema along with AddGraphTypes if you wish; it will not hurt.

With those examples, you will notice that if you attempt to use a transient lifetime for the schema, you'll get an exception, as there should be no reason for this scenario.  Either you are calling the service from the root service provider, in which case you'd have a memory leak, or you are not, in which case you can use the scoped lifetime.

With the GraphQL.NET Server v7 project, it should request the schema only from within scoped service providers.  So I do not yet understand why you have a memory leak issue even with your unsupported configuration.

You may also want to read up this article on how memory usage works in Azure:

https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-6.0

In my personal experience, it seems like .NET continually allocates memory until usage hits around 80%, at which point I start seeing the shark-tooth pattern of the GC kicking in periodically to drop consumption a bit, having it stay between 70%-80% no matter how much memory the application requires or the server has.  How many busy the server is doesn't seem to affect it much either; it always hovers at 70-80%.  See:

![image](https://user-images.githubusercontent.com/6377684/185408402-12c42ab0-50d8-4622-b215-371cbb0ec26a.png)

So just be aware that especially with a schema configured as scoped/transient, you're going to see the memory usage increase rapidly for every execution (because the schema needs to be rebuilt from scratch including all graph types) until the GC decides to kick in (which we do not have control of, apart from what is documented in the Microsoft link above).

**Comment by NicolaiJee** [comment]
The transient was just a test it was singleton.
I will try to change my set up of the schema to see if that helps.
I will report back.

**Comment by NicolaiJee** [comment]
> I guess the biggest thing I'm wondering is why the schema is registered as a transient. Disposable services registered as transients are known to cause a memory leak if created from the root service provider. Typically a singleton is strongly recommended but a scoped service provider is also supported.
> 
> https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposable-transient-services-captured-by-container
> 
> Also I see you were trying to use the SelfActivatingServiceProvider, but then you register the schema within the AddGraphQL call below, as well as AddGraphTypes.
> 
> You'd normally either do this:
> 
> ```cs
> // register all graph types, and do not use self activating schema
> services.AddGraphQL(builder => builder
>                 .AddSystemTextJson()
>                 .AddSchema<DefaultSchema>()    // insert service lifetime in argument here
>                 .AddErrorInfoProvider((opts, serviceProvider) =>
>                 {
>                 })
>                 .AddGraphTypes(typeof(DefaultQuery).Assembly));
> ```
> 
> or
> 
> ```cs
> // use self activating schema; no need to register graph types
> services.AddGraphQL(builder => builder
>                 .AddSystemTextJson()
>                 .AddSelfActivatingSchema<DefaultSchema>()    // insert service lifetime in argument here
>                 .AddErrorInfoProvider((opts, serviceProvider) =>
>                 {
>                 }));
> ```
> 
> However, you may use AddSelfActivatingSchema along with AddGraphTypes if you wish; it will not hurt.
> 
> With those examples, you will notice that if you attempt to use a transient lifetime for the schema, you'll get an exception, as there should be no reason for this scenario. Either you are calling the service from the root service provider, in which case you'd have a memory leak, or you are not, in which case you can use the scoped lifetime.
> 
> With the GraphQL.NET Server v7 project, it should request the schema only from within scoped service providers. So I do not yet understand why you have a memory leak issue even with your unsupported configuration.
> 
> You may also want to read up this article on how memory usage works in Azure:
> 
> https://docs.microsoft.com/en-us/aspnet/core/performance/memory?view=aspnetcore-6.0
> 
> In my personal experience, it seems like .NET continually allocates memory until usage hits around 80%, at which point I start seeing the shark-tooth pattern of the GC kicking in periodically to drop consumption a bit, having it stay between 70%-80% no matter how much memory the application requires or the server has. How busy the server is doesn't seem to affect it much either; it always hovers at 70-80%. See:
> 
> ![image](https://user-images.githubusercontent.com/6377684/185409848-2dabb5da-d876-4ef1-8f18-3095be987c03.png)
> 
> So just be aware that especially with a schema configured as scoped/transient, you're going to see the memory usage increase rapidly for every execution (because the schema needs to be rebuilt from scratch including all graph types) until the GC decides to kick in (which we do not have control of, apart from what is documented in the Microsoft link above).

Thank you for your help.
I changed my setup to this:

```
            services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddSchema<DefaultSchema>()
                .AddGraphTypes(typeof(DefaultQuery).Assembly));
```
And removed my manual registration of the schema and that seems to have helped a lot.
Even when I push the server much more than yesterday it does not run out of memory or anything like that.
