### ISSUE TITLE
Question : ?>? syntax 

### ISSUE THREAD

**Issue by ASaxoC** [graphql-dotnet/graphql-dotnet#3299]
I am going through the code of the library trying to understand it better.

In _ComplexGraphType_ file  on line 171 there is this function:
`public FieldType Field(Type type, string name, string? description = null, QueryArguments? arguments = null, Func<IResolveFieldContext<TSourceType>, object?>? resolve = null, string? deprecationReason = null)
        {`

I am curious to understand the syntax: **object?>?**.

My GraphQL.NET version should be 4.6.1. 

thank you in advance

**Comment by sungam3r** [comment]
It is [nullable annotations](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references).

`Func<IResolveFieldContext<TSourceType>, object?>? resolve` means that 
1) `resolve` argument **can** be `null`
2) `Func` delegate **can** return `null` as a result of resolving value

**Comment by Shane32** [comment]
No, it's `object?` versus `object`.  `object?` indicates that it can be an object or null.  In this case 'it' is the return type of the delegate.

Then, you have the generic delegate type `Func<......>?` versus `Func<......>`.  Since there's a `?` on the end, it indicates that the argument can be a valid `Func<.....>` delegate reference -- or it can be null.

There's nothing special about `?>?`.  You can write: `Func<Func<Func<Func<string?>?>?>?>?` or `Func<Func<Func<Func<string>>>>` or `Func<Func<Func<Func<string>>>>?` or `Func<Func<Func<Func<string>>?>>`.  But each carries a different meaning.

Going back to the prior sample, because of the NRT annotations, we can do this:

```cs
// assuming this:
void Test(Func<IResolveFieldContext<TSourceType>, object?>? arg) { }

// this is valid:
Test(null); // because of second question-mark
Test(context => null); // because of the first question-mark

// whereas if we defined it this way
void Test2(Func<IResolveFieldContext<TSourceType>, object>? arg) { }

// then:
Test2(null); // valid
Test2(context => null); // invalid because the delegate must return an object and not null

// and finally if we defined it this way
void Test3(Func<IResolveFieldContext<TSourceType>, object?> arg) { }

// then:
Test3(null); // invalid because arg must be non-null
Test3(context => null); // valid
```

**Comment by Shane32** [comment]
You can also define `Func<string?, object>?`.  This would mean that the delegate parameter might be null, but the delegate must return a value.  However the method could be passed null instead of a delegate.

```cs
void Test4(Func<string?, object>?) { }

Test4(null); // valid because the arg may be null
Test4(arg => {
    // arg could be null here because it's 'string?'
    // must return a non-null object because it's 'object'
    return "hello";
});
```

**Comment by ASaxoC** [comment]
I wad confused by the nested <>.  Now it makes more sense. Thank you !
