### ISSUE TITLE
How to solve runaway memory problems

### ISSUE THREAD

**Issue by NicolaiJee** [graphql-dotnet/graphql-dotnet#3305]
Hi 
I have a web app that uses GraphQL and we have had some memory problems for a while.
Today I found out that it was the Ef Datacontext that fills up the memory.

This is registered like this:

```
 services.AddDbContext<DataContext>
                (options => options.UseSqlServer(connection, x => x.UseNetTopologySuite()), ServiceLifetime.Transient, ServiceLifetime.Transient);
```

My graphql is registered like this:
```

            services.AddGraphQL(builder => builder
                .AddSystemTextJson()
                .AddSchema<DefaultSchema>()
                .AddGraphTypes(typeof(DefaultQuery).Assembly));
```

My services are registered like this:

```

            services.AddTransient<IAccountService, AccountService>();
            services.AddTransient<IAnswerService, AnswerService>();
            services.AddTransient<IAssignmentService, AssignmentService>();
            services.AddTransient<IAssignmentCategoryService, AssignmentCategoryService>();
```

I use my datacontext in services like this

```
 readonly DataContext _dataContext;
        public AnswerService(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
```

My transient datacontext helps to solve the problem of executing multiple queries at the same time.
But it causes a massive memory leak.
I have searched a lot good solutions to clean up or other ways to do this.

What is your recommended way to avoid this problem ?

**Comment by Shane32** [comment]
The root of your cause is that MS-DI never disposes of transient services created in the root service context.

See: https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposable-transient-services-captured-by-container

I suggest reading our documentation on this topic:

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#schema-service-lifetime

In general, you have a few options with the default Scoped lifetime of DbContext:  (I'm assuming you use ASP.NET Core to host your endpoint)

1. Use a scoped schema with serial execution strategy, and inject the DbContext into your graph types (not recommended due to poor performance)
2. Use a singleton schema, with a serial execution strategy, and pull the DbContext as a scoped service from `context.RequestServices`.
3. Use a singleton schema, define a service scope for each resolver that needs to access DbContext, and pull the DbContext as a scoped service from `context.RequestServices`.

Another option is to use a singleton schema, register DbContext as Transient, but be SURE to only pull DbContext from `context.RequestServices`.  When the scope (created by ASP.NET Core) is disposed, all transient services created within that scope will also be disposed.  This may be dangerous as if you accidentally pull DbContext from the root service provider anywhere, you will have a memory leak.

**Comment by Shane32** [comment]
In general I use a serial execution strategy and pull DbContext from `context.RequestServices`, either via `[FromServices]`, or `WithService<>` or directly from `context.RequestServices`.  I use data loaders extensively to enhance performance by grouping similar calls to the database together.

**Comment by NicolaiJee** [comment]
Thank you I will look into it.

**Comment by NicolaiJee** [comment]
Just to be sure, you would register services and DbContext as scoped and then consume the services like this ?

defaultQuery
                .Field<ListGraphType<BrandDTOType>>(this.GetType().Name.Replace("Query", "_") + "LoadAll")
                .Resolve()
                .WithScope()
                .WithService<IBrandService>()
                .ResolveAsync(async (context, brandService) => await brandService.LoadAll());
BrandService uses a instanse of DbContext.

**Comment by Shane32** [comment]
Yes, that certainly would work well.  Since you have specified `WithScope` the resolver will create a dedicated service scope for this resolve function, and then `WithService` defines the needed service(s) (which in turn can depend on other scoped services like your DbContext).

There will be no memory leak, it supports parallel execution, and it uses the DbContext is the recommended fashion.

**Comment by NicolaiJee** [comment]
Thank you for the help.
It solved all the memory issues we had :)

I did hit the limit of 5 WithServices 2 places, but I just rewrote the code :)
