### ISSUE TITLE
Inject a query if a directive is present.

### ISSUE THREAD

**Issue by keithcarter5** [graphql-dotnet/graphql-dotnet#3355]
I have created a custom directive, placed on a mutation field that would instruct the mutation as follows:

The mutation's resolver is capable of forming, based on the mutation, a "smart query" that would retrieve the items affected by the mutation.  The directive would tell the mutation to "append/inject" this smart query into the mutation's response as if the client had been knowledgeable enough to send the query in the first place.  The client would specify, using the custom field directive, that it would like the server to execute in this manner.

I have injected into the DI system an object where this "smart query" could be get/set.

I have a few questions:
1. If this behavior occurs only when the directive is present, does this violate the GraphQL protocol?
2. Is using FieldMiddleware the best way to do this...I could not get a DirectiveVisitor to work?
3. I saw in issue #2649 how to create the "smart query" document, but I don't know how to modify the executing document to add the smart query AST elements.  Would you offer any suggestions?

**Comment by Shane32** [comment]
Can you provide a sample GraphQL request and response that you are attempting to implement?

**Comment by keithcarter5** [comment]
Mutation:
mutation {
  module {
    setUserName(name: "KeithsModule") @performQuery {
      result {
        code
      }
    }
  }
}

Imagining this mutation affected "userName", "userDescription", and "catalogNumber", the mutation would (using a DI suggestQuery service) specify "{ module { userName userDescription } module { catalogNumber } }" as the "suggestedQuery". 
 The @performQuery directive would signal the server to retrieve the suggestedQuery (via the serviceProvider) insert the query into the executing document.

**Comment by Shane32** [comment]
Ok so just for clarification can you post the combined query that you’d like it to execute?

note that you can have GitHub format the code by typing something like this:

````
```gql
query {
  sample
}
```
````

which will look like this:

```gql
query {
  sample
}
```

**Comment by keithcarter5** [comment]
the client enters the following mutation:
```gql
mutation {
module {
setUserName(name: "KeithsModule") @performQuery {
result {
code
}
}
}
}
```

the resolver inserts into the mutation's response the query:
```gql
{
    module {
        userName userDescription
    }
    module {
        catalogNumber
    }
}
```
the graphql response to the mutation would be:
```gql
{
  "data": {
    "module": {
      "setUserName": {
        "result": {
          "code": 0
        },
        "suggestedQuery": {
          "module": {
            "userName": "KeithsModule",
            "userDescription": "Keiths Module Description",
            "catalogNumber": "2198-EW"
          }
        }
      }
    }
  }
}
```

**Comment by Shane32** [comment]
Rather than a directive, have you considered this instead:

```gql
mutation {
    module {
        setUserName(name: "KeithsModule") {
            result {
                code
            }
            suggestedQuery
        }
    }
}
```

Then `suggestedQuery` is a `JsonScalarType` or similar (a custom scalar graph type), which is a legal GraphQL scalar which returns structured data in the format you described:

```json
{
  "data": {
    "module": {
      "setUserName": {
        "result": {
          "code": 0
        },
        "suggestedQuery": {
          "module": {
            "userName": "KeithsModule",
            "userDescription": "Keiths Module Description",
            "catalogNumber": "2198-EW"
          }
        }
      }
    }
  }
}
```

The above could be implemented by having the `suggestedQuery` field call another GraphQL call internally to execute whatever suggested query was dictated by your DI-injected service.  You can use `.ToValue()` or similar to convert the internal GraphQL response back into a dictionary to return from the `suggestedQuery` resolver.  You will need to consider what happens if the internal execution returns an error, of course -- perhaps just returning null is sufficient.

Now, all of this assumes that the caller will know what the format of the suggested query would be.  Which begs the question: if the caller knows what the suggested query is, why doesn't the schema know what it is and assign the correct GraphQL type to the field?  I'll assume you have a good answer for this question, and offer a suggestion as a solution: include the suggested query text in the response, as shown below:

```gql
mutation {
    module {
        setUserName(name: "KeithsModule") {
            result {
                code
            }
            suggestedQuery
            suggestedQueryResponse
        }
    }
}
```

which returns:

```json
{
  "data": {
    "module": {
      "setUserName": {
        "result": {
          "code": 0
        },
        "suggestedQuery": "{ module { userName userDescription catalogNumber } }",
        "suggestedQueryResponse": {
          "module": {
            "userName": "KeithsModule",
            "userDescription": "Keiths Module Description",
            "catalogNumber": "2198-EW"
          }
        }
      }
    }
  }
}
```

Now I wouldn't want callers to have to parse the `suggestedQuery` field to decipher the `suggestedQueryResponse` field, but I guess it is possible to do so.

**Comment by Shane32** [comment]
Here are some other things I've done in the past which you may be able to pull ideas from:

1. The GraphQL type of the `setUserName` mutation is the `ModuleType` so that any property from the updated module can be returned

```gql
mutation {
    module {
        setUserName(name: "KeithsModule") {
            userName
            userDescription
            catalogNumber
            # any other fields of the updated module can be selected here
        }
    }
}
```

2. Add a `query` field to the root of the `MutationType` which points to `QueryType` so that any query can be run in conjunction with the mutation.  These queries could execute within the same SQL transaction as the mutation, for example.  And since according to GraphQL spec, mutations execute serially, the caller can define if the query can run before or after the mutation:

```gql
mutation {
    module {
        setUserName(name: "KeithsModule") {
            result { code }
        }
    }
    query {
        module(name: "KeithsModule") {
            userName
            userDescription
            catalogNumber
        }
    }
}
```

Since GraphQL spec allows querying the same field multiple times via aliases, it is even possible to return any arbitrary data from both before and after the mutation, like this:

```gql
mutation {
    queryBefore: query {
        module(name: "KeithsModule") {
            userName
            userDescription
            catalogNumber
        }
    }
    module {
        setUserName(name: "KeithsModule") {
            result { code }
        }
    }
    queryAfter: query {
        module(name: "KeithsModule") {
            userName
            userDescription
            catalogNumber
        }
    }
}
```

**Comment by Shane32** [comment]
Back to your original question regarding using a directive to inject query results into the mutation results, within GraphQL.NET this would be difficult to implement in the exact manner you described.  Basically, I'm not sure how or if you could inject into the results.  Best bet would be to injecting a field into the request (i.e. the `suggestedQuery` field that I first suggested above), and letting it process exactly as if the `suggestedQuery` field was requested directly from the caller.  At that point it seems a little pointless to use a directive at all.  However, if it was a requirement, you could implement a schema filter to hide `suggestedQuery` from introspection queries and simply use the hidden field to inject when the directive was used.  I don't really have a better answer there.

**Comment by Shane32** [comment]
> JsonScalarType

#474 relates to what I was talking about.  I wrote `ComplexScalarGraphType` in #3257 to serve that purpose, but honestly `AnyGraphType` is all you need here.  Although designed for GraphQL federation, it will serve your purpose nicely.  `ComplexScalarGraphType` has `ToAST` implemented where `AnyGraphType` does not, but this does not matter for your needs.

If you look through the open PRs you will also see #3246 -- this represents stringified JSON and is not what I was talking about.

**Comment by keithcarter5** [comment]
I just realized the sillyness of my question on how to internally execute my own graphql query...thanks for ignoring that.  I think I have everything I needed to move forward.  Thanks very much for your help!

**Comment by Shane32** [comment]
Feel free to ask if there's anything else.

**Comment by Shane32** [comment]
You might or might not want to create a service scope for the subquery execution.  Probably not I'm guessing.

**Comment by keithcarter5** [comment]
Now I feel like I had a good question after all, since your above example hits some items I would have missed.  Thanks again.
