### ISSUE TITLE
Custom Server protocol needs to support Subscriptions

### ISSUE THREAD

**Issue by keithcarter5** [graphql-dotnet/graphql-dotnet#3368]
We are using a custom server (not Rest, not WS) and have plugged that server into our GraphQL server implementation.  When the server receives the request, it is calling 
```cs
public string ExecuteQueryOrMutation(string queryOrMutation)
    {
        var schema = _graphQlServices.GetService<ISchema>();

        string reply = string.Empty;
        using (var scope = _graphQlServices.CreateAsyncScope())
        {
            reply = schema.ExecuteAsync(_ =>
            {
                _.Query = queryOrMutation;
                _.RequestServices = _graphQlServices;
            }).GetAwaiter().GetResult();
        }

        return reply;
    }
```

I need to connect our server to the Subscription capability in GraphQL.NET, but I cannot find any info on how to do this.  I'd appreciate any guidance you could offer.

**Comment by Shane32** [comment]
If using the default registrations, use the `IDocumentExecuter<ISchema>` interface to execute the request rather than using the `ExecuteAsync` extension method on the schema instance.  The return value (of type `ExecutionResult`) has a `Streams` property which returns an `IObservable` stream of `ExecutionResult` instances -- see here:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionResult.cs#L33

You can convert `ExecutionResult` instances to JSON strings by pulling `IGraphQLTextSerializer` from DI and serializing the `ExecutionResult`.

On a side note, I suggest two changes in your above code:

1. Use `CreateScope` rather than `CreateAsyncScope` if you're not using `async using`.

2. Set `RequestServices` to pull the scoped service provider.

```cs
// was
_.RequestServices = _graphQlServices;

// should be
_.RequestServices = scope.ServiceProvider;
```

As it is now, your scoped service provider is not being used, and as such is ineffective.

Keep in mind that if you have need of a scoped service provider, it is likely that you also need a serial execution strategy, and a scoped serial execution strategy for subscription requests.  See related documentation here:

https://github.com/graphql-dotnet/server#additional-notes--faq

On the other hand, if you field resolvers create their own scope as-needed, or if all of your DI-injected services are singletons, there is no need to create a scope at all, and the default configuration (with parallel execution of query nodes) is suitable.

**Comment by keithcarter5** [comment]
You stated:
 > If using the default registrations, use the `IDocumentExecuter<ISchema>` interface...

What do you mean by "using the default registrations"?

And I was specifying the serial execution strategy for queries...although now I'm beginning to question why.  I am only concerned about queries occurring before/after/around mutations.  My mutations, however, always return a query type so the client can propose a query after the mutation...I also have mutations return a "suggested query", referring to issue #3355 (which works excellently thank you!).  So I'm thinking to remove scoping and go back to the standard parallel execution strategy.

**Comment by Shane32** [comment]
> What do you mean by "using the default registrations"?

If you used code similar to the following to register the GraphQL services:

```cs
services.AddGraphQL(b => b
    .AddSchema<MySchema>()
    .AddSystemTextJson());
```

**Comment by Shane32** [comment]
> So I'm thinking to remove scoping and go back to the standard parallel execution strategy.

So long as you do not rely on scoped services, such as Entity Framework, you should be fine.  Mutations will always execute serially, as specified in the GraphQL specification (unless otherwise configured).

**Comment by keithcarter5** [comment]
If a GraphQL client subscribes as
```gql
subscription {
   dataChanges
}
```
then how does a GraphQL client unsubscribe?  My GraphiQL seems to like:
```gql
subscription unsubscribe {
   dataChanges
}
```

I could not find any info in the GraphQL spec about this.

**Comment by Shane32** [comment]
That is left up to the transport implementation.  Here are some of the most common subscription transport protocols:

- GraphQL over WebSockets: https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md
- GraphQL over SSE: https://github.com/enisdenjo/graphql-sse/blob/master/PROTOCOL.md

If you are implementing a binary or other proprietary protocol, in general you can either support single or multiple subscriptions per connection.

If multiple subscriptions per connection, you will likely need to:
- Upon subscribing, return a unique identifier along with the result
- When there are data events from the subscription, include the unique identifier
- Allow the client to unsubscribe, using the unique identifier to identify which subscription to unsubscribe from
- Automatically unsubscribe if the communication channel unexpectedly terminates

If only single subscriptions are supported per connection, such as the Distinct Connections Mode of the SSE protocol linked above, then you can simply infer an unsubscription when the connection is terminated.

**Comment by keithcarter5** [comment]
It appears that the server must manage 2 subscriptions:
1.  The `IObservable` in the `ExecutionResult.Streams` property.  I am planning on having my server connection subscribe to this and transmit the `ExecutionResult` upon reception,
2.  The `IObservable` returned by the Subscription itself, which is the source of the subscribed data.

If I plan on supporting an unsubscribe, must I dispose both of these subscriptions?  If so, I'm wondering how I can easily reference both IDisposables.  

Also, if I dispose of the `IObservable` returned by the `SubscriptionType`, how would I ensure it could be subscribed to again?  I'm wondering about the lifetime of that IObservable.  I was thinking it is effectively a Singleton, processed once when the Schema is registered.

**Comment by Shane32** [comment]
As for subscription # 2 above, the `IObservable` returned from the field resolver will be disposed when the `IObservable` from the `ExecutionResults.Streams` property is disposed.  You should not have access to, or need to access, this underlying subscription.

You can see the code for how the observables are linked up here:
- https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/SubscriptionExecutionStrategy.cs#L130-L145
- https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Extensions/ObservableExtensions.cs

So your server code should only have access to the # 1 subscription above, returned by the `IObservable<ExecutionResult>` value within the `ExectionResults.Streams` property.  Just dispose of that to disconnect from a subscription.  Note that it is very important -- essential, actually -- to dispose of this subscription to prevent memory leaks within your application.

Also, it is important to understand that it is not the `IObservable` that is being disposed of, but rather the subscription that its `Subscribe` method returns.  As for the lifetime of the `IObservable`, there is a few ways to design it:

1. The `IObservable<T>` can be a singleton which always broadcasts a sequence of events, regardless if there are none, one or many listeners attached.  Using the `System.Reactive` library, this can be filtered via `.Where` to only return events which meet a certain criteria, or mapped to another type via `.Select`, but the basis for the event stream is the same regardless.  This works well when monitoring event sequences generated within the codebase, such as a live stream of server logging output, as there is little negative to generating events when there is no listener, and it is simple to implement.  If the event stream requires a scoped service, the singleton can create a service scope for its own use.

2. You can build on the above to add automatic spin-up and tear-down when there are no listeners.  While being complicated to implement, this eliminates CPU and/or DB time generating events when there are no listeners.  

3. You can create a new event stream for each client.  Essentially the `IObservable<T>` implementation would contain the metadata required to set up the event stream, and the event stream would actually be set up when `.Subscribe` was called.  This is important as the `IObservable<T>` class is not disposed -- only the subscription set up from calling `.Subscribe` is disposed.  Within GraphQL.NET, the `IObservable<T>` returned to the field resolver would only have `.Subscribe` at most one time (in rare circumstances, it may not be called at all).  This scenario may work well if the GraphQL.NET server is mapping requests to a legacy endpoint.

Regardless of the chosen method of implementing the `IObservable<T>`, there is also the matter of DI service scope upon receipt of data from the event stream, as essentially a new GraphQL execution occurs for each data event:

1. The connection's service scope is kept alive and used for the duration of the subscription.  This makes sense when utilizing a connection that only supports a single GraphQL subscription for the connection's duration, such as the Distinct Connections Mode of the SSE protocol linked above.

2. A service scope is created for the initial request, and for each data event, and closed as soon as possible.  This makes sense when the connection supports multiple concurrently active subscriptions.  When coupled with the `.AddScopedSubscriptionExecutionStrategy()` extension method, this is how GraphQL.NET Server operates.

**Comment by keithcarter5** [comment]
If the ```UserContext``` was transferred into the ```ExecutionResult```, that would be a useful mechanism to pass the subscription id from the source subscribe to the server subscribing to the ```IObservable<ExecutionResult>```.  What do you think about that?

**Comment by Shane32** [comment]
Sorry I have not had much time to answer recently.  Basically, I think you're heading down the wrong avenue; I think the subscription ID and method to unsubscribe should be handled out-of-band as it is with the other existing protocols.  I can provide examples, but I have already supplied links to those protocols, which have excellent samples and documentation.

Since I do not understand your requirements, nor why the existing protocols or existing protocol designs do not work for your needs, I cannot help recommend solutions.  For example, it would be incredibly easy to implement the existing protocol design across a different underlying protocol, since almost all of the existing subscription support classes could be re-used.

**Comment by keithcarter5** [comment]
Thanks for your response...that’s exactly the kind of guidance I am looking for.  I’ll proceed just as you suggest.  Thanks again.

**Comment by Shane32** [comment]
As a specific answer to your questions, first, if you wanted to return the subscription ID within the GraphQL response, you could add it to the extensions property of the response of each data event.  Probably something like this:

```cs
var result = await executer.ExecuteAsync(...);
var id = /* new id */;
var eventStream = result.Streams[0].Select(ret => {
    ret.Extensions ??= new Dictionary<string, object?>();
    ret.Extensions["subscriptionId"] = id;
});
```

Again, this is not my recommendation, but it is possible, as is creating a mutation to unsubscribe.

**Comment by Shane32** [comment]
It is correct that you'll need a map that relates the ID to active subscriptions.  You also need to provide code to notify callers if the end of the event stream has been reached or an error encountered.  You also need to monitor if clients disconnect and if so disconnect the subscription.  Finally, you likely will want to ensure that clients can only unsubscribe from their own subscriptions, not other clients' subscriptions.

**Comment by Shane32** [comment]
Feel free to ask if you have any other questions, and I'll try to help when I have time.

**Comment by Shane32** [comment]
If you wish to re-use the existing subscription support, just start with the `WebSocketConnection` class and modify it to use your own underlying protocol rather than `WebSocket`.  So long as it implements `IWebSocketConnection`, you can re-use the `GraphQL.Server.Transports.AspNetCore.WebSockets.GraphQLWs.SubscriptionServer` class which will handle the entire implementation of setting up and disconnecting from subscriptions, authentication, errors, timeouts, keep alive, etc.

**Comment by Shane32** [comment]
Or, to make slight changes to the message protocol, just derive from `BaseSubscriptionServer` or one of the two `SubscriptionServer` classes, and make changes to the handling for your own needs.  This assumes that messages are going to conform to the same general pattern.  Any bigger changes will require starting from scratch.
