### ISSUE TITLE
Should non nullable types allow explicit null

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#3373]
if i have a an argument `id` that is a `guid` and hence a `NonNullable<IdGraphType>`

and i have query
```
{
  entity(id: null) {
    property
  }
}
```
graphql-dotnet considers this valid. since "id has a value" and IdGraphType wil happily parse it

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/IdGraphType.cs#L33
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/IdGraphType.cs#L53

but it would seem that if it is a NonNullable it should error when someone passes an explicit null?

**Comment by Shane32** [comment]
If the argument `id` in the example above is defined as a non-null argument (`NonNullGraphType<GuidGraphType>`), then the above query is invalid according to GraphQL spec.  See the 'Input Coercion' paragraph here:

https://spec.graphql.org/June2018/#sec-Type-System.Non-Null

If GraphQL.NET is not working in this fashion, please provide a sample for review.

On the other hand, if the argument is a nullable `GuidGraphType`, and you are discussing the `GetArgument<Guid>` capability of GraphQL.NET, this by design returns the C# `default` value for `null` inputs.  In this case, the result would be equivalent to `Guid.Empty`.  Simply use `GetArgument<Guid?>` to receive a null value when parsing `null` from the GraphQL query.

**Comment by SimonCropp** [comment]
@Shane32 thanks for the clarification. i will dig in deeper. it is possible i am "holding it wrong"

**Comment by SimonCropp** [comment]
yep i was  "holding it wrong". sorry
