### ISSUE TITLE
Error trying to resolve field

### ISSUE THREAD

**Issue by jee-mj** [graphql-dotnet/graphql-dotnet#3407]
## Problem:

This should work, but does not.
```cs
var applicationString = builder.Configuration.GetConnectionString("database") ?? throw new InvalidOperationException("'database' not found.");

builder.Services.AddDbContext<AppDbContext>(options => { options.UseSqlServer("database"); }, ServiceLifetime.Singleton);
```

## Temporary workaround

```cs
// You just gotta pass it in like this otherwise EF => GraphQL freaks out </3
builder.Services.AddDbContext<AppDbContext>(options => { options.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=MGEFNET;Trusted_Connection=True;MultipleActiveResultSets=true"); }, ServiceLifetime.Singleton);
``` 

### Environment

```xaml
<TargetFramework>net7.0</TargetFramework>
  <ItemGroup>
	<PackageReference Include="GraphQL" Version="7.1.1" />
	<PackageReference Include="GraphQL.DataLoader" Version="7.1.1" />
	<PackageReference Include="GraphQL.MicrosoftDI" Version="7.1.1" />
	<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="7.1.1" />
	<PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="7.1.1" />
	<PackageReference Include="GraphQL.SystemTextJson" Version="7.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0" />
  </ItemGroup>
```

## [entire solution](https://github.com/jee-mj/Modular-GraphQL-EntityFramework-dotNET) `(jee-mj/Modular-GraphQL-EntityFramework-dotNET)`

Kind Regards,

jee-mj

**Comment by sungam3r** [comment]
> line: 33, column: 3

It points to coordinates into input GraphQL query string.


Thanks for the repro 👍  but we need an example query to pass it into your GraphQL server.

**Comment by jee-mj** [comment]
I made a quick video outlining how to reproduce the error:
https://user-images.githubusercontent.com/28581723/202466748-a5e4d2ca-36d0-4118-8620-1227c505c0c1.mp4

The queries I try running are as follows:
```json
query { restaurant(id:"1"){name}}
else
query{restaurants{name}}
```
You can find below the fields that should be read:
![image](https://user-images.githubusercontent.com/28581723/202467198-aea72a86-3cf1-484f-b1f4-99a8d0ddfa40.png)

**Comment by Shane32** [comment]
I think perhaps you're misunderstanding what a data loader's function is.  Typically a data loader is used to group calls to the database for a set of ids.  For instance, if you had a list of products, and each Product had a ManufacturerId, rather than pulling each manufacturer from the database individually, you can use a data loader to retrieve all the manufacturers at once.  However, the root query does not typically need a data loader - it is already a single call that is not expected to be called again in the query.

Take the below sample:

```gql
{
  restaurants {   # typically the resolver would not have a data loader here
    name
    address {     # this would be a good use of a data loader, assuming the addresses were stored in a separate table
      city
    }
    menuItem {    # this is another type of use of a data loader
      name
      price
    }
  }
}
```

In the sample above, Address uses the `GetOrAddBatchLoader` method, as it is retrieving a single item per child id, and MenuItem uses the `GetOrAddCollectionBatchLoader` method, as it retrieves a list of items per parent id.

You can read more about data loaders here:
- https://graphql-dotnet.github.io/docs/guides/dataloader

Regardless, I don't immediately see anything wrong with the code sample you provided.  Although perhaps not very useful, there is no reason why a SimpleDataLoader cannot be created to load the list of restaurants.  I suggest turning on exception stack traces within responses to better diagnose the issue.  If you can post the stack trace, I can take another look.

```cs
services.AddGraphQL(b => b
    // etc
    .AddErrorInfoProvider(options => options.ExposeExceptionDetails = true);
);
```

**Comment by Shane32** [comment]
I would also like to confirm that `IApiRepository` and the `AppDbContext` is uses are registered as a singletons in your program?  (Note: Entity Framework contexts are scoped services.)

**Comment by Shane32** [comment]
I see you have this code in your sample:

```cs
builder.Services.AddDbContext<AppDbContext>(options => { options.UseSqlServer("YourConnectionString"); }, ServiceLifetime.Singleton);
```

This isn't going to work long-term because Entity Framework does not support concurrent requests, and GraphQL.NET Server is going to execute each request it receives as soon as it arrives, which may be concurrent with another request.  You do have queries configured to execute serially, so at least it should work for testing.

Long term you'll want to have your `DbContext` and `IApiRepository` as scoped services, and change your field resolver like so:

```cs
    public class ApiQuery : ObjectGraphType
    {
        public ApiQuery(IDataLoaderContextAccessor accessor)
        {
            var loader = accessor.Context;
            Name = "ApiQuery";

            Field<RestaurantType, Restaurant>("restaurant")
                .Argument<NonNullGraphType<StringGraphType>>("id", "the restaurant identifier")
                .Resolve()
                .WithService<IApiRepository>()
                .ResolveAsync(async (context, repository) => await repository.GetRestaurantById(context.GetArgument<int>("id")).ConfigureAwait(false));
                
            Field<ListGraphType<RestaurantType>, IDataLoaderResult<List<Restaurant>>>("restaurants")
                .Resolve()
                .WithService<IApiRepository>()
                .ResolveAsync(async (context, repository) =>
                {
                    return loader?.GetOrAddLoader("GetAllRestaurants", repository.GetAllRestaurants)
                        .LoadAsync();
                });
        }
    }
```

**Comment by jee-mj** [comment]
From the GraphQL.NET Documentation, In DataLoader at the bottom of Examples / just above [Exceptions](https://graphql-dotnet.github.io/docs/guides/dataloader/#exceptions) it mentions the following:

> See this [blog series](https://fiyazhasan.me/graphql-with-net-core-part-xi-dataloader/) for an in depth example using Entity Framework.

In this example, fiyazbinhasan uses Transient lifecycle as follows:
```cs
services.AddDbContext<ApplicationDbContext>(options => options.UseLoggerFactory(loggerFactory).UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=GameStoreDb;Trusted_Connection=True;"), ServiceLifetime.Transient);
```

----

I was using Singleton because that is the preferred approach according to the documentation for the initial implementation. Once everything functions / I pull the data from the database successfully, then I was going to look at mutations, and eventually the fine-tuning. The last bit -- subscriptions, is not for this implementation.

I have code debt in that the final implementation would go back and remove the Repository Pattern and swap it out for a Service pattern as per the structure of [this](https://www.linkedin.com/learning/api-development-in-dot-net-with-graphql) LinkedIn Learning course by Glenn Block.

----

Anyway, the exception details point towards my implementation of `GraphQL.EntityFramework` as follows:

```cs

System.MissingMethodException: Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.
```
See [error.json](https://github.com/graphql-dotnet/graphql-dotnet/files/10036447/error.json.txt) for the full stack trace.

I will return with my findings after looking into `GraphQL.EntityFramework` on GitHub.

Kind Regards,

jee-mj

**Comment by jee-mj** [comment]
On further inspection, this does not seem to be the correct package to use.

It's not a part of GraphQL Foundation's collection of Packages, hence I am not going to use it. I will have another look at Docs.DataLoader.

I had a problem implementing step 4 and omitted it because I don't have DocumentExecuter to modify as it is an internal class of the package.

> ### Add the DataLoaderDocumentListener to the DocumentExecuter.

> ```cs
> var listener = Services.GetRequiredService<DataLoaderDocumentListener>();
> 
> var executer = new DocumentExecuter();
> var result = executer.ExecuteAsync(opts => {
> 
> 	...
> 
> 	opts.Listeners.Add(listener);
> });
> ```

I will try to follow in the footsteps of fiyazbinhasan and make a DocumentListener in my project file as he has done for `GraphQLMiddleware` and `GraphQLMiddlewareExtensions` in his root directory.

**Comment by Shane32** [comment]
As for the data loader, the instructions you are following are out of date.  The call to `AddDataLoader` here:

https://github.com/jee-mj/net6-graphql-ef-api/blob/main/Program.cs#L43

Already performs the work of these lines:

https://github.com/jee-mj/net6-graphql-ef-api/blob/main/Program.cs#L31-L32

It also adds the document listener to the execution.  For reference, see the source of the `AddDataLoader` method:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.DataLoader/Extensions/DataLoaderGraphQLBuilderExtensions.cs#L16-L20

And the source of the `AddDocumentListener` method:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Extensions/GraphQLBuilderExtensions.cs#L656-L665

I didn't mention it before because the extra registration should have no effect.

Just FYI, you can also remove `builder.Services.AddSingleton<ISchema, ApiSchema>();` because the schema is registered within the call to `.AddSchema<ApiSchema>()`.  And if you want to remove the calls to register `ApiQuery` and `RegistrationType`, just add a call to `.AddGraphTypes()` within your Program.cs, which will scan the calling assembly for graph types and register them with your DI provider.

**Comment by Shane32** [comment]
For any other configurations to the execution options, just call `.ConfigureExecutionOptions(opts => { ... });`

**Comment by jee-mj** [comment]
> I'd check to be sure that matching versions of Microsoft.EntityFrameworkCore nuget packages are installed. Perhaps you have an older version of Microsoft.EntityFrameworkCore.SqlServer installed than the Microsoft.EntityFrameworkCore package.

Okay, I will check this one first by downgrading my existing bsAPI project references to 6.0.11, and if that still presents issues, I have another project on NET 7 I am working to re-produce the same setup in something that can be used as reference for the future by others. 🥂

**Comment by Shane32** [comment]
A transient lifecycle for a DbContext can help in certain situations.  In your case, it won't, at least not yet.  The thing is that since `IApiRepository` is a singleton, the DbContext will also be effectively a singleton.  If you register `IApiRepository` as a transient, then it too will have a singleton effective lifetime because it is created with the graph type that references it.

Now if you're thinking that you can just use a transient (or scoped) schema, that's true, and in fact GraphQL.NET supports scoped schemas.  But it takes a long time to construct a schema, and so it is not recommended for performance reasons.

If you did want to use a scoped schema, remove all your manual registrations as described above, adding the call to `.AddGraphTypes()`.  Then change the `.AddSchema<ApiSchema>()` call to specify that it should be created as scoped.

There is a danger to transient DbContexts in that transient services are not disposed until the container that holds them is disposed.  This is not an issue if the DbContext is created within a scope, but if it is repeatedly created from the root (e.g. from a singleton), then you will have a memory leak.  See link here:

https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposable-transient-services-captured-by-container

**Comment by Shane32** [comment]
Transient DbContexts can provide a benefit where if you also have `IApiRepository` a transient, and then reconfigure the field resolvers as previously described, then you can use parallel execution as each field resolver will receive its own instance of `IApiRepository` and the `DbContext`.  This doesn't work for my code because I have many services that operate on the DbContext, and it is essential that each DbContext is the same reference so that `SaveChanges` works properly.

**Comment by Shane32** [comment]
Just FYI, my own GraphQL project that uses Entity Framework currently is a .NET 6 project, running with GraphQL.NET 7, and EF Core 3.1.  The database project is currently also referenced by code that executes on .NET 4.8, so I am prevented from upgrading to EF 5.x or newer.  Another of my projects uses the linq2db database layer rather than EF Core.

**Comment by Shane32** [comment]
Just FYI, Entity Framework Core 7.0 relies on SqlClient 5.0.1, which has a catastrophic memory leak if you make repeated calls within a `BackgroundService`.  See https://github.com/dotnet/SqlClient/issues/1810

**Comment by jee-mj** [comment]
> > I am working to re-produce the same setup in something that can be used as reference for the future by others.
> 
> One of my wish-list goals is to write a "real-world" sample GraphQL project that uses a Entity Framework back-end and utilizes data loaders and so on, including a React SPA demonstration application with JWT authentication and subscription support. So many of the samples available now can't really be used for production applications, and/or don't explain how to implement "real-world" tasks. You can build GraphQL.NET applications either by "code-first", "schema-first", or "type-first", and having the same program implemented each way would allow people to compare writing styles to see what works best for them, and/or compare logic across writing styles.

will have to leave that to you 😋 for the time being, [this is the full setup](https://github.com/jee-mj/Modular-GraphQL-EntityFramework-dotNET). Just running update-database should pull everything given that the following connection strings are valid for you:
`"Server=(localdb)\\mssqllocaldb;Database=MGEFNET;Trusted_Connection=True;MultipleActiveResultSets=true"`
Note that I use `GUID` instead of `Int` here.

**Comment by jee-mj** [comment]
re-opening this for GraphQL developers to look at if it is intentional or not

**Comment by jee-mj** [comment]
The issue is that the following returns an error:

```cs
var applicationString = builder.Configuration.GetConnectionString("database") ?? throw new InvalidOperationException("'database' not found.");

builder.Services.AddDbContext<AppDbContext>(options => { options.UseSqlServer("database"); }, ServiceLifetime.Singleton);
```
The following does not:
```cs
// You just gotta pass it in like this otherwise EF => GraphQL freaks out </3
builder.Services.AddDbContext<AppDbContext>(options => { options.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=MGEFNET;Trusted_Connection=True;MultipleActiveResultSets=true"); }, ServiceLifetime.Singleton);
```
