### ISSUE TITLE
Register Dictionary<string, object> as Json Type

### ISSUE THREAD

**Issue by nichovski** [graphql-dotnet/graphql-dotnet#3432]
Hi,

In the latest version, my solution for registration of Dictionary<string, object> is not working anymore. This is the error I'm getting:
The GraphQL type for field 'MyClass.myProperty' could not be derived implicitly. Could not find type mapping from CLR type 'System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' to GraphType. Did you forget to register the type mapping with the 'ISchema.RegisterTypeMapping'?

Here is the code that worked in version 5.3
```
 RegisterTypeMapping(typeof(KeyValuePair<,>), typeof(JsonScalarType));

 RegisterTypeMapping(typeof(KeyValuePair<string, string>), typeof(JsonScalarType));

 RegisterTypeMapping(typeof(KeyValuePair<string, object>), typeof(JsonScalarType));
```

Where JsonScalarType is a class inherited from ScalarGraphType
 ```
public class JsonScalarType : ScalarGraphType
    {
        public JsonScalarType()
        {
            Name = "json";
        }
}

```

Any suggestion is highly appreciated!

Thanks

**Comment by Shane32** [comment]
Very likely due to this change:
- https://graphql-dotnet.github.io/docs/migrations/migration7#7-code-classlanguage-textglobalswitchesmapallenumerabletypescode-has-been-removed-only-specific-types-are-detected-as-lists

Offhand, probably something like this would work:

```cs
RegisterTypeMapping(typeof(Dictionary<string, object>), typeof(JsonScalarType));
```

However, it would like change the schema so that instead of a field being detected as a list of `JsonScalarType`s, it's now a single `JsonScalarType`.  This in turn may serialize differently (although perhaps more accurately).

There's a chance also that this would work, providing equivalent operation to before:

```cs
RegisterTypeMapping(typeof(Dictionary<string, object>), typeof(ListGraphType<JsonScalarType>));
```

It's also possible that writing a custom [IGraphTypeMappingProvider](https://github.com/graphql-dotnet/graphql-dotnet/blob/27ab561c0b878bf78856c62420323b3052766eb8/src/GraphQL/Types/Collections/IGraphTypeMappingProvider.cs) would serve your needs best.

I guess to provide a better recommendation, I'd like to see the schema definition and response format that's desired

**Comment by nichovski** [comment]
> Very likely due to this change:
> 
> * https://graphql-dotnet.github.io/docs/migrations/migration7#7-code-classlanguage-textglobalswitchesmapallenumerabletypescode-has-been-removed-only-specific-types-are-detected-as-lists
> 
> Offhand, probably something like this would work:
> 
> ```cs
> RegisterTypeMapping(typeof(Dictionary<string, object>), typeof(JsonScalarType));
> ```
> 
> However, it would like change the schema so that instead of a field being detected as a list of `JsonScalarType`s, it's now a single `JsonScalarType`. This in turn may serialize differently (although perhaps more accurately).
> 
> There's a chance also that this would work, providing equivalent operation to before:
> 
> ```cs
> RegisterTypeMapping(typeof(Dictionary<string, object>), typeof(ListGraphType<JsonScalarType>));
> ```
> 
> It's also possible that writing a custom [IGraphTypeMappingProvider](https://github.com/graphql-dotnet/graphql-dotnet/blob/27ab561c0b878bf78856c62420323b3052766eb8/src/GraphQL/Types/Collections/IGraphTypeMappingProvider.cs) would serve your needs best.
> 
> I guess to provide a better recommendation, I'd like to see the schema definition and response format that's desired

Thank you very much! 

It works correctly when I'm registering Dictionaries instead of KeyValuePair.

You saved me 3 days of debugging. I really wish GitHub had an option "Buy a beer" :)

**Comment by sungam3r** [comment]
It has 
![изображение](https://user-images.githubusercontent.com/21261007/205343330-ef78fc2f-4a44-4c0e-a2f5-cefaccba295a.png)
