### ISSUE TITLE
Can DataLoader discover what fields are required to be loaded?

### ISSUE THREAD

**Issue by bartecargo** [graphql-dotnet/graphql-dotnet#3435]
My DataLoader calls an existing API that was not designed with GraphQL in mind. The API loads objects, and optionally loads various fields associated with those objects. Loading the additional fields is optional because they can be expensive in terms of execution time.

I would like my DataLoader to be able to only request fields from the underlying API that are actually required to service the GraphQL request. Is it possible for DataLoader to find out the union of all the fields that the resolver needs? I understand that different parts of the GraphQL query may request different fields, so I'm only looking to exclude fields that are not required by any nodes in the query.

**Comment by Shane32** [comment]
Yes....more or less.  I do this in one of my projects, and I do it as follows:

- create a data loader where the key is a valuetuple of (1) the `IResolveFieldContext`, and (2) the id to be loaded
- within the fetch delegate of the data loader, group by `context.GraphQLField`; loop over each group and independently retrieve results
- within each group, take the first context, and pull the SubFields property (note: any of the contexts in this group will return the same set of subfields)
- match the subfields to the data fields to be retrieved from the data source
- retrieve the data and supply the values to the data loader nodes
- go to the next group and repeat

The grouping is grouping by node in the query, because they will always have exactly the same fields.  This means that it may cause this effect for a GraphQL query:

```gql
{
  hotProducts {   # list of hot products which are data loaded together
    id
    name
    popularity
  }
  recentProducts {   # list of recent products which are data loaded together
    id
    name
    lastPurchaseDate
  }
  # note that the two above groups normally would data load
  # together, but now with grouping are not (on purpose)
}
```

Note that GraphQL fields may be aliased in the query, and even be requested twice.  It may also use fragments...  so you should test that queries like this still performs correctly:

```gql
{
  products {
    id
    currentPrice: price
    lastPrice: price
    ...example
  }
}

fragment example on Product {
  name
  description
}
```

With a few tweaks to the design above, you can likely make it so that it takes the union of all the subfields across all contexts.  Pulling the SubFields property for each context isn't ideal for performance reasons, but something like this could probably work:  (untested; just a concept)

```cs
var subFields = keys.GroupBy(x => x.Context).Select(x => x.First().Context.SubFields).SelectMany(x => x);
```

Then you need to do something like `Distinct()`, but I'm guessing `Distinct()` wouldn't exactly work.  You get the picture...
