### ISSUE TITLE
wrong depth calculation with fragments 

### ISSUE THREAD

**Issue by negue** [graphql-dotnet/graphql-dotnet#344]
**This issue participates in bounty program, see https://github.com/graphql-dotnet/graphql-dotnet/blob/master/BOUNTY.md**

**bounty amount: $100**

Tasks to be done:
1. Complexity analyzer should be fully documented (xml comments).
2.  Add documentation page regarding comolexity analyzer with explaining how calculation is performed, including setup instructions, and examples of common configurations.
3. Update sitemap.yaml and include page into solution tree. 

[ORIGINAL POST BELOW]

I think the depth calculation has a bug, it adds every used fragment to the total sum.  

I have a query which only has a depth of 4 levels, but... `Query is too nested to execute. Depth is 12 levels, maximum allowed on this endpoint is 10.` 

'X' Fragment used 5 times with a depth of 1
'Y' Fragment used twice with a depth of 2

Example:
```graphql
query myQuery($id: Int) {
   data(id: $id) {
      a1
      a2 {
         b1 {
            c1
         }
      }
      a3 {
         ...Y
      }
      a4 {
         ...Y
      }
   }
   some1: someList(byType: 1) {
      ... X
   }
   some2: someList(byType: 2) {
      ... X
   }
   some3: someList(byType: 3) {
      ... X
   }
   some4: someList(byType: 4) {
      ... X
   }
   some5: someList(byType: 5) {
      ... X
   }
}

fragment X on FirstGraphType {
   a1
}

fragment Y on SecondGraphType {
   b1 {
      c1
      c2
   }
}


```

**Comment by joemcbride** [comment]
Possibly related to #298

**Comment by jalovatt** [comment]
I'm having the same (or a similar) issue - the calculated depth increases as I add more fields even though there are no recursive relationships and the apparent depth remains constant.

Did this ever get resolved? Or am I just misunderstanding what "depth" means in this context?

The following returns a depth of 38. (`count` and `year` are integers)

```
query{
  conditionsPerYear{
    filing {
      REQUIRED {
        count
        year
      }
      NOT_REQUIRED {
        count
        year
      }
    }
    status {
      CLOSED {
        count
        year
      }
      IN_PROGRESS {
        count
        year
      }
    }
    theme {
      ADMINISTRATIVE_ {
        count
        year
      }
			CONSERVATION_OF_RESOURCES {
        count
        year
      }
      CROSSINGS {
        count
        year
      }
      DAMAGE_PREVENTION {
        count
        year
      }
      ENFORCEMENT {
        count
        year
      }
      ENGINEERING {
        count
        year
      }
      ENVIRONMENTAL_PROTECTION {
        count
        year
      }
      FINANCIAL {
        count
        year
      }
      IAMC_OBSERVATION {
        count
        year
      }
      INTEGRITY_MANAGEMENT {
        count
        year
      }
      LANDOWNER {
        count
        year
      }
      MANAGEMENT_SYSTEM {
        count
        year
      }
      PUBLIC_AWARENESS {
        count
        year
      }
      SAFETY_MANAGEMENT {
        count
        year
      }
      SECURITY {
        count
        year
      }
      SOCIOECONOMIC {
        count
        year
      }
      STANDARD_CONDITION {
        count
        year
      }
      SUNSET_CLAUSE {
        count
        year
      }
    }
    timing {
      ABANDONMENT {
        count
        year
      }
      DURING_CONSTRUCTION_PHASE {
        count
        year
      }
      EXPIRY_DATE_OF_REG_INSTR {
        count
        year
      }
      INCLUDES_ALL_PHASES_OF_CONSTR {
        count
        year
      }
      NOT_CONSTRUCTION_RELATED {
        count
        year
      }
      POST_CONSTRUCTION_PHASE {
        count
        year
      }
      PRIOR_TO_CONSTRUCTION_PHASE {
        count
        year
      }
      UNSPECIFIED {
        count
        year
      }
    }
    type {
      NON_STANDARD {
        count
        year
      }
      STANDARD {
        count
        year
      }
      
    }
  }
}
```

**Comment by sungam3r** [comment]
@negue @jalovatt First of all, I want to say that I have not worked with `ComplexityAnalyzer` before. Nevertheless, I am aware of what it is and how it works. After some tests I came to the conclusion that the behavior is correct. The total depth for your case is really equal to 12. Pay attention to the name of the property - `ComplexityResult.TotalQueryDepth` (**total**). This is not just about the maximum depth of a single "section" of the request. This metric is not very helpful in calculating the total complexity. It's about the cumulative total depth. That is, you need to add the depth of all "sections". For myself, I have defined a simple rule for calculating the total query depth - it is equal to the sum of the opening curly braces inside the entire query after substitution of all fragments (inline or spreads).

@Shane32 See #2119 . I thought about the fact that it is worth supplementing the documentation with the information that was discovered. Also, I think we should rename `ComplexityConfiguration.MaxDepth` to `ComplexityConfiguration.MaxTotalQueryDepth` so as not to mislead package clients.
![изображение](https://user-images.githubusercontent.com/21261007/108916990-1a876f00-7640-11eb-8457-0c6884e8269a.png)

And maybe rename something else. `Complexity` -> `TotalComplexity` ? It is better to do this before v4.

**Comment by sungam3r** [comment]
Also this thread https://github.com/graphql-dotnet/graphql-dotnet/pull/2119/files#r551552275

**Comment by Shane32** [comment]
@sungam3r What is the goal here for 4.0?

**Comment by sungam3r** [comment]
1. Update xml documentation. 
2. Probably change names.

**Comment by infogulch** [comment]
Perhaps adding the word "Sum" to the name of the "MaxDepth"/"MaxTotalQueryDepth" ComplexityConfiguration option would aid understanding: `MaxQueryDepthSumTotal` or some variation? Then again perhaps not.

**Comment by sungam3r** [comment]
I'm not a native speaker but `Total` and `Sum` in one word seem redundant.

**Comment by infogulch** [comment]
Yes, they are synonyms. However, both [`Sum`](https://www.merriam-webster.com/dictionary/sum) and [`Total`](https://www.merriam-webster.com/dictionary/total) have additional meanings which may be the cause of people getting tripped up on the name as demonstrated in this thread. [`Sum Total`](https://www.merriam-webster.com/dictionary/sum%20total) in comparison is more narrowly defined to only the case we have here, though there are [cogent arguments](https://nicothewriter.medium.com/10-phrases-you-should-cut-from-your-writing-25378f644b0a) against using this phrase for the reason you mentioned.

**Comment by Shane32** [comment]
The xml comments are extremely basic; indeed I wrote them myself, just so there was more than nothing. But I have not used the complexity analyzer, and I don't fully understand what the properties mean.

I suggest we add significantly more text to the xml comment, and then assess if the properties need to be renamed and what would be proper.

At first glance, I would think the names in the configuration should match the names in the response, so, for example only, `MaxTotalDepth` and `TotalDepth`.  Or `MaxDepth` and `Depth`.  Or `MaxTotalQueryDepth` and `TotalQueryDepth`.  The xml comment should make it very clear how these numbers are calculated.

**Comment by sungam3r** [comment]
My intuition tells me that this task should be postponed, because ComplexityAnalyzer can be changed a lot. Even if we rename properties now, it will not change anything fundamentally, and the comments can be added after the v4 release. I am not familiar with ComplexityAnalyzer so that with 100% confidence to write comments and documentation. I do not want to delay the v4 release because of this so I removed 4.0 milestone.

**Comment by Shane32** [comment]
I'm in the same boat.

**Comment by MahdiKarimipour** [comment]
Same here.

**Comment by ansulgoenka1** [comment]
Hi @sungam3r , is max depth still calculates total depth? I see that complexity configuration states max depth not total depth

"_.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = maxDepth };"

**Comment by sungam3r** [comment]
> is max depth still calculates total depth?

Yes. This is precisely the sum of all the depths in terms of AST, and not the maximum depth of the most nested branch of AST. I rewrote complexity analizer in #2863 . Honestly, I forgot about this issue. Regarding my https://github.com/graphql-dotnet/graphql-dotnet/issues/344#issuecomment-797060698 - now I better understand all this stuff to make proper changes in comments or/and rename properties. _Total_ word may be confusing. I mean both complexity and depth terms work as total numbers (see `three_depth_query_wide` test) but only one (TotalQueryDepth) has _total_ in its name. I think that I would remove _Total_ word from `TotalQueryDepth` property at all (and I feel that _Query_ word may be removed as well).

So I suggest this:

```cs
public class ComplexityResult
{
        public Dictionary<ASTNode, double> ComplexityMap { get; } = new Dictionary<ASTNode, double>();

        public double Complexity { get; set; }

        public int Depth { get; set; }
}
```

At the same time _Total_ meaning should be described in xml comments for both `Complexity` and `Depth` properties since they both accumulate total metrics. Also ping @Shane32  for comments.

**Comment by Shane32** [comment]
I guess I'm still confused.  I had though we specifically discussed both the naming and how MaxDepth should work, but I could be wrong.  You rewrote it @sungam3r so you would know.

It seems from a user's perspective, it's exceedling clear that MaxDepth should refer to the maximum depth (whether counted as AST nodes or otherwise) of the deepest AST node, counting through selected fragments.  Otherwise a client could just split up a query into fragment to work around the depth limitation.  And 'total depth' seems a contradiction in nature -- 'total nodes' makes sense, and 'maximum depth' makes sense, but I have no idea what 'total depth' would refer to.  All sibling selections should have the same depth.  You can't sum them up - it would be an illogical result.  For example:

```gql
{               # e.g. depth 1
  field1 {      # e.g. depth 2
    child1      # e.g. depth 3
    child2      # e.g. depth 3
    child3      # e.g. depth 3
  }
  field2        # e.g. depth 2
}
```

If you look at the above simple example, what could "total depth" possibly mean?  1+2+3+3+3+2 ??  Fairly meaningless from a complexity analysis perspective.  So as I see it, we should have "maximum depth" and "node count" or something, but don't use "maximum total depth".

I also don't know what the API does, but it seems to me that a complexity calculation would also involve assigning a cost to each node and calculating the cost based on the estimation of work required

```gql
{               # 0 cost
  field1 {      # 100 cost (because estimating retrieving 100 records)
    child1      # 0 cost (record has already been retrieved)
    child2      # 0 cost (record has already been retrieved)
    child3 {    # 1 cost (needs to retrieve child record)
      sub1       # 0 cost (record has already been retrieved)
    }
  }
  field2        # 10 cost (for whatever reason)
}
```

Then the complexity calculation calculates to 210 because `child3` needs to be multiplied by the 100 cost of `field1`, and the sum added to the `10` of `field2`.

GitHub does this but actually inspects the `first` and `last` properties passed to GraphQL Relay nodes to calculate the cost, rather than just using a simple estimate.

**Comment by sungam3r** [comment]
>  it's exceedling clear that MaxDepth should refer to the maximum depth (whether counted as AST nodes or otherwise) of the **deepest** AST node, counting through selected fragments.

Nope, no deepest, it's sum of all depths. Each field (as is or from fragment) counts - `TotalQueryDepth` incremented by 1 every time the `ComplexityVisitor` visits field.

> 'total nodes' makes sense, and 'maximum depth' makes sense, but I have no idea what 'total depth' would refer to. 

Just a problem of naming. I agree that 'total nodes' sounds more clear. Most likely Initial author considered the number of nodes in the context of the depth so...   We can make naming even simpler:
```cs
public class ComplexityResult
{
        public Dictionary<ASTNode, double> ComplexityMap { get; } = new Dictionary<ASTNode, double>();

        public double Complexity { get; set; }

        public int NodesCount { get; set; } <--- current TotalQueryDepth

        public int MaxDepth { get; set; } <---- new property, maximum depth of the deepest AST node, finally!
}
```

> but it seems to me that a complexity calculation would also involve assigning a cost to each node 

#298 / #1254

**Comment by A-Cheong** [comment]
> Nope, no deepest, it's sum of all depths. Each field (as is or from fragment) counts - TotalQueryDepth incremented by 1 every time the ComplexityVisitor visits field.

Bit late to the party but this along with additional reading made it clear the purpose of it and the naming proposal is more clear to me

Depth was confusing to me because I would associate it with Depth First Search and think of it in the context of the deepest AST node rather than the _amount_ of nodes

**Comment by Shane32** [comment]
Complexity analyzer has been rewritten for v8 in #3989 .  Depth calculation is logical and works the same whether or not fragments are in use.
