### ISSUE TITLE
Receiving nulls for a list of interfaces

### ISSUE THREAD

**Issue by justRu** [graphql-dotnet/graphql-dotnet#346]
When I have a field of type `ListGraphType<SomeInterface>` I receive a bunch of nulls in response.

How to reproduce: in StarWarsQuery remove all fields and add the following one:

```csharp
Field<ListGraphType<CharacterInterface>>("heroes", resolve: context => new[] { new Droid() { Name = "R2-D2" } });
```

For query
```graphql
query {
  heroes {
    name
  }
}
```

response will be
```graphql
{
  "data": {
    "heroes": [
      null
    ]
  }
}
```

When I add another field with `Droid` type it works again.

**Comment by joemcbride** [comment]
My guess is that this is due to there not being a `GraphType` registered that knows how to render the `Droid` type.  In this case, use the `RegisterType` or `RegisterTypes` method on `ISchema`.

**Comment by negue** [comment]
I had the same issue, then after using `RegisterType(s)` the null values are now `{}` even though I requested multiple properties on this type

**Comment by spicydonuts** [comment]
Also ran into this and had no idea what to do.. I was learning from the Star Wars example project and it does not use `AddPossibleType`: https://github.com/JacekKosciesza/StarWars/blob/master/StarWars.Api/Models/CharacterInterface.cs

Once I added that it started working.  It'd be better to throw something like `Type [type] doesn't appear to be a member of interface [interface].  Did you forget to add it as a possible type in the interface graph type definition?` instead of just returning null.  In my case it was in a list of non-nullable things, so instead of seeing what the problem was I was just getting an opaque `400 "TypeError"` on the GraphiQL client.

Also, why is `AddPossibleType` necessary when the implementing type already has `Interface<CharacterInterface>()`?

**Comment by joemcbride** [comment]
@negue @spicydonuts There are a few problems with this code.  You basically shouldn't ever be using the `AddPossibleType` directly.  That perhaps should be an internal method.

There are basically two ways to create a Schema.  An "instanced" based `Schema` where you manually `new` up all of the `GraphType`s yourself, and a "type" based `Schema` that may or may not use Dependency Injection.  The sample that @negue posted is mixing the two and its causing issues.

When the Schema is built, it looks at the "root" types (Query, Mutation, Subscription) and gathers all of the `GraphType`s they expose.  Often when you are working with an `interface` type, the concrete types are not exposed on the root types (or any of their children).  Since those concrete types are never exposed in the type graph, the `Schema` doesn't know they exist.  This is what the `RegisterType` on the `Schema` is for.

So yes, you are adding `Interface<CharacterInterface>` to say `DroidType`, though `DroidType` isn't in the type graph itself, only the `CharacterInterface` is.

Sort of related, see the docs for [`IsTypeOf`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#istypeof) and [`ResolveType`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#resolvetype) for how interface types figure out what concrete type to use.

**Comment by joemcbride** [comment]
@negue I believe this should fix that issue.

```diff
public class TestSchema : Schema
{
    public TestSchema()
    {
        Query = new TestQuery();

-        RegisterTypes(new MyClass1GraphType(), new MyClass2GraphType());
+        RegisterType<MyClass1GraphType>();
+        RegisterType<MyClass2GraphType>();
    }
}

public class TestQuery : ObjectGraphType
{
    public TestQuery()
    {
        Field<ListGraphType<InterfaceType>>("entries", resolve: ctx => new IMyType[]{
            new MyClass1(),
            new MyClass2()
        });
    }
}

public interface IMyType
{
    int Id { get; }
}


public class InterfaceType : InterfaceGraphType<IMyType>
{
    public InterfaceType()
    {
        Field(x => x.Id);

-        AddPossibleType(new MyClass1GraphType());
-        AddPossibleType(new MyClass2GraphType());
    }
}

public class MyClass1 : IMyType
{
    public int Id => 1;

    public string StringInClass1 => "Class 1";
}


public class MyClass2 : IMyType
{
    public int Id => 2;

    public string StringInClass2 => "Class 2";
}

public class MyClass1GraphType : ObjectGraphType<MyClass1>
{
    public MyClass1GraphType()
    {
        Field(x => x.Id);
        Field(x => x.StringInClass1);

        Interface<InterfaceGraphType>();
    }
}


public class MyClass2GraphType : ObjectGraphType<MyClass2>
{
    public MyClass2GraphType()
    {
        Field(x => x.Id);
        Field(x => x.StringInClass2);

        Interface<InterfaceGraphType>();
    }
}

var query = @"{
    entries {
      id
    }
}";

var executer = new DocumentExecuter();
var result = await executer.ExecuteAsync(_ =>
{
    _.Schema = new TestSchema();
    _.Query = query;
});
```

**Comment by spicydonuts** [comment]
> When the Schema is built, it looks at the "root" types (Query, Mutation, Subscription) and gathers all of the GraphTypes they expose. Often when you are working with an interface type, the concrete types are not exposed on the root types (or any of their children). Since those concrete types are never exposed in the type graph, the Schema doesn't know they exist. This is what the RegisterType on the Schema is for.

Ah, that makes sense!  Thanks for the explanation.
I removed the hacks and added `RegisterTypes` to my root schema:
```csharp
    public StorefrontSchema(Func<Type, GraphType> resolveType)
        : base(resolveType)
    {
      Query = (StorefrontQuery)resolveType(typeof(StorefrontQuery));

      RegisterTypes(
        resolveType(typeof(StorefrontDealInterface)),
        resolveType(typeof(StorefrontDealLiveType))
      );
    }
```
Seems to work now 👍

**Comment by joemcbride** [comment]
@spicydonuts If you are using the type-based API for building your schema, you don't have to use the instance-based API of `RegisterTypes`.  The `Schema` will call the `resolveType` for you.  https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L163

```diff
public StorefrontSchema(Func<Type, GraphType> resolveType)
        : base(resolveType)
{
  Query = (StorefrontQuery)resolveType(typeof(StorefrontQuery));

-  RegisterTypes(
-    resolveType(typeof(StorefrontDealInterface)),
-    resolveType(typeof(StorefrontDealLiveType))
-  );
+   RegisterType<StorefrontDealInterface>();
+   RegisterType<StorefrontDealLiveType>();
+   // or
+   RegisterTypes(new[]{ typeof(StorefrontDealInterface), typeof(StorefrontDealLiveType) });
}
```

**Comment by justRu** [comment]
Sorry, I haven't updated this issue earlier. `RegisterType<>` worked for me. Thanks!

> When the Schema is built, it looks at the "root" types (Query, Mutation, Subscription) and gathers all of the GraphTypes they expose. Often when you are working with an interface type, the concrete types are not exposed on the root types (or any of their children). Since those concrete types are never exposed in the type graph, the Schema doesn't know they exist. This is what the RegisterType on the Schema is for.

Can you add this to the docs? It would be very helpful. Or is it already there?

**Comment by joemcbride** [comment]
@justRu Its not, I'm adding it to the interface section.

**Comment by joemcbride** [comment]
In the docs!

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs/getting-started.md#registertype

**Comment by negue** [comment]
@joemcbride no it doesn't fix that. Like I already wrote before:

- If I remove:
   ```patch
   -        AddPossibleType(new MyClass1GraphType());
   -        AddPossibleType(new MyClass2GraphType());
   ```

	I get this result:
	` {"data":{"entries":[null,null]}} `

- If I leave the `AddPossibleType` calls I get:
	`{"data":{"entries":[{},{}]}}`

None of those are right!

What I expect to get is:
`{"data":{"entries":[{"id": 1},{"id": 2}]}}`

**Comment by joemcbride** [comment]
@negue The other bug in your code:

```diff
-Interface<InterfaceGraphType>();
+Interface<InterfaceType>();
```

**Comment by negue** [comment]
@joemcbride  oh wow, I should've used better class names, thanks! Now that the example works I can test it on the real project. Thanks!!

**Comment by spicydonuts** [comment]
> ```csharp
> RegisterType<StorefrontDealInterface>();
> RegisterType<StorefrontDealLiveType>();
> ```

@joemcbride Ohh, much better.  Thanks!
