### ISSUE TITLE
Using field middleware breaks subscriptions

### ISSUE THREAD

**Issue by georgiosd** [graphql-dotnet/graphql-dotnet#3463]
## Description

Adding field middleware, breaks the resolution of streams (subscriptions). 

When field middleware are in place, it seems that the runtime tries to then use `Resolve*` instead of `ResolveStream*` and fails.

### Steps to reproduce

1. Configure a schema with a subscription
2. Apply at least one field middleware with `return next(context);`
3. Query the subscription

### Expected result

The subscription should return results.

### Actual result

```
System.InvalidOperationException: 'Expected to find property or method '<subscription field name>' on type '<subscription field type>' but it does not exist.'
```

### Environment

I have `7.*` in my `.csproj` so using the latest version. .NET 6.0.

**Comment by georgiosd** [comment]
The bug seems to be in `ApplyMiddleware` which initializes `Resolver` with `NameFieldResolver.Instance` if null, not taking into account when `StreamResolver` is set. 

What is the right fix here though? Happy to submit a PR.

**Comment by georgiosd** [comment]
A workaround is to imitiate the `SourceFieldResolver` and manually provide:

```
.Resolve(context => context.Source)
```

**Comment by Shane32** [comment]
Field middleware just loops through each field resolver and applies the middleware to the FieldResolver as the field is being built. It shouldn’t affect the SourceStreamResolver at all.  At runtime, the executer and execution strategy do not know about the presence of middleware. 

Subscriptions initially execute the SourceStreamResolver in order to get the IObservable. No results are returned initially, and no field resolvers are executed. As each event occurs, execution takes place again for the same subscription field with the event data as the source. So the field resolver for the subscription field must be (generally) `context => context.Source` in addition to having the SourceStreamResolver set. Middleware will change this of course but that shouldn’t be a problem so long as the returned value is the same type. Like for Apollo tracing, it’s just storing some tracing data to Metrics. 

If I recall correctly, we may have recently changed something to assume a field resolver of `context => context.Source` for subscription fields. Perhaps when applying middleware, it does not make this assumption and instead uses the default NameFieldResolver used elsewhere. This makes sense and fits with your symptoms and workaround.  I’ll have to check when I’m at a PC. 

If you want to write a PR, look at the middleware builder and find the `?? NameFieldResolver.Instance` and change it to be conditional upon the SourceStreamResolver being null. Otherwise it should use the SourceFieldResolver. I’d also check that this same assumption is made during execution. Probably have to check ExecutionStrategy for that.

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionStrategy.cs#L456..L457

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs#L31..L39

**Comment by Shane32** [comment]
Looks like it may be hard to fix there. Maybe easier to, when applying middleware, first check all root subscription fields and set the SourceStreamResolver for any fields without a FieldResolver set. Then let the middleware apply normally.

**Comment by Shane32** [comment]
The fix probably needs to be placed immediately before this line of code:

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Schema.cs#L448

**Comment by Shane32** [comment]
lol

**Comment by georgiosd** [comment]
Thank you guys - sorry I never submitted a PR, the last few months have been crazy.
