### ISSUE TITLE
Query is too complex to execute. The field with the highest complexity is: GraphQLParser.AST.GraphQLFragmentSpreadWithLocation

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#3482]
Upgrading from 3.3 to 7.2.2, I'm getting this error when the introspection query runs from the GraphQL playground.

Not finding any info or direction to solve this one.

I did follow this:
https://github.com/graphql-dotnet/graphql-dotnet/pull/3172

And change the code for Complexity on ExecuteAsync
_.ComplexityConfiguration = new ComplexityConfiguration { MaxDepth = 15 }; 

Over to a validation rule"
new ComplexityValidationRule(new ComplexityConfiguration()
                {
					MaxComplexity = 15 //Current Min. is 15 due to "IntrospectionQuery"
                })

I even tried upping it to 25, but that didn't make any difference.

Thanks for the help! 

```
{
	"errors": [{
		"message": "Query is too complex to execute. The field with the highest complexity is: GraphQLParser.AST.GraphQLFragmentSpreadWithLocation",
		"extensions": {
			"code": "COMPLEXITY",
			"codes": ["COMPLEXITY"]
		}
	}]
}
```

**Comment by sungam3r** [comment]
15 is toooo little :) @Shane32 I suggest to add calculated complexity into error message.

**Comment by Shane32** [comment]
With the changes to GraphQL Parser v7/v8 there is much more depth required than previously - around double most likely.

I think we need to consider the error message from a security aspect also.  Perhaps it should not reveal to the caller the computed/highest complexity allowed.  I certainly would not want my production sites telling anonymous callers exactly how much they can burden my server.  Rather, I would want that information logged server-side if there was an issue.  On the other hand, perhaps authenticated users should know these values.

And personally, I think the entire complexity analyzer needs to be scrapped and rewritten, with features such as:
- per user limits
- per IP limits
- time-based rate limits
- GraphQL Relay-aware for connection fields
- Being able to programmatically set the 'work factor' for fields, and expected number of children if appropriate

See GitHub's API limiter for a good sample. https://docs.github.com/en/graphql/overview/resource-limitations

**Comment by sungam3r** [comment]
> The field with the highest complexity is: GraphQLParser.AST.GraphQLFragmentSpreadWithLocation"

🤦‍♂️

**Comment by Shane32** [comment]
Perhaps the burden is on the developer to implement per user/ip/time limits, but certainly we should allow some type of hooks so that on a per-connection basis, the available complexity factor [for the user/ip] can be retrieved, and once the query is run, it is deducted from the available amount.

**Comment by sungam3r** [comment]
> I think we need to consider the error message from a security aspect also. 

`ErrorInfoProvider` to tghe rescue!

**Comment by OpenSpacesAndPlaces** [comment]
For Color:
On 3.3 - 15 worked. 
On 7.2.2 - I tried 10000 and it failed.

I gave up and used Int32.MaxValue for now :)

My original thinking was no real query should be more complicated than the introspection query.
But now I'm thinking in an enhanced version, it would be good to have more control over introspection vs. regular queries.

**Comment by Shane32** [comment]
Clearly something is not working correctly.  If you can provide a copy of the query that failed, we can test it.  No need for the schema definitions.

**Comment by OpenSpacesAndPlaces** [comment]
{
	"operationName": "IntrospectionQuery",
	"variables": {},
	"query": "query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n    }\n    mutationType {\n      name\n    }\n    subscriptionType {\n      name\n    }\n    types {\n      ...FullType\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n      }\n    }\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n    }\n    type {\n      ...TypeRef\n    }\n    isDeprecated\n    deprecationReason\n  }\n  inputFields {\n    ...InputValue\n  }\n  interfaces {\n    ...TypeRef\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n  }\n  possibleTypes {\n    ...TypeRef\n  }\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n  }\n  defaultValue\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"
}

**Comment by Shane32** [comment]
FYI, the computed complexity factor was 73706 and depth of 59.

**Comment by Shane32** [comment]
(right or wrong)

**Comment by Shane32** [comment]
The complexity code seems real stupid.  It's got code like "if zero impact then use default" right after it's got ??= default.  So you can't set a field to a complexity of 0.  Besides that, setting the complexity for __schema doesn't work at all and is completely ignored.

My head hurts every time i look at the complexity analyzer, which is why i have not done so.

**Comment by zspasojevic** [comment]
Anyone got a workaround for this? I'm having the same issue after moving from 4.8.0 to 7.6.0, our IntrospectionQuery sent from the gateway when fetching the backend schemas is now failing due to the 73706 calclated complexity. It never failed before and our maxComplexity was always set to 1200.

`GraphQL.Validation.Errors.Custom.ComplexityError: Query is too complex to execute. Complexity is 73706, maximum allowed on this endpoint is 1200. The field with the highest complexity is 'FullType' with value 61388.\r\n" +
      '   at GraphQL.Validation.Complexity.ComplexityAnalyzer.Validate(GraphQLDocument document, ComplexityConfiguration complexityParameters, ISchema schema) in /_/src/GraphQL/Validation/Complexity/ComplexityAnalyzer.cs:line 25\r\n' +
      '   at GraphQL.Validation.Rules.Custom.ComplexityValidationRule.PostponeComplexityValidationVisitor.LeaveAsync(ASTNode node, ValidationContext context) in /_/src/GraphQL/Validation/Rules.Custom/ComplexityValidationRule.cs:line 73'`

**Comment by Shane32** [comment]
@zspasojevic  How do you think it should work?  What do you want it to do?

**Comment by zspasojevic** [comment]
To sum up, we have a bunch of .NET backend services and we're using node.js gateway to fetch/load all BE schemas and stich/merge them into one...then UI talks to this one endpoint/schema. Schema loading from BE is done using the same introspection query mentioned in this topic above. 

While BE was on graphql v4 and bellow, using the same complexity configuration as now, none of the queries (including the introspection) was above 1000 in complexity. This is the config:

![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/43961181/812fada6-2f2d-4da0-ad23-412b6b37763f)

Once it goes beyond 1200, we were getting 400 codes as expected and increased it where needed meaning that the analyzer was working fine.

Now after we've updated to 7.6.0, that same Introspection query with same complexity config says that it has 73706 complexity and fails the default complexity validation rule. So there were obviously some major changes in how the complexity is calculated, at least for the introspection.

So what I'm looking at is to keep using validating the max complexity, keep using the introspection query but without having to increase the configuration 70 times above the default. It doesn't make any sense to allow that kind of complexity in a system where the most complex query/mutation is around 1500.

**Comment by Shane32** [comment]
The complexity is indeed calculated completely differently than it was in the past (see #2863), and I do not find it to be useful at this time.  I suggest copying the complexity analyzer from an earlier version and using it in your codebase.  I can assist with that endeavor.

It would be very helpful if you can assist me to write specifications for how the complexity analyzer should work for v8.  Some of my ideas:
- Should be able to anticipate estimated number of child nodes for a list programmatically, such as using the `first` or `last` argument from connection types, or estimate based on typical values for that field
- Should be able to estimate execution/database time/complexity and also response complexity (sheer number of fields or depth), such that complex database queries may be rejected, and simple-but-verbose queries may also be rejected
- Should be able to implement per-IP and per-user throttling if desired (supported but not necessarily built-in)
- Should be able to exclude introspection queries (which are typically very verbose)

We could look at GitHub's throttling as a comparison also: https://docs.github.com/en/graphql/overview/resource-limitations

Once a set of specifications are written, it would not be hard to implement the necessary changes.

**Comment by Shane32** [comment]
Note: the complexity of an introspection query is known to be approximately 73706 currently, even if it's stupid.  See https://github.com/graphql-dotnet/graphql-dotnet/pull/3485/files

**Comment by Shane32** [comment]
> I suggest copying the complexity analyzer from an earlier version and using it in your codebase. I can assist with that endeavor.

Correction: this won't work because the complexity analyzer was rewritten when the AST was dumped from GraphQL.NET in favor of directly using the AST classes from GraphQLParser.  Best we can do is figure out how to modify the existing analyzer to be more effective for your needs.  For example, perhaps we can zero out the impact of the introspection fields.

**Comment by zspasojevic** [comment]
@Shane32 Thanks for the proposals. I've ended up implementing a custom complexity rule to not validate complexity on the introspection query and keep doing it for all the other queries.

As for the specs on complexity logic, I'd say your bullet points are on track. I'd just add for the queries like introspection, if they are not doing any DB requests / not fetching any data, I don't think they should be considered too complex.

**Comment by A-Cheong** [comment]
I think what's contributing to such a disparity in complexity levels between the versions is:

- no `fieldImpact` value means by default it fallsback to `AvgImpact`
- `AvgImpact` is set to `2.0` and throws an error for `1.0` - this leads each child node to essentially double in complexity


``` csharp
var fieldImpact = _visitor?.GetFieldDef()?.GetComplexityImpact() ?? context.AvgImpact;
var zeroImpact = fieldImpact == 0;
if (context.CurrentSubSelectionImpact == null)
{
    context.CurrentSubSelectionImpact = zeroImpact ? context.AvgImpact : fieldImpact;
}
```

```
var complexity = (context.CurrentSubSelectionImpact ?? context.AvgImpact) / context.AvgImpact * fragmentComplexity.Complexity;
```

From my understanding, there are a few assumptions that contradict this

- complexity of a query is trying to estimate the amount of data from the output based on the input
- `fieldImpact` is used when you're aware of how many results will come back from a specific (complex) **field** (i.e. an array of items) which is different to a basic field like `name`
  - if you don't know the specific number, you can average it and set that as the `fieldImpact`
- `avgImpact` was set to 2.0 in the old code, but I'm not sure of the previous logic associated with it. The new implementation calculates complexity by doubling the `avgImapact` with each nesting - it doesn't make sense that a child node doubles in complexity just by being a child
  - my reasoning here is that since we're _estimating_ the potential output, stamping a static x2 figure on every child is creating a "fake" complexity value because every solution is different
  - a deeply nested query (~10) with one property each can hit 3000 complexity 
 - `avgImpact` sounds like the job of `fieldImpact` - where we as the consumers are able to better guess the estimated **output** of a field and a child shouldn't have an arbitrary complexity by being a child but by us knowing the output of that child and thus complexity

**Comment by Shane32** [comment]
Complexity analyzer rewrite for v8:
- #3989

**Comment by Shane32** [comment]
> With the changes to GraphQL Parser v7/v8 there is much more depth required than previously - around double most likely.
> 
> I think we need to consider the error message from a security aspect also. Perhaps it should not reveal to the caller the computed/highest complexity allowed. I certainly would not want my production sites telling anonymous callers exactly how much they can burden my server. Rather, I would want that information logged server-side if there was an issue. On the other hand, perhaps authenticated users should know these values.
> 
> And personally, I think the entire complexity analyzer needs to be scrapped and rewritten, with features such as:
> 
> * per user limits
> * per IP limits
> * time-based rate limits
> * GraphQL Relay-aware for connection fields
> * Being able to programmatically set the 'work factor' for fields, and expected number of children if appropriate
> 
> See GitHub's API limiter for a good sample. https://docs.github.com/en/graphql/overview/resource-limitations

Complexity analyzer has been rewritten for v8 in #3989 with capability for all these features.
