### ISSUE TITLE
Nullable DateGraphType Argument Type Mapping Failing?

### ISSUE THREAD

**Issue by Presipope** [graphql-dotnet/graphql-dotnet#3507]
## Description

To preface this, I recently upgraded my solution from GraphQL v4 -> v7. This issue did not occur for me on v4. 

When using the type GraphQL.Types.DateGraphType as an argument and also passing nullable as true I get the following error.

The GraphQL type for argument 'DateMutations.updateDate.value' could not be derived implicitly. Could not find type mapping from CLR type 'GraphQL.Types.DateGraphType' to GraphType. Did you forget to register the type mapping with the 'ISchema.RegisterTypeMapping'?

### Steps to reproduce

If I write my example field like so I get the error:

```
            Field<BooleanGraphType>("updateDate")
                .Argument<DateGraphType>("newDate", true)
                .Argument<int>("id")
                .Resolve()
                .WithScope()
                .WithService<IMediator>()
                .ResolveAsync(UpdateDateResolver);
```

If I remove the nullable as true the schema generates successfully. 

```
            Field<BooleanGraphType>("updateDate")
                .Argument<DateGraphType>("newDate")
                .Argument<int>("id")
                .Resolve()
                .WithScope()
                .WithService<IMediator>()
                .ResolveAsync(UpdateDateResolver);
```

### Environment

.NET 7
GraphQL 7.2.2
GraphQL.DataLoader 7.2.2
GraphQL.MicrosoftDI 7.2.2
GraphQL.NewtonsoftJson 7.2.2
GraphQL.Server.All 7.2.0
GraphQL.Server.Transports.AspNetCore 7.2
GraphQL.Server.Ui.Playground 7.2.0

**Comment by Shane32** [comment]
In GraphQL.NET 7, you can define an argument two ways:

`.Argument<TGraphType>(string name)`

or

`.Argument<TClrType>(string name, bool nullable = false)`

When you attempted `.Argument<DateGraphType>("newDate", true)` the compiler assumed the second syntax which is incorrect since `DateGraphType` is a graph type, not a CLR type.  We should add a initialization-time check for this and throw a descriptive error.

You can manually specify the `DateGraphType` as nullable or not via:

```cs
.Argument<DateGraphType>("newDate")  // nullable
.Argument<NonNullGraphType<DateGraphType>>("newDate") // non-null
```

Another option is to register all `DateTime` CLR types to use `DateGraphType` via `RegisterTypeMapping` in the schema constructor, and then use `.Argument<DateTime>("newDate", true).  Another option for .NET 6 is to use the `DateOnly` CLR type in a similar fashion which by default maps to the `DateGraphType`.

**Comment by Presipope** [comment]
Ahhh yes I was definitely overthinking it with the addition of the CLR types. 

That makes perfect sense. It's a little strange to wrap your head around Argument<TGraphType> defaults in as nullable but Argument<ClrType> defaults as not nullable but I understand why it is that way given the addition of CLR types in the argument generics. 

Thanks so much for the quick response @Shane32 I really appreciate it. Fun how you can overlook such tiny/obvious things in code :)

**Comment by Shane32** [comment]
No problem.  Just FYI, the reason nullable=false as default with CLR types is because GraphQL.NET has long had a syntax for field members of `Field(x => x.Name, true)` which has always defaulted nullable=false.  So when we recently added additional syntax for arguments, we copied the same convention so it was familiar to users.

In my own code, I attempt to discontinue direct use of graph types through my graph definitions, and instead rely on CLR type mappings.  This is not always possible -- for example when specifying an ID graph type for a string field.  In these cases I typically add an extension method for the same end goal.

**Comment by Presipope** [comment]
That all makes sense!

Great idea on extensions for some of those pesky types and I've already migrated a decent amount of our code base to using the CLR types. I almost jumped out of my chair when I read the migration notes and saw the CLR type support. :) Keep up the great work!

**Comment by Shane32** [comment]
I'm going to re-open this issue until the error message is added to the codebase.  Thanks!

**Comment by sungam3r** [comment]
>  We should add a initialization-time check for this and throw a descriptive error.

Damn! I wanted to do this at least 2 times and forgot. I am sure that I will forget for the third time.

**Comment by sungam3r** [comment]
🤔 The best thing to not forget - fix it now. I'll try.

**Comment by Shane32** [comment]
I feel like we did already do this for `Field<TClrType>(...)` ... I think ????  Maybe not ????

**Comment by sungam3r** [comment]
Nope. Look - there are different `Field<T>/Argument<T>` APIs that all calls `GetGraphTypeFromType` to build `GraphType`. Now even "wrong" type is eventually "successfully" built by `  graphType = (mode == TypeMappingMode.OutputType ? typeof(GraphQLClrOutputTypeReference<>) : typeof(GraphQLClrInputTypeReference<>)).MakeGenericType(type);` line. In fact exception occurs at the schema initialization time a bit later when `SchemaType` searches needed GraphType. I changed error message for more friendly one + (as a bonus) added explicit check into `Schema.RegisterTypeMapping`.

Note that we _can_ add additional check to `GetGraphTypeFromType` method itself to get error even earlier but I doubt to do that. I'm not sure that `GetGraphTypeFromType` should take only CLR type as `this` first argument.

**Comment by sungam3r** [comment]
Imagine an awkward but since probable situation when Schema represents a sort of view on top of other GraphTypes exposing their properties so `MyDataGraphType` is mapped to `SomeOtherViewGraphType`. I mean when there are graph types that act as CLR types.
