### ISSUE TITLE
"Schema is not configured for queries" on metadata query in mutation-only schema

### ISSUE THREAD

**Issue by floyd-may** [graphql-dotnet/graphql-dotnet#3537]
## Description

A metadata query is failing on a schema that only has mutations configured.

### Environment

GraphQL 7.2.2

### Additional info

This, I believe, is wrong, as it erroneously throws on metadata-only queries.

https://github.com/graphql-dotnet/graphql-dotnet/blob/fe881cd75d6ee13866733bda14cf4b708b5dbc4f/src/GraphQL/Execution/ExecutionStrategy.cs#L52-L58

**Comment by Shane32** [comment]
As shown in the note you referenced, a schema that meets GraphQL specifications must have a query type defined on it.  Types must contain at least one field.  GraphQL.NET only allows schemas without query types because this makes for easier testing.  We may revisit this policy in the future and throw an exception during schema initialization.  For now, define a query type with at least one field to meet spec and allow introspection queries to execute successfully.

Ref https://spec.graphql.org/October2021/#sec-Root-Operation-Types :

> The query root operation type must be provided and must be an Object type.

Ref https://spec.graphql.org/October2021/#sec-Objects :

> An Object type must define one or more fields.

**Comment by Shane32** [comment]
@sungam3r We should consider a breaking change in v8 to enforce this schema validation rule.  For internal GraphQL.NET testing, we can implement a global option to disable this schema check.  The global option could be `public` or `internal`.

**Comment by sungam3r** [comment]
I'm fine with making it required "as spec says" in v8. Also I'm fine with global option like `GlobalSwitches.RequireRootQueryType { get; set; } = true;`. Regarding our codebase - I would not set this option to `false` to bypass schema validation check. Instead I would change all tests to meet the spec. Also I would mark this option as `[Obsolete("The query root operation type must be provided and must be an Object type. See https://spec.graphql.org/October2021/#sec-Root-Operation-Types")]` immediately in v8.
