### ISSUE TITLE
ToAST is not called on custom InputObjectGraphType

### ISSUE THREAD

**Issue by justinmchase** [graphql-dotnet/graphql-dotnet#3545]
## Summary

We have a custom InputGraphType called `RequiredValueInputGraphType` which is an object with a value field which is not nullable. When we are applying validation to a field of this type we want to be able to cast and get the inner value for validation. We have overriden the `ToAST` function but it seems to never be called. I can see the constuctor being called but in the actual NodeVisitor the field type is actually an `GraphQLObjectValue` not my custom `RequiredGraphQLObjectValue`.

How can I create a custom type which can be handled in validation rules?

#### custom input graph type
```cs
public class RequiredValueInputGraphType<TValue> : InputObjectGraphType<RequiredValue<TValue>> where TValue : notnull {
  public RequiredValueIGT()
  {
    // this is called...
    this.Name = $"RequiredValue_{typeof(TValue).Name}";
    _ = this.Field(_ => _.Value, nullable: false);
  }

  public override GraphQLValue ToAST(object? value)
  {
    // this is not called...
    return value;
  }
}

public record RequiredValue<TValue>(TValue Value) where TValue : notnull;
```

#### registering the field
```cs
_ = this.Field(_ => _.TaxId, type: typeof(RequiredValueInputGraphType<string>))
     .ApplyMinMaxStringLengthDirective(new(9, 9));
```

#### visiting the field in the validator
```cs
private static readonly INodeVisitor nodeVisitor = new NodeVisitors(
      new MatchingNodeVisitor<GraphQLArgument>((arg, context) => CheckLength(arg, arg.Value, context.TypeInfo.GetArgument(), context)),
      new MatchingNodeVisitor<GraphQLObjectField>((field, context) =>
      {
        if (context.TypeInfo.GetInputType(1)?.GetNamedType() is IInputObjectGraphType input)
        {
          if (value is RequiredGraphQLObjectValue obj)
          {
            // expected to be true but is null...
          }
        }
      })
  );
```

So in the MinMaxStringLengthDirective, the field type is not the RequiredValue<T> we are expecting, how can we make sure its  the right type in the input graph?

### Environment (if relevant)

```xml
<PackageReference Include="GraphQL.Server.All" Version="6.0.0" />
```

**Comment by Shane32** [comment]
What happens is this:

1. Document arrives at the server as a string

2. The GraphQLParser project parses this into a well-defined set of objects, starting with a root object of GraphQLDocument.  The parser does not perform any interpretation of the content, but merely parses it.  Any text that does not meet parsing specifications causes a failure.  No validation is performed at this point.  So `{ abcd }` would be parsed even if `abcd` were not a field, because it is structurally intact.  But `{ ab-cd }` would fail because `ab-cd` is an invalid GraphQL name, and `{ abcd` would fail because it is missing the closing brace.

3. All configured validation rules in the form of `IValidationRule` are run.  Validation rules may perform any analysis on the document it wishes.  However, if one were to do so at this point, there would be no context for any given node of the document as it relates to the schema.  But it is useful for things like verifying that the user is authorized to access the schema, or verifying that a mutation does not execute during a GET request.  The validation rules may also return `INodeVisitor` instances and `IVariableVisitor` instances.

4. All `INodeVisitor` instances are run together against the document.  By accessing `ValidationContext.TypeInfo` within these node visitors, contextual information about the field or type (e.g. which type within the schema that it represents) can be determined.  Most schema validation code exists as a `INodeVisitor` instances.  It is important to realize that the document may be invalid, like a self-referencing fragment, or an invalid type or field name, but are still processed by each `INodeVisitor`.  Also, variables have not been read at this point, so any argument values that reference an argument must be manually parsed from the `ValidationContext.Variables` property.  The latter point can be extremely complex in the event you are attempting to validate a value contained within another input object.

5. All variables are read from the document and ran through any configured `IVariableVisitor` instances.

6. At this point, if no errors have been reported, the document is executed.

If this sounds complex, it is; it's a real pain to implement any type of validation rule that examines argument values.  One specific problem is that validation rules also run prior to parsing by a scalar.  So for example, if you wanted a validation rule that enforces a minimum or maximum date on a DateGraphType, you would need to be sure to pass the raw text from the literal or variable through the DateGraphType's ParseLiteral or ParseValue function to validate it.

Our best sample is contained within the `InputFieldsAndArgumentsOfCorrectLength` sample validation rule.  I recommend you review that as a template.

In version 8, I hope to make this much easier.  The plan is to (a) validate the basic syntax of the document first, then (b) if no errors, parse field arguments (pulling from variables if necessary), and (c) if no errors, run custom validation rules.  Then the custom validation rules would have access to the parsed argument values already.  This code is not yet complete but has been started.

An easy option for prior versions is to implement a custom scalar which fails to parse invalid values.  This only works in certain situations, like validating that an `ID` graph type contains a value that can be converted to an `int`.

If you are validating input objects, you can override `ParseDictionary`, and throw an exception when the generated value does not meet the validation criteria.  However, this only runs (a) when calling `GetArgument` or (b) when the object is a variable or inside a variable.  In version 8 this will be called during validation and so errors would be returned to the caller before execution begins regardless of whether they are in a literal or variable.

As for `ToAST`, this is only used when printing a schema which contains a input object with a field containing a default value.  Then `ToAST` is called to convert the default value to an AST which can be printed.  But unless using `SchemaPrinter`, `ToAST` is never called.

Creating a custom `RequiredGraphQLObjectValue` class is not beneficial unless you rewrite the entire parsing library to use it.

**Comment by Shane32** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs

**Comment by justinmchase** [comment]
Thank you for the detailed response, that example you shared is super close to our code to the point where I think the team probably relied on it to write our rule :) We were able to use some of this info to get pointed in the right direction, the below is our solution for anyone in the future landing on this issue..

The thing we're trying to solve is that here on this line:
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Validation/Rules.Custom/InputFieldsAndArgumentsOfCorrectLength.cs#L81

So in addition to just `GraphQLStringValue` we have essentially an input type called `RequiredStringGraphType`, which is just an object with `{ value: String! }`. When setting a field during an update mutation if the object itself is `null` then the field is not changed, but if its not `null` then you must specify a non-null string (you can't set the field in the database to `null`). As opposed to `OptionalStringGraphType`, which is `{ value: String }`.

So then in this validator on line 81 we are basically getting back an `ObjectGraphType` and attempting to determine which "Type" it is, is it a required or an optional, or some other object?

I was able to solve this by adding another parameter to the CheckLength function `IGraphType? resolvedType` then in the visitor adding something like:

```cs
var f = input.GetField(field.Name);
var resolvedType = f?.ResolvedType;
CheckLength(field, field.Value, f, resolvedType, context);
```

Then we are updating the check like so:
```cs
            else if (value is GraphQLObjectValue obj && resolvedType is RequiredStringGraphType)
```
