### ISSUE TITLE
[Block request when call graphql to mu application]

### ISSUE THREAD

**Issue by vansangnguyen1998** [graphql-dotnet/graphql-dotnet#3587]
## Summary
I have implementat graphql dotnet version **4.7.1** and dotnet 6.0 with middlewave:
```c#
var result = await _executor.ExecuteAsync(doc =>
{
      doc.Schema = schema;
      doc.ValidationRules = rules;
      if (request.Query != null)
      {
          doc.Query = request.Query;
      }
      if (request.Variables.ToInputs() != null)
      {
          doc.Inputs = request.Variables.ToInputs();
      }
      doc.UserContext = new GraphQLUserContext() { User = httpContext.User, Info = account };
      doc.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
      doc.EnableMetrics = false;
 }).ConfigureAwait(false);
```
when I stress test my application, my application block request from line  await _executor.ExecuteAsync(), I guest because i have alot of response type and input type. 
When request call and my server have top init all response type and input type per a request. it make my application block request.
## Question.
Can you help me solve it, or give my logic have impact to my application?

Thank alot. 
Best regrads,
Sang

**Comment by sungam3r** [comment]
You may restrict executing queries with limited complexity, see https://graphql-dotnet.github.io/docs/getting-started/malicious-queries.

**Comment by vansangnguyen1998** [comment]
> You may restrict executing queries with limited complexity, see https://graphql-dotnet.github.io/docs/getting-started/malicious-queries.

Your mention about the depth query in graphql, but my issue is about the logic init alot of response type and inputtype when call request to server, it make my application is slow and block orther request call to server?

**Comment by sungam3r** [comment]
> about the logic init

What logic? Your code? We can do nothing with your code. At least without comprehensive example.

**Comment by vansangnguyen1998** [comment]
First of all, I sorry about the confuse and didn't clear, @sungam3r 
## MyCode
I have middleware to call graphql.
```

public async Task InvokeAsync(HttpContext httpContext, ISchema schema, IServiceProvider serviceProvider, IEnumerable<IValidationRule> rules, IConfiguration configuration)
        {

            var appToken = httpContext.Request.Headers["x-app-token"].FirstOrDefault();
            var requiredAccessToken = _configuration.GetValue<bool>("FeatureToggles:IsAuthAppToken");

            httpContext.User = new ClaimsPrincipal();
            if (appToken != null)
            {
                httpContext.User.AddIdentity(new ClaimsIdentity(new[] { new Claim("AppToken", appToken) }));
            }
            var token = httpContext.Request.Headers["Authorization"].FirstOrDefault()?.Split(" ").Last();
            var account = new Account();
            if (token != null)
            {
                account = attachUserToContext(httpContext, token, configuration);
            }
            if (httpContext.Request.Path.StartsWithSegments(_options.EndPoint) && string.Equals(httpContext.Request.Method, "POST", StringComparison.OrdinalIgnoreCase))
            {
                try
                {
                    var cancelation = CancellationToken.None;
                    var start = DateTime.UtcNow;
                    var request = await JsonSerializer.DeserializeAsync<GraphQLRequest>(
                                                httpContext.Request.Body,
                                                new JsonSerializerOptions
                                                {
                                                    PropertyNameCaseInsensitive = true
                                                });
// When i add StopWatch in this line and Console.Write(), i have value is slow around 5s to 10s if have alot of request parallel
                    var result = await _executor
                              .ExecuteAsync(doc =>
                              {
                                  doc.Schema = schema;
                                  doc.ValidationRules = rules;
                                  if (request.Query != null)
                                  {
                                      doc.Query = request.Query;
                                  }
                                  if (request.Variables.ToInputs() != null)
                                  {
                                      doc.Inputs = request.Variables.ToInputs();
                                  }
                                  doc.UserContext = new GraphQLUserContext() { User = httpContext.User, Info = account };
                                  doc.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
                                  doc.EnableMetrics = false;
                              }).ConfigureAwait(false);

                    if (_configuration.GetValue<bool>("FeatureToggles:EnrichWithApolloTracing"))
                    {
                        result.EnrichWithApolloTracing(start);
                    }

                    if (MyFeatureToggles.Setting.Environment != CommonConstants.ENVIRONMENT_PRODUCTION && result.Errors != null && result.Errors.Count > 0)
                    {
                        var response = new ErrorResponse();
                        response.data.Code = 599;
                        foreach (var item in result.Errors)
                        {
                            httpContext.Response.ContentType = "application/json";
                            httpContext.Response.StatusCode = 599;
                            var inner = (Exception)item;
                            if (item.InnerException != null)
                            {
                                while (inner.InnerException != null)
                                {
                                    inner = inner.InnerException;
                                }
                            }
                            response.errors.Add(new()
                            {
                                message = inner.Message,
                                StackTrace = inner.StackTrace,
                            });
                            await httpContext.Response.WriteAsync(Newtonsoft.Json.JsonConvert.SerializeObject(response));
                            return;
                        }
                    }
                    httpContext.Response.ContentType = "application/json";
                    httpContext.Response.StatusCode = 200;

                    await _writer.WriteAsync(httpContext.Response.Body, result);
                }
                catch (Exception ex)
                {
                    throw;
                }

            }
            else
            {
                if (requiredAccessToken)
                {

                    httpContext.Items["Access"] = false;
                    if (string.IsNullOrEmpty(appToken))
                        await _next(httpContext);
                    if (appToken != _configuration["AppToken"])
                        await _next(httpContext);
                    if (appToken == _configuration["AppToken"])
                    {
                        httpContext.Items["Access"] = true;
                    }
                }
                else
                {
                    httpContext.Items["Access"] = true;
                }
                await _next(httpContext);
            }
        }

```
###       Moreover, I have 2 class **RootQuery : ObjectGraphType** and **RootMutation : ObjectGraphType**, in 2 class i init alot of FieldType for my application graphql type.  
I DI query and mutation into 

```
public class SubjectSchema : Schema
    {
        public SubjectSchema(IServiceProvider serviceProvider ) : base(serviceProvider)
        {          
            Query = serviceProvider.GetService<RootQuery>();
            Mutation = serviceProvider.GetService<RootMutation>();
          
        }
    }

```
With each query in RootQuery i have response type abd input type for this query.



> > about the logic init
> 
> What logic? Your code? We can do nothing with your code. At least without comprehensive example.

**Comment by vansangnguyen1998** [comment]
Extra information: I inject rootQuery and rootMutation with Scope, SubjectScheme => Scope.
because, i need to inject some repo and some service to run query.

**Comment by sungam3r** [comment]
Note for all - we found out that the problem is in creating of a scheme for each request. I provided links to documentation.

**Comment by Shane32** [comment]
Can you post your DI setup, as it relates to GraphQL.NET?  Can you post the nuget packages that relate to GraphQL.NET you are using along with their version numbers?

I suggest adding a call to `schema.Initialize();` immediately before the `ExecuteAsync` call.  Since the schema is then initialized, it will not need to initialize within the call to `ExecuteAsync`.  So you can see if the delay is due to schema initialization or not.

If it is, you need to use a singleton schema and reconfigure your types' access to scoped services.  This will eliminate the initialization time, and also the time that DI is initializing all of your types, which occurs before your middleware (`InvokeAsync`) executes.  See documentation: [Dependency Injection: Scoped services with a singleton lifetime](https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#scoped-services-with-a-singleton-schema-lifetime)

If schema initialization is not the issue, then I suggest using apollo tracing to review which nodes are causing a delay.  You need to enable metrics via `doc.EnableMetrics = true` and also add the `InstrumentFieldsMiddleware` if you have not already done so (implicitly or explicitly) besides calling `EnrichWithApolloTracing`.

Finally, I suggest basing your code off of the GraphQL.NET Server middleware rather than writing your middleware from scratch.  Although it is likely that your code works fine as-is, there are a number of deficiencies I can see:
- The provided validation rules likely do not includes the core set of rules (unless you registered all the core rules within DI); this is critical to verify
- `doc.User` is not set, which although not necessary, is used by the current versions of the provided authorization rules.  It is accessible via `IResolveFieldContext.User` also, so it is not necessary to carry the value within your own user context
- `doc.RequestServices` is not set, which is critical to supporting scoped services within a singleton schema
- You are not using the GraphQL serializer to deserialize the request, and you should not need to call `.ToInputs` on the variables.  Chances are that you are using your own `GraphQLRequest` rather than the one provided (`GraphQL.Transports.GraphQLRequest`).
- You are not injecting document listeners via DI
