### ISSUE TITLE
How can I know a request is a query or mutation in a `ConfigureExecution`?

### ISSUE THREAD

**Issue by wakuflair** [graphql-dotnet/graphql-dotnet#3644]
I have  a `ConfigureExecution` implementing `IConfigureExecution` and works well so far.

Now I want to begin something like a transaction for all mutations.

But in the `IConfigureExecution.ExecuteAsync` method, I can't figure out what the request type is.

**Comment by Shane32** [comment]
Since that code is run before the document is parsed, the request type is not known at that time.  I have the same need and I have listed below what I did.  Note that GraphQL is designed to allow for a single GraphQL call to execute multiple mutations -- for example, adding a person and adding a widget simultaneously.  The solution I used would create a single mutation for the entire request, and if any errors were detected, the transaction would be rolled back.  So even if some data was returned by the call (e.g. adding the person succeeded and returned the new id, while adding a widget failed), it should be ignored as it would not be persisted to the database.  The only way to solve this would be to add a transaction wrapper within each field resolver that accesses the database.

## IConfigureExecution implementation

1. Add a document listener (see below)
2. Within a try/finally block, call the next function in the chain
3. In the finally block, pull the transaction context from the user context and commit/rollback the transaction if any errors had occurred

## Document listener - BeforeExecutionAsync

1. Create a transaction if `context.Operation.Operation == OperationType.Mutation`
2. Store the transaction object in the user context (e.g. `context.UserContext["Transaction"]`)

**Comment by Shane32** [comment]
My code also creates a snapshot transaction for Query type operations, so no matter how much data is requested, the entire GraphQL response will be consistent, even if the data is read over several SQL calls (as would be typical when data loaders are in use).

**Comment by Shane32** [comment]
It's also important to note that while you'd expect that `IDocumentListener` could be used entirely in place of `IConfigureExecution`, while often true, GraphQL.NET does not guarantee that `AfterExecutionAsync` is called after `BeforeExecutionAsync`.  Some scenarios would be if another document listener were to throw an exception, or if `ThrowOnUnhandledException` were true, or if the client disconnected and the cancellation token were triggered.

**Comment by wakuflair** [comment]
Thank you @Shane32! I made it by following your instructions.

Here's a sample code in case someone needs it:

``` csharp
public class TransactionConfigureExecution : IConfigureExecution
{
    public async Task<ExecutionResult> ExecuteAsync(ExecutionOptions options, ExecutionDelegate next)
    {
        // Add document listener
        options.Listeners.Add(new TransactionDocumentListener());

        var result = await next(options);
        if (options.UserContext.TryGetValue("TRANSACTION", out object? obj) && obj is Transaction trans)
        {
            if (result.Errors == null || result.Errors.Count == 0)
            {
                await trans.Commit();
            }
            else
            {
                await trans.RollBack();
            }
        }

        return result;
    }

    public float SortOrder { get; }
}

public class TransactionDocumentListener : IDocumentExecutionListener
{
    public Task AfterValidationAsync(IExecutionContext context, IValidationResult validationResult)
    {
        return Task.CompletedTask;
    }

    public Task AfterExecutionAsync(IExecutionContext context)
    {
        return Task.CompletedTask;
    }

    public Task BeforeExecutionAsync(IExecutionContext context)
    {
        if (context.Operation.Operation == OperationType.Mutation)
        {
            var trans = // create your transaction here;
            context.UserContext["TRANSACTION"] = trans;
        }

        return Task.CompletedTask;
    }
}
```

**Comment by Shane32** [comment]
That's great!  I would only suggest that the `var result = await next(options)` be within a try/finally block so if an exception is thrown (e.g. an `OperationCanceledException` if a client unexpectedly disconnects), the transaction is rolled back.

```cs
        ExecutionResult result;
        bool success;
        try
        {
            result = await next(options);
            success = true;
        }
        finally
        {
            if (options.UserContext.TryGetValue("TRANSACTION", out object? obj) && obj is Transaction trans)
            {
                if (success && (result.Errors == null || result.Errors.Count == 0))
                {
                    await trans.Commit();
                }
                else
                {
                    await trans.RollBack();
                }
            }
        }
```

**Comment by Shane32** [comment]
I'll close this issue now but feel free to comment if you wish me to re-open it.
