### ISSUE TITLE
Can we depend on the UserContext being preserved across Serial Mutations?

### ISSUE THREAD

**Issue by BillBaird** [graphql-dotnet/graphql-dotnet#3645]
I've found the UserContext dictionary to be quite useful in a number of scenarios.  My question is whether we can depend on the content of it being preserved across a mutation sequence?  The specification (section 6.3.1) clearly states "When executing a mutation, the selections in the top most selection set will be executed in serial order, starting with the first appearing field textually.".  I'm hoping to depend on that and also depend on the content of UserContext being preserved across the mutation sequence.  My tests indicate that it is preserved (not reset between each mutation).  Can this behavior be depended on the future.

Imagine the following mutation sequence:
```graphql
mutation TransGroup {
  m1:startTransaction(name:"myTrans")
  m2:updateSomething(param:"Y")
  m3:updateSomethingElse(param:"Y")
  m4:commitTransaction(name:"myTrans"){id}
}
```
In this case, m1 would place a "transaction" object in the UserContext.  m2 would extend the content of the transaction object.  m3 would extend it with something else.  Finally, m4 would take the built up transaction object from the context and execute it atomically.  Only m4 would even open a database connection.  m1, m2, and m3 would be developing the "transaction" object, which represents a sequence of operation to be done, entirely in memory.  Then, m4 would take the memory structure, open a connection to whatever form of persistence was being used, and execute it atomically.

Of course for this pattern to work, we have to depend on the content of UserContext being preserved across the entire sequence.  My testing shows this is the case - but can I depend on it?

**Comment by Shane32** [comment]
Yes you may rely on it being the same across a single execution, regardless of whether it is a serial or parallel execution.

Please be aware that the user context does not include synchronization locks and even with a serial execution strategy, you may run into concurrency issues when writing to the user context in the following scenarios due to sharing of a single instance of the user context:

- A client executes a batch request to the GraphQL server.
- Multiple requests are executed simultaneously across a single WebSocket connection.  (Note: queries and mutations can be executed across a WebSocket connection; not just subscriptions.)

You may disable those features within the GraphQL Server library if you do not need them - just set the `HandleWebSockets` and `EnableBatchedRequests` options to `false`.  Rather than disabling batched requests, you could set `ExecuteBatchedRequestsInParallel` to `false`, but be aware that the user context may contain data from the previous executions within the same batch.

Another option is store transient data within a dictionary contained within an `AsyncLocal` instance initialized within a document listener.  In this way the dictionary instance would be unique per running execution.  Finally, you could also register an object to hold your transient data within your dependency injection platform as a scoped service.  Since GraphQL.NET creates a service scope for each execution, the instance will be unique per request.  However, any scoped field resolvers would not have access to the transient data.

**Comment by Shane32** [comment]
References:
- https://github.com/graphql-dotnet/server/blob/007fc5d79d68be7bc1f6bbaa742234336044f53b/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L322
- https://github.com/graphql-dotnet/server/blob/007fc5d79d68be7bc1f6bbaa742234336044f53b/src/Transports.AspNetCore/WebSockets/GraphQLWs/SubscriptionServer.cs#L248
- https://github.com/graphql-dotnet/server/blob/007fc5d79d68be7bc1f6bbaa742234336044f53b/src/Transports.AspNetCore/WebSockets/GraphQLWs/SubscriptionServer.cs#L197

**Comment by Shane32** [comment]
The links above show the code that re-uses the user context across multiple executions.

The below link shows that only a single user context property exists for a given execution:
- https://github.com/graphql-dotnet/graphql-dotnet/blob/90cddce94aa7d243c0c8508f3b2754d8f1743505/src/GraphQL/Execution/ExecutionOptions.cs#L50

**Comment by BillBaird** [comment]
Thank you Shane!  I appreciate the detailed response.  This is very helpful.
