### ISSUE TITLE
Runtime dynamic schema example

### ISSUE THREAD

**Issue by Molochnikov** [graphql-dotnet/graphql-dotnet#3648]
Hello!

Is there any example or starting point for building  schema which can dynamicly changed at runtime (using MSDI preferably)? I've seen many topics but can't understand whole idea.

I'm thinking about building schema on the fly with scoped lifetime in MSDI for each connected client depending on some database table. And when this table changes then any new connected client will get a new schema with new dynamic resolvers.

**Comment by Shane32** [comment]
I don't know that there's an existing sample, but it's certainly possible to do.  Do you have any specific questions?  Here's some thoughts I have:

- There should be plenty of samples of dynamically creating a schema; this is very common I think
- For very large schemas, GraphQL.NET will need to build the entire schema before executing even a small request.  Careful programming of how the schema is dynamically generated can reduce the schema initialization time.  Perhaps also the GraphQL.NET schema initialization checks could be skipped in production.
- You may be able to increase performance with caching of the schema, or at least the data that is used to build the schema
- MSDI will always synchronously create instances, and as DB access is usually async, you may instead wish to override the GraphQL.NET Server's `ExecuteRequestAsync` method so that the schema can be created asynchronously.  Another option would be to install an `IConfigureExecution` implementation to change the `ExecutionOptions.Schema` property prior to the document executer executing the query.

**Comment by Shane32** [comment]
Please reopen if you have further questions
