### ISSUE TITLE
MatchingNodeVisitor does not handle async enter\leave listeners.

### ISSUE THREAD

**Issue by roman-bilyi** [graphql-dotnet/graphql-dotnet#3650]
## Summary
Should MatchingNodeVisitor handle async enter\leave listeners or it's a bad idea to put async code inside a visitor?

I see that INodeVisitor already does async Enter/Leave but inside MatchingNodeVisitor does not await for _enter or _leave visitors. Looks like it's very easy to fix on my own, by creating my own AsyncMatchingNodeVisitor, but would be nice to have it out of the box or a small explanation if it's a bad way.
### Environment (if relevant)

GraphQL 7.5.0

**Comment by Shane32** [comment]
`MatchingNodeVisitor` was/is a simple helper/wrapper around `INodeVisitor`, and exists primarily because it was heavily used in prior versions of GraphQL.NET (and likely also in third-party libraries) before the `INodeVisitor` was converted to support asynchronous execution.  As you noticed, it still only supports synchronous delegates.  There is no reason not to use asynchronous code within a `INodeVisitor` implementation, so I suggest writing your own implementation of `AsyncMatchingNodeVisitor` at this time.  It seems, however, that with a slight change we could support asynchronous delegates.  I'll write a PR.
