### ISSUE TITLE
Deprecated input fields are deleted from the schema

### ISSUE THREAD

**Issue by jannickj** [graphql-dotnet/graphql-dotnet#3658]
## Description

I just upgraded from 4.7.1 to 7.5 because I read that deprecation messages on inputs was fixed, however when I used it instead of getting deprecation messages the inputs are just deleted from the schema.
I am still able to query them (even though they are not in the schema), which is nice as it means I won't break production by upgrading. 
However actually getting the deprecation messages would be very nice :)

I saw that in the spec it says: https://github.com/graphql/graphql-spec/blob/main/spec/Section%204%20--%20Introspection.md#Input%20object that to include deprecations you need to turn it on, but I found no such toggle in this library.

e.g.

```graphql
query {
     jedis(filter: { 
        is_youngling: true  <--- deperecated input "is_youngling", will show as not existing but will still work when running
    }) {
        name
   }
}
```

**Comment by Shane32** [comment]
> I read that deprecation messages on inputs was fixed

can you refer me to what you were reading?


Also, can you include a snippet of how you define deprecated fields?

**Comment by jannickj** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/7.4.0

> Allow deprecation of input values by @sungam3r in https://github.com/graphql-dotnet/graphql-dotnet/pull/3571

example:

```csharp
var filterInput = InputObjectGraphType { Name = "filter" };
filterInput.AddField(new FieldType
{
	Name = "is_youngling",
        ResolvedType = new NonNullGraphType(new BooleanGraphType()),
        DeprecationReason = "No longer useful"
});
```

**Comment by Shane32** [comment]
Try:
```cs
schema.Features.DeprecationOfInputValues = true;
```
or within the `AddGraphQL` configuration:
```cs
    .ConfigureSchema(s => s.Features.DeprecationOfInputValues = true);
```

You can also check out the `EnableExperimentalIntrospectionFeatures` extension method for `ISchema`.

**Comment by jannickj** [comment]
thanks :grin:

**Comment by Shane32** [comment]
Well, I have not got it to work yet even with those options/methods...hmm...

**Comment by Shane32** [comment]
Ok so setting `schema.Features.DeprecationOfInputValues = true;` is necessary, but then it still doesn't show up in Playground since Playground doesn't query for `inputFields (includeDeprecated:true) {`.  So deprecated fields still don't show up.  But you can query for them manually with a query like this:

```gql
{
  __type(name:"HumanInput") {
    name
    fields	(includeDeprecated: true){
      name
    }
    inputFields (includeDeprecated:true) {
      name
    }
  }
}
```

Perhaps an updated UI package will show the deprecated input fields.

**Comment by jannickj** [comment]
ah that makes sense, it's also the behavior I would expect, as it's the same behavior for output fields :)

**Comment by jannickj** [comment]
do you know when it will stop being an experimental feature?

**Comment by Shane32** [comment]
I do not know if/when the 'deprecated input fields' feature will be released as a non-draft spec.  We can see [here](https://spec.graphql.org/) that it is not in the October 2021 spec (which is current), but it is in the draft spec.

When the next major version of GraphQL.NET is released, the feature will be enabled if the draft spec has been released at that time.  Otherwise it will remain as an opt-in feature.

I was hoping to add a property to set the version of the GraphQL spec that the schema meets, so you can just set `schema.SpecVersion = SpecVersions.June2018;` or something.  Each major version of GraphQL.NET would increment the default version to the latest, so if using older tooling which doesn't support certain features (e.g. deprecated input fields or descriptions within the printed SDL), setting the property to an old version will ensure compatibility with your tooling.  This feature has not been added yet; for now you will need to use the properties/methods I mentioned previously.
