### ISSUE TITLE
Add XML documentation comments for VS IntelliSense and "Go To Definition"

### ISSUE THREAD

**Issue by antmdvs** [graphql-dotnet/graphql-dotnet#369]
We should ship [XML Documentation Comments](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments). This would improve the discoverability and understandability of the APIs. For example, there are currently 6+ `Field` registration methods, which could be confusing at best/overwhelming at worst to someone trying to navigate the API for the first time.

**Comment by drobertson123** [comment]
Just my 2 cents. I would certainly love more documentation, but in my experience, it seems like XML Documentation has a tendency to overwhelm the code and make it harder to follow.

In many cases, the XML docs just state what is already there and little effort is put into adding the knowledge and context that needed to understand what is actually going on. I can figure out a method signature easily enough. What I would like to get from any documentation is the context for using the code. What is it used for, is there anything special in the way it works, are there side effects from interacting with the objects/code, etc...

I am not saying that XML docs are horrible or that in this case they would be a bad idea, but there is a tradeoff when using them. Code files explode in size with less code per screen space vs the comments in the file.

Aside from disagreeing (generally) with the idea of XML docs I think more documentation and information would be a wonderful thing. I am happy to pitch in to help some if that is useful.

Personally, I like the idea of more of a Living Documentation approach to the documentation. I believe Marten uses this. The basic concept is combining markdown files with a tool that renders them into a website containing the documentation (github pages). The markdown has syntax for linking directly to code examples that are rendered into the HTML documents as you go. The focus would be on writing good documentation of the software concepts and using descriptive Tests as the embedded code to show how things are done.

If the tests get out of sync with the markdown due to code changes it becomes fairly obvious and the markdown can be revised. Knowing that the tests are likely to be visible in the documentation encourages people to make well written and expressive tests (hopefully).

[Storyteller](http://storyteller.github.io/documentation/docs/) seems to have a good system for this. Jeremy Miller has an article on doing this. [How I’m Documenting OSS Projects](https://jeremydmiller.com/2016/01/05/how-im-documenting-oss-projects/)

**Comment by joemcbride** [comment]
@drobertson123  I have started some markdown doc files for basically that purpose.  I just haven't gotten around to generating a site for them yet.  I do like what the st-docs is doing.

https://github.com/graphql-dotnet/graphql-dotnet/tree/master/docs

**Comment by drobertson123** [comment]
To be fair, I have been trying to get motivated enough to use st-docs on an internal project. I really like the concepts and it seems like a very sensible aproach, but I haven't gone throught setting everything up yet. So all I have is opinions.

If I get it done I can share anything I learn back here.

In an open source project, having a list of methods isn't that useful. I can get most of that right from the code base. Documentation that helps a user understand the concepts and process flow is much more valuable, especially in this project. I have followed data front to back in debugging sessions and it jumps around a lot in graphql-dotnet. Having some good documentation that explains it all would be a big help.

I can see two types of documentation. The conceptual docs would help explain how and why it works the way it does. Ideally putting the major sections of the code in context so new devs can come up to speed faster and contributors could help sooner.

The second section would be practical how-to focused information. st-docs could tie the topics directly to relevant unit tests as examples of how something is done. The unit tests would need to stay current as code changes so the documentation would be partially self updating.

The real hard part is how to do documentation without it being a serious time suck. Better yet, how to get motivated contributors to do a lot of that work for you. You and this project need more minions.

**Comment by drobertson123** [comment]
@joemcbride I am playing with setting up Storyteller for documentation in one of my projects and I need to do some tests. The GraphQL-DotNet project would be a great functional test of what I want to do.

I could do a branch of the project and set up the living documentation system from storyteller. It would involve adding a Documentation project and would have some dependencies for storyteller. I am not entirely sure how everything would go together with GitHub, but I am willing to try it out.

My thought is that if the setup goes well it could be pulled back into the main project.

I am happy to do it (it would help me), but before I put the effort in I wanted to see if you are interested in this solution at all. No big deal either way, but if it works I would like it to be useful.

**Comment by antmdvs** [comment]
I think *both* forms of documentation are valuable and have come to be expected from any library with a non-trivial API surface.

A lot of .NET developers rely on IntelliSense for guidance, (both in VS proper and VS Code), as well as `Go to Definition` (F12) results, Object Browser, etc., all of which surface documentation sourced from XML doc comments.

As I alluded to above, I think this is particularly warranted for Field registration. Currently, when I type `Field(`, I'm presented with 6 overloads. This is further conflated by generic type inference, i.e. when I type `Field<>(`, I'm presented with 4 overloads. And then there's `AddField`.

For IntelliSense users, after a user types `Field(`, it would be ideal if they could cycle through the overloads and use the *descriptions* in addition to the signatures to inform their method selection, only breaking out a web browser when they want to see example usage and/or read more details.

> In many cases, the XML docs just state what is already there and little effort is put into adding the knowledge and context that needed

Yeah, so they need to be informative yet terse. @joemcbride If we take a stab at this with `Field` and find that it's difficult to accomplish, it may be an indication that there's simply too many (exposed) ways to register a field. I suppose this could be a separate issue.

> Code files explode in size with less code per screen space vs the comments in the file.

This would only be a potential issue for contributors, consumers savvy enough to view the repo (many may not even GitHub, increasingly so as the audience/adoption grows), and those who employ XML comments in their own code. For the latter, `Edit -> Outlining -> Collapse to Definitions` and go from there. This issue is more concerned with the majority of current and future consumers, not contributors.

**Comment by joemcbride** [comment]
@drobertson123 Yes I would be interested in that.  I work with Jeremy (he's run the Architecture Team I'm on) so I'm very familiar with Storyteller (though admittedly not as familiar with the st-docs).  I have commit access to the ST repo so I can help facilitate changes there.

@antmdvs 

> there's simply too many (exposed) ways to register a field

I think this is certainly part of the problem.  Most of them are just overloads and I would think that after using the project for just a little while that would come to light.  I think XML docs could help though won't necessarily solve the problem of knowing which one to use and why, without perhaps adding tons of docs in the XML comments which I think I would be opposed to.

**Comment by drobertson123** [comment]
I have no issue with focused use of XML docs. The key is that they should actually add value instead of just being autogenerated placeholders that make the code impossible to read.  I have seen way too many projects where the screen real estate was more than half un-informative XML docs and comments. It actually reduces your ability to understand the code when the code gets so spread out. 

@joemcbride I will Branch the code and start playing with st-docs as a test project. If I can get it into a useful setup I will send it over to you. Maybe something will come together and we can do a PR. 

graphql-dotnet has matured pretty nicely. It is time that it has a solid set of documentation to go along with it. I will see how far I can get. If I run into a wall I may reach out to you for your contacts in that project.

**Comment by drobertson123** [comment]
@joemcbride I am working on some documentation process ideas. I have a quick question. What was your intent with the YAML in the new docs? Did you want to use jekyll or are you open to a different approach?

I was working with a st-docs system or possibly a pandoc based transform so far. Any thoughts would be welcome.

**Comment by joemcbride** [comment]
@drobertson123 this was so I could publish to GitHub pages in just a few minutes of work.  I want to use st-docs or perhaps [gatsbyjs which uses GraphQL](https://github.com/gatsbyjs/gatsby) long term.

**Comment by antmdvs** [comment]
@joemcbride Feel free to rename this issue or close it and create a new one to track the other documentation effort being discussed.

**Comment by PeteDuncanson** [comment]
Adding XML Documentation seems like a no brainer. I'm reading through the examples but its damn hard to get your head around some of the concepts. Allowing me to explore the API along with the examples with good intellisense it invaluable I think. I've started having a poke around in the source some more and see if I can't get some added (assuming I can make any sense of it!)

Also of note if you are worried about comment bloat (I don't think you should be as long as we avoid GhostDoc auto generated bollocks thats there just to pass some style cop rules) you could include the comments separately in a separate xml file if needed (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/include)?

**Comment by joemcbride** [comment]
@antmdvs Sorry for hijacking this issue, I created #388 to track "better docs" and can keep this one for XML docs.

**Comment by Grauenwolf** [comment]
The idea behind GhostDoc was that it writes the tedious bits, but you are supposed to supply the details. Since we all know that doesn't happen, GhostDoc now has quality checks to watch for purely auto-generated documentation that doesn't actually provide information. I think you can even tell it to remove any XML that exactly matches the auto-generated templates.

**Comment by Grauenwolf** [comment]
Anyways, I'm going to take a stab at this because that's the only way I'm going to understand what the heck is going on.

**Comment by SimonCropp** [comment]
IMO this should be closed. 

 * no specific commit will fix this
 * it is unlikely we will ever get to 100% xml docs coverage
 * obviously if anyone want specific xml docs we would accept a PR

**Comment by sungam3r** [comment]
Closed because of https://github.com/graphql-dotnet/graphql-dotnet/tree/master/docs2
