### ISSUE TITLE
Date Formatting on a Query basis

### ISSUE THREAD

**Issue by StefanKoenigMUC** [graphql-dotnet/graphql-dotnet#3719]
Hi there,

for some use cases, I need to have different date formats on a per-query basis in place. Basically, my users want to do something like that

{
   myDateQuery(dateFormat: "mm:dd:yyyy") {date_output}
}

the date should be formatted accordingly (maybe even better, if possible on a per-field basis). 

What came to my mind as an easy solution, is to not use DateGraphType, instead a StringGraphType is returned and its converted according to the provided string/default values. But that doesn't seem to be a very clean solution. 

Do you maybe have any other ideas on how I can realize that requirement? 

Thanks in advance,

**Comment by Shane32** [comment]
The first idea that comes to mind is to create your own custom date graph type (e.g. `MyDateGraphType`), which behaves identical to a string graph type.  And then write some GraphQL field middleware which checks if the returned type is a `DateTime` (or `DateOnly` or `DateTimeOffset`, etc), and if so, checks the field's arguments for a `dateFormat` argument, and reformats the result according to the argument, converting the value to a string.  Although it would be ideal to write this code within the scalar graph type itself, scalar graph types do not have direct access to the `IResolveFieldContext`.

You'll still need to add the `dateFormat` field argument to every applicable field, but you could probably write some schema initialization code to automatically the argument to every field that has a return graph type of `MyDateGraphType`.

Unfortunately, `MyDateGraphType` would accept and return a string rather than a date value, so there's less validation on responses.  You could use a custom type such as a struct containing the date and the format to preserve type safety.  Then the custom scalar graph type would throw unless the returned value was the right kind of struct, which it would once the field middleware converted the date value to the struct.  Then the scalar converts the struct to a string for representation within the json response.

Instead of adding the `dateFormat` to every date field, another option would be to add a `@dateFormat` directive that can be applied to the query as a whole.  (I've done this to specify the time zone for date/time responses.)  The directive could be applied to the field itself, so no field argument is necessary, eliminating the need for schema initialization code (but also making it more difficult for users to know the feature exists).  You could do some combination of the above suggestions.

**Comment by StefanKoenigMUC** [comment]
hmm, thanks a lot. I'll make up my mind and come back what solution I'll take :-)

**Comment by Shane32** [comment]
Closing as answered
