### ISSUE TITLE
Performance degradation after upgrading from 4.8.0 to 7.6.1

### ISSUE THREAD

**Issue by zspasojevic** [graphql-dotnet/graphql-dotnet#3727]
## Summary

Hi team,

Our backend running on .NET 6 had GraphQL 4.8.0 running for a long time. Recently, we've decided to upgrade to the new version so we moved to 7.6.1. 
After the upgrade, we noticed significant performance degradation. Queries that usually take around 100ms on production are now taking 180-200ms. Testing this locally gives us around 650ms compared to 550ms before.

We're using the graphql gateway (with multiple schemas stitching) to have a unique endpoint for all UI requests and also as a proxy for internal communication between our .NET backend services. This means we trigger 20-30 queries along the way to complete some of the most complex UI queries, meaning that we now have a couple of seconds of performance degradation compared to the response timings with 4.8.0.

Looking at the migration changes, we haven't found anything mentioning this as a possibility:

https://graphql-dotnet.github.io/docs/migrations/migration5/
https://graphql-dotnet.github.io/docs/migrations/migration7/

NOTE: We're registering schema and services within the resolvers and types as scoped. We are aware that it's recommended to register schema as singleton and then use service provider to get the scoped service while resolving a field, if needed.
But our schemas were scoped before and as I mentioned, performance was better.

Can someone provide us with more details of what we can try in order to improve this, here's how we're configuring gql in code?
It doesn't make sense to be forced to revert to a no longer supported version.

7.6.1 - we're using the GraphQL.DI extensions:

![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/43961181/821a1678-aa1f-4314-b719-fdf2de8cbdd4)

4.8.0 - (schema was registered with just AddScoped<Schema>):

![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/43961181/4749fa04-3656-4a9f-9430-e38397e17bfc)

**Comment by Shane32** [comment]
I don't have a good answer for you here.  I can say that our design has been focused with the assumption that people will be using a singleton schema, and especially anyone that is looking for performance.  That being said, we still support scoped schemas, and in that vein have also fixed multiple multithreading bugs for scoped schemas over the last couple years.  These bug fixes typically come at the cost of performance, as they are usually fixed by separating graph type instances previously shared by multiple schema instances, such as introspection graph types.  We have also overhauled `AutoRegisteringObjectGraphType` and similar classes, making heavy use of reflection and dynamic runtime compilation during initialization.  And we have added schema validation code which did not previously exist.  Since GraphQL.NET is not optimized for scoped execution, these bug fixes and new features could considerably slow down schema initialization time.

If you were to switch to a singleton schema, you should notice the performance increase drastically.  I have a couple "large" schemas (~300 types), and they can execute simple requests in 10-15ms.  They execute with a serial execution engine and make use of scoped services to access the underlying database and/or database logic.  A larger request, with data sourced from a dozen SQL tables, and including apollo tracing data for the whole request, only takes 25ms including the database execution time.

However, if scoped schemas were necessary for your application, such as when your schema is dynamically generated at runtime, I would recommend some of the following:
- Time the total length of time it takes to both (1) pull the schema from DI and (2) execute `schema.Initialize()`; use this as a reference when making other changes (this time goes to 0 with a singleton schema for subsequent requests)
- Eliminate use of `AutoRegisteringObjectGraphType` or design a custom implementation which caches the dynamically compiled resolver and/or other reflection calls. (Potentially a feature that could be added to GraphQL.NET)
- Ensure that every field has a resolver set on it.
- Check the `GlobalSwitches` and see if you can turn off any of them.  (`EnableReadDescriptionFromXmlDocumentation` is painfully slow but already defaults to `false`.)
- Disable schema initialization checks.
- Investigate where graph types could be safely shared across instances without memory leaks, and register those as singletons.  Certainly scalars, but also perhaps input types or object types that only reference scalars and do not reference scoped services, for example.  Doing so correctly requires a good understanding of GraphQL.NET's architecture, however.

**Comment by Shane32** [comment]
> design a custom implementation which caches the dynamically compiled resolver and/or other reflection calls

See the following as an example:
- #3728

**Comment by zspasojevic** [comment]
@Shane32 Thank you for the feedback, we switched to using singleton schemas together with scoped domain services and the performance looks great now!
