### ISSUE TITLE
Support Apollo Tracing

### ISSUE THREAD

**Issue by benpriebe** [graphql-dotnet/graphql-dotnet#381]
I am wondering if anyone has had success in instrumenting a graphql-dotnet implementation to send analytics to Apollo Data Optics service (http://www.apollodata.com/optics/)?

Apollo Optics currently have examples on how to instrument your NodeJS or Ruby GraphQL servers but not .Net. I have reached out to their support team and they suggested I reach out to this community.

**Comment by joemcbride** [comment]
No, there isn't anything built in for that at present.  I looked into it after it was announced at the last GraphQL Summit, though at the time they didn't have free accounts so that made it a lot harder to integrate.  They also want the metrics in a very specific format.  I would say the current metrics are about 70% of what Apollo Optics want.

See the docs on metrics: http://graphql-dotnet.github.io/graphql-dotnet/learn#metrics

**Comment by benpriebe** [comment]
Thanks for the link.

**Comment by pekkah** [comment]
This will replace optics https://dev-blog.apollodata.com/introducing-apollo-engine-insights-error-reporting-and-caching-for-graphql-6a55147f63fc

**Comment by joemcbride** [comment]
It looks like they've switched to wanting a new, simpler format.  This should be much easier to accomplish than what was previously required.

https://github.com/apollographql/apollo-tracing

**Comment by jbaxleyiii** [comment]
@joemcbride awesome! I'll start playing around with it over the next few weeks and reach back out! Thanks for this great project 🤗

**Comment by RehanSaeed** [comment]
Is there any example on how to set this up with GraphQL.NET Server? The [docs](https://graphql-dotnet.github.io/docs/getting-started/metrics) don't cover that. I've only just found out about Apollo Tracing, is there an easy way to ship these logs to Apollo to get the free metrics and charts?

**Comment by csboling** [comment]
I haven't used the [server](https://github.com/graphql-dotnet/server) project but it looks to me like you should be able to configure a customized service for `IGraphQLExecuter<TSchema>`, something like:

```csharp
public class MyGraphQLExecuter<TSchema> : DefaultGraphQLExecuter<TSchema>
    where TSchema : ISchema
{
    public override async Task<ExecutionResult> ExecuteAsync(string operationName, string query, Inputs variables, object context, CancellationToken cancellationToken = default(CancellationToken))
    {
        var result = await base.ExecuteAsync(operationName, query, variables, context, cancellationToken);
        result.EnrichWithApolloTracing();
        return result;   
    }
}
```
and instead of `services.AddGraphQL` you would adapt the [service bindings](https://github.com/graphql-dotnet/server/blob/develop/src/Core/ServiceCollectionExtensions.cs#L19)   to use `MyGraphQLExecuter` instead. I don't have any experience with setting up Apollo's analytics stuff but if your responses contain the tracing extension then GraphQL Playground's tracing view ought to display it, so I'd guess Apollo can figure it out too.

**Comment by joemcbride** [comment]
@RehanSaeed The way they want you to do it is run a proxy in front of your GraphQL server.

https://www.apollographql.com/docs/engine/setup-standalone.html#configure-proxy

**Comment by RehanSaeed** [comment]
@csboling Thanks for that. I added the code and see the tracing section show up in the GraphQL playground:

```json
"extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2018-09-14T15:31:49.5565957Z",
      "endTime": "2018-09-14T15:31:49.5595957Z",
      "duration": 3241900,
      "parsing": {
        "startOffset": 13900,
        "duration": 280500
      },
      "validation": {
        "startOffset": 13900,
        "duration": 280500
      },
      "execution": {
        "resolvers": []
      }
    }
  }
```

However, I don't see the tracing pane in the GraphQL Playground that seems to exist. I looked at the GraphQL.NET Playground NuGet package and don't see anywhere where we would be turning Apollo Tracing off.

**Comment by RehanSaeed** [comment]
Also, does anyone know if the Apollo Engine Tracing strips the tracing data once it's been consumed?

**Comment by csboling** [comment]
In my GraphQL Playground I get a "TRACING" pane I can expand in the bottom right:
![image](https://user-images.githubusercontent.com/7418731/45562747-81b25f80-b808-11e8-8918-eee7eb5b4026.png)

Not sure what exactly the Playground configuration is like for the GraphQLDotnet `server`.

Also it looks like your `"resolvers":` section is empty. For that to get populated you need the [InstrumentFieldsMiddleware](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Instrumentation/InstrumentFieldsMiddleware.cs) installed. So probably you also need:

```csharp
public class MyGraphQLExecuter<TSchema> : DefaultGraphQLExecuter<TSchema>
    where TSchema : ISchema
{
    . . .

    protected override ExecutionOptions GetOptions(string operationName, string query, Inputs variables, object context, CancellationToken cancellationToken)
    {
        var options = base.GetOptions(operationName, query, variables, context, cancellationToken);
        options.FieldMiddleware.Use<InstrumentFieldsMiddleware>();
        return options;
    }
}
```

Otherwise it's possible that GraphQL Playground is seeing that the `"resolvers":` section is empty and not displaying tracing data.

**Comment by RehanSaeed** [comment]
It turns out GraphQL Playground disables tracing by default. I've enabled it in what I thought would be a PR [here](https://github.com/graphql-dotnet/server/commit/de433c4d92b3c86d0d1ef0979960499f9f8e53f2) but I forgot that I'm now a contributor, so when I hit the edit button it does a commit instead, Doh!
