### ISSUE TITLE
Performance when using large lists.

### ISSUE THREAD

**Issue by holm0563** [graphql-dotnet/graphql-dotnet#435]
My company has several data sets that have a lot of properties and have lists of lists returned. I've noticed this library could have a few improvements in this area.

I was going to submit a pull request but it looks like this project is moving towards 2.0. I went to submit a pull request but it looks like a lot of the files like DocumentExecutor already have some major changes. I'd be happy to re-evaluate with 2.0 but want to make sure these fit in with any 2.0 objectives. So here are a summary of changes. 

The changes address the issue of running tests with a list with 10k items in a list and measuring performance. These changes result in a 120% speed increase in this setup. 

https://github.com/holm0563/graphql-dotnet/tree/performance

1. The document executor assumes all fields should be run in a new thread. Most of the time this is not true. The data is returned and usually only the NameFieldResolver to resolve the current data. Resolving these async instead results in big performance gains.

Simple example:
https://github.com/holm0563/graphql-dotnet/commit/e82565c74f4cd49ac8d005ae069e2f5b3bb4120d#diff-9ee075dfc3429298a3c5de0c1b53bef2

We definitely still want the ability to resolve fields in a thread whenever it would connect to a database or external source. The current pipeline of always using a thread and then recursively calling CompleteValueAsync -> ExecuteFieldsAsync can be optimized. I propose adding an opt in policy on the IFeildResolver to signify if it should run threaded. Also I removed the FieldMiddlewareBuilder default behavior of wrapping every field with a resolver. Allowing the resolver to be null and using the NameFieldResolver as the default helped performance. Most of the changes seen in the performance branch of my fork revolve around this idea.

2. Typically in production environments this library would often be re-running the same query over and over. Adding caching to the documentvalidator improves performance by 500% when just running simple queries repeatedly against the star wars schema. Should this be a built in feature? 

Example:
https://github.com/holm0563/graphql-dotnet/blob/performance/src/GraphQL/Validation/CachedDocumentValidator.cs

3. Reflection is slowe(er). Especially when running against lists, caching property info can improve performance. This gave about a 2% speed jump.
https://github.com/holm0563/graphql-dotnet/blob/performance/src/GraphQL/ObjectExtensions.cs

4. When running a performance analysis the TrimGraphQLTypes was on the list and shaved another 2% of the tests to cache this tests.

https://github.com/holm0563/graphql-dotnet/blob/performance/src/GraphQL/GraphQLExtensions.cs

Again I get that not all users have lists or large data sets. These improvements would also help when running queries a second time which I would anticipate being very common for almost all users of this library. 

Let me know I can help with these ideas in 2.0. So far the changes are looking great.

**Comment by joemcbride** [comment]
Hey, thanks for these suggestions.  I think it would be great to get some of these in the 2.0 release.

1. > all fields should be run in a new thread

That was definitely not the intent.  The intent was that they were all ran async.  Overall the executor does need an overhaul.  Right now the project is technically not following the spec in that queries should be ran async and mutations should ran serial.  Right now both run async.

> adding an opt in policy on the IFieldResolver to signify if it should run threaded

First thought on that is I don't want to have to deal with an api for that (thinking some sort of property marker).  My original intent was that fields that returned a `Task` would signify that they should be awaited and that is the only API the framework would need.  Open to making changes here though.

> FieldMiddlewareBuilder wrapping every field with a resolver

This was specifically implemented for metrics.  So if you want to opt-out of that pipeline I can see that being beneficial as that does add some overhead.

2. > cache query validation

I do think this could be a good idea, though caching the validation result would only work if the context of the validation does not change.  For instance, I have created some authentication/authorization rules which would need to get evaluated on each request since the authentication or authorization context may have changed between requests and between users.

Related to this - you could cache the actual parsing of the `Document` itself based on the `Query`.  The `ExecutionOptions` allows you to pass in an already populated `Document` for that purpose.  One thing with this sort of caching is making sure that your cache doesn't get overly bloated.  So if we were going to provide some sort of caching mechanism for queries I think we would want to make sure that it could be limited to say the top 10/50/100 queries or whatever fits your domain and your servers can handle.  There's a specific caching pattern for that though I'm not remembering the exact name of it at present ...

3. 👍  to this one
4. 👍  to this one

So I think it would be great to get 3 &4 in, with a maybe? on 2.  I think the changes to 1 could go in a 2.1 or 3.0 release, with finally fixing the serial mutation issue.

**Comment by kamsar** [comment]
For the validation caching, what if a `bool Cacheable` property was added to the `IValidationRule` interface, and the validation result would be cached if none of the validation rules were uncacheable. That would provide a way for must-run rules to be executed while having static rule results get cached.

**Comment by sungam3r** [comment]
@holm0563 Is this issue still actual?

**Comment by SimonCropp** [comment]
closing this due to no response. @holm0563 please ping back if it still effect you

**Comment by sungam3r** [comment]
May be related to #942
