### ISSUE TITLE
Typed Arguments

### ISSUE THREAD

**Issue by rvlietstra** [graphql-dotnet/graphql-dotnet#44]
Hi.

I'm trying to understand how to use GraphQL.Types.ResolveFieldContext.Arguments. 

```c#
            Field<UserPayloadType>(
                "UpdateUser",
                arguments: new QueryArguments(
                    new List<QueryArgument>
                    {
                        new QueryArgument<UserInputType> { Name = "input" }
                    }),
                resolve: context =>
                {
                   Dictionary<string, object> input = (context.Arguments["input"] 
                                                       as Dictionary<string, object>);
                   string id = (string)input["id"];
                   ...
```

Arguments as a dictionary work ok when its simple types like id, but I have a complex input type

```c#
    public class SomeInputType : InputObjectGraphType
    {
        public SomeInputType(Entities db, TheDataQuery query)
        {
            Name = "SomeInput";
            Field<StringGraphType>("id");
            Field<StringGraphType>("Name");
            Field<StringGraphType>("clientMutationId");
            Field<ListGraphType<SomeOtherInputType>>("Others");
        }
    }
```

Is there any built in way to get an instance of the actual argument type ?
At the moment I have to do something like this: 

```c#
(((input["Others"] as Object[])[0] as object) as Dictionary<string, object>)["id"]
```

Thanks!

**Comment by joemcbride** [comment]
For simple types you can use a generic, which is a little nicer:

```
var id = context.Argument<string>("id");
```

For complex types, there isn't any specific helper for arguments.  There is however a [`ToObject<T>`](https://github.com/graphql-dotnet/graphql-dotnet/blob/4df5e90d6aa8531b57671c89349b59e3dc084da1/src/GraphQL/ObjectExtensions.cs#L11) extension available on `Dictionary<string, object>`.  An [example test](https://github.com/graphql-dotnet/graphql-dotnet/blob/4df5e90d6aa8531b57671c89349b59e3dc084da1/src/GraphQL.Tests/Execution/InputConversionTests.cs#L27) shows it in action.

```
public class MyInput
{
    public int A { get; set; }
    public string B { get; set; }
    public List<string> C { get; set; }
}

var obj = context.Argument<Dictionary<string, object>>("input");
var myInput = obj.ToObject<MyInput>();
```

You can create an extension method that combines those two together.

```
public static class ResolveFieldContextExtensions
{
    public static TType ArgumentAsObject<TType>(this ResolveFieldContext context, string name)
        where TType : class, new()
    {
        if (context.Arguments.ContainsKey(name))
        {
            var dict = context.Arguments[name] as Dictionary<string, object>;
            if (dict != null)
            {
                return dict.ToObject<TType>();
            }
        }

        return null;
    }
}

var myInput = context.ArgumentAsObject<MyInput>("input");
```

That won't help with nested complex types however, the current form of `ToObject` isn't smart enough for that.  For that, since there isn't anything built-in, your best option is probably to create a model class that represents that data and use JSON.NET to convert it.

```
public class MyDataObject
{
  public MyOtherDataObject Property { get; set; }
}

public class MyOtherDataObject
{
  ...
}

var json = JsonConvert.SerializeObject(context.Arguments["input"]);
var input = JsonConvert.DeserializeObject<MyDataObject>(json);
```

A little dirty but it should work.

**Comment by rvlietstra** [comment]
Thanks that seems to work!
