### ISSUE TITLE
Making this library better - what I think needs to be done

### ISSUE THREAD

**Issue by Cooke** [graphql-dotnet/graphql-dotnet#442]
Thanks for a good library. I use it in production at my current client and have [contributed](https://github.com/graphql-dotnet/graphql-dotnet/pull/342) to it myself. Though I have some concerns which run out of a frustration which emerges whenever I work with any graphql endpoints with this library, or set up new ones.

Here are some ideas that I have investigated by spiking a GraphQL library of my own. The purpose is to have a discussion about the direction of this library (graphql-dotnet) and hear what others think.

* I believe it is significantly easier to use a convention based library
* The library should be ready to go with ASP.NET Core (delivered with middleware)
* The library should be delivered with an available/suggested authorization technique
* The library interface should be intuitive/easy to understand

One could argue about a convention based approach being easier or not, but the way we define APIs today with this library feels like too much ceremony. I haven't played much with the convention add-on since I don't fully trust the underlying library and it has very few github stars (lol, but still). I think merging in the convention based approach or creating some easier method for defining API:s is a good way forward.

It is quiet some work to get an endpoint/controller/middleware up running to pipe the request into the QueryExecutioner. I copied code from some samples, which feels less than optimal. I think this library should be delivered with a middleware for serving requests. Perhaps as a separate nuget package but still as a promoted way of using it.

I suspect most GraphQL API:s out there need to deal with authorization and with good support for authorization in ASP.NET I believe this too should be included in this library, perhaps in the same nuget package as an eventual middleware. The suggested way to do authorization today in this library works well enough for my use-cases but it is an unnecessary speed bump and requires too much ceremony again. 

What makes a library easy to use and intuitive is of course subjective but still... One example is when creating a field with complex input arguments one have to instantiate QueryArguments, QueryArgument<NonNullGrapType<InnerType>> and then also instantiate the ResolvedType (which I have missed several times and had the query processor puke on me). Another example is when creating errors one has to first instantiate the ExecutionError class, then call AddLocation then add the error to the context, which has a lot of stuff exposed on it. These examples are somewhat of nitpicking but corresponds with my general feel fot the design for the library. 

My proof of concept library is implemented at [graphql-solid-dotnet](https://github.com/Cooke/graphql-solid-dotnet). It only works for basic queries and the future of it is uncertain. Hopefully the things I suggest will make it into graphql-dotnet instead. 

Looking forward to hear your thoughts!

**Comment by Kurren123** [comment]
I use this library to wrap existing APIs which use strings rather than classes. E.g. `api.GetAll("customers")`. Because of this I build my graphQL api manually (adding my own `FieldType`s etc) rather than auto generating through static classes. So a convention based approach won't help me.

**Comment by pekkah** [comment]
## Conventions

Yep they're good when getting started or building from scratch but if you're adding GraphQL on top of existing APIs then they just get into way. Installing another package to get Conventions support is not that bad.

## delivered with middleware

I like how the core library does not bind to any specific hosting method or include one. It doesn't take that long to make your own or copy/paste from samples. One middleware to handle both normal queries and subscription is being done here [Subscriptions](https://github.com/graphql-dotnet/subscriptions-transport-ws)

## The library should be delivered with an available/suggested authorization technique

Again my opinion is that it should be and is its own package you can opt-in if you need it. In my experience in any API the authentication can be common pre-packaged dropin to your project, but authorization requirements are so wide that it's hard to make one to fit all or it would be horribly complex.

**Comment by Cooke** [comment]
@Kurren123 @pekkah I have no problem with installing another package/library for a convention based approach. What I think is bad is that it is not part of the main repository and promoted and documented and maintained accordingly. I think the difference is big mentally especially for newcomers, though small in practice. 

The same goes for middleware and authorization. It can be a separate package but I want it their, up for grabs, maintained by the library authors. Copy pasting samples is an unnecessary bump on the road. 

I guess what it boils down to is that I assume that many of the library users do run on ASP.NET Core and that the library should be delivered with packages that solve a majority of the library users headache. My assumption could also be a projection of my own current needs.

**Comment by jquense** [comment]
I also think the current approach is the correct one. I think some of the tension here is cultural differences and expectations between folks that are coming from a purely C# windows environment and those of us that are coming form the JS/frontend world. For example the JS implementations of graphql has a few different packages, the base implementation of the GQL spec and schema language, and graphql-express which provides easy to use middleware and http stuff for running a server. As it is I think that distinction makes the most sense. As you move up the abstraction stack needs get far more personalized and opinionated. Folks build web servers a lot of different ways, and it would be restrictive to require a single path to use GQL in DOTNET. 

I've hit this tension myself, trying to author Relay extensions for graphq-dotnet. Originally I provided direct hooks into WebAPI, but have since pulled that back and now only require a request body stream, so folks can build wahtever server they want. And to be clear the reason there is even http bits in the Relay lib, is because Realy specifies the request format whereas plain ol graphql does not.

**Comment by joemcbride** [comment]
Some good comments here.  A few thoughts from me.

* _instantiate QueryArguments, QueryArgument<NonNullGrapType>_ I agree that it is a bit verbose, especially around Arguments.  I'm open to suggestions to make the "do it by hand" less verbose.  Note that for the most part, these are just extension/overload methods that build a `FieldType` and add it to the list.

* _instantiate the ResolvedType_ This sounds like to me that perhaps you're using the library differently than originally envisioned (you could blame that on the API).  You essentially should never need to do this outside of DI container unless you're building your own schema builder.  I would like to hear more about how you're using the library and perhaps point you in a different direction.

* _one has to first instantiate the ExecutionError class, then call AddLocation then add the error to the context_ This is another one of those "can you tell me why/how you are using those?" questions.  You shouldn't have to be dealing with those basically ever.

* The core library is purposefully server agnostic and mostly transport agnostic, though you would need to add a few more steps to support something other than JSON.

* I wouldn't mind having an "official" nuget for ASP.NET Core, though I don't personally want to have to support others.

* Version 2.0 provides a Schema Builder centered around the [Schema type language](http://graphql.org/learn/schema/#type-language).  It is not fully-featured at present for what can be done with using the GraphType classes directly, but it should help those new to GraphQL to get started easier.

```csharp
public class Droid
{
  public string Id { get; set; }
  public string Name { get; set; }
}

public class Query
{
  // context is optional
  public Droid Hero(ResolveFieldContext context)
  {
    return new Droid { Id = "123", Name = "R2-D2" };
  }
}

var schema = Schema.For(@"
  type Droid {
    id: String
    name: String
  }

  type Query {
    hero: Droid
  }
", _ => {
    _.Types.Include<Query>();
});

var result = schema.Execute(_ =>
{
  _.Query = "{ hero { id name } }";
});
```

* There is a fairly new [authorization](https://github.com/graphql-dotnet/authorization) project that uses claims based authorization based on the [suggested pattern in the core docs](http://graphql-dotnet.github.io/graphql-dotnet/learn#authentication--authorization).  Docs in the authentication project are lacking, but it looks like the following in conjunction with a validation rule to check that a request passes the given Policy.

```csharp
var settings = new AuthorizationSettings();
settings.AddPolicy("MyPolicy", _ => _.RequireClaim("role", "admin"));

public class Query
{
  [GraphQLAuthorize(Policy="MyPolicy")]
  public Droid Hero()
  {
    return new Droid { Id = "123", Name = "R2-D2" };
  }
}
```

* _maintained by the library authors_ There are honestly very few core contributors (thanks to all those reading this!).  Maintenance is an issue.  There is lots of interest, though not a whole lot of consistent contributors.  Those that are solving issues that the community may be interested in I have created additional repos under this Org for those authors to have at it.  I personally mostly work on this project as a side project since we haven't adopted it as a standard at my workplace (at present).  That is why weeks/months can go by without code reviews/merges/deploys/new features.  I'm guessing a lot of those reading this are in that same position, or what has been provided so far has been "good enough" to solve their need.

**Comment by Cooke** [comment]
@joemcbride Thanks for your elaborate answer. 

* _instantiate the ResolvedType_ example:
```c#
new QueryArguments(
  new QueryArgument<NonNullGraphType<StringGraphType>>
    {
       Name = "key",
       ResolvedType = new NonNullGraphType<StringGraphType>
       {
            ResolvedType = new StringGraphType()
       }
    }),
```
I suspect instantiation if resolved type is only required for mutations, or perhaps in other circumstances.

* _ExecutionError class_: we use custom errors a lot with help of a middleware we catch exceptions and do the following:
```c#
var error = new BusinessExecutionError(ex.Message, ex.ErrorCode);
error.AddLocation(context.FieldAst, context.Document);
context.Errors.Add(error);
```
This is a very minor detail and nothing to get hang up on. Though another thing to note is that we can't extend the errors with custom codes so we worked around that with a custom ExecutionResult structure that we can serialize the way we want (instead of ExecutionResultJsonConverter). 

* I get that the core library is server agnostic and I think that is good. I just would like to see more official support for ASP.NET Core in particular. I could probably ship on such a package. Though I think that it needs to be closely related to graphql-dotnet, with examples and links straight from the core library. Just like graphql-express is linked straight from http://graphql.org/graphql-js/. I also believe that in such an opinionated ASP.NET Core package support for ASP.NET authorization should be included.

* Perhaps the schema builder can help new comers, from graphljs, but it feels inferior to a convention based approach, thought it is more compact. 

* The authorization project looks promising. Thought looks like a separate implementation not using asp.net core. 

* _maintained by the library authors_ should probably more like _maintained by the community_. I don't mind shipping in on stuff that I use.

I hope graphql will have a bright future and thus a great dotnet library is needed. This library could very well be that library. With this post I just want to express my thoughts around what could be done and here if others felt the same and perhaps we could join efforts to fill the gaps. The response so far indicates that what I suggest are not overwhelmingly missed properties of this library. 

Maybe we can keep this issue open a little bit longer to hear if anyone else has anything to say. Thanks.

**Comment by joemcbride** [comment]
> I suspect instantiation of resolved type is only required for mutations, or perhaps in other circumstances.

Having the `ResolvedType` populated is required for everything.  If you look at the `QueryArgument` class, there is a `Type` property in addition to the `ResolvedType` property.  When you use `QueryArgument<T>`, it sets the `Type` property.  When your `Schema` is initialized, it walks the Graph Type tree and resolves all of the defined types, setting that `ResolvedType` property for you.

When this project was first released, only the "type-based" API was available and the "resolved type" was fetched on the fly.  To support an "instance-based" API, the behavior was changed so that the types are resolved when the `Schema` is first initialized and "cached" in the `ResolvedType` property.  The library then uses that `ResolvedType` property instead of the `Type` property.

**Comment by drobertson123** [comment]
Just a small request regarding the title of this post. Can we keep the politics out of here?

The post title may seem like a small political joke but I would rather have this focused on GraphQL than have politics dragged into every corner of my life. I feel like I am getting PTSD from all the politics these days.

**Comment by drobertson123** [comment]
_Note - I took some of this from comments I made in Conventions. Sorry for the cross post._

I have been thinking about the Conventions library and graphql-dotnet. I think it could really use a place inside the main project. Possibly as a tightly connected subproject.

What I am suggesting isn't to make Conventions the only way to use graphql-dotnet, but to integrate some of its core concepts and to make it a directly available first choice way to use graphql-dotnet. Right now the projects are getting out of sync and it is impossible to use Conventions with the new GraphQL 2.0. By bringing it into the project it would be easier to keep it up to date.

I understand the idea of keeping graphql-dotnet pure and focused (a good goal), but the industry is already expanding beyond the GraphQL spec with features that are being widely adopted. Apollo has many features like this. As long as the outside interface stays true to and only expands the GraphQL standards then I see additional features as a good thing (as long as standard GraphQL always works as a base.)

The .NET side also has a disadvantage. We don't have the huge ecosystem of NPM and similar packages of small tools. Nuget is great, but it is more focused of full-fledged libraries. NPM fills in the gaps for connecting to back-end data. We don't have as full a toolset on the .NET side (at least for GraphQL.)

graphql-dotnet has focused on being a direct copy of the javascript implementation from the beginning, but .NET isn't javascript and the approaches to programming in the environments are different. I think this has hurt adoption of graphql-dotnet. The initial learning curve is harder than other libraries because of the conceptual impedance mismatch between javascript and .NET concepts.

In my mind, this argues for a more feature rich connection to the data and business layers. Conventions could be an effective part of that. It could give a more familiar approach to regular .NET devs right inside the graphql-dotnet system.

Please don't take any of this as criticism of graphql-dotnet. I love the project and rely on it now for some big projects I am involved in. I just believe that this change would increase adoption of graphql-dotnet and hopefully bring more devs in to support the efforts. The more interest, the more it will grow and get better. I want to see that.

Keep going and good luck on everything.

**Comment by joemcbride** [comment]
@drobertson123 I agree with a lot of what you posted.  At present, there _is_ a convention based approach in the 2.0 codebase (examples posted above).  Granted it is different than what is provided in the `conventions` project, though it is what I can currently support.  As from the start, the `conventions` project was created due to the lack of core contributors.  Tommy did a great job on it, though as it happens, he has no longer been contributing to the core project and instead forked it to add behavior specific to his business needs.  Future goals I had in mind for the project were to be an "instance-based" type system vs. the "type-based" system that the `conventions` project is currently based on.  I honestly just don't have the cycles to be able to support the additional overhead of someone else's code of that size.  There are _dozens_ of issues and features in the core project (and the server project) waiting to be fixed/added.  Any volunteers?

**Comment by drobertson123** [comment]
Conventions is a good project but I am open to any approach to smoother binding between GraphQL and the data/business layer. That is my greatest pain right now. Looking forward to seeing more changes in the future.

I seriously wish I could contribute more but I am buried in the middle of an early stage startup right now. When things settle down I would enjoy giving back to this project. It has been a great base for what we are doing. 

I do have some work that may/may not be useful to the users. Mainly I am trying to simplify the process of schema creation, configuration and DI in an ASP.NET Core 2.0 server. Is there a way to share those items that would be useful?

If the concepts are useful it would be great to hand them off. I may even be able to do a PR if it is worthwhile, but I don't have the bandwidth (or temperament) to do a fully supported extension project.

**Comment by SimonCropp** [comment]
IMO this issue is too large to be tackled. also many of the request dont fit logically under a parent issue. 

I propose we close it. if people still want the specific subitems, they should raise them a standalone issue, or add that context to existing issue.

@sungam3r @joemcbride thoughts?

**Comment by sungam3r** [comment]
I agree. I think such issues are not viable. This is from the category of "let's make the world a better place". I myself often do not mind redoing everything. But after working for some time in the open source, I see that we need to more clearly formulate tasks and set tangible goals. Only by focusing on individual small tasks one can solve them and move forward.
