### ISSUE TITLE
Problem with .net core 2 DI, ISchema Singleton and not Singleton dependencies

### ISSUE THREAD

**Issue by olegBryukhanov** [graphql-dotnet/graphql-dotnet#478]
Hi. I use .net core 2 DI and Microsoft.AspNet.Identity.
AspNet.Identity registered as in ConfigureServices
```csharp
            services.AddIdentity<CustomUser, CustomRole>(x =>
                                                         {
                                                             x.Password.RequireDigit = false;
                                                             x.Password.RequiredLength = 1;
                                                             x.Password.RequireLowercase = false;
                                                             x.Password.RequireNonAlphanumeric = false;
                                                             x.Password.RequireUppercase = false;
                                                         })
                    .AddDapperIdentityFor<PostgreSqlConfiguration, Guid>()
                    .AddDefaultTokenProviders();
```

I have IAccountService interface 
```csharp
    public interface IAccountService
    {
        Task<UserView> RegisterUser(UserRegisterDto request);        
    }
```

and have AccountService realisation of  IAccountService which  uses UserManager<CustomUser> and SignInManager<CustomUser> from Microsoft.AspNet.Identity. AccountService get these dependecies from constructor

```csharp
    public class AccountService : IAccountService
    {
        private UserManager<CustomUser> UserManager { get; }
        private SignInManager<CustomUser> SignInManager { get; }
        private IMapper Mapper { get; }

        public AccountService(UserManager<CustomUser> userManager, SignInManager<CustomUser> signInManager, IMapper mapper)
        {
            Mapper = mapper;
            UserManager = userManager;
            SignInManager = signInManager;
        }
```
IAccountService registered in DI as AddTransient. It can not be as Singletone because UserManager and SignInManager registered as Transient and Transient can not be resolved in Singletons.

```csharp
services.AddTransient<IAccountService, AccountService>();    
```
And I always get an exception
```
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.dll: 'Cannot resolve scoped service 'Trytoremember.Services.GraphQL.Mutations.GraphQLMutation' from root provider.'
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, ServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Trytoremember.Api.Startup.<>c__DisplayClass4_0.<ConfigureServices>b__5(Type type) in /home/olegbryukhanov/repositories/Trytoremember/Trytoremember.Api/Startup.cs:line 105
```
GraphQLMutation uses accountService

```csharp
    public class GraphQLMutation : ObjectGraphType<object>
    {
        public GraphQLMutation(IUserService userService, IAccountService accountService)
        {
            FieldAsync<UserType>(
            "createUser",
            arguments: new QueryArguments(
                new QueryArgument<NonNullGraphType<UserInputType>> { Name = "user" }
            ),
            resolve: async context =>
            {
                var user = context.GetArgument<UserView>("user");
                user = await userService.CreateUser(user);
                return user;
            });

            FieldAsync<UserType>(
                "register",
                arguments: new QueryArguments(new QueryArgument<NonNullGraphType<RegisterUserInput>> { Name = "user" }),
                resolve: async context => {
                    var data = context.GetArgument<UserRegisterDto>("name");
                    var user = await accountService.RegisterUser(data);
                    return user; 
                }
            );

        }

    }
```
and registered as AddScoped ()
```csharp
 services.AddMvc();
            services.AddTransient<IAccountService, AccountService>();            
            services.AddSingleton<IUserService, UserService>();
            services.AddSingleton<IRoleService, RoleService>();
            services.AddSingleton<RoleType>();
            services.AddSingleton<UserType>();
            services.AddSingleton<UserInputType>();
            services.AddSingleton<RegisterUserInput>();
            services.AddSingleton<GraphQLQuery>();
            services.AddScoped<GraphQLMutation>();
            services.AddScoped<IDocumentExecuter, DocumentExecuter>();
            services.AddAutoMapper();
            services.AddSingleton<ISchema>(
                s => new GraphQLSchema(new FuncDependencyResolver(type => (GraphType) s.GetService(type))));      

```
i changed ISchema registration to AddTransient but it did not help me.
```csharp
            services.AddTransient<ISchema>(
                s => new GraphQLSchema(new FuncDependencyResolver(type => (GraphType) s.GetService(type)))); 
```

Can we help me with this trouble?

**Comment by olegBryukhanov** [comment]
I have disabled scope validation in Progrma.cs and it helped me. But it seems to me it is not good idea.
```csharp
        public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseDefaultServiceProvider(options => options.ValidateScopes = false)
                .Build();
```

**Comment by joemcbride** [comment]
> Transient can not be resolved in Singletons

That is not the case.  You can resolve Transient classes in Singletons.  The transient instance resolved just takes on the same lifetime as its parent.  So it would hold onto an instance of the class for the Singleton lifetime.

From my understanding, `Scoped` means `Singleton for this request`.  So you are essentially registering `GraphQLMutation` as a Singleton for the request.  So I think your problem is mixing Singleton and Scoped - your Singleton Schema class (which is alive for the entire lifetime of the application) is requesting a Scoped Mutation class (which should only be a Singleton for only that request).  I believe if you changed your `GraphQLMutation` class to be a Transient or a Singleton itself then the error you are getting will go away.

Note that this Library does its own Caching of types.  So it only attempts to resolve a type once and then caches it.

**Comment by olegBryukhanov** [comment]
@joemcbride I changed GraphQLMutation to singletone and i have got an error 
```
An exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.dll but was not handled in user code: 'Cannot consume scoped service 'AutoMapper.IMapper' from singleton 'Trytoremember.Services.Interfaces.IAccountService'.'
```
because AutoMapper resolves as scoped and uses in my AccountService

**Comment by joemcbride** [comment]
Yep so same issue. You’ll have to change that.  Going to close since this is not an issue with this project.

**Comment by benmccallum** [comment]
Hi @joemcbride , sorry to beat a dead horse here, just wondering if there's a perf hit to be aware of registering the Mutation or Query classes as Scoped or Transient. I'm running into a similar issue using Mediatr in my resolvers. 

Reached out to Jimmy to see if IMediatr can be registered as Singleton, but I'm guessing there's a reason why the default is Scoped so I just want to have a backup plan but be sure performance isn't smashed by whatever happens when a Query or Mutation is setup (fields and all).

Thanks!

**Comment by joemcbride** [comment]
@benmccallum the main thing to be aware of is the internal caching and initialization.  Building a Schema is fairly expensive since the entire graph is walked on initialization.  So the bigger the graph the more expensive it would be to build it.  Since the types are internally cached then they take on the lifetime of the Schema.  So you can certainly change the lifetime, just be aware of those two things and do performance testing.
