### ISSUE TITLE
Query organisation

### ISSUE THREAD

**Issue by Themodem** [graphql-dotnet/graphql-dotnet#515]
Not sure if a bug or im doing something wrong or i dont understand graphql enough 😃 

I have the following structure

```json
{
    "heart": {
        "responses": [
            {
                "user": {
                    "name": "bob"
                    ...
                }
                ...
            }
         ]
    }
}
```

Which i can generate a schema for

```
{
  heart{
    responses{
      user{
        name
      }
    }
  }
}
```

However, executing this returns null

```
{
  "data": {
    "heart": null
  }
}
```

My code is never executed. It is parsed at compile time as i can breakpoint it and see that its called but when i try to execute a query against it its never called.

Here is my code so far

```csharp
Startup.cs

services.AddScoped<ISchema, DashboardSchema>(provider => new DashboardSchema(
    new FuncDependencyResolver(type =>
    {
        var t = (GraphType) provider.GetService(type);
        return t; // breakpoint for debugging hidden exceptions
    }),
    provider.GetService<DashboardQuery>(),
    provider.GetService<DashboardMutation>()
));
```

```csharp
public class DashboardQuery : ObjectGraphType
{
    public DashboardQuery()
    {
        Name = "Query";

        Field<HeartQuery>().Name("heart");
    }
}
```

```csharp
public class HeartQuery : BaseQuery
{
    public HeartQuery(IMemoryCache cache, IHeartRepository heartRepository)
        : base(cache)
    {
        Name = "heart";

        Field<ListGraphType<Types.Heart.Response>>(
            "responses",
            resolve: context => GetOrCache(
                "cache-heartResponses",
                heartRepository.GetResponses,
                TimeSpan.FromMinutes(10)
            )
        );
    }
}
```

```csharp
public class Response : ObjectGraphType<Models.Heart.Response>
{
    public Response()
    {
        Field<StringGraphType>().Name("date").Resolve(_ => _.Source.Date.HasValue
            ? _.Source.Date.Value.ToString("o")
            : new DateTime(1970, 01, 01).ToString("o")
        );
```

If i put the `Field<ListGraphType<Types.Heart.Response>>("responses",` code in the `DashboardQuery` the code is executed and i get back my response however that would mean that all of my queries would have to be top level

**Comment by joemcbride** [comment]
From what you posted, this is the structure I see:

```
{
  "heart": { <-- DashboardQuery
    "responses": { <-- HeartQuery
      "date": "..."  <-- Response
    }
  }
}
```

So if your `Reponse : ObjectGraphType<Models.Heart.Response>` has a `user` field, then that would work.

Are you getting any sort of errors in the response?  Are you sure your `GetOrCache` method is actually returning data?

**Comment by kamsar** [comment]
I suspect this might be the issue:

```
public class DashboardQuery : ObjectGraphType
{
    public DashboardQuery()
    {
        Name = "Query";

        Field<HeartQuery>().Name("heart");
    }
}
```

There's no resolver for the `heart` field, and there's no underlying root object with a `Heart` property to auto-resolve to. Thus, it's resolving to null. It works as a root field, because then there is a resolver function to call.

**Comment by joemcbride** [comment]
@kamsar Good call, yes that seems to be the case.  Not sure why I glazed over that.  😆

**Comment by Themodem** [comment]
Sorry @joemcbride that seems to be the worst copy/paste ive done.

If this was looked at as REST then it could be something like this `/api/heart/responses`

Which would return

```
{
    "responses": [
        {
            "user": { OBJECT... }
        }
    ]
}
```

What i am trying to avoid if possible is massive root level queries for things like `heartResponses` `heartSubmissions` etc.

It would be much nicer to be able to group them to

```
heart{
    responses:[]...
    submissions:[]...
}
```

```
{
  "heart": { <-- API Group
    "responses": [ <-- Controller
      { "date": "..." }  <-- Response
    ]
  }
}
```

Yes the `Models.Heart.Response` does have a user field.

```csharp
Field<User>(
    "user",
    "Response user",
    resolve: context => context.Source.User
);
```

The cache works as expected and returns data.



@kamsar Not sure what you mean by resolver. I can use `Field<HeartQuery>().Name("heart").Resolve(context => ...` but not sure what I would resolve it to?

**Comment by joemcbride** [comment]
You can have your `heart` API Group, but you do have to provide a resolver and return a value.  By default, if a resolver is not provided it tries to resolve the value from the Parent GraphType's Source, which in this case would be null if a `Root` object was not provided in `ExecutionOptions`.  In your case, you can just return `new {}` in the `heart` resolver and that would be sufficient.

```csharp
Field<HeartQuery>("heart", resolve: ctx => new {});
```

**Comment by Themodem** [comment]
@joemcbride, @kamsar Thank you both, it now works as expected 😄

**Comment by joemcbride** [comment]
I’m going to leave this open so we can document this approach.

**Comment by joemcbride** [comment]
Documentation for this is live here: https://graphql-dotnet.github.io/docs/getting-started/query-organization/

Feedback welcome.

**Comment by EmmanuelPonnudurai** [comment]
HI @joemcbride This post has been helpful, however, I am facing a slight organization blip with this structure. In my case, it ends up as as two levels of same verbiage. I'm going by the documentation sample and tweaking a little to explain my situation,

```js
{studentQuery 
  {sudentData(id: 123)
    {id fullName }
  } 
}
```

As you can see here, I am now having to deal with repeated verbiage. `studentQuery`(this is where I have the root query and register all my other types) and then `studentData`(this is from the actual type that i call into from the root query). Since I have to name the item in the root query and provide an empty resolver, I end up with two levels of same verbiage. I am aiming for something just like this,

```js
{sudentData(id: 123)
  {id fullName }
} 
```
Any help would be much appreciated.

**Comment by joemcbride** [comment]
@EmmanuelPonnudurai that is the trade off.  If you don’t have a lot of root queries you can just add them to the root. If you have a lot you can group them with the empty resolver.  You’ll have to decide what works best for your service.

**Comment by EmmanuelPonnudurai** [comment]
Thank you @joemcbride 👍 . I may have something in mind to get around this. If it works, I will be sure to post it here for feedback.

**Comment by danielpox** [comment]
How is this applied to the Schema First approach?

**Comment by joeaudette** [comment]
I encountered this issue because I develop a set of loosely coupled components that I ship as nuget packages and I ship a project template that can wire up the various nugets depending on selected settings.
So for me having to have the main web app know that much about the nugets to create a query and schema for all the selected components didn't seem like a good idea. So I pondered a solution that allows me to create separate Query objects for each of my components (using the GraphType first approach) and automatically aggregate them into one Query and Schema in the app.

I will explain my solution and hope to get some feedback on whether this is a reasonable idea.

First I define a marker interface to decorate my component Query objects:

    public interface IGraphQueryMarker
    {
    }

Then I defined a component Query like this:

    public class CoreQuery : ObjectGraphType<object>, IGraphQueryMarker
    {
        public CoreQuery(
            SiteService siteService
            )
        {
            Name = "CoreQuery";

            Field<ListGraphType<SiteInfoType>>(
                "sites",
                resolve: context => siteService.GetAllSites(context.CancellationToken)
            );
        }
    }


    services.AddSingleton<IGraphQueryMarker, CoreQuery>();

Then I defined a CompositeQuery that depends on an IEnumerable of IGraphQueryMarker

    public class CompositeQuery : ObjectGraphType<object>
    {
        public CompositeQuery(IEnumerable<IGraphQueryMarker> graphQueryMarkers)
        {
            Name = "CompositeQuery";
            foreach(var marker in graphQueryMarkers)
            {
                var q = marker as ObjectGraphType<object>;
                foreach(var f in q.Fields)
                {
                    AddField(f);
                }
            }
        }
    }

So I just inject my component queries as IGraphQueryMarker, and I have a CompositeSchema that uses the CompositeQuery

    public class CompositeSchema : Schema
    {
        public CompositeSchema(IDependencyResolver resolver) : base(resolver)
        {
            Query = resolver.Resolve<CompositeQuery>();
        }
    }

It works, though of course I still need to try something similar for CompositeMutation.

Just wonder does anyone see a problem with this approach?

My main goal is to keep my components loosely coupled while allowing them to be used in various combinations with GraphQL.
