### ISSUE TITLE
define ResolveType for interface definitions

### ISSUE THREAD

**Issue by hatami57** [graphql-dotnet/graphql-dotnet#593]
Suppose this example:

```
public class Droid
{
  public string Id { get; set; }
  public string Name { get; set; }
}

public class Query
{
  [GraphQLMetadata("hero")]
  public Droid GetHero()
  {
    return new Droid { Id = "123", Name = "R2-D2" };
  }
}

var schema = Schema.For(@"
  interface Node {
    id: String
  }
  type Droid implements Node {
    id: String
    name: String
  }

  type Query {
    hero: Node
  }
", _ => {
    _.Types.Include<Query>();
});

var result = schema.Execute(_ =>
{
  _.Query = "{ hero { id ... on Droid { name } } }";
});
```
I need to define ResolveType method for interface `Node`. I found this way:

`_.Types.For("Node").ResolveType = obj => { /* needs to return an ObjectGraphType here */ };`
the `ResolveType` gets a Droid object as input, but it needs an `ObjectGraphType` object! In NodeJS I could just return the resolved type as string like "Droid".

Is there any work around without defining new classes inheriting from `ObjectGraphType`?

**Comment by joemcbride** [comment]
I would suggest to use IsTypeOf instead.  The IGraphTypes are defined in the Schema class for you, though ResolveType is not optimal.

https://github.com/graphql-dotnet/graphql-dotnet/blob/ea0a324eb659c309fa70adced3aac5c5922c6a30/src/GraphQL.Tests/Utilities/SchemaBuilderExecutionTests.cs#L92-L132

**Comment by joemcbride** [comment]
You can read more about `IsTypeOf` vs. `ResolveType` here:

https://graphql-dotnet.github.io/getting-started/#istypeof
https://graphql-dotnet.github.io/getting-started/#resolvetype

Especially in large domains I would highly suggest to not use `ResolveType` (as it is required to be exhaustive), if nothing else just for maintainability and de-coupling.

I have not done any performance testing between the two definition patterns with those numbers.  I would not expect there to be any significant difference (they both essentially use the same patterns), though only the numbers would tell us.  The text-based schema definition may use a bit more reflection, so that could show with that type of load.  Compiled funcs or generated classes would be faster, though I haven't been able to fully look into that yet.  The major things that could be done to increase performance mostly seem to be query validation and metrics.  So if your domain is executing the same queries or mutations over and over, you could use "compiled queries", a pattern where the server is already familiar with that query.  Do so you could bypass validation since it already knows it is valid and already have a pre-parsed re-usable `Document` cached in memory.

Field middleware has be identified as particularly slow (it needs a bit of a re-design), and that is what Metrics currently uses.  So I would suggest to disable that.

We have some rudimentary performance tests here: https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.Tests/Execution/Performance

See here for a discussion on performance: https://github.com/graphql-dotnet/graphql-dotnet/issues/435

**Comment by meteor57** [comment]
Thank you for mentioning helpful notes!
You saved me a lot of time 😊

**Comment by joemcbride** [comment]
Can you talk to as per _why_ you would want to use `ResolveType` over `IsTypeOf`?  Do you have a specific scenario or just looking for parity?  From what I understand, Apollo also supports [`__isTypeOf`](https://github.com/apollographql/graphql-tools/blob/a97e6b3e10b971038761fe511d9a14ee3fa94bd5/src/Interfaces.ts#L28) as well as [`__resolveType`](https://github.com/apollographql/graphql-tools/blob/a97e6b3e10b971038761fe511d9a14ee3fa94bd5/src/Interfaces.ts#L27) (though it does not appear to be documented).



Taken that example given, to be able to add another `Vehicle`, say `Boat`, you would have to make the `Boat` type _and_ edit the `ResolveType` function for `Vehicle`.  Otherwise you would never be able to use`Boat`, even though it was added as a type.  Using `IsTypeOf` all you need to do is add `Boat` and any other number of types that implement `Vehicle` and you don't need to ever edit `Vehicle`.

The idea here being that `IsTypeOf` follows [Open/Closed principle](https://en.wikipedia.org/wiki/Open/closed_principle) and `ResolveType` does not.  I've found that `ResolveType` is a "gotcha" that people new to GraphQL run into.

**Comment by joemcbride** [comment]
Just a note to myself:

Could return a `GraphQLTypeReference` and have the engine find the real type if that is what is returned.  Could also change the signature of `ResolveType` to supply the `Schema` or a context class that contained the Schema.

`return new GraphQLTypeReference("Car")`

**Comment by meteor57** [comment]
The scenario in my mind is that instead of defining a `IsTypeOf` method for all types, I could just use a single `ResolveType` method with a single line of code! The way I did it before in NodeJS using Apollo GraphQL Tools.
In that library, if you have a `ResolveType` method, when it wants to resolve the type of an interface, it just calls the `ResolveType` method once (so time complexity is `O(1)`), however if you define `IsTypeOf` for each type, it needs to call it for all the types (until the right type is found)! so for `n` types, its time complexity is `O(n)`.

if we could do something like:
`Builder.Types.For("Vehicle").ResolveType = obj => obj.GetType();
`
or as you noted:
`Builder.Types.For("Vehicle").ResolveType = obj => new GraphQLTypeReference(typeof(obj).Name)`

In this way you can add any number of types without changing `ResolveType` method or defining `IsTypeOf` for them.

**Comment by joemcbride** [comment]
Makes sense.  Taking a look, with the recent changes made to support `DataLoader` making changes to support either of those scenarios I mentioned is going to be harder than I thought.

**Comment by Shane32** [comment]
@sungam3r I suggest closing this issue.  ResolveType has an inherit issue with DI as we have seen previously.  I would not extend the functionality (and the problem) to interface types, and there has no comments on this issue for 5 years.

**Comment by sungam3r** [comment]
OK.
