### ISSUE TITLE
Do not swallow all exceptions

### ISSUE THREAD

**Issue by jinhong-** [graphql-dotnet/graphql-dotnet#607]
Framework swallows all exceptions in the resolve function. I think this should not be the case or at least have some sort of customization exception handler for developer to decide. Reason being not all errors should be HTTP error codes of 400, which represents client errors. Some error codes should be HTTP 500 codes instead as they might be server side errors

**Comment by kamsar** [comment]
IMO the current behavior is fine. GraphQL doesn't really need HTTP status codes with the GQL protocol already including the ability to return errors. The returned errors themselves determine the type of error that occurred, and there is already control over that (`context.Errors` in the resolver).

In other words, GraphQL != REST. In this particular case to not catch and re-emit exceptions as a GraphQL error would not be following the GQL protocol because a query can be partially resolved when an error occurs.

**Comment by jinhong-** [comment]
I disagree. Have a read on HTTP Status codes: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
According to HTTP specs, not REST specs, it is said that 4XX represents client side errors and 5XX represents server side errors.
While I do agree with you that there could be potential scenarios that you might want to return partial results, that should be something that the developer should choose to handle. The library itself should not be concerned with catching all exceptions, just like it should not be concerned with handling transient faults and retries.
I think there are a couple of ways to handle this. One is to remove the catch all exception handler and allow the user to throw their own Validation or Execution exception. Or we could just use the field middleware to handle the exception in a custom manner. I think the foundation is there. We just need to allow custom behavior and not swallow the exception

**Comment by jinhong-** [comment]
If this is the behavior we want for this library, then maybe we need to figure out custom handling for the graphql server instead

**Comment by joemcbride** [comment]
Related: #564

**Comment by wingsking** [comment]
I'm in the same boat with you @jinhong- 
I need to intentionally throw an exception so that my service can return 500 under some circumstances. The way I think how it should work is to provide a "ThrowException" swutch in ExecutionOption, just like "ExposeException". And it should check this inside the catch block to determine whether the non-ExecutionError exceptions should be swallowed or re-thrown.
Alternatively, we can remove all catch blocks that catch general Exceptions, but keep the catch blocks that catch ExecutionErrors. In this way, if we want to handle the exception ourselves, we can throw a Exception; otherwise we can catch these exceptions ourselves, say in the resolvers, and turn it into ExecutionErrors which should be added to context.Errors.

What do you think?

**Comment by alexandervantrijffel** [comment]
It would be great if I can subscribe to an event similar to the [AppDomain.UnhandledException](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx) event. With such a callback, I would have a mechanism to log the unexpected exception.

**Comment by joemcbride** [comment]
Thought on this for a while.  I'm going to go with adding an option to `ExecutionOptions` to re-throw unhandled generic `Exception` while still catching and handling `ExecutionError`.
