### ISSUE TITLE
Mutation with a dynamic schema throws "Cannot query field ..."

### ISSUE THREAD

**Issue by alexolex** [graphql-dotnet/graphql-dotnet#613]
Hi there.

I am facing a problem with a mutation that has a field defined using the "AddField" method. I use this method to build a schema dynamically. Same approach I use for building query types and that works perfectly.

This issue can be reproduced by rewriting the StarWarsMutation class like this 

```
    public class StarWarsMutation : ObjectGraphType<object>
    {
        public StarWarsMutation(StarWarsData data)
        {
            Name = "Mutation";
            AddField(new FieldType
            {
                ResolvedType = new HumanType(data),
                Name = "createHuman",
                Arguments = new QueryArguments(
                    new QueryArgument<NonNullGraphType<HumanInputType>> { Name = "human" }
                ),
                Resolver = new FuncFieldResolver<Human>(context =>
                {
                    var human = context.GetArgument<Human>("human");
                    return data.AddHuman(human);
                })
            });
        }
    }
```

and running the test 
```
can_add_new_human
```
The exception message says 

> "Cannot query field \"name\" on type \"Human\". Did you mean \"Name\"?"". 

Is it a bug or I am missing something?

**Comment by joemcbride** [comment]
That error means there is not a field defined on `Human` with the value of `name` - but there is one with `Name`.  So in your query you should be using `Name` instead of `name`, or change the field on `Human` to be `name`.

```csharp
ResolvedType = new HumanType(data)
```

The above is a code smell and could lead to issues.  Namely, it could lead to multiple instances of the `HumanType` and you would start to see odd behavior.  If you need to inject data, use an IOC container instead of trying to manually construct the `ResolvedType` like this.  Constructing your own `FieldType` means you need to do a lot of the configuration yourself.  If you want to go that route I would suggest to look at the code in `ComplexType` which has a number of helper methods to properly construct a `FieldType`.

If you are trying to dynamically build a schema, I would suggest to look at [`SchemaBuilder`](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/SchemaBuilder.cs) and utilize `GraphQLTypeReference` where you need to dynamically reference other types.

**Comment by alexolex** [comment]
Thank you very much for your response!

Regarding the error
---

> So in your query you should be using Name instead of name, or change the field on Human to be name.

I thought field names are camel-cased automatically, aren't they?

After capitalizing first letters of field names, like this:
```
var mutation = @"mutation ($human:HumanInput!){ createHuman(human: $human) { Name HomePlanet } }";
```
(same test ```can_add_new_human```)

it resulted in an error saying:

> Error trying to resolve createHuman.

(Although this time it enters the field's resolver, adds Boba Fett and fails somewhere afterwards).

I will find time to debug it further.

Regarding my case
---
I do need to build a schema dynamically, since it depends on a data source which a query targets. Multiple data sources with different data schemas lead to the need to construct it dynamically.

To build a Query part of the schema I used the approach of instantiating a type and adding a ```FieldType``` with its ```ResolvedType``` set to that instance (there is only one type instance per a field, I am sure).

And since that worked out as expected, I attempted to take the same approach while implementing a Mutation part.

I will take a closer look at ```ComplexType```, ```SchemaBuilder``` and ```GraphQLTypeReference``` as you suggested. Thank you.

Tell me please, are mutations supposed to work with a dynamically constructed schema the way I am trying to make them work?

**Comment by joemcbride** [comment]
> I thought field names are camel-cased automatically, aren't they?

Fields are cased based upon the setting in `Schema.FieldNameConverter`, which defaults to `CamelCaseFieldNameConverter`.

> are mutations supposed to work with a dynamically constructed schema the way I am trying to make them work?

You are probably experiencing the issue I spoke of due to how you have it constructed.  There should only ever be 1 instance of a given GraphType for a given Schema.  So `new HumanType(data)` tells me that there could be more than 1 instance since you are manually creating that GraphType.  That instance should also be registered with the Schema.  So if you have a `new HumanType` anywhere, that should immediately be followed by a `schema.RegisterType(humanType)`.

The field names are probably not using `FieldNameConverter` due to that manual creation of `HumanType` and it not being registered with the Schema.

**Comment by joemcbride** [comment]
@mike-niemand your issue appears to be using an Input Type as a return type.  You need a different GraphType as the return type for the field definition.

```
Field<ConsultantInputType> -> Field<ConsultantType>

public class ConsultantType : ObjectGraphType<VMConsultant>
```

**Comment by alexolex** [comment]
@joemcbride You are exactly right. 
By looking at source of the ```Schema``` and ```SchemaBuilder``` classes I finally understood how it works. 

Thanks alot for your time and your efforts!

**For those who may need it.**
I made it work by implementing own schema builder that:
- keeps a dictionary of all dynamically instantiated types;
- immediately calls ```schema.RegisterType``` for every newly added type;
- and provides a ```GraphQLTypeReference``` instance for a field that needs a registered type.

Issue's been resolved. Thanks!
