### ISSUE TITLE
Remove FieldDelegate

### ISSUE THREAD

**Issue by MisinformedDNA** [graphql-dotnet/graphql-dotnet#617]
There really is no need for `ComplexGraphType.FieldDelegate`. Anything you can do with it, you can do it better with `ComplexGraphType.Field`. `FieldDelegate` uses reflection so it is slow and relies on parameter matching, whereas `Field` gives the user exactly what they ask for.

Also, it's not even immediately clear what `FieldDelegate` is and how it compares to `Field`. You have to look closely.

I don't see a reason to keep it. Thoughts?

**Comment by joemcbride** [comment]
They are essentially functionally equivalent when it gets executed, though it provides different features such as resolving the arguments for you strongly typed.  I can see removing that from the example since it creates confusion, though it provides a different purpose (and was a contribution by someone in the community that DID want the feature).

**Comment by MisinformedDNA** [comment]
The question isn't if someone wanted it, the question is if it belongs and provides additional value. If you aren't sure what value it provides, you should consider either finding out what/if any value it provides or deprecate it. Just my 2 cents.
