### ISSUE TITLE
DefaultValue as an argument to a Field method

### ISSUE THREAD

**Issue by MNie** [graphql-dotnet/graphql-dotnet#712]
I'm curious why `defaultValue` couldn't be set when adding a field like that:

```csharp
this.Field<IntGraphType>("name", defaultValue: 12);
```

Instead of this I have to write a code like this:
```csharp
this.Field<IntGraphType, int>().Name("name").DefaultValue(12);
```

Pull Request which would add a default value parameter to a [`ComplexGraphType`](https://github.com/graphql-dotnet/graphql-dotnet/blob/cc5d15fe68563b206e713d2144e6af9217860630/src/GraphQL/Types/ComplexGraphType.cs) `Field` methods would be accepted or I have to live with that?

CC: @joemcbride

**Comment by MNie** [comment]
@joemcbride make sense them to not adding it as an argument. I was curious not from a graphql specifications side, but from a user experience, thanks for an answer! :)

**Comment by joemcbride** [comment]
So may want to keep this open so we can _remove_ that from `FieldType`.

**Comment by MNie** [comment]
@joemcbride so you think it would be sensible to remove implementation of a `IHaveDefaultValue` from a `FieldType`?

**Comment by algodfried** [comment]
The spec seems to indicate that input objects can have default values:

3.10
Input Objects
InputObjectTypeDefinition
DescriptionoptinputNameDirectivesConstoptInputFieldsDefinitionopt
InputFieldsDefinition
{InputValueDefinitionlist}
Fields may accept arguments to configure their behavior. These inputs are often scalars or enums, but they sometimes need to represent more complex values.
A GraphQL Input Object defines a set of input fields; the input fields are either scalars, enums, or other input objects. This allows arguments to accept arbitrarily complex structs.
In this example, an Input Object called Point2D describes x and y inputs:
Example № 74
input Point2D {
  x: Float
  y: Float
}
Note
The GraphQL Object type (ObjectTypeDefinition) defined above is inappropriate for re‐use here, because Object types can contain fields that define arguments or contain references to interfaces and unions, neither of which is appropriate for use as an input argument. For this reason, input objects have a separate type in the system.
Result Coercion
An input object is never a valid result. Input Object types cannot be the return type of an Object or Interface field.
**Input Coercion
The value for an input object should be an input object literal or an unordered map supplied by a variable, otherwise a query error must be thrown. In either case, the input object literal or unordered map must not contain any entries with names not defined by a field of this input object type, otherwise an error must be thrown.
The result of coercion is an unordered map with an entry for each field both defined by the input object type and for which a value exists. The resulting map is constructed with the following rules:
If no value is provided for a defined input object field and that field definition provides a default value, the default value should be used. If no default value is provided and the input object field’s type is non‐null, an error should be thrown. Otherwise, if the field is not required, then no entry is added to the coerced unordered map.
If the value null was provided for an input object field, and the field’s type is not a non‐null type, an entry in the coerced unordered map is given the value null. In other words, there is a semantic difference between the explicitly provided value null versus having not provided a value.
If a literal value is provided for an input object field, an entry in the coerced unordered map is given the result of coercing that value according to the input coercion rules for the type of that field.
If a variable is provided for an input object field, the runtime value of that variable must be used. If the runtime value is null and the field type is non‐null, a field error must be thrown. If no runtime value is provided, the variable definition’s default value should be used. If the variable definition does not provide a default value, the input object field definition’s default value should be used.**
