### ISSUE TITLE
Use cake-build for build process instead of nodejs scripts

### ISSUE THREAD

**Issue by Meir017** [graphql-dotnet/graphql-dotnet#716]
We shouldn't have to instead nodejs and run npm/yarn install in order to build/test the project.

The build process should be similar to what https://github.com/graphql-dotnet/server does

**Comment by jquense** [comment]
You can still build and test via the dotnet cli if you want, but running any of the examples or frontend bits require node for the frontend tooling so for the full end to end build it's needed anyway. Using not-node for frontend stuff is a chore in and of itself at this point

**Comment by Meir017** [comment]
which part of this repo uses `nodejs`? the only parts I found are the build scripts and the docs site

**Comment by joemcbride** [comment]
The test harness uses node for GraphiQL.  I’ve used cake and rake on other projects.  I find node to be much easier to use and it’s nice not to have to swap between stacks. On projects that I used cake I also ran cake from node to make cross platform building easier (since you have to use a different entry for cake depending on the platform).  I build on both macOS and Windows.  The main contributors decided to use cake on the server project.  That’s fine, that’s their preference.
