### ISSUE TITLE
One field, multiple possible arguments

### ISSUE THREAD

**Issue by Perlkonig** [graphql-dotnet/graphql-dotnet#719]
Perhaps this is just a lack of general GraphQL knowledge. If so, I apologize.

I have a `user` field set up as shown in the Arguments section of the docs. So I can query my data source for a user by `id`. But what if I want them to be able to search by different fields as well? Or get a list of all users? If I create multiple `Field<UserType>("user", ...)` entries, it throws an error. 

```graphql
{
  user(id: 1) {
    name, country
  }
}
```

The above works just fine. But I want to support the following as well:

(All users asserting to be from Canada)
```graphql
{
  user(country: "CA") {
    name, country
  }
}
```

(All users)
```graphql
{
  user {
    name, country
  }
}
```

I appreciate your time!

**Comment by joemcbride** [comment]
You would need two different fields for that.

```graphql
type User {
  id: ID!
  name: String!
}

type Query {
  user(id: ID!): User
  users(country:String): [User!]!
}
```

`!` signifies that a value is non-null.

**Comment by joemcbride** [comment]
(P.S. You can see a view of your Schema in that syntax by using `SchemaPrinter`).

```csharp
Console.WriteLine(new SchemaPrinter(schema).Print());
```

**Comment by Perlkonig** [comment]
I'm not sure what to do with this. The following code works:

```csharp
Field<UserType>(
    "user",
    arguments: new QueryArguments(new QueryArgument<StringGraphType> { Name = "id" }),
    resolve: context =>
    {
        var id = context.GetArgument<string>("id");
        return db.Owners.Include(x => x.OwnersNames).Single(x => x.OwnerId.Equals(GuidGenerator.HelperStringToBA(id)) && !x.Anonymous);
    }
);
```

The following does not:

```csharp
Field<UserType>(
    "users",
    arguments: new QueryArguments(new QueryArgument<StringGraphType> { Name = "country" }),
    resolve: context =>
    {
        var country = context.GetArgument<string>("country");
        if (String.IsNullOrWhiteSpace(country))
        {
            return db.Owners.Include(x => x.OwnersNames).Where(x => !x.Anonymous).ToArray();
        }
        else
        {
            return db.Owners.Include(x => x.OwnersNames).Where(x => x.Country.Equals(country) && !x.Anonymous).ToArray();
        }
    }
);
```

I'm told `Expected value of type "abstractplay.GraphQL.UserType" but got: abstractplay.DB.Owners[].` But there's no casting that happens in the working code. So what am I supposed to do differently with this new code that returns multiple results?

**Comment by joemcbride** [comment]
Change `Field<UserType>(..)` to `Field<ListGraphType<UserType>>(...)`

**Comment by joemcbride** [comment]
Here's a good tutorial that goes through a lot of things and uses EF.  http://fiyazhasan.me/tag/graphql-dotnet/

**Comment by Perlkonig** [comment]
Many thanks. I'll walk through that. Thanks for your patience with my questions. Again, if you're open, I'll submit a docs PR once I get things working. There's some foundational stuff that might be helpful. Then again, maybe it's just me 😄

**Comment by joemcbride** [comment]
I think it would be helpful.  I was just looking at the basic StarWars example and it doesn't show returning a list of data.  So it would be helpful for sure.  This example has a few more features too: https://github.com/graphql-dotnet/example-orders

**Comment by eugenpaval** [comment]
I implemneted slightly different sorting, filtering and grouping inspired by Linq actually! In Linq you have pipes described by expressions which defer execution till it reaches a materializing expression. This is described very well in Linq ecosystem. For example users.Where(u => u.ID == givenID) is not excuted immediately but rather when a GetEnumerator() is called on that and even then only for the elements that are enumerated. Also, there is System.Linq.Dynamic nuget package which basically implements a good part of Linq by using string expressions. For my example I would then have users.Where("ID == givenID").

In your example then instead of creating multiple properties to basically just do filtering I would have
`type Users
{
     where(exp: String!): Users!
     select: [User!]!
}

type User
{
     id: String!
     name: String!
     country: String!
 }`

You can just imagine how this works with OrderBy and GroupBy as well (just follow Linq paradigm). The only downside is the variable shape of the output since where, orderBy and groupBy properties are going to appear in the output a variable number of ways depending on the query. My solution for that was to use in the query renaming of properties, which is a GraphQL feature and then use JsonPath to get to the actual results.

Thinking more about it, a better implementation would be to just use directives for where and orderBy since they do not actually modify the shape of the result. This would be my next implementation.

**Comment by stysiok** [comment]
@Perlkonig I encourage you to view this example project by Jacek Kosciesza. It has basic instruction step by step how to implement GraphQL server based on graphql-dotnet. Hope it will help you.
[Star Wars GraphQL by Jacek Kosciesza](https://github.com/JacekKosciesza/StarWars)

**Comment by Perlkonig** [comment]
I have been, but it also does not illustrate or explain what to me seem to be fundamental aspects of the library. Again, it could just be that I'm thick, but I'm having to do a lot of reading between the lines. 

It doesn't help that there's a lot of text (especially in the Jacek example) talking about the data layer and HTTP layer. That's not bad in and of itself, but the library itself should be front and center. I just think the documentation could benefit from some more focus (I say this as a professional editor).

I'll do a PR that shows what I mean and that we can discuss.

**Comment by espray** [comment]
@eugenpaval do you have a sample of this technique?

**Comment by Perlkonig** [comment]
See pull request #721

**Comment by eugenpaval** [comment]
@espray I put together a sample: [https://github.com/eugenpaval/graphql-linq-sample](url)
 A possible query would be:
`query Test
{
  products
  {
    where(exp: "category == \"Category-1\" or category == \"Category-2\"")
    {
      orderBy(exp: "category, name desc")
      {
        select
        {
          name
          category
          price
        }
      }
    }
  }
}`
