### ISSUE TITLE
Schema with mutation + query

### ISSUE THREAD

**Issue by Perlkonig** [graphql-dotnet/graphql-dotnet#725]
The only example of a schema with both query and mutation is in the mutations section:

```csharp
public class StarWarsSchema : Schema
{
    public StarWarsSchema(Func<Type, GraphType> resolveType)
        : base(resolveType)
    {
        Query = (StarWarsQuery)resolveType(typeof (StarWarsQuery));
        Mutation = (StarWarsMutation)resolveType(typeof (StarWarsMutation));
    }
}
```

But there's no example of actually instantiating this class. Where does this `Func<>` come from? If I go into the StarWars example, it looks like it's only instantiated in `StarWarsTestBase.cs`:

`Services.Singleton(new StarWarsSchema(new FuncDependencyResolver(type => Services.Get(type))));`

But I have no idea what this `FuncDependencyResolver` is.

What is the simplest way to create a schema that includes both a query and a mutator and that accepts a database context as well?

I tried the following, but I keep getting `Error trying to resolve createProfile` when I try to actually execute a mutation.

```csharp
public APSchemaRW(MyContext db)
{
    Query = new APQuery(db);
    Mutation = new APMutator(db);
}
```

I can provide the surrounding code if you want. Thank you again for your time!

**Comment by joemcbride** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/fbfc8c3ebe86fbeed7ca5ccb378252cb9e994ae9/src/GraphQL/Types/Schema.cs#L64-L71

Providing a `Func<Type, IGraphType> resolveType` is [the old way of providing Dependency Injection for a Schema](https://graphql-dotnet.github.io/learn/#dependency-injection).  This has been replaced with an `IDependencyResolver` interface in 2.0, which [the docs have not been updated yet to display](https://github.com/graphql-dotnet/graphql-dotnet/issues/440).  [The examples show this in use.](https://github.com/graphql-dotnet/examples/blob/a62468ebd08e6241502a33a9ff3bc5d33a9ea0ae/src/AspNetCoreCustom/Example/Startup.cs#L18)

Also - I know you have a lot of questions.  Since you have a lot of questions, can you please just keep them in a single issue instead of creating so many different ones?  We can open separate issues if there are specific tasks or features that need to be done.

**Comment by Perlkonig** [comment]
Thanks. I will try to figure this out. 

I'm happy to keep my questions in this thread if you like. I apologize. In other situations I've been asked to keep them separate 😄 

I do appreciate your assistance. This is the first library I've found that works in my scenario (EFCore + AWS Lambda), so I'm motivated to figure things out, but the docs are a stumbling block.

**Comment by Perlkonig** [comment]
The further down the rabbit hole I go, the more frustrated I get. Adding a query was the simplest thing in the world. But from the sample code, it looks like to add a mutation I have to add all this other cruft, and I can't tell how much of this is ASP specific and how much is actually essential to making things work.

I tried installing 2.0.0 and using `IDepedencyResolver` but couldn't see a way to pass the database context down the chain. I went back to 0.17.3 because queries are at least working there.

Is there a reason the library can't abstract away most of this? Why can't we simply do `Mutation = new MyMutation(dbContext);` like we do for adding a query?

Sorry. This all just feels much more complicated than it needs to. I'll walk through [Fizz's tutorial](http://fiyazhasan.me/graphql-with-asp-net-core/) again and see if I can see what I'm missing. He talks about dependency injection, but it appears to be ASP specific. I'm in an AWS Lambda context. I just need a standalone function to spin up; accept clear, already-processed input; instantiate a schema; and execute the input. 

For example, here's the totality of the function that processes read-only queries:

```csharp
public async Task<APIGatewayProxyResponse> GraphQL(APIGatewayProxyRequest request, ILambdaContext context)
{
    string query = request.QueryStringParameters["query"];
    var schema = new APSchemaRO(dbc);
    var result = await new DocumentExecuter().ExecuteAsync(_ =>
    {
        _.Schema = schema;
        _.Query = query;
    }).ConfigureAwait(false);
    var json = JsonConvert.SerializeObject(result, Formatting.Indented, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });

    var response = new APIGatewayProxyResponse
    {
        StatusCode = (int)HttpStatusCode.OK,
        Body = json,
        Headers = new Dictionary<string, string> { { "Content-Type", "application/json; charset=utf-8" } }
    };

    return response;
}
```

**Comment by joemcbride** [comment]
Please use the original thread you opened and not this closed one.  The reason I ask is so that I don't have to keep jumping between issues to answer questions.

> Is there a reason the library can't abstract away most of this? Why can't we simply do Mutation = new MyMutation(dbContext); like we do for adding a query?

You can.  There is literally no difference in the code you write for a mutation vs. a query.  The engine does execute them differently - a mutation is executed serially whereas a query is executed in parallel.
