### ISSUE TITLE
Lost task exception in ParallelExecutionStrategy

### ISSUE THREAD

**Issue by SapphireBrand** [graphql-dotnet/graphql-dotnet#781]
## Description

I am seeing tasks whose exception is not observed, which later causes an exception when the task is garbage collected

### Steps to reproduce
In ParallelExecutionStrategy.cs there is the following code around line 21:

                // Start executing all pending nodes
                for (int i = 0; i < pendingNodes.Count; i++)
                {
                    context.CancellationToken.ThrowIfCancellationRequested();
                    currentTasks[i] = ExecuteNodeAsync(context, pendingNodes[i]);
                }

ThrowIfCancellationRequested will throw an exception if the current request has been cancelled. However, existing tasks have been queued, so they might throw exceptions. Since the Task.WhenAll is after the loop, those exceptions will not be awaited.

Therefore, to trigger the bug, you should have tasks that will fail but not be cancelled. For example, a synchronous node can throw an exception.

### Expected result

All tasks should be cancelled.

(If the node is async then it should use the cancellation token directly. But I think that synchronous fields could have exceptions that are not observed.)

### Actual result

I am seeing lost exceptions on synchronous fields.

### Environment

I don't think the environment matters, but it was GraphQl 2.0.0-alpha-978, .Net 4.6.2 on 64-bit Windows 7, using Any CPU platform target.

**Comment by joemcbride** [comment]
Think you could write a test to demonstrate this behavior?

**Comment by sungam3r** [comment]
I did some research and am not sure that this is a bug. First, it must be said that the described behavior will be only in the case of setting `ExecutionOptions.ThrowOnUnhandledException = true`. Otherwise, all errors are [intercepted here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionStrategy.cs#L252) and the created tasks **always** (except of exotic exceptions like `StackOverflowException` or `ThreadAbortException` which I do not consider) go to the `RanToCompletion` state with some execution error in context and null result.

If `ExecutionOptions.ThrowOnUnhandledException = true` then such a situation with unobserved exception does arise, but not for every exception.

Let's take an example:
```c#
using GraphQL.Types;
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

namespace GraphQL.Tests.Bugs
{
    public class Bug781UnobservedFaultedTasks
    {
        [Fact]
        public void cancel_execution_should_not_create_zombie_tasks()
        {
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
            var cts = new CancellationTokenSource();
            ISchema schema = new Bug781Schema(cts);

            try
            {
                var result = schema.Execute(options =>
                {
                    options.Query = "{ do cancellation never }";
                    options.CancellationToken = cts.Token;
                    options.ThrowOnUnhandledException = true; // required
                });
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }

            while (true)
            {
                GC.Collect(); // GC causes UnobservedTaskException event
                GC.WaitForPendingFinalizers();
            }
        }

        private void TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
        {
            Console.WriteLine("Unobserved exception: " + e.Exception);
        }
    }

    public class Bug781Schema : Schema
    {
        public Bug781Schema(CancellationTokenSource cts)
        {
            Query = new Bug781Query(cts);
        }
    }

    public class Bug781Query : ObjectGraphType
    {
        public Bug781Query(CancellationTokenSource cts)
        {
            // First field with long calculation emulation
            FieldAsync<StringGraphType>(
                "do",
                resolve: async ctx =>
                {
                    await Task.Delay(10);
                    cts.Token.WaitHandle.WaitOne();

                    throw new Exception("Hello!");
                    //throw new OperationCanceledException();  // in this case there will be no unobserved exception event
                });

            // Second field causes cancellation of schema execution
            Field<StringGraphType>(
               "cancellation",
               resolve: ctx =>
               {
                   cts.Cancel();
                   return "cancelled";
               });

            // The third field is necessary for the control to fall on the context.CancellationToken.ThrowIfCancellationRequested() instruction.
            Field<StringGraphType>(
               "never",
               resolve: ctx => throw new Exception("Never called"));
        }
    }
}
```

> If the node is async then it should use the cancellation token directly. But I think that synchronous fields could have exceptions that are not observed.

The point is rather not about cancellation token itself and not about "synchronous " or "asynchronous" fields. The point is what type of exception does the task generate? A task (in resolver) can honestly handle a token from context (`ResolveFieldContext.CancellationToken`), but it can easily throw out some other logic-specific exception in the interval between checking a token. This exception will cause the task to go to `Faulted` status. And since the developer explicitly set the `ExecutionOptions.ThrowOnUnhandledException = true` property, he will receive an honest `UnobservedTaskException` event.

If a resolver generates `OperationCanceledException`, then the task will go to `Canceled` state and there will be no `UnobservedTaskException` side effect.

Thus, I cannot call the described situation an error. All possible cases make sense. In addition, `UnobservedTaskException` is [no longer as dangerous as before](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception?view=netcore-2.0#remarks) and does not lead to an abnormal termination of the process.

@joemcbride Any thoughts?

**Comment by Shane32** [comment]
@sungam3r I think this should be reviewed again.  I think you said that the effect can only happen when `ThrowOnUnhandledException = true`.  It would seem that `context.CancellationToken.ThrowIfCancellationRequested();` in `ParallelExecutionStrategy.ExecuteNodeTreeAsync` executes outside of the `try..catch` block, and can throw an `OperationCanceledException` before awaiting tasks it may have queued.  Am I missing something?  It may not change the decision here, but please confirm.

**Comment by Shane32** [comment]
In fact, it doesn't look like asynchronous exceptions are caught by the execution strategy at all !?!???

**Comment by Shane32** [comment]
Since the `await` also does not occur within a `try..catch` block (besides in the document executer).  So if an `ExecutionError` is thrown, it isn't caught. Please confirm

**Comment by Shane32** [comment]
Nevermind those last 2 comments.  Duh.  Of course they are caught inside `ExecuteNodeAsync`

**Comment by Shane32** [comment]
So the 'lost task' execute the rest of `ExecuteNodeAsync` which catches the unhandled exception.  Ok now I understand.  So nevermind @sungam3r .  Just took me a minute to figure out why you were of course correct to begin with.

**Comment by Shane32** [comment]
Personally, I'd agree with your assessment of the situation, and that it is reasonable for a `UnobservedTaskException` to be thrown when `ThrowOnUnhandledException = true`, considering that it doesn't crash the process by default.

**Comment by sungam3r** [comment]
I already managed to get scared that something was wrong. I'll leave it open for now.

**Comment by Shane32** [comment]
I ran additional tests yesterday on this issue.  It is certainly possible with asynchronous tasks to create unobserved task exceptions when `ThrowOnUnhandledException` is `true`.  I can manually create an synchronous task containing an exception - indeed, `Func<Task> fn = async () => new Exception(); var task = fn();` can do exactly that.  But since the next line of code after `ExecuteNodeAsync` checks `task.IsCompleted` and then awaits the task, I don't see how a synchronous task could possibly be unobserved.  Perhaps the codebase has changed since 2018.

In any case, these unobserved tasks could be masked, but then what's the point of the `TaskScheduler.UnobservedTaskException` event handler?  It seems that it was created exactly for that purpose - to report unobserved task exceptions!

It would seem that the current behavior is appropriate for the situation, considering that the default behavior for all targeted platforms is not to terminate the process.  Even when I changed the registry key as specified in the docs, and ran the code on .Net 4.7.1, I couldn't get it to terminate the process - although I probably did do something wrong, since it clearly should with the proper settings.  I don't think it's possible in .Net Core to have it terminate the process at all.

Let's close this issue.

**Comment by sungam3r** [comment]
I can hardly remember the problem. I just remember that I was completely sure that everything was working as it should. I still have a local branch with my experiment. Is it worth to make PR with test?

**Comment by Shane32** [comment]
Tests are not stable since calling GC.Collect does not reliably raise the event without adding artificial delays. Besides the test would be a "negative" test - testing that we "didn't fix" something, whereas if it was "fixed" then that's no worse than it is now. I would close it as-is.

**Comment by sungam3r** [comment]
In fact, a second's wait is quite enough to GC being complete. I agree that it may seem that the test "didn't fix" something but this will at least show our intentions and give a chance to see an error if the unobserved task behavior changes in future .NET versions.

**Comment by sungam3r** [comment]
![Uploading изображение.png…]()

Interesting. I have not used any `closes/fixes` mentions.

**Comment by Shane32** [comment]
You can link PRs to issues on the right-hand bar manually.  In this case, I had linked the PR to this issue because we had discussed that we were going to make a test and close out the issue.

**Comment by sungam3r** [comment]
Ok, I didn't notice.
