### ISSUE TITLE
Advanced uses of the DataLoader

### ISSUE THREAD

**Issue by Jefffrey** [graphql-dotnet/graphql-dotnet#796]
## Summary

I'm wondering. Say you have a situation like:

```
query {
    allCars {
        owner {
            father { id }
            mother { id }
        }
    }
}
```

Where `owner`, `father` and `mother` are all fetched using the `users.GetUsersByIds` function. Should I give the same key to each loader or should I use one per level (one for `owner` and one for `mother` and `father`? Would the user of the same key yield errors (maybe because the `owner` layer is fetched and then cached and `father` and `mother` fetch from the cached data?

The second question is about composability of loaders.

Given that maybe you have the following:

```
query {
    users {
        viewerCanA # return adminCertificate != null && moderatorCertificate != null
        viewerCanB # return moderatorCertificate != null
        viewerCanC # return adminCertificate != null || moderatorCertificate != null
        viewerCanD # return moderatorCertificate != null
        viewerCanE # return adminCertificate != null || moderatorCertificate != null
        viewerCanF # return adminCertificate != null
        adminCertificate
        moderatorCertificate
    }
}
```

And let's say that the `adminCertificate` and `moderatorCertificate` are fetched in some complicated way but once fetched they pretty much can determine the rest. Is there some way to make is so that for the above query only two queries are performed (one for each certificate) as opposed to 11 (one for each certificate request in each field)?

That is, are data loaders composable in any way?

**Comment by johnrutherford** [comment]
For your first question: You should use the same key if you’re using the same fetch delegate. Otherwise you won’t benefit from caching on the other query levels. 

For your second question: I think you should be able to use the DataLoader within the resolvers for the dependent fields. You could await the result from ‘LoadAsync()` and then calculate your return value. For resolvers that use more than one DataLoader, you need to start all tasks (call `LoadAsync()` without awaiting) and then await them all. Otherwise it may deadlock.

**Comment by corstian** [comment]
@johnrutherford If I understand you correctly that would be something like this?

```C#
var motherTask = motherLoader.LoadAsync(context.Source.Id);
var fatherTask = fatherLoader.LoadAsync(context.Source.Id);

var motherResult  = await motherTask;
var fatherResult = await fatherTask;
```

**Comment by johnrutherford** [comment]
@corstian Yes.
