### ISSUE TITLE
Expected non-null value, resolve delegate return null -error on all queries after upgrading to 2.0.0

### ISSUE THREAD

**Issue by codinglikejesus** [graphql-dotnet/graphql-dotnet#807]
Hello!

I recently updated the graphql version from 0.7.x to 2.0.0 to access all the new DateGraphTypes. I attempted to follow the migration guide and did the following changes to startup.cs in public void ConfigureServices(IServiceCollection services):

Old:
```
var sp = services.BuildServiceProvider();
services.AddScoped<ISchema>(_ => new FooSchema(type => (GraphType)sp.GetService(type)) {     Query = sp.GetService<FooQuery>() });
```

New

```
var sp = services.BuildServiceProvider();
services.AddSingleton<ISchema>(new FooSchema(new FuncDependencyResolver(type => sp.GetService(type))));

```
and in my FooSchema file:

```
{
    public class FooSchema : Schema
    {
        public FooSchema(IDependencyResolver resolve) : base(resolve)
        {
            Query = resolve.Resolve<FooQuery>();
            Mutation = resolve.Resolve<FooMutation>();`
```

I have not done any other changes to the code apart from those listed above. I've tried following multiple different examples with no avail. 

The full error i get for all of my queries:
```
{
  "errors": [
    {
      "message": "Expected non-null value, resolve delegate return null for \"$GraphQL.Types.ObjectGraphType`1[Foobar.Data.Bar]\"",
      "extensions": {
        "code": "INVALID_OPERATION"
      }
    }
  ]
}


```

Give me a heads up if you need more information/code and thanks a lot in advance!

**Comment by joemcbride** [comment]
Not much to go on here, I would look at the type that it is pointing to in the error - ``GraphQL.Types.ObjectGraphType`1[Foobar.Data.Bar]``.  I would look at the specific fields you are trying to access to figure out why it is returning a null value when it shouldn't.

**Comment by codinglikejesus** [comment]
Hello joemcbride, and thank you for your answer.

Considering this happens on all queries (of which there are dozens) regardless of the fields i'm trying to access, why would this be happening after i've upgraded the packet? The rest of the code was left the same as before the upgrade (when all queries worked correctly) which is the part that really confuses me.

I have quite a limited lack of knowledge in regards to graphql, and I wasn't involved in setting the whole thing up for our project initially so there could definately be something i'm missing. Anyways, your help is very much appreciated.

**Comment by mike-niemand** [comment]
> Hello joemcbride, and thank you for your answer.
> 
> Considering this happens on all queries (of which there are dozens) regardless of the fields i'm trying to access, why would this be happening after i've upgraded the packet? The rest of the code was left the same as before the upgrade (when all queries worked correctly) which is the part that really confuses me.
> 
> I have quite a limited lack of knowledge in regards to graphql, and I wasn't involved in setting the whole thing up for our project initially so there could definately be something i'm missing. Anyways, your help is very much appreciated.

Hey Coding, how did you solve this? I've run into the same problem after upgrading where if a query one field it throws this on another.

**Comment by sungam3r** [comment]
You get this error because you have not registered your types (`FooQuery`, `FooQuery`, other) in the DI-container. You have only registered `FooSchema`. Further in the constructor, you call the `Resolve` method to get object from DI-container. How does the container know which objects to give you? The container does not attempt to create an object even if there is a default constructor. The implementation of the `IServiceProvider.GetService` method returns **null** if it cannot find the required service. This behavior [is intended](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider.getservice?view=netstandard-2.0). If you used the [GetRequiredService](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceproviderserviceextensions.getrequiredservice?view=aspnetcore-2.1#Microsoft_Extensions_DependencyInjection_ServiceProviderServiceExtensions_GetRequiredService_System_IServiceProvider_System_Type_) extension method in your `FuncDependencyResolver`, you would get an error just earlier.

**Comment by sungam3r** [comment]
Closed as answered.
