### ISSUE TITLE
Subscriptions Organization (Grouping)

### ISSUE THREAD

**Issue by megasus** [graphql-dotnet/graphql-dotnet#823]
As described in the docs (https://graphql-dotnet.github.io/docs/getting-started/query-organization) it is possible to organize querys, mutations and subscriptions by putting them in groups and then having only the groups exposed in the root query or whathaveyou.

Although the example provided only deals with querys, it is easily applicable to mutations as well. Subscriptions on the other hand are giving me a bit of an headache.

While I can use this syntax for querys and mutations in the root object:

`Field<TestQueryGroupGraphType>("test", resolve: context => new { });`

How exactly does it translate to the `AddField...` Syntax of Subscriptions?

Thanks for your help!

**Comment by rose-a** [comment]
I'm having this issue too. As stated above the documented way works fine with queries and mutations.

But with Subscriptions this does not work since it tries to resolve the `Subscriber` of the subscription field, and the subscriber then must call `OnNext()` when something in its child elements changes, which is not hooked up automatically.

The concrete RX subscription must be evaluated for each query, because simply aggregating them would result in all subscriptions firing every time one of them pushes something...

@joemcbride Any idea how to create a `TopLevelSubscriptionGraphType` which could make this work?

**Comment by rose-a** [comment]
I managed to get the grouped Subscription working like so:

```c#
public class TestSchema : Schema
{
    public UnitTestSchema(IDependencyResolver dependencyResolver) : base(dependencyResolver)
    {
        this.AddSubscriptionWithTopLevelGroup<TestSubscription>("test");
    }
}
```

The used extension method:

```c#
public static void AddSubscriptionWithTopLevelGroup<TSubscription>(this Schema schema, string groupName) where TSubscription : ObjectGraphType
{
    if (schema.Subscription == null)
        schema.Subscription = new ObjectGraphType { Name = "Subscription" };

    schema.Subscription.AddField(new EventStreamFieldType
    {
        Name = groupName,
        Type = typeof(TSubscription),
        Resolver = new FuncFieldResolver<object>(context => context.Source as dynamic),
        Subscriber = new EventStreamResolver<object>(ctx =>
        {
            // try to get the first selected field which contains a Subscriber and return the subscription to that
            foreach (var selection in ctx.FieldAst.SelectionSet.Selections)
            {
                if (selection is Field field)
                {
                    if (ctx.FieldDefinition.ResolvedType is ObjectGraphType graphType)
                    {
                        var eventStreamField = graphType.GetField(field.Name) as EventStreamFieldType;

                        if (eventStreamField?.Subscriber != null)
                        {
                            return eventStreamField.Subscriber.Subscribe(ctx);
                        }
                    }
                }
            }

            return null;
        })
    });
}
```

This works for regular input, but I think this has lots of special cases where it could fail.

Maybe someone with good understanding of the document execution process can implement this so that instead of throwing an exception [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/SubscriptionExecutionStrategy.cs#L100) when no Subscriber is found the execution process tries to find a selected child which provides a Subscriber and forward that.

**Comment by rose-a** [comment]
Well, it fails when you have arguments for your subscription query... those are not passed as `Arguments` to the subscribe method...

**Comment by tomadj** [comment]
Any update ?

**Comment by corstian** [comment]
From peeking around it seems like the https://github.com/graphql-dotnet/graphql-dotnet/blob/7f5e6bd0571173d286c222ba3c75c8d05b159916/src/GraphQL/Execution/SubscriptionExecutionStrategy.cs has an issue where the observables are incorrectly being grouped together.

It will throw the following error (from line 100 of the file above):

```csharp
throw new InvalidOperationException($"Subscriber not set for field {node.Field.Name}");
```

While the `SubscriptionExecutionStrategy` derives from the `ParallelExecutionStrategy`, the `ExecuteAsync` method from the abstract `ExecutionStrategy` is overriden in the `SubscriptionExecutionStrategy`, meaning that the `ExecuteNodeTreeAsync` as defined in the `ParallelExecutionStrategy` is not being used at all, and therefore the `SubscriptionExecutionStrategy` could derive from `ExecutionStrategy` without change of behaviour.

Given the `ParallelExecutionStrategy` resolves query grouping just fine I assume this is the problem.

Could someone confirm this?

**Comment by sungam3r** [comment]
> How exactly does it translate to the AddField... Syntax of Subscriptions?

It does not. Subscription field should return observable objects.

**Comment by sungam3r** [comment]
@megasus @rose-a @corstian I'm looking through old issues now and found this one. I don't think that such design is applicable for subscriptions at all. Technically we **may try** to do something to allow it but I would not because it will complicate the code and probably will be against some requirements from spec. @Shane32 what do you think? 

Regarding errors mentioned above - a lot of them were fixed these years, please update to v7.

**Comment by Shane32** [comment]
Agree. Grouping of subscriptions is not feasible with the current design of GraphQL.NET. A major rewrite would be required.

**Comment by rose-a** [comment]
I agree, too.

**Comment by Shane32** [comment]
Note that specification rule 5.2.3.1 (June 2018 spec) is titled 'single root field' and implies a single subscription per request executed.  If subscription grouping were allowed, while this would not necessarily break the rule, it would be possible to request two separate subscriptions within the same request.  Although the specification does not explicitly that this cannot be done, I feel that rule 5.2.3.1 was intended to prevent that scenario.
