### ISSUE TITLE
Argument in Fluid syntax fails to properly construct schema

### ISSUE THREAD

**Issue by iadarroch** [graphql-dotnet/graphql-dotnet#882]
## Description

Using v2.3 of GraphQL, I was trying to implement the query structure seen in https://graphql-dotnet.github.io/docs/getting-started/query-organization.

I have been using the fluid syntax to define my fields, but have come across a problem where the schema is not being correctly generated. When I use the .Argument() builder on in a field definition, it causes the argument's name to appear as the enclosing object's type in the schema explorer.

### Steps to reproduce

Using the examples project, I have created a demonstration of the issue. See the following code which is the new query definition: [StarWarsQuery.txt](https://github.com/graphql-dotnet/graphql-dotnet/files/2522230/StarWarsQuery.txt)

When the AspNetCore project is run, the humans, droids and okFluidHumans correctly display in the Schema as their respective types.

Please note I have a branch of the examples project with all code to demonstrate the above issue here:
https://github.com/iadarroch/examples/tree/feature/show_fluid_failure.

### Expected result

badFluidHumans should display in the schema explorer as type BadFluidHumansQuery.

### Actual result

The badFluidHumans displays a type of "thisIsTheArgId", which is the name of the argument in the field definition inside BadFluidHumansQuery.

### Environment

GraphQL v2.3, VS 2017 v15.8.7, Windows 7.

**Comment by sungam3r** [comment]
@iadarroch Honestly, I did not expect that from the first attempt I will be able to reproduce your example. I almost pulled out of my chair when I saw this "bug". And for several minutes I was confused while I localized the error. In the end, everything turned out to be quite simple.

Look at the corrected example:
```c#
   public class BadFluidHumansQuery : ObjectGraphType<object>
    {
        public BadFluidHumansQuery(StarWarsData data)
        {
            Field<HumanType>()
                .Name("human")
            //  .Argument<NonNullGraphType<StringGraphType>>(Name = "thisIsTheArgId", Description = "id of the human")
                .Argument<NonNullGraphType<StringGraphType>>(name: "thisIsTheArgId", description: "id of the human")
                .Resolve(context => data.GetHumanByIdAsync(context.GetArgument<string>("id")));
        }
    }
```

You used the syntax to assign the properties of the class itself. These values were then passed to the `Argument` method. In other cases, you use `QueryArgument` ctor explicitly and property initialization syntax for it, so there is no such problem. At least you managed to surprise me ;)

I close this issue, though feel free to ask any questions.
