### ISSUE TITLE
Generate Offline Schema

### ISSUE THREAD

**Issue by BottlecapDave** [graphql-dotnet/graphql-dotnet#888]
Hi there.

I'm currently using GraphQL .Net with a typescript/react front end. We're using Apollo to integrate the front end with the backend, which provides a nice code generation feature when given a schema.

I was wondering if there was currently a way to produce this required schema, perhaps as a post build process, from the .NET classes/implementation without having the API up and running?

Thanks for your time,
Dave

**Comment by jumpinjackie** [comment]
If it helps, assuming you're using MVC core what we've done is modify our `Program.cs` so that if a certain argument is present (eg. `generate`), we build the aspnetcore web host *but do not run it*. We then resolve GraphQL's `IDocumentExecuter` from the built DI container and use it to run the introspection query and dump the result and exit afterwards.

**Comment by SimonCropp** [comment]
@BottlecapDave currently there is no such build process. At my current client we generate the schema file in a unit test, it can then be committed to source control and included as a build asset

You could also optionally create a new open source project that produces such a build task

**Comment by michal-ciechan** [comment]
@SimonCropp may I ask how do you get the Schema file out of a "Schema" object? Is it hand written?

**Comment by michal-ciechan** [comment]
Just for anyone stumbling upon this, I ended up using `graphql-cli get-schema` in the node world.

See this SO Answer [Get GraphQL whole schema query](https://stackoverflow.com/a/42010467)
