### ISSUE TITLE
Is it possible to change graphql schema once it is initialized

### ISSUE THREAD

**Issue by hasibul2363** [graphql-dotnet/graphql-dotnet#986]
I am using graphql-dotnet with asp.net core and populated schema based on different assembly types. Now I would like to add new types to an existing schema without restarting the application server. Is that possible? 

Expecting your help.

**Comment by Tarig0** [comment]
All you need to do is instead of creating a singleton service for your scheme use the addscoped function

**Comment by joemcbride** [comment]
As @Tarig0 mentioned, you can dynamically build the schema on request instead of making it a singleton.  However, once it has been initialized adding types can be dangerous.  It is technically possible to do so by getting the specific GraphType and adding a field, though you would need to ensure all of the models of the GraphType you are adding are properly populated.  That is not a typical scenario that I would suggest someone to do as there are a ton of issues you could run into.

Summary:  its technically possible, though not supported.
