### ISSUE TITLE
FieldAsync vs Field clarification

### ISSUE THREAD

**Issue by denisedelbando** [graphql-dotnet/graphql-dotnet#990]
Hello,

Is there a standard as to which one is the proper way of creating fields?
In some examples where there is FieldAsync and some are Field.

For example: this one uses async
https://github.com/graphql-dotnet/example-orders/blob/master/Orders/Schema/OrdersQuery.cs

![screenshot - 2019-01-23 11_45_14 am](https://user-images.githubusercontent.com/3780000/51622384-80a2e480-1f04-11e9-98dc-f39ac82c3ed5.png)

But the sample url https://github.com/graphql-dotnet/examples/blob/master/src/StarWars/StarWarsQuery.cs use non-async

![screenshot - 2019-01-23 11_27_26 am](https://user-images.githubusercontent.com/3780000/51622509-c069cc00-1f04-11e9-9a69-b125483240ce.png)

I've worked with this library for quite sometime now, and the difference I've experienced is the one with Async works better than non-async in regards to querying more 
```
{
   somequery {
      ..fields here
   }
   somequery2 {
      ..fields here
   }
}
```

also changing it to Async works with the data loader. Why is it then that we have Field (with no async). Is it better practice to just use with the Async?

Also, when creating the inner fields, should they be async as well?

**Comment by sungam3r** [comment]
> Is there a standard as to which one is the proper way of creating fields?

In fact, from the point of view of the library, it makes no difference which option you use - `Field` or `FieldAsync`. Everything is determined by the usability. If your resolver uses asynchronous code to get the field, then you can use `FieldAsync`. But this does not prohibit you from using the synchronous variant. This is nothing more than static typing by `ComplexGraphType<T>` public api. The fact is that further both resolvers - `FuncFieldResolver` and `AsyncFieldResolver` will be casted to `IFieldResolver` which returns just `object`.

Pay attention [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ExecutionStrategy.cs#L214) and what happens next - `result` variable is checked for `Task` type and if it is than just unwrap inner `Result`. So we **can use** even `Field` overload returning Task from it.

Yes, such flexibility may seem redundant. But one thing is performing mechanisms, and another thing is public api. In this respect, it seems to me that the authors of the library tried to make public api as statically typed as possible. At the same time (at lower level of abstraction), it remains possible to manipulate hierarchical data within wide limits.

Regarding data loader. Since its api involves asynchronous `LoadAsync()` calls in `resolve` parameter, it **motivates** you to use `FieldAsync` and not `Field`. Although you can try to use it in a synchronous context and maybe you can even get a result, although it will be incorrect use of data loader. It still depends on whether the deadlock happens inside the library because of an early synchronous call to the `LoadAsync().Result` method.

> Also, when creating the inner fields, should they be async as well?

Again, you can do so and so. The executing library engine will simply transfer the control one level lower and the whole process will be repeated on next node. See [this](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/SerialExecutionStrategy.cs) or [that](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/ParallelExecutionStrategy.cs).

I hope that this explanation will help.

**Comment by sungam3r** [comment]
Closed as answered.
